### ISSUE TITLE
Entity selection stays not filtered

### ISSUE THREAD

**Issue by youcube** [Clooos/Bubble-Card#1]
First of all, great work.

I noticed that in Entity Selection the dropdown doesn't stay filtered and it jumps back and shows all entities. 

For example:
When entering "lights....." only the "lights." entities are displayed for a short time (as it should be), then the dropdown list is re-rendered and shows all entities again.

![Screenshot (15)](https://github.com/Clooos/Bubble-Card/assets/8338042/c3918711-3cd2-4d8a-bfed-c68967196d4b)

Best Regards

**Comment by tempus2016** [comment]
+1
It needs to be sorted alphabetically and filter when text is entered.

**Comment by svb91** [comment]
Having the same issue

**Comment by cloudbr34k84** [comment]
Same issue, which put me off trying anything 😔

**Comment by Clooos** [comment]
I'm aware of this issue that I don't understand for now, but I will fix it. But beside that almost everything seems to work.
