### ISSUE TITLE
hass.formatEntityState is not a function

### ISSUE THREAD

**Issue by perrywtf** [Clooos/Bubble-Card#101]
![Screenshot_20231009_165014_Home Assistant](https://github.com/Clooos/Bubble-Card/assets/32226293/f190a044-180b-48fa-8fa4-c1816329b5e4)

Any hints on why this might be happening? Can't make a bubble button of any type, have made sure it's installed in the correct directory

**Comment by perrywtf** [comment]
![Uploading Screenshot_20231009_203554_Home Assistant.jpg…]()

**Comment by Clooos** [comment]
I can't see your image:
<img width="469" alt="image" src="https://github.com/Clooos/Bubble-Card/assets/36499953/f5e7336a-f218-4497-94c5-70d10637cda7">

**Comment by perrywtf** [comment]
Sorry mate, Not sure why it didn't load.

About page says:
Home Assistant 2023.8.1
Frontend 20230802.0 - latest

**Comment by Clooos** [comment]
This is expected but not documented indeed, the missing function was introduced in 2023.9, just update your system and everything will work perfectly.
