### ISSUE TITLE
Feature request: Disable scroll

### ISSUE THREAD

**Issue by JoaquinDillen** [Clooos/Bubble-Card#102]
Hello! it would be nice if we can toggle true or false the scroll feature, in that way we can control change between popups and only lock the flow of the dashboard to the buttons!

**Comment by Clooos** [comment]
Hi, I'm not sure of what you're asking for? You mean the fact that you can scroll into a pop-up when there is too much content? Can you be more specific?

**Comment by JoaquinDillen** [comment]
Hi sure! When a pop-up is added to the dashboard, I can access it by scrolling down the main dashboard screen without clicking the pop-up open button. Additionally, with one pop-up open on the dashboard, I can easily scroll between pop-ups without closing the previous ones. It would be helpful to disable the scroll feature to prevent unintended navigation between pop-ups.

**Comment by Clooos** [comment]
Well... In fact what you are experiencing seems like a bug, because pop-ups are hidden when they are not triggered. Can you give me more informations about your configuration?

**Comment by JoaquinDillen** [comment]
Yeah! at the beginning I also think of it as a bug, I will upload a video so that you can see the behavior i'm getting

![ezgif com-video-to-gif](https://github.com/Clooos/Bubble-Card/assets/36713733/d0833a12-0487-4b4a-9926-59149374f7f5)

**Comment by Clooos** [comment]
Have you tried with a different theme? Because it should work with most themes.

**Comment by JoaquinDillen** [comment]
Yes, I tried some, the one that I normally use is the "minimalist-mobile" from the UI Lovelace Minimalist and most of those "minimalist" themes don't work properly with this feature, but I know that is related to the themes, because trying different things I get the pop-ups to work correctly, but affecting the visuals of the dashboard.

**Comment by JoaquinDillen** [comment]
Hi! Yesterday I did some updates on my HAs and updated a bunch of things, and the "bug" got fixed! I guess I was running older components and somehow it wasn't working properly! 

Thank you for the support!
