### ISSUE TITLE
Media player no media info after changing volume

### ISSUE THREAD

**Issue by rapton** [Clooos/Bubble-Card#1023]
If you change the volume in the media player, the volume bar is superimposed over the media info. However, if you hide the volume bar again, the media information remains hidden. 

Really good work!!! Thank you!

![IMG_6815](https://github.com/user-attachments/assets/c6bc7c3b-3010-4f49-a709-7d203bdbaeb2)
![IMG_6816](https://github.com/user-attachments/assets/eacac341-42d4-4fce-9cef-af64c5f6081f)
![IMG_6817](https://github.com/user-attachments/assets/ac8db471-a237-4029-a5f3-b16bf448b448)

**Comment by Clooos** [comment]
Hi! I'm already aware of this and @MrBearPresident fixed it, just wait for the next release 👌

**Comment by rapton** [comment]
Thanks!!
