### ISSUE TITLE
[v2.3.2] Bubble Media card - No rounded corners

### ISSUE THREAD

**Issue by GunterAv** [Clooos/Bubble-Card#1034]
Hello,

with version 2.3.2 the corners from MediaPlayer are not rounded.
![Screenshot 2024-12-12 170746](https://github.com/user-attachments/assets/32672308-c876-4af9-9e1c-dc261341aafc)

Code:

```
type: custom:bubble-card
card_type: media-player
entity: media_player.soundtouch_300_3
```
others, such as Climate, are rounded off as usual.

Best regrds
Gunter

**Comment by mattred33** [comment]
Also seeing this issue in the 2.3.2 fix

![image](https://github.com/user-attachments/assets/e5decd68-0a88-4ec4-932e-23cb2afc71b7)

**Comment by Clooos** [comment]
This is now fixed! Sorry for that!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.3.3

**Comment by GunterAv** [comment]
Hello Clooos,

Thank you!

Best regards
Gunter
