### ISSUE TITLE
Button Type disappears in Pop-Up / Buttons not visible and actionable

### ISSUE THREAD

**Issue by DerLoco** [Clooos/Bubble-Card#104]
Button cards in pop has been created in YAML, not via visual editor

After saving the changes, the buttons are not visible and actionable. When going into editing mode (and visual editor is opened as per default) the button type is empty. In YAML editor it still have the value 'button'
<img width="507" alt="Bildschirmfoto 2023-10-11 um 10 53 58" src="https://github.com/Clooos/Bubble-Card/assets/92661887/c4d44198-5e30-4591-aefe-fb482d75e8df">
<img width="472" alt="Bildschirmfoto 2023-10-11 um 10 54 14" src="https://github.com/Clooos/Bubble-Card/assets/92661887/272031b3-7674-4ca8-b9f8-416c303cb6d2">
<img width="1174" alt="Bildschirmfoto 2023-10-11 um 10 54 50" src="https://github.com/Clooos/Bubble-Card/assets/92661887/0ac93de8-6af3-4b3f-bdb6-0a5dc7aace18">
<img width="902" alt="Bildschirmfoto 2023-10-11 um 10 55 21" src="https://github.com/Clooos/Bubble-Card/assets/92661887/3140ad6c-e591-4595-83ed-acc7b6103471">

**Comment by Clooos** [comment]
Hi, you have made a mistake, it's `button_type: switch` and not `button`, but you can remove that line because it's `switch` by default.

**Comment by DerLoco** [comment]
oh man, thanks a lot @Clooos. BTW: I absolutelly love what you have created =)

**Comment by DerLoco** [comment]
oh man, thanks a lot @Clooos. BTW: I absolutelly love what you have created =)

**Comment by Clooos** [comment]
Thanks! 😊
