### ISSUE TITLE
prevent sliders of accidently moving while scrolling on touchscreen

### ISSUE THREAD

**Issue by robbelt** [Clooos/Bubble-Card#1045]
**Describe the bug**  
Sliders immediately change their value when getting touched. That is really annoying while scrolling with smartphone/touchsreen and you accidently touch the slider.

**To Reproduce**  
1. touch a slider anywhere. it immediately changes its value. (even if you just accidently touch it to scroll up or down on the page.

**Expected behavior**  
Slider should not change its value while scrolling.
Slider should only change its value when moving it left/right.

**Informations (please complete the following information):**  
 - OS: Android, iOS
 - Browser/App: Chrome, Safari
 - Bubble Card version: v2.3.2
 - Home Assistant version: 2024.12.2

Thank you! 🍻

**Comment by MrBearPresident** [comment]
Merging to #1014 because this should be fixed in 1 go.
