### ISSUE TITLE
[v2.3.3] Sidebar & header no longer Visible

### ISSUE THREAD

**Issue by KLST2603** [Clooos/Bubble-Card#1047]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  

**To Reproduce**  

**Expected behavior**  

**Screenshots**  

**YAML**  
If applicable, add any relevant YAML code.

```yaml
Your code here
```

**Informations (please complete the following information):**  
 - Browser/App: [e.g. chrome, safari]
 - Bubble Card version: [e.g. 2.0.4]
 - Home Assistant version: [e.g. 2024.6.4]

**Additional context**  

Thank you! 🍻

**Comment by davidruigrok** [comment]
Do you mean that with the latest (bugfix) release, the sidebar and header are no longer visible on mobile? I had the same issue. Just turn your phone to landscape and you will see them again. Roll back to the previous version (2.3.2) and you will be fine for now.
And I guess it goes a bit far to open issues where you are stating this repository breaks home assistant. Its not breaking it, its a layout / ui issue. And besides, you are not providing any additional information 🤷
The author is clearly giving it a lot of work and is trying to solve everything very fast. 
So lets try to figure out what is exactly going on and provide some steps to reproduce.

**Comment by davidruigrok** [comment]
Not sure what is causing this. I have done rolled back to previous version (2.3.0) and still experiencing the disappearing sidebar and header when viewing the dashboard

**Comment by Clooos** [comment]
That's probably because of the theme you use, do you have installed my Bubble theme? If yes, it hides these by default. You can remove the card_mod part at the end of the YAML file, then `frontend.reload_themes`. 

Hope this help!

**Comment by davidruigrok** [comment]
Thats probably it! Will check it out, thanks 😀

**Comment by davidruigrok** [comment]
It was indeed caused by the bubble theme. Installed that at the same time as the last bubble card version which made me think it was caused by bubble card 😅 As far as I am concerned this issue is resolved!
