### ISSUE TITLE
Question about the "dark fading area" in Horizontal buttons stack

### ISSUE THREAD

**Issue by willliamchan** [Clooos/Bubble-Card#105]
Hi All

Can someone please help and confirm if the dark fading background looks like the attached or if it is something that I messed up?

Desktop
![Screenshot 2023-10-11 115341](https://github.com/Clooos/Bubble-Card/assets/54702221/c7223b30-eacb-4fb4-8d83-e66fa1f97146)

iOS (iPhone 13 Pro)
![IMG_0247](https://github.com/Clooos/Bubble-Card/assets/54702221/1fd72dcd-6d17-4192-a7be-f153a5e746a4)

**Comment by Clooos** [comment]
You can try to run this service in the dev tools `frontend.reload_themes`, then it should be back to normal.

**Comment by Clooos** [comment]
You can try to restart HA and cleaning your cache, but I'm not sure why `frontend.reload_themes` didn't worked.

**Comment by TheValist** [comment]
Hi, 
The same is happening to me. I'm not using the horizontal buttons stack though.
I tried to restart HA, with other styles, etc, and it kept happening
I later noticed that if i deleted "margin_top_mobile: -56px" from the pop-up card, it was working again, and no fading area was appearing.
Any idea why?

Thanks a lot!

**Comment by Clooos** [comment]
This is really weird, can you send a screenshot?

**Comment by TheValist** [comment]
Yes sure, here there are. One with the margin, one without. Thanks so much for your help=
![Screenshot_20231011_192201_Home Assistant](https://github.com/Clooos/Bubble-Card/assets/122882761/1704b921-3a6b-48f9-837f-4ba4234158b6)
![Screenshot_20231011_194133_Home Assistant](https://github.com/Clooos/Bubble-Card/assets/122882761/928abf60-c60f-487d-aaed-2af7c165d7cc)

**Comment by Clooos** [comment]
It's probably because of the new shadow I've added, to fix that you can temporary add `shadow_opacity: 0` to all your pop-ups. But I will fix that in the next release tomorrow, thanks for the feedback!

**Comment by TheValist** [comment]
Thanks, adding the shadow opacity fixed it for now!

**Comment by Clooos** [comment]
It's fixed in v1.3.0.
