### ISSUE TITLE
Custom element doesn't exist: bubble-card on iOS 18.1.1

### ISSUE THREAD

**Issue by emanuelegreco29** [Clooos/Bubble-Card#1063]
## Bug Description
Bubble Cards are working perfectly fine on desktop, but do not load correctly on iOS 18.1.1

## Steps to Reproduce
Simply installa Bubble Card and create any card, can it be button or popup or whatever. On desktop it works, on mobile it does not. 

## Expected behavior
I expect it to work flawlessly as on desktop

## Screenshots
![image](https://github.com/user-attachments/assets/7f0f0bdf-cd07-401b-8c0d-28d22de256bc)

## Informations:
 - OS: 18.1.1
 - Browser/App: Home Assistant App
 - Bubble Card version: 2.3.0
 - Home Assistant version: 2024.12.4

**Comment by emanuelegreco29** [comment]
# UPDATE
I updated to version 2.3.3 and it seems like the problem is gone. I'm closing the issue.

**Comment by MrBearPresident** [comment]
@emanuelegreco29
Please be aware that v2.3.3 is considerd unstable because loads of people experience problems with it.

I'm running it myself without problems but just be aware
