### ISSUE TITLE
Problem with popup and "back" button in sub-dashboards (bottom views)

### ISSUE THREAD

**Issue by Knight1981** [Clooos/Bubble-Card#1069]
Hello guys,

I really looove your bubble card, but I found a little issue.

I have a standard-dashboard which opens in a bottom view, so it has a "back" button (on the top left side) to go back to to the main page. On this sub-page I'm using the bubble cards. My popups open with the navigate action. Example:

`action: navigate
navigation_path: "#my-popup"`

When I open e.g. 3 popups, I now have to click 4 times on the "back" button to come back to the main page. I'm pretty sure it is because of the navigation history.

Is there any way to fix this? Sometimes I'm opening 6 or 10 popups on my page to do some stuff but than I need to click multiple times on the "back" button to go back to the previous view.

Thank you so much for you support and this awesome card mod!

**Comment by MrBearPresident** [comment]
Duplicate from #590.
Merging with that issue.
