### ISSUE TITLE
Popups are off screen on vertical Tablet

### ISSUE THREAD

**Issue by THEthatdude** [Clooos/Bubble-Card#107]
![20231011_195656](https://github.com/Clooos/Bubble-Card/assets/69739301/6aaaaaec-d348-42ef-a6da-581cb7b2f996)
So far bubble card is working amazingly- the only issue I have is with a wall mounted tablet- the popups are weirdly centered as shown in the picture. However the popups look good across all my other devices/computer/including a folding phone.
Tested using both the WallPanel app and FullyKiosk- both have the same behavior

**Comment by Clooos** [comment]
Hi and thanks for your feedback! Have you updated to v1.2.0 because this issue should be fixed 🙂

**Comment by THEthatdude** [comment]
Wow that was fast- it looks perfect now! Thank you so much!
