### ISSUE TITLE
Ability to have more than one pop up trigger

### ISSUE THREAD

**Issue by ahuffman** [Clooos/Bubble-Card#1073]
I'm using ubiquiti cameras that have detection for vehicles, people, and animals.  I would like to be able to trigger pop up on more than one trigger state.  

Love this project, thanks for your efforts!

**Comment by MrBearPresident** [comment]
Hey can you test the new beta version?
This should have the conditional trigger. That makes this possible. 

![image](https://github.com/user-attachments/assets/63cc7934-c273-414e-898c-5841d1c7a330)

**Comment by ahuffman** [comment]
Awesome!  Trying it out now.

**Comment by ahuffman** [comment]
@Clooos I did notice that with the new trigger (testing with 'or' operator) it is not respecting the pop up close timeout setting, and instead defaulting to close when the state of the trigger clears on the pre-release version.
