### ISSUE TITLE
Hauteur de la carte ??

### ISSUE THREAD

**Issue by schumi2309** [Clooos/Bubble-Card#1077]
Bonjour,
j'aimerais que ma carte soit plus grande en hauteur comme celle ci (3ème carte)

![Capture d’écran 2024-12-23 à 08 49 55](https://github.com/user-attachments/assets/28ff2f87-9e86-4b17-ad37-2dc2b8dc584b)

Mais je ne vois pas ou le faire.... j'ai essayer de changer dans "Layout options for sections" et de mettre "rows" sur 4/4 et voici ce que j'obtiens:

![Capture d’écran 2024-12-23 à 08 49 05](https://github.com/user-attachments/assets/0541bb63-2268-4ffc-90d0-6cea397f9af3)

la carte prend bien la place en hauteur, mais n'affiche toujours la carte sur un rows 1/1 tout en prenant la place de 4/4.

Je fais une erreur quelques part ? j'oublie quelques choses ?

voici ma simple carte:

```
type:` custom:bubble-card
card_type: media-player
entity: media_player.bureau_echo
force_icon: false
hide:
  power_button: true
card_layout: large-2-rows
rows: 4
cover_background: true
show_state: false
show_last_changed: false
show_attribute: true
scrolling_effect: true
show_name: true
attribute: media_title
styles: |+

sub_button: `[]
```

En un mot, j'aimerais faire des carte plus grande en hauteur, mais ma carte prend plus en hauteur mais pas l'affichage des informations.

Merci d'avance:

**Comment by MrBearPresident** [comment]
Hey there is a PR for this #965.
So you'll have to wait. 

I could make you a bèta file if you want.
There will be some kinks and hiccups but we can solve them.   Report if you are interested.

**Comment by schumi2309** [comment]
oui, je suis interesser, bien sur ! et je vous signalerais les problemes, si il y a !

**Comment by MrBearPresident** [comment]
Hi @schumi2309 although I speak some French. 
I'm not good/fluid in it.  So if you find some issues please report them on the PR but in English. 

You can find the file here: https://github.com/Clooos/Bubble-Card/pull/965#issuecomment-2563105722
I will close this issue.
