### ISSUE TITLE
Feature Request: Hide Popup by clicking outside of popup/ESC

### ISSUE THREAD

**Issue by Ashpork** [Clooos/Bubble-Card#11]
When presented with a popup, I'd like to be able to click anywhere "off" the popup and/or press the escape key, for the popup to be dismissed, not just the "X" in the top corner of the popup.

**Comment by Clooos** [comment]
+1 👀

**Comment by Clooos** [comment]
Hi, this is now a new feature available in the new beta! Thanks!
https://github.com/Clooos/Bubble-Card/releases/tag/v0.0.1-beta.6
