### ISSUE TITLE
Objects not centered on Tablet

### ISSUE THREAD

**Issue by currydani** [Clooos/Bubble-Card#112]
Hello, 
i am using your cards and theme now and i love them so far.
It's working everywhere (desktop, mobile) except on my tablet. There the buttons on the bottom are offcenter and the slider cards in combination with the layout grid card are also weird positioned. Can you or anyone help me with that? Can't figure out what is causing that, and only on that device.
Thanks in advance
![IMG20231014122203](https://github.com/Clooos/Bubble-Card/assets/78862555/2f45ff44-f783-4eee-aa64-09b223b4dd5e)
![IMG20231014123140](https://github.com/Clooos/Bubble-Card/assets/78862555/2ab37064-7342-40cb-a911-71f8c34d6927)
![IMG20231014123150](https://github.com/Clooos/Bubble-Card/assets/78862555/c3b8875a-7f1a-4c4a-b12c-8dc9d7a1bbe7)

**Comment by Clooos** [comment]
Hi and thanks for your feedback!

This issue should be fixed in the new v1.6.0 beta :

https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.0-beta.1
