### ISSUE TITLE
Slowing down of Lovelace and Companion App when using PopUp & Triggers

### ISSUE THREAD

**Issue by SynoUser-NL** [Clooos/Bubble-Card#113]
First of all, thanks for the Bubble set! Great addition, especially the popup.

However, I did encounter some issues.
With the Bubble PopUp card, I made a popup with a trigger on motion detection. This worked well in itself, but I did notice that the Lovelace Dashboard started getting slower and slower with each triggered popup. When viewing the dashboard on a phone (Android, V13, via Companion App) the dashboard, the phone was using CPU in such an amount that the phone began to noticably heat up. While other apps remained operational, I could not close the HA Companion App and had to resort to restarting the phone. After this the companion app started normally again, until I let it display the dashboard using the (triggered) popups.

Disabling the trigger remedied the problem with viewing the dashboard on the phone. Although I have not tested it, I suspect that the problem will re-occur when triggering a popup often (as the trigger did).

I have also noticed, editing the dashboard on my computer (Win10, I5 equivalent, no shortage of memory, firefox browser) will slow the entire browser editing session down after editing the dashboard for some time: slow loading of the editing screen, slow saving of changes.

Hope you can look into this and optimize some code so this is remedied.
Again, thanks for an excellent addition to dashboard possibilities.

**Comment by Clooos** [comment]
Hi and thanks for your feedback, can you tell me if it's working like it should in v1.3.0?

**Comment by SynoUser-NL** [comment]
Hi Clooos,

Thanks for your reply!
I've downloaded 1.31. this morning (I never got a message that 1.3.0. was available).
However, I did upgrade to 1.2.4 earlier (when it was released) and that already made a big difference!

Let me test for a couple of days and get back to you.

Thanks, again: great work! :)
DenW

**Comment by SynoUser-NL** [comment]
Hi Clooos,

Thanks for your reply!
I've downloaded 1.31. yesterday morning (I never got a message that 1.3.0. was available).
However, I did upgrade to 1.2.4 earlier (when it was released) and that already made a big difference!

Let me test for a couple of days and get back to you.

Thanks, again: great work! :)
DenW

**Comment by SynoUser-NL** [comment]
Hi Clooos,

First day running 1.3.1..
I opened a popup on my phone and let it remain open. Busy doing other things, the phone remained unlocked with the popup open. After a while I returned (about 2 hours or so) and noticed the phone was (much) warmer than it should be. 
Also, Home Assistant Companion App was unresponsive. I had to force stop the app, after which (after a while) the phone cooled down.
I did use the Dashboard I made with the popup cards during the remainder of the day, but it appears as long as you close the popup there is no issue.

I understand the AutoClose timeout value might be a workaround here.

Thanks!
DenW

**Comment by Clooos** [comment]
Interesting, I will take a further look at what can cause that.

**Comment by Clooos** [comment]
I've just released v1.3.2 and it should improve performances a lot for people using pop-ups 🤞

**Comment by SynoUser-NL** [comment]
Thanks for your quick changes!! Really cool!
Downloaded the new version, will do some more tests tomorrow.

**Comment by SynoUser-NL** [comment]
Hi Clooos,

After doing some tests it appears this version (1.3.3) is much more power-friendly. 
Phone doesn't get warm anymore.

Also, editing in browser on PC appears faster, and tabs don't crash or stall as much..

So: big improvement!!

Thank you!
DenW

**Comment by Clooos** [comment]
Thanks for the feedback! I'm glad that you are seeing improvements! I'm working hard on a new version that will be so much more power friendly, but I still don't know when I will be able to release it.

**Comment by SynoUser-NL** [comment]
Eager to test V1.4.1 out! 
Have a great holiday, hope you'll get some inspiring new ideas for BubbleCards.. :)

**Comment by Clooos** [comment]
Thanks! Glad that this new version fixed it for you!
