### ISSUE TITLE
Feature Request:  Change Bubble card slider icon color when the state is "on"

### ISSUE THREAD

**Issue by FrankJaco** [Clooos/Bubble-Card#115]
Would it be possible to change the icon of slider cards to match its state?  If used for a light, the icon should be in the color of the light when it is turned on at any brightness percentage.  I often have lights turned on at very low brightness levels.  Especially on a small screen (phone) it is difficult to see the state.  Below is an example.  In this my Entry light is in night mode at 5% brightness. To me this would be much more readable if the icon was also lit in the color.

![image](https://github.com/Clooos/Bubble-Card/assets/79318542/2883084c-b7d9-470b-b25b-fa1f818e2aac)

**Comment by jembamen** [comment]
Here's a way to make it work using card_mod, sorry if the formatting is weird...

`ha-card > div > div > div > div.icon-container {`
`  {% if(is_state('light.example', 'on')) %}`
`    background: rgb{{ state_attr('light.example', 'rgb_color') }};`
`  {% endif %}`
`}`

This is for a slider button, the card_mod selector may be slightly different for a standard button but the rest should be the same.

**Comment by Clooos** [comment]
The v1.3.0 is here, I hope you will like it 🙂
