### ISSUE TITLE
Horizontal buttons stack - Mobile Issue

### ISSUE THREAD

**Issue by npanayiotou** [Clooos/Bubble-Card#116]
Hello,
I've been trying the horizontal button stack and it works just fine on desktop but when I use it on my mobile (OnePlus 8 Pro) nothing happens when I click on the button.
It's been setup to redirect to a new page of my dashboard. Here is the code

type: custom:bubble-card
card_type: horizontal-buttons-stack
1_link: http://homeassistant.local:8123/np-home/home
1_entity: light.bedroom_lights
margin: 15px
auto_order: false
2_link: http://homeassistant.local:8123/np-home/livingroom
2_entity: light.living_room_lights
is_sidebar_hidden: true
3_icon: mdi:countertop-outline
3_entity: light.kitchen_lights
3_link: http://homeassistant.local:8123/np-home/kitchen
2_icon: mdi:sofa-outline
4_link: http://homeassistant.local:8123/np-home/office
4_icon: mdi:desktop-classic
4_entity: light.bedroom_lights
rise_animation: false
5_link: http://homeassistant.local:8123/np-home/bedroom
5_icon: mdi:bed-king-outline
5_entity: light.bedroom_lights
1_icon: mdi:home
width_desktop: 54px
6_link: http://homeassistant.local:8123/np-home/garage
6_icon: mdi:garage

**Comment by Clooos** [comment]
Hi, I've just tried and it's working on my side, but just change all your links to this, you don't have to add the full link:
```yaml
/np-home/home
```

**Comment by npanayiotou** [comment]
Just replaced the URLs as you suggested and everything works :) thanks for your help!!
________________________________

**Comment by Clooos** [comment]
You're welcome!
