### ISSUE TITLE
Popup header 'merged' when scrolling

### ISSUE THREAD

**Issue by realroywalker** [Clooos/Bubble-Card#119]
I have been testing bubble card and it looks amazing, however I noticed an issue with popups (on mobile) - some of my rooms have many devices causing the popup to require scrolling. When I scroll the popup header gets merged into the content of the popup and looks messy - it would be great if some background or something could be put on the header so that it looks like it's 'on top' of the content and covers the content behind it..

See the attached screenshot incase my explanation is no good 😊

![Screenshot_2023-10-20-18-03-17-09_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Clooos/Bubble-Card/assets/486860/ead31300-68be-4e74-8653-683ab2f52df2)

**Comment by Clooos** [comment]
Hi and thanks for your feedback, this is fixed in the v1.3.0 🙂
