### ISSUE TITLE
Stabilities & Performances (even with latest version 1.3.1)

### ISSUE THREAD

**Issue by willliamchan** [Clooos/Bubble-Card#125]
Hi Clooos

I've been looking for the ultimate dashboard on mobile and bubble card fulfilled every single thing that I need! Big thanks for your great work!

After I am completely getting rid of my previous dashboard and had everything loaded into one single page, I found several glitches which I am not sure if it is because my Home Assistant hardware (Pi 4B 4GB, NVMe) just not good enough to handle it or if it is something that might bring up your attention.

1. Whenever I want to edit a card using UI it becomes either very slow or sometimes the browser just stops responding. There is currently a 4000 lines dashboard with 24 cards in total and I'm not sure if that means too many.

2. Unexpected page refresh using HA iOS App, sometimes the dashboard refreshes once and sometimes twice before I can interact with it. And sometimes after several refreshes and it just goes blank.

3. Unable to load the dashboard using browsers (Edge & Safari) on iOS v17.0.3.
      Error with Edge - permanently-removed.invalid's server IP address could not be found.
      Error with Safari - A problem repeatedly occurred on https://myhaurl/lovelace/home.

Cheers

**Comment by Clooos** [comment]
Hi and thanks for your feedback, I'm aware that there is still optimization that needs to be done and I'm working on it almost everyday. Keep updating and it will be better releases after releases 🤞

**Comment by Clooos** [comment]
Perfect, thanks!

**Comment by Clooos** [comment]
I had this issue as well on my old iPad, rebooting it fixed the issue and I don't had this issue since. Tell me if it's working for you.

**Comment by Clooos** [comment]
I've just rebooted my iPad 🙂

**Comment by Clooos** [comment]
Yeah! I'm so glad that this new version fixed your issue! This should be some kind of iOS cache issue.

**Comment by Clooos** [comment]
Interesting, I've also cameras in one of my pop-ups, I'm using the Frigate card for that. For now I've not found a way to lazy load the content of an hidden pop-up, most of the default cards have that feature by default but I haven't found a way to force that for cards that not support that (for now).

**Comment by Nazze** [comment]
> Quick question for you tho, if you will do several swipe down (refresh) from HA app, any chance that you might see the blank screen? It is still happening to mine sometimes.

I saw it again after upgrading from 1.4.0 to 1.4.1. But rebooting the iPhone helped. And I am not seeing it anymore. Even after several swipe downs.
