### ISSUE TITLE
Misalignment on iPad Pro 11"

### ISSUE THREAD

**Issue by b101marc** [Clooos/Bubble-Card#126]
Running the most recent beta and have encountered this issue for several releases. ![image](https://github.com/Clooos/Bubble-Card/assets/41177825/a1dd7df1-4586-435d-a59f-a724d8a50310)

Pop-ups will appear at random places on the page, often mostly out of frame unless in the center column. Using this in conjunction with minimalist UI.

**Comment by Clooos** [comment]
Hi and thanks for your feedback, this is a known issue related to Minimalist UI, I've still never tried it but I can confirm that Bubble Card is working perfectly without it, even on iPad and iPad Pro (I've tested it on both of them).

**Comment by b101marc** [comment]
Thank you @Clooos for the quick reply. Glad to know it had already been found and hopefully there is a fix soon.

What method do you suggest to best take advantage of Bubble Card? I'm admittedly a bit of a novice.
