### ISSUE TITLE
Assigning Hash (ID) makes the JS go bananas

### ISSUE THREAD

**Issue by KeviinCosmos** [Clooos/Bubble-Card#127]
Something is very wrong.
When i add more than two Bubble options, the console goes bananas
and chrome is using a lot of resources.

I've tried with the newest 1.3.3 but also 1.2.4 just to test.

Watch my [1 min screen record](https://www.seee.link/xQuNzeko) to see errors

**UPDATE: I figured out something else. It's happening then I'm changing the ID (Hash) in the popup. Then the JS goes crazy**

**Comment by KeviinCosmos** [comment]
I figured out something new. It's happening then I'm changing the ID (Hash) in the popup. THen the JS goes crazy

**Comment by Clooos** [comment]
This is fixed in v1.4.0 and up 🙂
