### ISSUE TITLE
Slightly miss-clicking can result in brightness setting very low and pop-up opening 

### ISSUE THREAD

**Issue by wizbowes** [Clooos/Bubble-Card#13]
For the light slider:  The icon is quite small, and miss-touching slightly outside the area results in both the brightness coming down to about 8, and opening the detail pane.

Really I think the active part of the slider needs to start to the right of the icon in order to prevent this.

**Comment by Clooos** [comment]
Thanks for your feedback, can you tell me on what browser you are experiencing this issue? I had no issue with it on Chrome.

**Comment by dsellers1** [comment]
I see what @wizbowes is saying. This is on PC with a mouse but I think it still shows the symptoms. All mouse clicks were click & hold; no single clicks around the icon.
Win 11, Firefox 117.0
![firefox_kmjVhTYbus](https://github.com/Clooos/Bubble-Card/assets/67642332/9f96d0ea-6a1d-4e49-82d4-cc12c85b686f)
Maybe something that stops the more-info from showing within 1-2 seconds of a click & hold/drag event?

**Comment by Clooos** [comment]
This is fixed in the new beta 🙂
