### ISSUE TITLE
Light Slider tap and hold action for more info

### ISSUE THREAD

**Issue by holt3000** [Clooos/Bubble-Card#131]
The default action when using a bubble light slider card is obviously tapping or "sliding" the light brightness, and tapping the icon brings up the more info. 

I would like the option for holding the icon to toggle more-info, with color options and everything.  

Ideally, tap toggles the light (which works with adding tap_action). Double-tapping is unnecessary but would be nice to double tap the slider to bring up more-info, and of course holding to bring up more-info.

       tap_action:
          action: toggle
        double_tap_action:
          action: toggle
        hold_action:
          action: more-info

Thanks!

**Comment by ntallfellow** [comment]
https://github.com/Clooos/Bubble-Card#options-2

That functinality exists.

**Comment by holt3000** [comment]
Thank you, but the hold_action doesn't seem to work. Also, is there a way for the hold action to work on the slider section as well? Not just the icon area

**Comment by ntallfellow** [comment]
Hmm.. You are right. I cant seem to get the hold icon to work on any the slider or button. I would imagine that once its working it should be good to go, since double tap works on the slider section... @Clooos

**Comment by ncodee** [comment]
Whoop just saw this now, already opened a ticket for Actions support via UI [here](https://github.com/Clooos/Bubble-Card/issues/170). Tho, not sure why `hold_action` doesn't seem to work in yaml either?

**Comment by Clooos** [comment]
Hi everyone, I've just tried and this is working on Chrome but not on Safari indeed, I will fix that!

**Comment by ncodee** [comment]
> Hi everyone, I've just tried and this is working on Chrome but not on Safari indeed, I will fix that!

It's not working in Chromium based browsers either, please fix as soon as possible as it breaks core functionality.

**Comment by Clooos** [comment]
This is finally fixed in the new v1.6.0 beta! Sorry for the long wait!

https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.0-beta.1
