### ISSUE TITLE
trigger_close not working for me on pop-up

### ISSUE THREAD

**Issue by lambros414** [Clooos/Bubble-Card#134]
Playing around with these cards.  Lots of potential here.

I am trying an experiment when I create a pop-up and show a camera live view.  I have the pop-up trigger be when a switch is turned on.  I set the trigger_close to true when the state changes from the desired state (on).  When the state changes, the pop-up isn't closing.  the optional time-out is working, but not the trigger_close

**Comment by Clooos** [comment]
This should be fixed on v1.4.0 and up, it's working on my setup.
