### ISSUE TITLE
Hide sidebar after pop-up card is not centered

### ISSUE THREAD

**Issue by xysgx** [Clooos/Bubble-Card#135]
The pop-up card is not centered after hiding the sidebar, but is centered when opening the sidebar.
![动画](https://github.com/Clooos/Bubble-Card/assets/57667764/88bcc089-ee5d-4e26-af60-b2e0702177a8)

**Comment by xysgx** [comment]
I used the latest version 1.3.3
![20231026133810](https://github.com/Clooos/Bubble-Card/assets/57667764/24866dbc-9ced-4599-9aaa-bed05f0dcb34)

**Comment by xysgx** [comment]
I updated to the latest version, but the problem still hasn't been solved.
![image](https://github.com/Clooos/Bubble-Card/assets/57667764/8738c1c5-c01b-4c0c-83b8-f01f180260f9)

**Comment by Clooos** [comment]
Thanks for your feedback, I didn't knew that it was possible to hide it in the settings. I will take a look at that.

**Comment by Clooos** [comment]
I've tried it and I'm not able to replicate this issue, it's working with `is_sidebar_hidden: true` on my setup.
