### ISSUE TITLE
[DOCS] Add license section to the README

### ISSUE THREAD

**Issue by singodiyashubham87** [Clooos/Bubble-Card#136]
I want to add a new section for **LICENSE** in the README file for the visitors to get information on the overview page itself regarding the license of the repository.

I will add the License section before this Donate section.

![image](https://github.com/Clooos/Bubble-Card/assets/93720428/c6524f91-92fa-4672-9769-e43bc3752db0)

**Comment by Clooos** [comment]
We don't really need this but thanks anyway for the suggestion.
