### ISSUE TITLE
Need of code of conduct.md file

### ISSUE THREAD

**Issue by Parth4git** [Clooos/Bubble-Card#137]
Kindly assign it me .
The repository looks incomplete because of the missing Code of Conduct.md file to specify the rules and regulations to follow while  raising a issue to the repository, I want to add that file to the repo.

Proposal
Add Code of Conduct.md  file to the repository with guidelines.

**Comment by Parth4git** [comment]
@Clooos Kindly look into my issue

**Comment by Clooos** [comment]
We don't really need this for now but thanks for the suggestion.
