### ISSUE TITLE
Sliders in light color

### ISSUE THREAD

**Issue by ahlstromanton** [Clooos/Bubble-Card#14]
Would be neat if sliders could follow the color of the current state of the RBGW light.

**Comment by Clooos** [comment]
I'm not sure to understand, because the sliders should do that by default. For exemple if the light is blue the slider is blue as well. Please tell me more.

**Comment by brpeterso** [comment]
Here's what I see. Note the office lamp is set to pink in this example (mushroom card), but the bubble card is showing blue. I'm using the waves theme, which may have an impact.

![image](https://github.com/Clooos/Bubble-Card/assets/24624605/ff1107e7-08c4-4f7c-9a9e-513eeb650574)

**Comment by Clooos** [comment]
It is configured as a slider or as a switch?

**Comment by brpeterso** [comment]
> Is it configured as a slider or as a switch?

Slider.  Let me try switch.

**Comment by Clooos** [comment]
You're welcome!
