### ISSUE TITLE
Popup vertical-stack cards are rendered even if not visible

### ISSUE THREAD

**Issue by cadavre** [Clooos/Bubble-Card#140]
I've created successfully a pop-up card based on vertical stack. In one of the cards I've added a camera stream. When I go to dashboard view with toggles, even that I don't see the pop-up (with camera stream) – the stream is being fetched from the server. This causes lot's of resources being used for nothing.

Is there any chance to not render (or remove from DOM?) pop-up cards that are not currently being displayed?

<img width="573" alt="Zrzut ekranu 2023-10-27 o 23 57 05" src="https://github.com/Clooos/Bubble-Card/assets/461796/3966c5be-c53d-40dd-9cde-908aa76071f6">

**Comment by MrLemur** [comment]
@Clooos Could you implement similar functionality to the conditional card?

**Comment by Clooos** [comment]
This is finally fixed in the last beta, take a look at the changelog 😃 

https://github.com/Clooos/Bubble-Card/releases/tag/v1.5.0-beta.3

**Comment by cadavre** [comment]
This is amazing! First thing tomorrow I'm updating to test it. :)

**Comment by Clooos** [comment]
This is now available as a stable version! 🥳

https://github.com/Clooos/Bubble-Card/releases/tag/v1.5.0
