### ISSUE TITLE
Button bubble-cards ceased to update its background

### ISSUE THREAD

**Issue by cadavre** [Clooos/Bubble-Card#141]
When clicking on a button card, the background is no longer updated to the current state. It updates when I refresh the page. See GIF recording attached:

![dots_bug](https://github.com/Clooos/Bubble-Card/assets/461796/849d8d22-77ca-4171-b388-c0b0a0c4f1a1)

**Comment by tonka3000** [comment]
I have the same issue.

I can easy reproduce that on Android when I force close the Home Assistant app restart it. When I show the bubble card for the first time the background of the active lights have the background-color set and when clicking on them the background color is still the same, which is quite confusing.

**Comment by Clooos** [comment]
Yes I thought I fixed it, but I've already fixed it for good. Just wait for the next release 🙂

**Comment by tonka3000** [comment]
@Clooos Nice.

Thanks for this awesome bubble cards, amazing idea.

**Comment by Clooos** [comment]
This is fixed in v1.4.2!

https://github.com/Clooos/Bubble-Card/releases/tag/v1.4.2
