### ISSUE TITLE
WebKit and Safari related issues are slowing down the system / TypeError: undefined is not an object (evaluating 'e.entity_id') entity_id 

### ISSUE THREAD

**Issue by marwonn** [Clooos/Bubble-Card#144]
Hi,

Thanks again for your hard work and wonderful card! Since 1.3.0 I am experiencing I guess WebKit related issues which massively slows down the user interface (mobile app and web browser).

I am on iOS 17.1 and MacOS 14.1 and use Bubble Card 1.4.1.

Here is what I have found in my logs:

```Logger: frontend.js.latest.202310050
Source: components/system_log/__init__.py:300
First occurred: 17:04:42 (18056 occurrences)
Last logged: 19:33:21

Uncaught error from Safari 17.1 on Mac OS 10.15.7 TypeError: undefined is not an object (evaluating 'e.entity_id') entity_id (src/common/entity/compute_state_display.ts:53:37) e (/hacsfiles/Bubble-Card/bubble-card.js:1:7965) /hacsfiles/Bubble-Card/bubble-card.js:1:17620
Uncaught error from WebKit 605.1.15 on iOS 17.1 TypeError: undefined is not an object (evaluating 'e.entity_id') entity_id (src/common/entity/compute_state_display.ts:53:37) i (/hacsfiles/Bubble-Card/bubble-card.js:1:7149) /hacsfiles/Bubble-Card/bubble-card.js:1:17350
Uncaught error from WebKit 605.1.15 on iOS 17.1 TypeError: undefined is not an object (evaluating 'e.entity_id') entity_id (src/common/entity/compute_state_display.ts:53:37) e (/hacsfiles/Bubble-Card/bubble-card.js:1:7965) /hacsfiles/Bubble-Card/bubble-card.js:1:17620
Uncaught error from Mobile Safari 17.1 on iOS 17.1 TypeError: undefined is not an object (evaluating 'e.entity_id') entity_id (src/common/entity/compute_state_display.ts:53:37) e (/hacsfiles/Bubble-Card/bubble-card.js:1:7965) /hacsfiles/Bubble-Card/bubble-card.js:1:17620
```

Any idea what this can cause?

**Comment by Clooos** [comment]
Hi and thanks for your feedback, this issue seems related to a missing/wrong entity, but can you try making a new view with some Bubble Cards and see if you still have this error?

**Comment by marwonn** [comment]
Does that mean that one of my Bubble cards has a missing entity and once I find out which one, removing it would probably solve the issue?

**Comment by Clooos** [comment]
It's possible that this is fixed in v1.4.2 but I'm not sure, can you try it?

https://github.com/Clooos/Bubble-Card/releases/tag/v1.4.2

**Comment by marwonn** [comment]
Amazing!

It seems that v1.4.2 solved my issue! My system is snappy as it used to be. The error message has gone as well.

Thanks a lot!

**Comment by Clooos** [comment]
Yeah, I'm glad that this version fixed it! 😀
