### ISSUE TITLE
Can't Click on horizontal Stacks due to iPhone nav bar

### ISSUE THREAD

**Issue by THEthatdude** [Clooos/Bubble-Card#149]
![IMG_20231030_123757](https://github.com/Clooos/Bubble-Card/assets/69739301/35b3ed18-ada5-4352-ac21-2d6561b79142)
Hello,
As shown in the picture- I am unable to click any of the navigation buttons at the bottom of the screen on an iphone in the official companion app- it simply tries to bring up the home bar. Is there a way to adjust the vertical padding for iPhones? Or is there a setting im missing? Thank you!

**Comment by Clooos** [comment]
Hi and thanks for your feedback, is it working on desktop? 

If yes, you can just edit this margin by adding this in your horizontal buttons stack YAML:
```yaml
styles: |
  .card-content {
    bottom: 32px !important;
  }
```
