### ISSUE TITLE
Visual editor for horizontal-buttons-stack not modifying the yaml

### ISSUE THREAD

**Issue by 5H4D0W-X** [Clooos/Bubble-Card#15]
when I add a button with the visual editor and set up its values, the yaml only shows the 1_icon and 1_entity properties. It doesn't matter how long I let it sit, the name and link don't appear in the yaml and don't save. My instance is fully up to date and I restarted the server after installing bubble-card

**Comment by jenssvedlund** [comment]
Found the same issue. 
Noticed that it works if you add it directly in yaml using the code editor.

After that it also shows up in the UI editor

**Comment by Clooos** [comment]
Thanks for your feedback, it's possible that this issue was introduced in the new beta. I will take a look at that, it seems that there is some issues with the editor.

For now you can take a look at the documentation for the yaml, I've finally finished it.

**Comment by Clooos** [comment]
This is fixed in beta 4 with a lot of other editor fixes!
