### ISSUE TITLE
Bug: Invalid gradient when no entity is selected

### ISSUE THREAD

**Issue by damru** [Clooos/Bubble-Card#153]
### Description
When you dont select any `entity` in a `pop-up` card, the top gradient css property becomes `invalid` because the color becomes `undefined`: 

![image](https://github.com/Clooos/Bubble-Card/assets/1413179/f48b1ab5-a3e9-4a1b-9d67-56bca58f78e6)

### Expected behavior
Whether or not an `entity` (which is `optional`) is defined in a `pop-up`, this should not change the color of the gradient as it should be the same as the `pop-up` background color.

**Comment by Clooos** [comment]
This is now fixed in the new v1.6.0 beta! 🥳

https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.0-beta.1
