### ISSUE TITLE
Error Logs - I'm doing it wrong :( 

### ISSUE THREAD

**Issue by tim-tom-88** [Clooos/Bubble-Card#158]
Everything seems to be working as expected but i have multiple log entries telling me my popup needs to be in a vertica-stack...which they are. here is my dashboard YAML:
![image](https://github.com/Clooos/Bubble-Card/assets/54896166/5a3edc6e-6943-47b9-9563-46f5ec68e5f9)

`views:
  - title: Home
    type: custom:grid-layout
    badges: []
    cards:
      - square: true
        type: grid
        cards:
          - type: custom:mushroom-template-card
            primary: CCTV
            secondary: ''
            icon_color: teal
            layout: vertical
            fill_container: true
            tap_action:
              action: navigate
              navigation_path: '#cctv'
            icon: mdi:cctv
            card_mod:
              style:
                mushroom-card: |
                  :host {
                    --mush-icon-size: 100px;       
                    }
          - tap_action:
              action: navigate
              navigation_path: '#living-room'
            icon: mdi:sofa
            type: custom:mushroom-template-card
            primary: Living Room
            secondary: ''
            icon_color: orange
            layout: vertical
            card_mod:
              style:
                mushroom-card: |
                  :host {
                    --mush-icon-size: 100px;       
                    }
            fill_container: true
          - tap_action:
              action: navigate
              navigation_path: '#office'
            icon: mdi:chair-rolling
            type: custom:mushroom-template-card
            primary: Office
            secondary: ''
            icon_color: pink
            layout: vertical
            fill_container: true
            card_mod:
              style:
                mushroom-card: |
                  :host {
                    --mush-icon-size: 100px;       
                    }
          - type: custom:mushroom-template-card
            primary: Dining Room
            icon_color: blue
            layout: vertical
            fill_container: true
            tap_action:
              action: navigate
              navigation_path: '#dining-room'
            icon: mdi:table-chair
            card_mod:
              style:
                mushroom-card: |
                  :host {
                    --mush-icon-size: 100px;       
                    }
          - type: custom:mushroom-template-card
            icon_color: brown
            layout: vertical
            fill_container: true
            primary: Kitchen
            tap_action:
              action: navigate
              navigation_path: '#kitchen'
            icon: mdi:stove
            card_mod:
              style:
                mushroom-card: |
                  :host {
                    --mush-icon-size: 100px;       
                    }
          - type: custom:mushroom-template-card
            icon_color: '#006400'
            layout: vertical
            fill_container: true
            primary: Bedrooom
            tap_action:
              action: navigate
              navigation_path: '#bedroom'
            icon: mdi:bed-empty
            card_mod:
              style:
                mushroom-card: |
                  :host {
                    --mush-icon-size: 100px;       
                    }
          - type: custom:mushroom-template-card
            icon_color: '#DAA520'
            layout: vertical
            fill_container: true
            primary: Spare Room
            tap_action:
              action: navigate
              navigation_path: '#spare-room'
            icon: mdi:bed-clock
            card_mod:
              style:
                mushroom-card: |
                  :host {
                    --mush-icon-size: 100px;       
                    }
          - type: custom:mushroom-template-card
            icon_color: yellow
            layout: vertical
            fill_container: true
            primary: Landing/Stairs
            tap_action:
              action: navigate
              navigation_path: '#landing'
            icon: mdi:stairs
            card_mod:
              style:
                mushroom-card: |
                  :host {
                    --mush-icon-size: 100px;       
                    }
          - type: custom:mushroom-template-card
            icon_color: purple
            layout: vertical
            fill_container: true
            primary: Under The Stairs
            tap_action:
              action: navigate
              navigation_path: '#under-the-stairs'
            icon: mdi:stairs-box
            card_mod:
              style:
                mushroom-card: |
                  :host {
                    --mush-icon-size: 100px;       
                    }
          - type: custom:mushroom-template-card
            icon_color: red
            layout: vertical
            fill_container: true
            primary: Settings
            tap_action:
              action: navigate
              navigation_path: '#settings'
            icon: mdi:cog
            card_mod:
              style:
                mushroom-card: |
                  :host {
                    --mush-icon-size: 100px;       
                    }
        columns: 5
      - type: horizontal-stack
        cards:
          - type: custom:mushroom-template-card
            icon_color: '#FF4500'
            layout: vertical
            fill_container: false
            primary: HA Settings
            card_mod:
              style:
                mushroom-card: |
                  :host {
                    --mush-icon-size: 100px;       
                    }
            tap_action:
              action: navigate
              navigation_path: /config
            icon: mdi:cog-box
          - type: custom:mushroom-template-card
            icon_color: blue
            layout: vertical
            fill_container: false
            primary: Devices
            tap_action:
              action: navigate
              navigation_path: /config/integrations/dashboard
            icon: mdi:devices
            card_mod:
              style:
                mushroom-card: |
                  :host {
                    --mush-icon-size: 100px;       
                    }
          - type: custom:mushroom-template-card
            icon_color: green
            layout: vertical
            fill_container: false
            primary: Automations
            card_mod:
              style:
                mushroom-card: |
                  :host {
                    --mush-icon-size: 100px;       
                    }
            tap_action:
              action: navigate
              navigation_path: /config/automation/dashboard
            icon: mdi:robot
          - type: custom:mushroom-template-card
            icon_color: purple
            layout: vertical
            fill_container: false
            primary: System
            card_mod:
              style:
                mushroom-card: |
                  :host {
                    --mush-icon-size: 100px;       
                    }
            tap_action:
              action: navigate
              navigation_path: /config/system
            icon: mdi:web
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#cctv'
            name: CCTV
            icon: mdi:cctv
            margin_top_mobile: 10px
            bg_color: '#4ca6ae'
            trigger_entity: input_boolean.motion_detected
            trigger_close: false
            auto_close: '30000'
            trigger_state: 'on'
          - show_state: false
            show_name: false
            camera_view: live
            type: picture-entity
            entity: camera.bedroom_hd_stream
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#living-room'
            name: Living Room
            icon: mdi:sofa
            margin_top_mobile: 10px
            auto_close: '15000'
            bg_color: '#fbbf4c'
          - square: false
            type: grid
            cards:
              - type: custom:mushroom-entity-card
                entity: switch.switch_livingroom_tv_switch
                icon: mdi:television
                icon_color: deep-purple
                name: TV
                tap_action:
                  action: toggle
              - type: custom:mushroom-light-card
                entity: light.livingroom_lamp
                icon: mdi:floor-lamp-torchiere-variant-outline
                name: Lamp
                icon_color: orange
                show_brightness_control: true
                collapsible_controls: true
                tap_action:
                  action: toggle
              - type: custom:mushroom-light-card
                entity: light.livingroom_light
                icon: mdi:ceiling-light
                icon_color: yellow
                show_brightness_control: true
                collapsible_controls: true
                tap_action:
                  action: toggle
              - type: custom:mushroom-entity-card
                entity: binary_sensor.sensor_livingroom_motion_motion
                name: Motion
                icon_color: deep-orange
                fill_container: false
                tap_action:
                  action: more-info
              - type: custom:mushroom-entity-card
                icon: mdi:tablet-dashboard
                name: Dash Screen
                tap_action:
                  action: toggle
                entity: switch.dashboard_living_room_screen
              - type: custom:mushroom-climate-card
                entity: climate.thermostat_1
                show_temperature_control: true
            columns: 2
          - type: horizontal-stack
            cards:
              - type: custom:mushroom-entity-card
                entity: sensor.thermostat_1_boost
                icon_color: accent
                fill_container: true
                layout: vertical
                name: Boost 1 Hour
                tap_action:
                  action: call-service
                  service: hive.boost_heating_on
                  target: {}
                  data:
                    time_period: '01:00:00'
                    temperature: 20
                    entity_id: climate.thermostat_1
              - type: custom:mushroom-entity-card
                entity: sensor.thermostat_1_boost
                icon_color: red
                fill_container: true
                layout: vertical
                name: Boost 2 Hour
                tap_action:
                  action: call-service
                  service: hive.boost_heating_on
                  target: {}
                  data:
                    time_period: '02:00:00'
                    temperature: 20
                    entity_id: climate.thermostat_1
                double_tap_action:
                  action: call-service
                  service: hive.boost_heating_off
                  target: {}
                  data:
                    entity_id: climate.thermostat_1
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#office'
            name: Office
            icon: mdi:chair-rolling
            auto_close: '15000'
            bg_color: '#FF7A9C'
          - square: false
            type: grid
            cards:
              - type: custom:mushroom-entity-card
                entity: switch.office_x1c
                tap_action:
                  action: navigate
                  navigation_path: '#3d'
              - type: custom:mushroom-entity-card
                entity: switch.office_resin_printer
                tap_action:
                  action: toggle
              - type: custom:mushroom-entity-card
                entity: switch.office_wash_station
                tap_action:
                  action: toggle
              - type: custom:mushroom-entity-card
                entity: switch.socket_office_backwall_switch
                tap_action:
                  action: toggle
              - type: custom:mushroom-entity-card
                entity: switch.socket_office_backwall_switch_2
                icon: ''
                icon_color: light-green
                tap_action:
                  action: toggle
              - type: custom:mushroom-entity-card
                entity: switch.socket_office_wall_switch
                name: Spare
                tap_action:
                  action: toggle
              - type: custom:mushroom-entity-card
                entity: switch.socket_office_wall_switch_2
                tap_action:
                  action: toggle
              - type: custom:mushroom-entity-card
                entity: switch.socket_office_topwall_switch
                tap_action:
                  action: toggle
              - type: custom:mushroom-entity-card
                entity: switch.socket_office_topwall_switch_2
                tap_action:
                  action: toggle
              - type: custom:mushroom-entity-card
                tap_action:
                  action: toggle
                name: Big Light
                icon: mdi:ceiling-light
                entity: switch.light_toms_room
            columns: 2
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#dining-room'
            name: Dining Room
            icon: mdi:table-chair
            margin_top_desktop: 10px
            margin_top_mobile: 10px
            bg_color: '#8ebbfd'
          - type: custom:mushroom-entity-card
            entity: switch.socket_diningroom_right_switch
            tap_action:
              action: toggle
          - type: custom:mushroom-entity-card
            entity: switch.socket_diningroom_right_switch_2
            tap_action:
              action: toggle
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#kitchen'
            name: Kitchen
            icon: mdi:stove
            margin_top_mobile: 10px
            bg_color: '#634456'
          - square: false
            type: grid
            cards:
              - type: custom:mushroom-entity-card
                entity: binary_sensor.sensor_kitchen_backdoor_opening
                name: Back Door
                icon: mdi:door
              - type: custom:mushroom-entity-card
                entity: binary_sensor.sensor_kitchen_window_opening
                name: Window
                icon: mdi:window-closed
                tap_action:
                  action: more-info
              - type: custom:mushroom-entity-card
                entity: switch.socket_kitchen_first_switch
                tap_action:
                  action: none
              - type: custom:mushroom-entity-card
                entity: switch.socket_kitchen_first_switch_light
                tap_action:
                  action: toggle
            columns: 2
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#bedroom'
            name: Bedroom
            icon: mdi:bed-empty
            margin_top_mobile: 10px
            bg_color: '#3a683a'
          - square: false
            type: grid
            cards:
              - type: custom:mushroom-entity-card
                entity: sensor.sensor_bedroom_temp_temperature
                name: Temp
              - type: custom:mushroom-entity-card
                entity: sensor.sensor_bedroom_temp_humidity
                name: Humidity
              - type: custom:mushroom-entity-card
                entity: binary_sensor.sensor_bedroom_window_opening
                name: Window
                icon: mdi:window-closed
              - type: custom:mushroom-entity-card
                entity: switch.switch_bedroom_spare_switch
                name: Socket
            columns: 2
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#spare-room'
            name: Spare Room
            icon: mdi:bed-clock
            margin_top_mobile: 10px
            bg_color: '#fbe24c'
            auto_close: '15000'
          - square: false
            type: grid
            cards:
              - type: custom:mushroom-entity-card
                entity: binary_sensor.lumi_lumi_sensor_magnet_aq2_opening
                name: Window
                icon: mdi:window-closed
              - type: custom:mushroom-entity-card
                entity: switch.switch_bedroom_spare_switch
                name: Left Switch
                tap_action:
                  action: toggle
              - type: custom:mushroom-entity-card
                entity: switch.socket_spareroom_wall_switch_2
                name: Right Switch
                tap_action:
                  action: toggle
            columns: 1
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#landing'
            name: Landing / Stairs
            icon: mdi:stairs
            margin_top_mobile: 10px
            bg_blur: 12
            bg_color: '#faf050'
          - square: false
            type: grid
            cards:
              - type: custom:mushroom-light-card
                entity: light.landing_lights
                icon: mdi:ceiling-light-multiple
                name: Landing Lights
                icon_color: orange
                show_brightness_control: true
                collapsible_controls: true
                tap_action:
                  action: toggle
              - type: custom:mushroom-light-card
                entity: light.stairs
                icon: mdi:ceiling-light
                icon_color: yellow
                show_brightness_control: true
                collapsible_controls: true
                tap_action:
                  action: toggle
              - type: custom:mushroom-light-card
                entity: light.landing
                icon: mdi:ceiling-light
                icon_color: amber
                show_brightness_control: true
                collapsible_controls: true
                tap_action:
                  action: toggle
              - type: custom:mushroom-entity-card
                entity: binary_sensor.sensor_stairs_motion_motion
                name: Stairs Motion
              - type: custom:mushroom-entity-card
                entity: binary_sensor.sensor_landing_motion_motion
                name: Landing Motion
            columns: 2
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#under-the-stairs'
            name: Under The Stairs
            icon: mdi:stairs-box
            bg_color: '#a1006b'
          - square: false
            type: grid
            cards:
              - type: custom:mushroom-entity-card
                icon: mdi:vacuum
                entity: switch.understairs_hoover
              - type: custom:mushroom-entity-card
                entity: switch.understairs_dash_charger
                name: Charger - Dash
              - type: custom:mushroom-entity-card
                entity: switch.understairs_powerstrip_spare
            columns: 2
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#settings'
            name: Settings
            icon: mdi:cog
            margin_top_mobile: 10px
            bg_color: '#C70039'
          - type: entities
            entities:
              - sensor.dashboard_living_room_battery_2
              - sensor.dashboard_office_battery
              - sensor.pixel_7_pro_battery_level
              - sensor.pixel_7_pro_battery_state
              - sensor.sensor_bathroom_window_battery
              - sensor.sensor_bedroom_temp_battery
              - sensor.sensor_bedroom_window_battery
              - sensor.sensor_diningroom_innerdoor_battery
              - sensor.sensor_diningroom_motion_battery
              - sensor.sensor_kitchen_backdoor_battery
              - sensor.sensor_kitchen_motion_battery
              - sensor.sensor_kitchen_window_battery
              - sensor.sensor_landing_motion_battery
              - sensor.sensor_livingroom_motion_battery
              - sensor.sensor_office_motion_battery
              - sensor.sensor_office_window_battery
              - sensor.sensor_porch_frontdoor_battery
              - sensor.sensor_porch_letterbox_battery
              - sensor.lumi_lumi_sensor_magnet_aq2_battery
              - sensor.sensor_stairs_motion_battery
              - sensor.small_dash_battery_level
              - sensor.small_dash_battery_state
              - sensor.lumi_lumi_remote_b28ac1_battery
              - sensor.switch_landing_toilet_battery
              - sensor.lumi_lumi_remote_b28ac1_battery_2
              - sensor.thermostat_1_battery_level
              - sensor.tomdash_browser_battery
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#3d'
            icon: mdi:printer-3d-nozzle
            auto_close: '15000'
            bg_color: '#42f57b'
            name: Bambu Lab - X1 Carbon
          - type: custom:mushroom-title-card
            title: 3D Printer Overview
          - show_state: false
            show_name: false
            camera_view: live
            type: picture-entity
            image: https://demo.home-assistant.io/stub_config/bedroom.png
            entity: camera.x1c_00m00a2b0807294_camera
          - type: grid
            cards:
              - type: custom:mushroom-entity-card
                entity: sensor.x1c_00m00a2b0807294_current_stage
                layout: vertical
                name: Stage
              - type: custom:mushroom-entity-card
                entity: sensor.x1c_00m00a2b0807294_current_layer
                name: Current Layer
                layout: vertical
              - type: custom:mushroom-entity-card
                entity: sensor.x1c_00m00a2b0807294_total_layer_count
                name: Layer Count
                icon: mdi:layers
                layout: vertical
          - type: custom:mushroom-entity-card
            entity: switch.office_x1c
`

**Comment by Clooos** [comment]
Hi guys, this error changed and can be ignored if your pop-ups are working. It should also be less sensitive in the new beta.
