### ISSUE TITLE
Action to turn on not working in button card

### ISSUE THREAD

**Issue by cseelmann** [Clooos/Bubble-Card#161]
I noticed it is possible for me to turn entities off in the button card inside of the pop-up, however it is not possible to turn them on other then using the more_info HA pop up. Both for switch and slider. 

YAML tap_action and icon_tap_action: toggle do not work as well as call service. 

Nothing specific in HA logs, despite an error which might be unrelated:
```Logger: frontend.js.latest.202310301
Source: components/system_log/__init__.py:300
First occurred: 12:18:26 (4 occurrences)
Last logged: 12:19:13
Uncaught error from Firefox 119.0 on Linux x86_64 NotFoundError: Node.removeChild: The node to be removed is not a child of this node set hass/T/< (/local/bubble-card.js:1:28751)
```

My entities are all created by the nodered integration, where I create entities via API call (so no unique_id is available and the entity selection does only show the entity_id and not the Name I gave them via API).

**Comment by Clooos** [comment]
Hi! This should be fixed in the new v1.6.0 beta :

https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.0-beta.1
