### ISSUE TITLE
main view still visible through popup

### ISSUE THREAD

**Issue by TheBashan** [Clooos/Bubble-Card#162]
Hello Clooos,

Thank you for this great Add-on!

I have implemented your add-on and creating a couple of popups. My main dashboard is using a custom theme with custom buttons. The problem I am having is that when i open a popup i can still see the text of the main dashboard.

Attached are both views:
![Main dashboard](https://github.com/Clooos/Bubble-Card/assets/65565159/2dbf0275-07f6-4924-b19c-681b7f7fe876)
![Popup card](https://github.com/Clooos/Bubble-Card/assets/65565159/c80505f5-20f0-4ee9-ae16-dc472684d5d7)

Could you tell me if this is related to the custom cards i'm using on my main dashboard?

**Comment by hellomarb** [comment]
It looks like a z-index issue, I use this card_mod style on all my popup cards:

```
    styles: |
      div#root {
        z-index: 5 !important;
      }
```

**Comment by TinyShark** [comment]
double check the order of your cards. Popups should be after all other cards on your dashboard.

I had the same issue before and re-ordering fixed it.

See #97

**Comment by TheBashan** [comment]
> double check the order of your cards. Popups should be after all other cards on your dashboard.
> 
> I had the same issue before and re-ordering fixed it.
> 
> See #97

Thats correct. I already had my popups last in my yaml file.



> It looks like a z-index issue, I use this card_mod style on all my popup cards:
> 
> ```
>     styles: |
>       div#root {
>         z-index: 5 !important;
>       }
> ```

This solved my issue! Thank you!
