### ISSUE TITLE
Portait Mode on Tablet PopUp Card ist not centered

### ISSUE THREAD

**Issue by mrfrag1** [Clooos/Bubble-Card#166]
Hi, 

I have a problem with portrait mode. My dashboard on the tablet is set portrait. The bubble cards are displayed too far to the right. It fits in landscape format.
Does anyone have a solution

![bubble_card](https://github.com/Clooos/Bubble-Card/assets/108211193/12fcfb5f-45f2-4628-a377-3dbe67ae7c44)

**Comment by mrfrag1** [comment]
I think I know the problem.

The pop-up cards are on the same dashboard as the rest.
But the pop-ups are not visible.

Nevertheless, the bubble integration centers the cards including invisible pop-up cards.

So it's not really centered.

Do the pop-up cards have to be on the same dashboard?

Or can I put it on another dashboard and access it from the original dashboard?

**Comment by Clooos** [comment]
Hi and thanks for your feedback, can you show me your YAML code for this pop-up?

**Comment by mrfrag1** [comment]
Suddenly it's ok. I just did a reboot.
You can close the issue.

Thanks. but I still have to open a feature request 

type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#shutter'
    name: Rolläden
    icon: mdi:window-shutter
    entity: light.alle_lampen
    width_desktop: 600px
    width_mobile: 600px
    margin_top_mobile: 7px
    margin_top_desktop: 13px
    styles: |
      #root { 
        opacity: 0.95; 
      }
    auto_close: 15000
  - type: custom:bubble-card
    card_type: separator
    name: Küche - Wohnzimmer
    icon: mdi:countertop-outline
    card_mod:
      style: |
        ha-card {
          
          margin-top:0px;
          margin-bottom: -10px;
          
        }
  - type: horizontal-stack
    cards:
      - type: tile
        entity: cover.rolladen_kuche
        hide_state: false
        show_entity_picture: true
        features:
          - type: cover-open-close
          - type: cover-position
        name: Küche
      - type: tile
        entity: cover.rolladen_terrasse
        hide_state: false
        show_entity_picture: true
        features:
          - type: cover-open-close
          - type: cover-position
        name: Terasse
  - type: horizontal-stack
    cards:
      - type: tile
        entity: cover.rolladen_tv
        hide_state: false
        show_entity_picture: true
        features:
          - type: cover-open-close
          - type: cover-position
        name: TV
      - type: tile
        entity: cover.wohnzimmer_gross
        hide_state: false
        show_entity_picture: true
        features:
          - type: cover-open-close
          - type: cover-position
        name: Wohnz. groß
  - type: custom:bubble-card
    card_type: separator
    name: Schlafzimmer
    icon: mdi:bed
    card_mod:
      style: |
        ha-card {
          
          margin-top: -0px;
          margin-bottom: -10px;
        }
  - type: horizontal-stack
    cards:
      - type: tile
        entity: cover.rolladen_balkon
        hide_state: false
        show_entity_picture: true
        features:
          - type: cover-open-close
          - type: cover-position
        name: Balkon
      - type: tile
        entity: cover.schlafzimmer_gross
        hide_state: false
        show_entity_picture: true
        features:
          - type: cover-open-close
          - type: cover-position
        name: Schlafz. groß
