### ISSUE TITLE
Feature Request: Add tap action to buttons

### ISSUE THREAD

**Issue by brpeterso** [Clooos/Bubble-Card#17]
Can you add the tap action to the button/slider? Instead of pulling up more info for lights, it would be great to assign toggle and then more info can be on double tap or hold...depending on what user wants. Thanks.

**Comment by Clooos** [comment]
This is definitely something that is missing and I will add that in a future release.

**Comment by chrjsorg** [comment]
<img width="519" alt="toggle" src="https://github.com/Clooos/Bubble-Card/assets/441326/7740127a-c3ad-429a-80cf-21577458e1f4">
Tap on this area should toggle the switch/slider by default, yeah.

**Comment by mattmon** [comment]
I'd like to see this feature also. 
Though, I still want to access the more info dialog (or link to another vertical stack)
Would it be possible to also  have an option to do that?

As an example, if this image was exclusively a light slider: 
![266340800-8b578756-5c7e-4a03-a96d-6db1c93b71b3](https://github.com/Clooos/Bubble-Card/assets/924673/2e850a45-229e-4883-9f3e-e5cf5e353c3b)
maybe the link could occupy the same space as the power or X buttons.

**Comment by Clooos** [comment]
This is now a new feature in the new beta! 
https://github.com/Clooos/Bubble-Card/releases/tag/v0.0.1-beta.7

**Comment by crafty35a** [comment]
> This is now a new feature in the new beta! https://github.com/Clooos/Bubble-Card/releases/tag/v0.0.1-beta.7

Any chance we could get this in the UI editor, similar to how Mushroom cards work? Thank you!
