### ISSUE TITLE
Feature request: call service on closing popup

### ISSUE THREAD

**Issue by hellomarb** [Clooos/Bubble-Card#171]
Following usecase:

- The content of a popup is inside a conditional card, that's activated when an input_boolean is on
- **Part of an walkaround:** A trigger (in my case a mushroom chip) calls a button press that starts an automation to reset an input_boolean if needed, if I deactivate the input_boolean, I lose the conditional card
- The popup is opened on entity_trigger state on of the input_boolean
- **New feature:** on close I want to reset the input_boolean back to off and need to call a service

Perhaps it could be integrated as "action" for the close button?

**Comment by hellomarb** [comment]
With the new approach with the 1.5 beta we can skip that ;)

**Comment by Clooos** [comment]
Thanks for your feedback! Can you tell me more about that?

**Comment by hellomarb** [comment]
It was my attempt to make complex dashboards usable, but since you have integrated the logic now in the beta, it isn't needed (for me) anymore. It felt too complicated for that anyway, always a bad sign.

**Comment by Clooos** [comment]
I’m glad to see this finally functioning as intended (fingers crossed!). After dedicating days to optimizations, my focus is on ensuring stability before introducing new features. I plan to take some time to continue testing this new beta version before that.
