### ISSUE TITLE
Feature Request: Order on Horizontal Stack

### ISSUE THREAD

**Issue by shawndamon** [Clooos/Bubble-Card#172]
Order on Horizontal Buttons stack for some reason was not following what i have set on yaml.

I changed the Auto Order to False and it worked but wondering if this should be on the UI?

<img width="993" alt="Screenshot 2023-11-12 at 11 44 31 PM" src="https://github.com/Clooos/Bubble-Card/assets/31374940/b1e64813-1ef0-4055-bd30-f808c61ee45a">

**Comment by Clooos** [comment]
This is because of the `auto_order` and also because of the `2_pir_sensor`, you can set `auto_order` to `false` and remove `2_pir_sensor` because it's useless with only one sensor. I hope this helps!

**Comment by shawndamon** [comment]
thank you for letting me know
