### ISSUE TITLE
Custom element doesn't exist: bubble-pop-up.

### ISSUE THREAD

**Issue by kevinbegley** [Clooos/Bubble-Card#184]
Hello,

I just updated to 1.5.0 and as part of the update I added the following to the configuration file. However, when I update the card to "custom: bubble-pop-up" and I get the error "Custom element doesn't exist: bubble-pop-up.".  
frontend:
  extra_module_url:
    - /hacsfiles/Bubble-Card/bubble-pop-up.js

Thank you,
Kevin

**Comment by meanaverage** [comment]
Same here. Tried using 'config/www/community' as well but I guess hacsfiles is supposed to be an alias for that so shouldn't matter. Bummer.

**Comment by meanaverage** [comment]
This is my .storage/lovelace_resources file:

{
  "version": 1,
  "minor_version": 1,
  "key": "lovelace_resources",
  "data": {
    "items": [
      {
        "id": "77e731b0c1f143e39043a47e5f27149f",
        "url": "/hacsfiles/vacuum-card/vacuum-card.js?hacstag=261291295276",
        "type": "module"
      },
      {
        "id": "b05bb660c28146fd83a95dfcb612ea28",
        "url": "/hacsfiles/Bubble-Card/bubble-card.js?hacstag=680112919150",
        "type": "module"
      }
    ]
  }
}

I feel like the issue is bubble-pop-up.js is not here? The extra_module_url line in config yaml seems to do nothing? Does a certain mode need to be enabled in order to use that tag? Extremely new to HA, just installed it a couple days ago. Could use some direction here. I want to bubble!

**Comment by Clooos** [comment]
Hi and thanks for your feedback. Have you rebooted Home Assistant? Can you show me your browser console if it's not the case?

**Comment by meanaverage** [comment]
I had rebooted multiple times. I checked dev tools in my browser and I had network record mode on from a previous 'adventure'. After turning it off and clearing my record log and wiping console, it actually started working. No clue how that could have been the issue but maybe record mode was holding my cache or something.

But now the 'add button' on the horizontal stack (inside of a vertical stack, first card = pop-up card, second card = horizonal stack) does not work. It's not clickable. This seems to be a separate issue though. Think I'm going to bed and will just come back tomorrow and see if these are broader issues with this update or I just need to reboot my client machine vs. my home assistant vm.

Thanks for developing this. Looks really nice. Excited to use it.

**Comment by Clooos** [comment]
Glad that you find out how to make it work! 😀

**Comment by KKox-26** [comment]
Hello i have the same issue on android, it works on my browser.

I have cleared the cache data in android but i have the message "Custom element doesn't exist: bubble-pop-up."

**Comment by TheFinalJoke** [comment]
Hey Everyone! I was having this problem in chrome and I was checking everything and follow the instructions. I finally got it working by refreshing my cache in my browser. I wonder if they cached has default card options and card locations. But might be worth to note in the installation for Existing Users to refresh the cache! Love this card and thanks for making it!

**Comment by Clooos** [comment]
I will add that in the instructions, thanks for your feedback!

**Comment by mrgrlscz** [comment]
I had to do the same (delete home assistant Android app's user data)

**Comment by guy0nabuffalo** [comment]
Having this issue on Android app. Tried clearing the app cache, did not clear the data. Still showing custom element doesn't exist: bubble-pop-up. It's working fine on desktop Chrome.

**Comment by meanaverage** [comment]
As a new user of bubble card, having never installed a previous version, I
had all of the same issues with the bubble-popup-card error. Also had lots
of problems with mdi icons not auto-completing and had to edit source
manually. Most of these issues have gone away with time, but persisted for
2 days and across different devices and browsers while they were occurring.

I can't really explain why the issues stopper, but the only advice I can
give is CLEAR YOUR CACHE on any and every device you're using to access HA
and give Bubble Card some time to get settled in.

Let it breathe. Go to bed. Wake up. Go to bed again. Try Bubble Card after
you're well rested and seemingly out of nowhere all of the hiccups may be
gone. Browsers need sleep, too.

**Comment by Shinigami777** [comment]
I also have a problem. i have Restarted HA multiple times, clear cache and problem still persistent on HA app on android and on browser on windows. Any advice what to do next?

**Comment by meanaverage** [comment]
> I also have a problem. i have Restarted HA multiple times, clear cache and problem still persistent on HA app on android and on browser on windows. Any advice what to do next? 

Please try using another browser you have not accessed HA with since you installed, or the Home Assistant application itself. If either of those works, clear cache in the browser which isn't working properly with bubble card, then kill all processes related to the browser or reboot your client machine (not HA) if you can, assuming that you've already rebooted HA.

**Comment by Shinigami777** [comment]
> > I also have a problem. i have Restarted HA multiple times, clear cache and problem still persistent on HA app on android and on browser on windows. Any advice what to do next?
> 
> Please try using another browser you have not accessed HA with since you installed, or the Home Assistant application itself. If either of those works, clear cache in the browser which isn't working properly with bubble card, then kill all processes related to the browser or reboot your client machine (not HA) if you can, assuming that you've already rebooted HA.

Ok, I've jus did this and it seems that everything only works in browsers that I haven't used before. But on others, this problem occurs even after clearing the cache.
