### ISSUE TITLE
Light sliders (standard tiles and mushrooms) are not shown correctly in popups

### ISSUE THREAD

**Issue by Nazze** [Clooos/Bubble-Card#185]
Hi

if I add a standard tile card for a light entity with a slider for e.g. brightness into a popup-up it looks like this. 

![IMG_8699](https://github.com/Clooos/Bubble-Card/assets/33813707/1741b3ea-73fd-4f1f-9775-32219c72de13)

Also mushroom light cards with sliders don’t look correctly (squared instead of round edges). 

![IMG_8700](https://github.com/Clooos/Bubble-Card/assets/33813707/97392a00-8425-4542-b04f-a69326c8fe07)

KR
Denis

**Comment by Clooos** [comment]
Hi and thanks for your feedback!

I've just tried and I can't replicate your issue, here is how it looks on my test setup:

<img width="568" alt="image" src="https://github.com/Clooos/Bubble-Card/assets/36499953/0a1a89f7-f2f0-4eff-b5e2-199226d6238b">

**Comment by Nazze** [comment]
Actually, after playing around with the themes it is not happening atm. 
I saw it in a regular dashboard in edit mode, too, so I don’t think it is a bubble card issue. 
I will close it for now. Thanks and sorry for the inconvenience
