### ISSUE TITLE
problem since  v1.5.0

### ISSUE THREAD

**Issue by N0BaDaY** [Clooos/Bubble-Card#188]
>
Since updating to v1.5.0 I get this notification of which I don’t understand the first sentence: “…you need to manually add a new frontend extra module into you configuration.yaml”.
Now I know how to edit my configuration.yaml but I don’t understand what I have to add specifically.
Any help on this would be appreciated as I really love bubbling!!
![IMG_4445](https://github.com/Clooos/Bubble-Card/assets/60921630/9e8964de-a119-4895-b837-c164fcd1c1ab)

**Comment by erikgeurts** [comment]
This is explained in the release notes at https://github.com/Clooos/Bubble-Card/releases/tag/v1.5.0

**Comment by N0BaDaY** [comment]
Thanks for the swift response…Seems liked I missed those.

**Comment by forfeitjunk** [comment]
I reverted to 1.4.4, updated all my bubble cards with - type: custom:bubble-pop-up and then upgraded to 1.5.0 and it worked
