### ISSUE TITLE
Feature Request: slider outline

### ISSUE THREAD

**Issue by brpeterso** [Clooos/Bubble-Card#19]
When using certain themes, it means you don't have visibility of the the sliders until they are on.  Would it be possible to have a thin outline of the icon area and the slider area? This is different from the card border you recently fixed. Maybe this could be accomplished using card_mod, but I haven't had luck just yet. 

Example below:
1) First light group has a lighter background, so you lose slider shape. 
2) Second light group...When at the top/bottom of a stacked card, you lose outer edge of slider. 
3) Third light group is just a mushroom example for comparison. 

![image](https://github.com/Clooos/Bubble-Card/assets/24624605/c20269ed-d126-4a5e-8ce1-9fa070462946)

Fyi...using waves dark theme. 

Thanks.

**Comment by Clooos** [comment]
Hi and thanks for the feedback, you can add a border to your buttons easily with card-mod, just add this:

```
card_mod:
  style: |
    ha-card {
        border: 1px solid white !important;
    }
```

**Comment by brpeterso** [comment]
So I just tried this.  This solution gives a border for the card (rectangle), but not for the slider.  I was thinking is there a way to have a border that follows the round edges of the slider and the icon circle.

**Comment by Clooos** [comment]
Oh yeah I forgot, add this:
```
card_mod:
  style: |
    ha-card {
        border-radius: 25px !important;
        border: 1px solid white !important;
    }
```
