### ISSUE TITLE
Feature Request: Auto/dynamic entity display

### ISSUE THREAD

**Issue by Coder84619** [Clooos/Bubble-Card#192]
I would love the ability to dynamically show a specific class of entities, such as ALL lights. And I'd love to also narrow it to specific area(s), such as ALL lights in the Entry and Kitchen. Same goes for other classes such as covers, camera, motion sensors, etc. And even more advanced, provide a filter to only show entities in a particular state (e.g. on or off). So for instance a card would dynamically show only ON lights in the Kitchen.

**Comment by twanjaarsveld** [comment]
That already exist its awesome i'm using it for years now 
[](https://github.com/thomasloven/lovelace-auto-entities)

**Comment by twanjaarsveld** [comment]
Here im using it to show all the lights that are on in a Bubble-pop-up card  

type: vertical-stack
cards:
  - type: custom:bubble-pop-up
    hash: '#verlichting'
    back_open: true
  - type: grid
    cards:
      - type: custom:button-card
        entity: light.woonkamer_hue
        color: auto
        color_type: card
        state:
          - value: 'off'
            styles:
              card:
                - filter: opacity(70%)
          - value: 'on'
            styles:
              name:
                - color: black
              label:
                - color: black
              icon:
                - color: black
        tap_action:
          action: toggle
        hold_action:
          action: more-info
        double_tap_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.popup
            data:
              size: normal
              content:
                type: custom:auto-entities
                icon: null
                card:
                  type: entities
                  show_header_toggle: false
                  state_color: false
                filter:
                  include:
                    - domain: light
                      area: Woonkamer
                  exclude:
                    - state: unavailable
                sort:
                  method: friendly_name
                  numeric: false
                  reverse: false
                show_empty: true
        name: Woonkamer
        aspect_ratio: 1/1
        styles:
          card:
            - font-size: 12px
            - font-weight: bold
      - type: custom:button-card
        entity: light.keuken_hue
        color: auto
        color_type: card
        state:
          - value: 'off'
            styles:
              card:
                - filter: opacity(70%)
          - value: 'on'
            styles:
              name:
                - color: black
              label:
                - color: black
              icon:
                - color: black
        tap_action:
          action: toggle
        hold_action:
          action: more-info
        double_tap_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.popup
            data:
              size: normal
              content:
                type: custom:auto-entities
                icon: null
                card:
                  type: entities
                  show_header_toggle: false
                  state_color: false
                filter:
                  include:
                    - domain: light
                      area: Keuken
                  exclude:
                    - state: unavailable
                sort:
                  method: friendly_name
                  numeric: false
                  reverse: false
                show_empty: true
        name: Keuken
        aspect_ratio: 1/1
        styles:
          card:
            - font-size: 12px
            - font-weight: bold
      - type: custom:button-card
        entity: light.tuin_hue
        color: auto
        color_type: card
        state:
          - value: 'off'
            styles:
              card:
                - filter: opacity(70%)
          - value: 'on'
            styles:
              name:
                - color: black
              label:
                - color: black
              icon:
                - color: black
        tap_action:
          action: toggle
        hold_action:
          action: more-info
        double_tap_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.popup
            data:
              size: normal
              content:
                type: custom:auto-entities
                icon: null
                card:
                  type: entities
                  show_header_toggle: false
                  state_color: false
                filter:
                  include:
                    - domain: light
                      area: Tuin
                  exclude:
                    - state: unavailable
                sort:
                  method: friendly_name
                  numeric: false
                  reverse: false
                show_empty: true
        name: Tuin
        aspect_ratio: 1/1
        styles:
          card:
            - font-size: 12px
            - font-weight: bold
      - type: custom:button-card
        entity: light.slaapkamer_hue
        color: auto
        color_type: card
        state:
          - value: 'off'
            styles:
              card:
                - filter: opacity(70%)
          - value: 'on'
            styles:
              name:
                - color: black
              label:
                - color: black
              icon:
                - color: black
        tap_action:
          action: toggle
        hold_action:
          action: more-info
        double_tap_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.popup
            data:
              size: normal
              content:
                type: custom:auto-entities
                icon: null
                card:
                  type: entities
                  show_header_toggle: false
                  state_color: false
                filter:
                  include:
                    - domain: light
                      area: Slaapkamer
                  exclude:
                    - state: unavailable
                sort:
                  method: friendly_name
                  numeric: false
                  reverse: false
                show_empty: true
        name: Slaapkamer
        aspect_ratio: 1/1
        styles:
          card:
            - font-size: 12px
            - font-weight: bold
      - type: custom:button-card
        entity: light.kantoor_hue
        color: auto
        color_type: card
        state:
          - value: 'off'
            styles:
              card:
                - filter: opacity(70%)
          - value: 'on'
            styles:
              name:
                - color: black
              label:
                - color: black
              icon:
                - color: black
        tap_action:
          action: toggle
        hold_action:
          action: more-info
        double_tap_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.popup
            data:
              size: normal
              content:
                type: custom:auto-entities
                icon: null
                card:
                  type: entities
                  show_header_toggle: false
                  state_color: false
                filter:
                  include:
                    - domain: light
                      area: Kantoor
                  exclude:
                    - state: unavailable
                sort:
                  method: friendly_name
                  numeric: false
                  reverse: false
                show_empty: true
        name: Kantoor
        aspect_ratio: 1/1
        styles:
          card:
            - font-size: 12px
            - font-weight: bold
      - type: custom:button-card
        entity: light.eetkamer_hue
        color: auto
        color_type: card
        state:
          - value: 'off'
            styles:
              card:
                - filter: opacity(70%)
          - value: 'on'
            styles:
              name:
                - color: black
              label:
                - color: black
              icon:
                - color: black
        tap_action:
          action: toggle
        hold_action:
          action: more-info
        double_tap_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.popup
            data:
              size: normal
              content:
                type: custom:auto-entities
                icon: null
                card:
                  type: entities
                  show_header_toggle: false
                  state_color: false
                filter:
                  include:
                    - domain: light
                      area: Eetkamer
                  exclude:
                    - state: unavailable
                sort:
                  method: friendly_name
                  numeric: false
                  reverse: false
                show_empty: true
        name: Eetkamer
        aspect_ratio: 1/1
        styles:
          card:
            - font-size: 12px
            - font-weight: bold
      - type: custom:button-card
        entity: light.babykamer_hue
        color: auto
        color_type: card
        state:
          - value: 'off'
            styles:
              card:
                - filter: opacity(70%)
          - value: 'on'
            styles:
              name:
                - color: black
              label:
                - color: black
              icon:
                - color: black
        tap_action:
          action: toggle
        hold_action:
          action: more-info
        double_tap_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.popup
            data:
              size: normal
              content:
                type: custom:auto-entities
                icon: null
                card:
                  type: entities
                  show_header_toggle: false
                  state_color: false
                filter:
                  include:
                    - domain: light
                      area: Babykamer
                  exclude:
                    - state: unavailable
                sort:
                  method: friendly_name
                  numeric: false
                  reverse: false
                show_empty: true
        name: Babykamer
        aspect_ratio: 1/1
        styles:
          card:
            - font-size: 12px
            - font-weight: bold
      - type: custom:button-card
        entity: light.gang_hue
        color: auto
        color_type: card
        state:
          - value: 'off'
            styles:
              card:
                - filter: opacity(70%)
          - value: 'on'
            styles:
              name:
                - color: black
              label:
                - color: black
              icon:
                - color: black
        tap_action:
          action: toggle
        hold_action:
          action: more-info
        double_tap_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.popup
            data:
              size: normal
              content:
                type: custom:auto-entities
                icon: null
                card:
                  type: entities
                  show_header_toggle: false
                  state_color: false
                filter:
                  include:
                    - domain: light
                      area: Gang
                  exclude:
                    - state: unavailable
                sort:
                  method: friendly_name
                  numeric: false
                  reverse: false
                show_empty: true
        name: Gang
        aspect_ratio: 1/1
        styles:
          card:
            - font-size: 12px
            - font-weight: bold
      - type: custom:button-card
        entity: light.kerst
        color: auto
        color_type: card
        state:
          - value: 'off'
            styles:
              card:
                - filter: opacity(70%)
          - value: 'on'
            styles:
              name:
                - color: black
              label:
                - color: black
              icon:
                - color: black
        tap_action:
          action: toggle
        hold_action:
          action: more-info
        double_tap_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.popup
            data:
              size: normal
              content:
                type: custom:auto-entities
                icon: null
                card:
                  type: entities
                  show_header_toggle: false
                  state_color: false
                filter:
                  include:
                    - domain: light
                      area: Gang
                  exclude:
                    - state: unavailable
                sort:
                  method: friendly_name
                  numeric: false
                  reverse: false
                show_empty: true
        name: Kerst
        icon: mdi:pine-tree
        aspect_ratio: 1/1
        styles:
          card:
            - font-size: 12px
            - font-weight: bold
    square: true
    columns: 3
  - square: true
    title: Automatische verlichting
    type: grid
    cards:
      - type: custom:button-card
        entity: automation.living_light_on
        icon: mdi:sofa
        name: Woonkamer
        show_state: true
        styles:
          grid:
            - grid-template-areas: '"i" "n" "s"'
            - grid-template-columns: 1fr 40%
            - grid-template-rows: 1fr min-content min-content
          img_cell:
            - align-self: start
            - text-align: start
          name:
            - justify-self: start
            - padding-left: 20%
            - font-weight: bold
          state:
            - justify-self: start
            - padding-left: 20%
            - padding-bottom: 10%
        state:
          - value: 'off'
            styles:
              card:
                - filter: opacity(80%)
              icon:
                - filter: grayscale(100%)
        double_tap_action:
          action: fire-dom-event
          browser_mod:
            command: popup
            hide_header: true
            title: |
              [[[ return entity.attributes.friendly_name ]]]
            card:
              type: entities
              entities:
                - type: custom:light-popup-card
                  entity: |
                    [[[ return entity.entity_id ]]]
                  icon: none
                  fullscreen: false
                  brightnessWidth: 130px
                  brightnessHeight: 460px
                  borderRadius: 2.7em
                  sliderColoredByLight: true
                  sliderTrackColor: rgba(25, 25, 25, 0.9)
        aspect_ratio: 1/1
      - type: custom:button-card
        entity: automation.kitchen
        icon: mdi:stove
        name: Keuken
        show_state: true
        styles:
          grid:
            - grid-template-areas: '"i" "n" "s"'
            - grid-template-columns: 1fr 40%
            - grid-template-rows: 1fr min-content min-content
          img_cell:
            - align-self: start
            - text-align: start
          name:
            - justify-self: start
            - padding-left: 20%
            - font-weight: bold
          state:
            - justify-self: start
            - padding-left: 20%
            - padding-bottom: 10%
        state:
          - value: 'off'
            styles:
              card:
                - filter: opacity(80%)
              icon:
                - filter: grayscale(100%)
        double_tap_action:
          action: fire-dom-event
          browser_mod:
            command: popup
            hide_header: true
            title: |
              [[[ return entity.attributes.friendly_name ]]]
            card:
              type: entities
              entities:
                - type: custom:light-popup-card
                  entity: |
                    [[[ return entity.entity_id ]]]
                  icon: none
                  fullscreen: false
                  brightnessWidth: 130px
                  brightnessHeight: 460px
                  borderRadius: 2.7em
                  sliderColoredByLight: true
                  sliderTrackColor: rgba(25, 25, 25, 0.9)
        aspect_ratio: 1/1
      - type: custom:button-card
        entity: automation.bedroom_lights
        icon: mdi:bed
        name: Slaapkamer
        show_state: true
        styles:
          grid:
            - grid-template-areas: '"i" "n" "s"'
            - grid-template-columns: 1fr 40%
            - grid-template-rows: 1fr min-content min-content
          img_cell:
            - align-self: start
            - text-align: start
          name:
            - justify-self: start
            - padding-left: 20%
            - font-weight: bold
          state:
            - justify-self: start
            - padding-left: 20%
            - padding-bottom: 10%
        state:
          - value: 'off'
            styles:
              card:
                - filter: opacity(80%)
              icon:
                - filter: grayscale(100%)
        double_tap_action:
          action: fire-dom-event
          browser_mod:
            command: popup
            hide_header: true
            title: |
              [[[ return entity.attributes.friendly_name ]]]
            card:
              type: entities
              entities:
                - type: custom:light-popup-card
                  entity: |
                    [[[ return entity.entity_id ]]]
                  icon: none
                  fullscreen: false
                  brightnessWidth: 130px
                  brightnessHeight: 460px
                  borderRadius: 2.7em
                  sliderColoredByLight: true
                  sliderTrackColor: rgba(25, 25, 25, 0.9)
        aspect_ratio: 1/1
      - type: custom:button-card
        entity: automation.dining
        name: Eetkamer
        icon: mdi:table-chair
        show_state: true
        styles:
          grid:
            - grid-template-areas: '"i" "n" "s"'
            - grid-template-columns: 1fr 40%
            - grid-template-rows: 1fr min-content min-content
          img_cell:
            - align-self: start
            - text-align: start
          name:
            - justify-self: start
            - padding-left: 20%
            - font-weight: bold
          state:
            - justify-self: start
            - padding-left: 20%
            - padding-bottom: 10%
        state:
          - value: 'off'
            styles:
              card:
                - filter: opacity(80%)
              icon:
                - filter: grayscale(100%)
        double_tap_action:
          action: fire-dom-event
          browser_mod:
            command: popup
            hide_header: true
            title: |
              [[[ return entity.attributes.friendly_name ]]]
            card:
              type: entities
              entities:
                - type: custom:light-popup-card
                  entity: |
                    [[[ return entity.entity_id ]]]
                  icon: none
                  fullscreen: false
                  brightnessWidth: 130px
                  brightnessHeight: 460px
                  borderRadius: 2.7em
                  sliderColoredByLight: true
                  sliderTrackColor: rgba(25, 25, 25, 0.9)
        aspect_ratio: 1/1
      - type: custom:button-card
        entity: automation.motion_office_lights
        name: Kantoor
        icon: mdi:desk-lamp
        show_state: true
        styles:
          grid:
            - grid-template-areas: '"i" "n" "s"'
            - grid-template-columns: 1fr 40%
            - grid-template-rows: 1fr min-content min-content
          img_cell:
            - align-self: start
            - text-align: start
          name:
            - justify-self: start
            - padding-left: 20%
            - font-weight: bold
          state:
            - justify-self: start
            - padding-left: 20%
            - padding-bottom: 10%
        state:
          - value: 'off'
            styles:
              card:
                - filter: opacity(80%)
              icon:
                - filter: grayscale(100%)
        double_tap_action:
          action: fire-dom-event
          browser_mod:
            command: popup
            hide_header: true
            title: |
              [[[ return entity.attributes.friendly_name ]]]
            card:
              type: entities
              entities:
                - type: custom:light-popup-card
                  entity: |
                    [[[ return entity.entity_id ]]]
                  icon: none
                  fullscreen: false
                  brightnessWidth: 130px
                  brightnessHeight: 460px
                  borderRadius: 2.7em
                  sliderColoredByLight: true
                  sliderTrackColor: rgba(25, 25, 25, 0.9)
        aspect_ratio: 1/1
      - type: custom:button-card
        entity: automation.hallway_lights
        name: Gang
        icon: mdi:hanger
        show_state: true
        styles:
          grid:
            - grid-template-areas: '"i" "n" "s"'
            - grid-template-columns: 1fr 40%
            - grid-template-rows: 1fr min-content min-content
          img_cell:
            - align-self: start
            - text-align: start
          name:
            - justify-self: start
            - padding-left: 20%
            - font-weight: bold
          state:
            - justify-self: start
            - padding-left: 20%
            - padding-bottom: 10%
        state:
          - value: 'off'
            styles:
              card:
                - filter: opacity(80%)
              icon:
                - filter: grayscale(100%)
        double_tap_action:
          action: fire-dom-event
          browser_mod:
            command: popup
            hide_header: true
            title: |
              [[[ return entity.attributes.friendly_name ]]]
            card:
              type: entities
              entities:
                - type: custom:light-popup-card
                  entity: |
                    [[[ return entity.entity_id ]]]
                  icon: none
                  fullscreen: false
                  brightnessWidth: 130px
                  brightnessHeight: 460px
                  borderRadius: 2.7em
                  sliderColoredByLight: true
                  sliderTrackColor: rgba(25, 25, 25, 0.9)
        aspect_ratio: 1/1
    columns: 4
  - square: false
    columns: 1
    type: grid
    title: 'Lampen aan:'
    cards:
      - type: custom:auto-entities
        filter:
          include:
            - domain: light
              state: 'on'
          exclude:
            - attributes:
                type: browser_mod
        card:
          show_name: true
          show_icon: true
          show_state: false
          type: glance
          state_color: true
          columns: 3
        show_empty: false
        sort:
          method: last_changed
          reverse: true

**Comment by Clooos** [comment]
Hi and thanks for your suggestions, but as @twanjaarsveld said they are other solutions and I'm not planning to add that to Bubble Card, at least for now.
