### ISSUE TITLE
HA app can't recognize "custom:bubble-pop-up"

### ISSUE THREAD

**Issue by tikel1** [Clooos/Bubble-Card#193]
I updated to v15 via HACS and changed my configuation.yaml file.
This works well in the browser, but won't work on my app (tablet and phone)
Tried clearing cache

![image](https://github.com/Clooos/Bubble-Card/assets/121404448/c2036a1c-0712-4bb3-8e64-b5a8c4542d9c)

**Comment by panhans** [comment]
Already discussed here: https://github.com/Clooos/Bubble-Card/issues/189#issuecomment-1818487145
