### ISSUE TITLE
To do list it is not updating when the pop up is hidden

### ISSUE THREAD

**Issue by tobalowar** [Clooos/Bubble-Card#194]
I have a pop up that shows me my shopping listbut after updating to 1.5.0 if I add an item to my to do list while the pop up was hidden, is not displayed on the list...but if i add a new item when the pop up is displayed, it work without problems

**Comment by Clooos** [comment]
Hi! This is now fixed in the new v1.6.0 beta!

https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.0-beta.1
