### ISSUE TITLE
button_type: custom not showing icon?

### ISSUE THREAD

**Issue by willliamchan** [Clooos/Bubble-Card#197]
Happy Tuesday! First time using it, and somehow it is not showing the icon.

type: custom:bubble-card
card_type: button
button_type: custom
entity: binary_sensor.front_door
name: Entrance
show_state: true

![image](https://github.com/Clooos/Bubble-Card/assets/54702221/13a8ddb8-e0aa-4553-a136-008a51e8bbc5)

Any thoughts?

**Comment by Clooos** [comment]
For now they are no default icons for entities without custom icons, you need to define it manually. But I will change that in the future.
