### ISSUE TITLE
pop up card not working

### ISSUE THREAD

**Issue by Davecl** [Clooos/Bubble-Card#198]
I've updated to version 1.5 

I've added the extra module to configuration.yaml and altered my pop-ups accordingley but I get the following error

Custom element doesn't exist: bubble-pop-up.
type: custom:bubble-pop-up
card_type: pop-up

any ideas?
thanks

**Comment by danielholm** [comment]
In my setup I the URL of the new module file (.js) was wrong. The correct path on my setuo (HAOS) was /config/www/community/Bubble-Card/bubble-pop-up.js

See if yours is correct.

**Comment by Davecl** [comment]
> In my setup I the URL of the new module file (.js) was wrong. The correct path on my setuo (HAOS) was /config/www/community/Bubble-Card/bubble-pop-up.js
> 
> See if yours is correct.

Thanks, I'll have a look

**Comment by Clooos** [comment]
This is already discussed here:
https://github.com/Clooos/Bubble-Card/issues/189

But I'm on it!

**Comment by Davecl** [comment]
> This is already discussed here:
> [#189 custom element doesnt exist: bubble-pop-up](https://github.com/Clooos/Bubble-Card/issues/189)
> 
> But I'm on it!

Thanks 👍👍
