### ISSUE TITLE
No Preview

### ISSUE THREAD

**Issue by tempus2016** [Clooos/Bubble-Card#2]
There is no preview when an light is selected or entered into the entity box. It only shows after your save the card.
<img width="1651" alt="Screenshot 2023-08-28 at 20 52 58" src="https://github.com/Clooos/Bubble-Card/assets/40920327/e29e004b-40d6-4fe8-9154-5cc30331f365">

There is also a weird shadow when you select a button card.
<img width="1651" alt="Screenshot 2023-08-28 at 20 56 07" src="https://github.com/Clooos/Bubble-Card/assets/40920327/c89e9c1d-2de2-4d2f-9b14-0e58b791136f">

**Comment by youcube** [comment]
+1 Having also this issue

**Comment by Clooos** [comment]
The weird shadow is fixed in beta 4, and for now the live preview is only working for the Bubble Cards that are created inside of a pop-up, but I'm on it!

**Comment by Clooos** [comment]
This is now possible in the new beta, see here :
https://github.com/Clooos/Bubble-Card/releases/tag/v0.0.1-beta.9
