### ISSUE TITLE
Feature Request: Ability to use a picture icon

### ISSUE THREAD

**Issue by Daniel-dev22** [Clooos/Bubble-Card#20]
Currently the icon only supports "icons" but it would be nice to be able to use custom pictures similar to the mushroom template card I can specify a picture by providing the file path and it uses that over an icon if it's defined.

**Comment by Clooos** [comment]
This is indeed something that is missing, I add that at in my to-do list 👌

**Comment by mattmon** [comment]
a 'show_entity_picture' option would be nice; like in custom:button-card

**Comment by Clooos** [comment]
This is now fixed in the new beta :
https://github.com/Clooos/Bubble-Card/releases/tag/v0.0.1-beta.8
