### ISSUE TITLE
Minor issues with pop-up card

### ISSUE THREAD

**Issue by willliamchan** [Clooos/Bubble-Card#201]
When I lock the screen or screen off while a pop-up card is in the foreground, next time when I unlock the phone, I must click to open another pop-up card before I can open the same one that was left on the screen before the screen is off/lock.

To reproduce the issue:

1. Trigger a pop-up card to open (e.g. #kitchen)
2. Screen off / lock the phone.
3. Trigger again the same pop-up (e.g. #kitchen) and it won't work.
4. Trigger any other pop-up and then pop-up #kitchen and it will work again.

**Comment by Clooos** [comment]
Hi! This is now fixed in the new v1.6.0 beta!

https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.0-beta.1
