### ISSUE TITLE
Feedback - Bubble Card 1.5.1

### ISSUE THREAD

**Issue by willliamchan** [Clooos/Bubble-Card#203]
For the very first time, I see no error from Edge browser on Windows!
![image](https://github.com/Clooos/Bubble-Card/assets/54702221/162bf0e2-1274-4930-af27-9923666fee57)

Several questions tho:-

![image](https://github.com/Clooos/Bubble-Card/assets/54702221/ffad8011-ef23-4aa6-b9c2-252c27d9b9e7)
Not that it should be -/hacsfiles/Bubble-Card/bubble-pop-up.js?

I had module_installed: true added to the very last card (bubble stack card) but wondering what exactly it is doing?

![image](https://github.com/Clooos/Bubble-Card/assets/54702221/040486aa-6e5a-4486-a345-51638828cd75)
1.5.0 or 1.5.1?

**Comment by Clooos** [comment]
Glad that this version fixed your errors! And it seems that you still need to clear your cache manually, you should see v1.5.1.

Have you tried that?

**Comment by Clooos** [comment]
You can remove it from your resources in your dashboard, keep it in your `configuration.yaml`.

**Comment by Clooos** [comment]
If the pop-up initialization is fast enough for you, you can indeed just keep it like this.

But I still don't understand why it's not working for everyone! 😅 This is why I've made this method optional in this version.

**Comment by Clooos** [comment]
Thanks for your help! I'm glad that you found a way to make it work, I've mentioned your comment in the documentation here:

https://github.com/Clooos/Bubble-Card#pop-up-optimization

**Comment by Clooos** [comment]
It's working for you so I hope that this will help others!

**Comment by Clooos** [comment]
Templates are on my list, I really can't wait to move on a bit!

**Comment by skank01** [comment]
> You can remove it from your resources in your dashboard, keep it in your `configuration.yaml`.
> 
> Edit: Oh and `module_installed: true` should automatically remove `bubble-pop-up.js` from the frontend resources, and the cache refreshed on all browsers at the first use of this version.

So after it, i can delete?
- url: /hacsfiles/Bubble-Card/bubble-card.js
  type: module

**Comment by skank01** [comment]
> > > You can remove it from your resources in your dashboard, keep it in your `configuration.yaml`.
> > > Edit: Oh and `module_installed: true` should automatically remove `bubble-pop-up.js` from the frontend resources, and the cache refreshed on all browsers at the first use of this version.
> > 
> > 
> > So after it, i can delete?
> > 
> > * url: /hacsfiles/Bubble-Card/bubble-card.js
> >   type: module
> > 
> > Also, on my laptop running chrome, the popups are ok But when i view that same dashboard on my tablet (fully kiosk browser), it says i need to update my popup cards on v 1.5.0 (i'm on 1.5.1 and followed ur steps)
> > Do i still need to change my cards type to custom:bubble-pop-up ?
> 
> First, you will need to make sure Kiosk browser is all cleared. Secondly, we only update Pop-up cards to use "custom:bubble-pop-up" starting from 1.5.0.
> 
> Anything look like this are bubble-pop-ups ![image](https://user-images.githubusercontent.com/54702221/285290261-d6a792da-ceec-46b4-8a96-d19a34466be8.png)
> 
> And the rest should remain custom:bubble-card.

Yes kiosk is cleared.
I adjusted the cards, but it still says
![error](https://github.com/Clooos/Bubble-Card/assets/53368406/d61eed42-596e-4926-b0d5-1f3c367c230d)

So can i clear it from that resource file?

**Comment by Clooos** [comment]
The path for the configuration.yaml in the documentation was wrong, can you check if you don't have pasted the wrong one?

**Comment by skank01** [comment]
> The path for the configuration.yaml in the documentation was wrong, can you check if you don't have pasted the wrong one?

I have 2 dashboards, one default (using yaml edit) and one for mobile (no yaml edit)
In my configuration i have

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/bubble-pop-up.js


In my resources for the default dashboard i still have
- url: /hacsfiles/Bubble-Card/bubble-card.js
  type: module

I dunno where the resource is for the mobile dashboard

**Comment by skank01** [comment]
ah i see
extra_module_url:
    - /hacsfiles/Bubble-Card/bubble-pop-up.js

**Comment by skank01** [comment]
ok its ok on laptop/chrome and fully kiosk now.
But its not ok on my companion app now

**Comment by skank01** [comment]
> > ok its ok on laptop/chrome and fully kiosk now. But its not ok on my companion app now
> 
> Forcibly close companion app, open it again, go dashboard and if it still breaking, swipe down the page and give it a refresh.

i did, i even cleared cache via settings > app > storage

It still says the custom element doenst exist
However if i look at the same dashboard with my laptop, all is good

**Comment by skank01** [comment]
This is that dashboard om my laptop
![1](https://github.com/Clooos/Bubble-Card/assets/53368406/a4b5ddfe-6c26-4ec7-96a8-7d044f41cfda)

**Comment by skank01** [comment]
Yeah will sort out rest, however i need it on my companion first

**Comment by Clooos** [comment]
> I'd personally recommend to install the "Watchman" integration and run a scan and sort out all invalid entities in your dashboard as Bubble Card hates invalid entity.

It's time for me to fix that issue, you are not the first to say that. Can you tell me what is the problem exactly?

And thanks for the update! I've nothing to add because everything worked directly on my setup, and after my research I can say that this issue is probably for everyone using https only (source: https://community.home-assistant.io/t/ha-caching/313906/2). Your step-by-step seems to be the only way for installing it on https, so thanks again!

**Comment by Clooos** [comment]
I really have to fix that, thanks for details!

**Comment by Clooos** [comment]
> Follow up re v1.5.1
> 
> While I had bubble-pop-up.js removed from resource and loaded it using frontend, extra_module_url. And I found it will be added back as resource every time after a reboot of HA. Any idea what causing it?

The best way is to keep `module_installed: true` somewhere in a `custom:bubble-card`, this should prevent that.

**Comment by Clooos** [comment]
> > > Follow up re v1.5.1
> > > While I had bubble-pop-up.js removed from resource and loaded it using frontend, extra_module_url. And I found it will be added back as resource every time after a reboot of HA. Any idea what causing it?
> > 
> > 
> > The best way is to keep `module_installed: true` somewhere in a `custom:bubble-card`, this should prevent that.
> > v1.5.2 edit: This is not needed anymore, more details here: https://github.com/Clooos/Bubble-Card/releases/tag/v1.5.2
> 
> Great job!
> 
> Quick question here with 1.5.2. If we can use only bubble-card.js is that means we can load bubble-card.js using config.yaml and completely get rid of bubble-pop-up.js? I don’t mind to spend some time and rollback everything to use custom:bubble-card at all.

It will cause issues, only bubble-pop-up.js can be added as a module.

**Comment by ChrisMancini** [comment]
I recently updated to 1.5.2 and I think I have followed the suggestions that were made.

I have modified configuration.yaml:

`
frontend:
  extra_module_url:
    - /hacsfiles/Bubble-Card/bubble-pop-up.js?v=1.5.2
`

I also have all of my pop ups declared as:

`
type: custom:bubble-pop-up
...
`

My dashboard seems to be loading properly however the console prints the following two errors repeatedly (about 50 times a second).

![image](https://github.com/Clooos/Bubble-Card/assets/3649366/ee3690fc-2109-4297-8e05-7cbaed47e1d1)


Is this cache related?

**Comment by Clooos** [comment]
You need to remove bubble-pop-up.js from the frontend ressources (but keep it in your configuration.yaml).

To remove it just go in edit mode, click on the three dots icon at the top right corner, click on frontend ressources, search for bubble-pop-up.js then remove it. Refresh.

**Comment by ChrisMancini** [comment]
That seems to have done the trick... Thank you!
