### ISSUE TITLE
Text issue and bubble not round

### ISSUE THREAD

**Issue by samuel9554** [Clooos/Bubble-Card#204]
I'm using a Samsung Fold and the display is not large.
The temperature text is all mess up. Also the bubble isn't round. ![Screenshot_20231124_112006_Home Assistant.jpg](https://github.com/Clooos/Bubble-Card/assets/10778993/e4979b90-fa73-4add-a5dd-21683eab7de5)

**Comment by samuel9554** [comment]
@Clooos you could add min-width: fit-content ; for the temp
```
#header-container p {
    display: inline-flex;
    line-height: 0px;
    font-size: 16px;
    min-width: fit-content ;
}
```
and change width with min-width
```
.header-icon {
    display: inline-flex;
    min-width: 38px;
    min-height: 38px;
    background-color: var(--card-background-color,var(--ha-card-background));
    border-radius: 100%;
    margin: 0 10px 0 0;
    cursor: ${!this.config.entity && !this.config.double_tap_action && !this.config.tap_action && !this.config.hold_action ? 'default' : 'pointer'}; 
    flex-wrap: wrap;
    align-content: center;
    justify-content: center;
    overflow: hidden;
}
```
That will fix the issue.

**Comment by Clooos** [comment]
Thanks! I was aware of that issue, but I have so much to do now that I forgot about that one! I will try that now, cheers! 🍻

**Comment by samuel9554** [comment]
@Clooos Awesome !! Thank for your plugin!!!
