### ISSUE TITLE
Slider moves on it's own and is irratic

### ISSUE THREAD

**Issue by smartypantsuk** [Clooos/Bubble-Card#208]
I setup a single bubble card to act as a slider control for a light.
When the slider is tapped or adjusted and the left alone, it jumps up and down at varying levels all on it's own.

`
type: custom:bubble-card
card_type: button
entity: light.kitchen_light
button_type: slider

`
It does this with any entity i've tried, also does it inside a stack.
My lights are now possessed by a yoyo.

**Comment by Clooos** [comment]
Hi and thanks for your feedback. Is it still happening in v1.5.2?

**Comment by frieck** [comment]
For me it is still happening in v1.7.3.
When you slide it changes up and down and when you release it erratic jumps to the desired position/value.
