### ISSUE TITLE
Console log spammed with error after updating to v1.5.1

### ISSUE THREAD

**Issue by scalt** [Clooos/Bubble-Card#211]
After apdating the latest version v1.5.1 the console log is being spammed with this error:

![image](https://github.com/Clooos/Bubble-Card/assets/47013873/d0cc2e4f-6d27-4104-bb85-11d7ed577c83)

**Comment by Clooos** [comment]
Hi and thanks for your feedback. You have this error because of the duplicated `bubble-pop-up.js`, just remove it from your frontend resources, refresh and everything will be ok. 

But I'm working on a better solution to fix that definitely.

**Comment by Clooos** [comment]
This is now fixed in v1.5.2! 🍻
https://github.com/Clooos/Bubble-Card/releases/tag/v1.5.2
