### ISSUE TITLE
power-flow-card-plus always in front

### ISSUE THREAD

**Issue by UlrichThiess** [Clooos/Bubble-Card#215]
The power-flow-card-plus is not in the background. The circles are still visible.

![grafik](https://github.com/Clooos/Bubble-Card/assets/79257887/4c47d0f8-0fa9-4935-8a46-e8cac9153d4e)

**Comment by UlrichThiess** [comment]
I have 15 cards on this dashboard. The cards include power-flow-card-plus as number 8, Bubble-Cards as numbers 12, 13, and 14, and a Bubble-Pop-Up card as number 15.

Regarding the second issue: When I open one of the Bubble-Cards, I can see the bubbles from the Bubble-Pop-Up card on all cards except for the last one, number 14. Why is this happening?

**Comment by Clooos** [comment]
> I have 15 cards on this dashboard. The cards include power-flow-card-plus as number 8, Bubble-Cards as numbers 12, 13, and 14, and a Bubble-Pop-Up card as number 15.

In that case this issue is caused by power-flow-card-plus, you should open an issue on its GitHub page. Or change the z-index to 0 with card-mod on this card, that should fix it.

> Regarding the second issue: When I open one of the Bubble-Cards, I can see the bubbles from the Bubble-Pop-Up card on all cards except for the last one, number 14. Why is this happening?

Check your configuration for this pop-up, also check that the entities are correct.

**Comment by UlrichThiess** [comment]
I added this, but it is still in front.
```
type: custom:mod-card
style: |
  :host {
    z-index: 0;
  }
card:
  type: custom:power-flow-card-plus
```

**Comment by Clooos** [comment]
Try to add !important at the end of that line, like this `z-index: 0 !important;`

**Comment by UlrichThiess** [comment]
This works:
```
type: custom:mod-card
style: |
  ha-card {
    z-index: 0;
  }
card:
  type: custom:power-flow-card-plus
```

**Comment by UlrichThiess** [comment]
When the horizontal-bubble-stack is in its own column, then this column remains empty even after exiting the edit mode. In this case, the bubbles sometimes appear and sometimes do not at the bottom of the screen. If I change the view mode to sidebar, the bubbles at the bottom of the screen remain visible all the time. If I move a different card to position 14, filling the third column as well, it works correctly.

![grafik](https://github.com/Clooos/Bubble-Card/assets/79257887/d21d7c4f-fd50-4aba-8505-b15cc92b6802)
![grafik](https://github.com/Clooos/Bubble-Card/assets/79257887/4c6bd2bf-ae97-4e4a-8a84-9ed38d310500)

**Comment by UlrichThiess** [comment]
I would be happy to demonstrate it via Teams as well. I am readily available tomorrow.

**Comment by UlrichThiess** [comment]
It really depends on the position of the cards. I have now moved them to the first, second, and third positions and it works. However, in edit mode, a pop-up card is alone in a column. In the dashboard, it's hidden, but an empty column is displayed.
