### ISSUE TITLE
Bubble card slow

### ISSUE THREAD

**Issue by skank01** [Clooos/Bubble-Card#216]
Hi

Im on latest version.
Do you guys also find the card very slow to react?
That is using fully kiosk, and using the companion app

**Comment by Clooos** [comment]
Hi, are you using the Optimized mode?

**Comment by skank01** [comment]
Hi Cloos, you mean latest version? 
Yes
Both cards are loaded when i look

**Comment by Clooos** [comment]
So your pop-ups are custom:bubble-pop-up and not custom:bubble-card? Just to be sure.

**Comment by skank01** [comment]
Yes they are custom:bubble-pop-up

Is there anything else i can check?

**Comment by Clooos** [comment]
Can you send me a screenshot from your browser console? It's possible that you have an error somewhere. 

But on my old iPad the closing/opening animation of the pop-ups is still a bit laggy sometime, but this happens only on that device. I'm still looking for a solution.

**Comment by skank01** [comment]
Sure off course.
Just updated from 1.5.1 to 1.5.3
Now i cant follow.. Whats the difference now between optimized mode with the popup card, and the normal bubble card with the popup type?

I should use the popup card (optimized) right? So coming from 1.5.1 i dont have to change a thing?

Anyway, this is the browser console (loaded on my galaxy tab s4) using fully kiosk browser

![popup1](https://github.com/Clooos/Bubble-Card/assets/53368406/7b509498-ef73-47ac-95b8-278aa5af16bf)
![popup2](https://github.com/Clooos/Bubble-Card/assets/53368406/098285fb-e782-43fb-9b37-2982e422de29)


On my smartphones (using companion app) its slow too

**Comment by Clooos** [comment]
Yes you don't have to change anything, the difference is that the regular mode is almost the same mode than before, and the optimized mode (when you use custom:bubble-pop-up and added the JS file in your configuration.yaml) is loaded before all your other custom cards, this means a faster initialization for you pop-ups when the page is loaded, that's the only difference. 

When you say that it is slow on your smartphone, what is slow exactly? Only the animations, everything or something else? 

And one more question, did you had this issue before 1.5.0 or is this version the first you've tried?

**Comment by skank01** [comment]
Slow is that i have to press the custom button, and sometimes it doenst respond to popup
i have to tap multiple times sometimes...
Then i close the app cause it doesnt respond, then back open, and it pops up
Will see how it goes now with 1.5.3 if its any better

I was using it before 1.5.0 but not for long... i was then just starting to completely rebuild my dashboard for it, and didnt test long enough to know if it was there...
Then i upgraded to 1.5.0 ,and started realkly using it everywhere... then i noticed it

**Comment by skank01** [comment]
> Yes I'm aware that there is an issue right now that force you in some cases to tap twice on a button to trigger the action. I'm not sure if it's the same issue as you? But I'm working on a fix for that.
Not sure either.

I tried this:
Open companion app
Tap button which opens popup
Close it
Minimize the app
Leave it running in background
Leave smartphone alone for 10 min, go outside, turn on screen of smartphone
Open the companion app
Try to tap that same button

Nothing happens, sometimes need to tap 4 times, sometimes it doenst popup...

**Comment by Clooos** [comment]
This should be fixed in the new v1.6.0 beta!

https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.0-beta.1
