### ISSUE TITLE
Cannot add local image as icon in button

### ISSUE THREAD

**Issue by b101marc** [Clooos/Bubble-Card#217]
Attempting to replace the icon with an image hosted locally (the user's profile photo) however it just appears blank within the circle of the button.

```
type: custom:bubble-card
card_type: button
entity: sensor.brayden_iphone_status
show_state: true
icon: local/image/512x512b.jpg
button_type: switch
```

Anyone aware of how to make this happen? Maybe by using card-mod?

**Comment by Clooos** [comment]
Hi and thanks for your feedback, to be honest I realize that I've never tested this feature. So it's probably a bug.

But it's perfectly working if you set the picture directly on the entity. Like for a media player, it will show the album covers.

**Comment by Clooos** [comment]
Here is where to start:
https://www.home-assistant.io/docs/configuration/customizing-devices/#customizing-entities

**Comment by b101marc** [comment]
Thanks for this. Went through this yesterday for hours and wasn't ever able to get it to work. Will re-attempt. Thanks.

**Comment by Clooos** [comment]
You're welcome!
