### ISSUE TITLE
Dashboard crashes randomly

### ISSUE THREAD

**Issue by simensus** [Clooos/Bubble-Card#221]
Hi,

my Dashboards are Crasing randomly since the last Update (1.5.3)

Here is a Screenshot of the console!

![image](https://github.com/Clooos/Bubble-Card/assets/101661986/64fd9ec3-d330-426b-bdb4-47b4bab03168)

**Comment by simensus** [comment]
> Hi,
> 
> my Dashboards are Crasing randomly since the last Update (1.5.3)
> 
> Here is a Screenshot of the console!
> 
> ![image](https://private-user-images.githubusercontent.com/101661986/287562136-64fd9ec3-d330-426b-bdb4-47b4bab03168.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2NTAwOTEsIm5iZiI6MTcwMTY0OTc5MSwicGF0aCI6Ii8xMDE2NjE5ODYvMjg3NTYyMTM2LTY0ZmQ5ZWMzLWQzMzAtNDI2Yi1iZGI0LTQ3YjRiYWIwMzE2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNFQwMDI5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDYwMzBhMmExY2E3OGIwN2IyZjVkMjRlZjFkOWE0NGMzZTFhYWQwY2EwZmM1NmRhNDBjNTEwZGEyMmU4YTE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ASH3d_A5kmmiVcW9lCrga8D1waBQRfDXfIHXOP_6LqA)

Optimized Mode enabled!

**Comment by shawndamon** [comment]
im having a weird issue too with the horizontal stack
<img width="497" alt="Screenshot 2023-12-04 at 11 27 12 PM" src="https://github.com/Clooos/Bubble-Card/assets/31374940/d5392831-ba1a-4fc6-b36c-6f5e95ed1978">

**Comment by Clooos** [comment]
> Hi,
> 
> my Dashboards are Crasing randomly since the last Update (1.5.3)
> 
> Here is a Screenshot of the console!
> 
> ![image](https://private-user-images.githubusercontent.com/101661986/287562136-64fd9ec3-d330-426b-bdb4-47b4bab03168.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4ODg5MTIsIm5iZiI6MTcwMTg4ODYxMiwicGF0aCI6Ii8xMDE2NjE5ODYvMjg3NTYyMTM2LTY0ZmQ5ZWMzLWQzMzAtNDI2Yi1iZGI0LTQ3YjRiYWIwMzE2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQxODUwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNGJlMTFhMWMwYjRhNTE1ZWM4ZTM1NWVlZDkzYWE4MTY3Y2Y1YjBhMTQwZjI0NjMwOWJhZDQ4Y2Y4OGM5Yjg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ojb7xRwtBYyWHaZLIvNwtqZ2tiIqTGsytwj5obefyeA)

It looks like that some cards don't like being removed when the pop-ups are closed. I have mostly Bubble Cards in my pop-ups, I will have to extend my test pop-ups to more custom cards.

I will take a serious look at that for the next release.

**Comment by Clooos** [comment]
This is now fixed in the new v1.6.0 beta!

https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.0-beta.1

**Comment by simensus** [comment]
> This is now fixed in the new v1.6.0 beta!
> 
> https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.0-beta.1

Thanks a lot. No problems since updating this morning. 😍
