### ISSUE TITLE
Unstable 

### ISSUE THREAD

**Issue by ignacio82** [Clooos/Bubble-Card#223]
I recently adopted bubble cards for my dashboard and I love the concept. Alas, I found my dashboard is sometimes unstable (not always) see [this video](https://photos.app.goo.gl/JGdF9Ci53Q6boUaH6) below for a better understanding of what I'm talking about. Any ideas for what might be causing this and how to solve it?

**Comment by ignacio82** [comment]
Thanks @Clooos. I'm using a pixel 7 pro and I do use the HA companion app.

**Comment by shpongledsummer** [comment]
I'm also experiencing stability issues and slow opening of Popups on a pixel 6a running the companion app. No issues on my Xiaomi 12, so maybe this is Google related.

**Comment by bxsteez** [comment]
I'm having this issue on the fire hd 10+ using fully kiosk.  Sometimes it works and sometimes it doesn't.  It's mostly with the use of the buttons.  The trigger opening seems to work every time.

**Comment by ignacio82** [comment]
I'm not sure if this is helpful:
![image](https://github.com/Clooos/Bubble-Card/assets/1833309/35b62db8-6783-4bcb-b8fc-028346a7cf0a)

Is there something that I can do on my end to avoid having these issues? Do you know if the problem is something like using X card, or integration?

**Comment by Clooos** [comment]
This issue should be fixed in 1.6.0, I'm working mainly on stability for now, but I still don't know when I will be able to release it.

**Comment by Clooos** [comment]
This should now be fixed in the new v1.6.0 beta!

https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.0-beta.1
