### ISSUE TITLE
cover card without state

### ISSUE THREAD

**Issue by piecesnbits** [Clooos/Bubble-Card#229]
is it possible to have a cover card without state? this is useful for covers that don't have a sensor to keep track of whether they are open/closed.

thanks

![image](https://github.com/Clooos/Bubble-Card/assets/44613132/8cea9cfd-5f78-47ba-abae-730bd4f28909)

**Comment by Clooos** [comment]
Hi! This feature was missing indeed, but this will be possible in 1.6.0 👌

**Comment by Clooos** [comment]
This is now a feature in the new betas:

https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.0-beta.5
