### ISSUE TITLE
Cover Card Icons

### ISSUE THREAD

**Issue by cloudbr34k84** [Clooos/Bubble-Card#23]
The icons you can set with the cover card don't stay selected. see screenshot below if sequence of events.

I select the mdi icons I want to display. I click save.
They do not show on the card. I them edit card and they are not selected 

![Screenshot_20230901-170402.png](https://github.com/Clooos/Bubble-Card/assets/58960644/0e16c87e-d4e6-486c-86a6-c941e77a9559)

![Screenshot_20230901-170419.png](https://github.com/Clooos/Bubble-Card/assets/58960644/1bfb1ff7-28ef-4ca4-ab62-8a9e9cfd954b)

![Screenshot_20230901-170603.png](https://github.com/Clooos/Bubble-Card/assets/58960644/2eca3233-7bbf-4a0f-88fd-380e1c25b895)

**Comment by Clooos** [comment]
Hi and thanks for the feedback, this is now fixed in the new beta
