### ISSUE TITLE
Dark mode iOS makes the pop up unreadable

### ISSUE THREAD

**Issue by PartyingChair** [Clooos/Bubble-Card#231]
![image](https://github.com/Clooos/Bubble-Card/assets/74517189/0033a8f1-9bbb-44a7-9e83-5e2adb046947)

Pop up comes up white, and the text for the name is borderline unreadable in dark mode.

**Comment by Clooos** [comment]
Have you tried with another theme or have you tried to clear your cache?

Can you also send me a link to your current theme?

**Comment by PartyingChair** [comment]
Reinstalling the app half works, going from light mode to-> dark mode now works, going from dark mode -> light mode leaves it stuck in dark mode until I next force close the app. Which is way more readable, so definitely an improvement anyway. 


Happy to send you a link with my current theme, but not sure exactly what you mean or how to do that (noob here unfortunately)

**Comment by PartyingChair** [comment]
I spoke too soon, it's back to being stuck in light mode sometimes. But force closing it does fix it for now at least.

**Comment by Clooos** [comment]
Oh I get what is your issue now, it's indeed fixed when you refresh the page but if it switch automatically it's an issue. I will fix that. 

Thanks for the feedback!

**Comment by PartyingChair** [comment]
No problem! Hope it's an easy fix, and thanks for looking into it!

**Comment by Clooos** [comment]
This is now fixed in the new v1.6.0 beta!

https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.0-beta.1
