### ISSUE TITLE
Using dashboard via Device Control in Android 14 crops horizontal navigation bubble 

### ISSUE THREAD

**Issue by vcntt** [Clooos/Bubble-Card#236]
In android 14 they introduced more options for the Device Control shortcut menu. It's possible to directly access Home Assistant dashboards.

Whenever I open the bubble card dashboard the horizontal navigation bubble is cropped. Even when I scroll down all the way to the bottom I cannot reach it. 

This is Device Control. 
![Screenshot_20231211_215743_One UI Home](https://github.com/Clooos/Bubble-Card/assets/34486569/bc0fd9d5-2b69-486d-af17-aeb3649c5f02)

Navigation bar cropped. 
![Screenshot_20231211_215655_Home Assistant](https://github.com/Clooos/Bubble-Card/assets/34486569/eb469ed3-8869-4e85-a55f-d59699e697e6)

**Comment by Clooos** [comment]
Hi, I really have no idea of how I could fix that 😅 This issue seems to come from Android.
