### ISSUE TITLE
Popup not working. 

### ISSUE THREAD

**Issue by McFarTech** [Clooos/Bubble-Card#240]
Hi. 

Not sure what i am doing wrong. I have created a new page as a subview called test. On that page i have used the example code from the website. 

`type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#kitchen'
    name: Kitchen
    icon: mdi:fridge
    entity: light.kitchen
    state: sensor.kitchen_temperature
    back_open: true`

Then on a separate page i have added a button via the following example code 

`type: button
tap_action:
  action: navigate
  navigation_path: '#kitchen'
name: Kitchen
icon: mdi:fridge`

Now when i click the button the URL changes to /test#/kitchen pop nothing works. there is no pop up. 

really not sure what i am doing wrong

**Comment by McFarTech** [comment]
I have this working now and LOVE IT. 

Question though. Lets say i have two rooms A and B. If i create a Bubble popup in room A can i only call it from room A or can it also be used in room B?

**Comment by Clooos** [comment]
You can call it from an other page by adding the hash in the navigation path, but the main goal of Bubble Card is to  have everything on one page. 

And I'm glad that you fixed your issue! 😀
