### ISSUE TITLE
background: undefined

### ISSUE THREAD

**Issue by jondavidsson** [Clooos/Bubble-Card#243]
I have a problem with the ::after linear gradient at the top of the pop-up card.

The first card works as expected, but all the other cards shows: background: linear-gradient(0deg, **undefined** 0%, rgba(244, 246, 251, 0.88) 80%);

Obviously you need to have enough entities in the card so scrolling is needed.

No difference in version, android app or browser.

**Comment by Clooos** [comment]
Hi and thanks for your feedback, I'm aware of this issue and it will be fixed in 1.6.0 🙂

**Comment by Clooos** [comment]
This is now fixed in the new v1.6.0 beta!

https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.0-beta.1
