### ISSUE TITLE
Feature Request: Catch Events and run again after all is ready?

### ISSUE THREAD

**Issue by lexusburn** [Clooos/Bubble-Card#244]
I have a large dashboard with over 7.000 lines and 22 of your great pop-ups. 

My most annoying "problem" behavior is, that after starting the app my wife or i quickly start clicking on a room to open the corresponding pop-up. In most cases it's not ready at this moment and nothing happens. 

Clicking again, after all should be loading doesn't work in this case too.

Only solution is to reload the dashboard and wait until all is ready and then click. 

Would be great if you find a solution for this? Is it possible to check for presence of an anker  in URL ("#livingroom" for example) after all is ready and do the same, like you do, when i click then?

**Comment by Clooos** [comment]
Hi and thanks for your feedback! This issue was annoying me a lot too and I've just fixed it, and a lot of other issues as well! 

Now just wait for 1.6.0 in a few days 😀

**Comment by lexusburn** [comment]
Yeah! Can't wait! 😊👍

**Comment by Clooos** [comment]
This is now fixed in the new v1.6.0 beta!

https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.0-beta.1

**Comment by lexusburn** [comment]
> This is now fixed in the new v1.6.0 beta!
> 
> https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.0-beta.1

@Clooos on a desktop browser (chrome for example) it's working very nice now with the beta version.

On iOS App i have a new issue: if i start/restart the app, some icons will not be displayed, the your button slider is missing and after a few seconds the whole dashboard went to grey.
Only help is to reload the dashboard by dragging down. Then the whole dashboard does a restart and now it's working fine.

**Comment by lexusburn** [comment]
Yeah, tried that. Does not change anything. :-(
Same problem on mobile safari.
Don't get any suspicious logs in mobile safari web inspector panel. :-/

Now try to switch back to last version and hopefully will get the problem under control.

**Comment by lexusburn** [comment]
Ok, it's not related to horizontal-buttons-stack. 
The dashboard crashes without this card too. :-/

**Comment by Clooos** [comment]
I'm on it, I've maybe found what can cause this issue 🤞

**Comment by lexusburn** [comment]
> I'm on it, I've maybe found what can cause this issue 🤞

Sounds good. Create a new beta and i will try it. 😊

**Comment by Clooos** [comment]
Everything should be fixed now 🤞

https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.0-beta.5
