### ISSUE TITLE
bg_color, bg_opacity don't work

### ISSUE THREAD

**Issue by Paxxil** [Clooos/Bubble-Card#246]
They stopped working for me in latest Beta.
Workaround is to put style to #root with background_color: rgba(r,g,b,o) !important;

**Comment by Clooos** [comment]
Hi and thanks for your feedback! 

This issue is now fixed in the new 1.6.0-beta.2!
https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.0-beta.2
