### ISSUE TITLE
Disable padding around popup-card?

### ISSUE THREAD

**Issue by Presswerk65** [Clooos/Bubble-Card#254]
I want to get rid of the (red for visualisation) padding around the popup card, unfortunately it doesn't work

```
styles: |
  #root {
    border-radius: var(--ha-card-border-radius) !important;
    padding: 0px 0px 0px 0px !important;
    background-color: red !important;
  }
```
![image](https://github.com/Clooos/Bubble-Card/assets/75246200/6eb21260-5230-43b1-9d18-b9db34d909f9)

What do I wrong?

![image](https://github.com/Clooos/Bubble-Card/assets/75246200/4320e9b9-d8e3-47bd-9b36-71d0b7090292)

Greez!

**Comment by Vince-arch** [comment]
Hey I would be glad to fix this issue.

**Comment by crixle** [comment]
Try using

`#root.open-pop-up`

as your selector instead. Works for me.

**Comment by shaheer21-sys** [comment]
assign it to me , will make a fix
