### ISSUE TITLE
Mushroom light card border-radius conflict

### ISSUE THREAD

**Issue by samuele2723** [Clooos/Bubble-Card#261]
Hello, 

with 10.6.0 beta 2 i am testing and when i have nested some mushroom light card and when i am from mobile only (ios companion app iphone) shows border radius 0% for some seconds while interacting with the light in light control both color or brightness 

please let me know if i can support with more data

https://github.com/Clooos/Bubble-Card/assets/66970905/0501f667-983f-4b78-bb66-88a56b12605c

**Comment by Nazze** [comment]
Man, I love your dashboard! That is so cool!

**Comment by samuele2723** [comment]
Tanks Nazze! But ufortunately as good as bad in performance at the time 😂

**Comment by latargere** [comment]
I have exactly the same issue with the mushroom light card

**Comment by Clooos** [comment]
Hi! Is this issue is still happening in the new v1.7.X?

https://github.com/Clooos/Bubble-Card/releases/tag/v1.7.1

**Comment by Nazze** [comment]
Hi! I am still seeing it with 1.7.1

![IMG_9676](https://github.com/Clooos/Bubble-Card/assets/33813707/dfcce248-4903-4607-ba1a-d3e7f07487d5)

**Comment by Clooos** [comment]
Is this still happening when you remove the pop-up card from that vertical stack? I just want to be sure that this issue is really related to Bubble Card and not from the vertical stack itself.

**Comment by Nazze** [comment]
Hi! If I put the mushroom lights outside of the pop up, it is working. Is this what I should try out? 
I tried a basic view with just a popup and two mushroom lights and it is working, too. So it seems to be related to my complex setup, too.

**Comment by Nazze** [comment]
Hi! Wow this beta is gorgeous! I can confirm that this issue is fixe for me. But I can’t speak for @samuele2723 .
I have another issue with the width of the content of the popup. But I will browse through the issues and see if a similar ticket is existing or if I open a new ticket.

**Comment by Clooos** [comment]
Yeah, I'm glad that it's fixed! And I'm aware of the other issue, I've added it to my to-do list.
