### ISSUE TITLE
 popup hoz - buttons overlapping each other 

### ISSUE THREAD

**Issue by pressurejets** [Clooos/Bubble-Card#264]
Just installed and was working well restart ha, as added media server to ha and now 
m buttons at the bottom is overlapping the first button.

`type: custom:bubble-card
card_type: horizontal-buttons-stack
1_link: '#masterbedroom'
1_name: master bedroom
1_icon: mdi:bed
1_entity: light.bedroom_light
is_sidebar_hidden: true
rise_animation: true
2_link: '#Livingroom'
2_name: Living room
2_icon: mdi:sofa-outline
2_entity: light.energizer_rgbcct_led_cdl_4
3_link: '#Reolinkdoor'
3_name: Door Camera
3_icon: mdi:cctv
4_link: '#Frontcamera'
4_name: Front Camera
4_icon: mdi:cctv
width_desktop: 100%`

Have trie on new dashboard the same, try no theme no grid layouts etc . dont see why this is happening 
any ideas

**Comment by Clooos** [comment]
Hi, just open your editor, that should be fixed that way.

**Comment by pressurejets** [comment]
Thank you worked a charm great car, is there a way to global set to all views ?? or is it a case of pasting into every view 
hope you have a fab new year

**Comment by Clooos** [comment]
Glad that it worked! You can open a pop-up from an other view, with your view path followed by the hash like this `/lovelace/your-view#your-pop-up` but it will be opened on that view.

The main goal of Bubble Card is to have everything on a single view and this is how I use it.
