### ISSUE TITLE
bubble pop up an kiosk mode 

### ISSUE THREAD

**Issue by pressurejets** [Clooos/Bubble-Card#265]
Problem if leave a popup on screen for few mins i cant  close the popup via x close button
i have to click on other popup before i'm able to close it ??

but works if you use time 15000 fine, and also if you close the pop up straight away

**Comment by Clooos** [comment]
Hi, can you tell me on which version you are?

**Comment by pressurejets** [comment]
bubble card v1.5.3

**Comment by Clooos** [comment]
Could you try the last v1.6.0-beta.4 that is available in HACS? I've worked a lot on stability on this version.

https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.0-beta.4

**Comment by pressurejets** [comment]
worked a charm working great noticed a extra setting Optional - Highlight current hash / view?? Don't seen to work yet but its beta keep the great work up.

**Comment by Clooos** [comment]
Glad that it's fixed! This feature should works but it's a really soft animation (but maybe too soft 👀).
