### ISSUE TITLE
Conflict between Service Confirmation Popup and Bubble Popup

### ISSUE THREAD

**Issue by aaronperreault** [Clooos/Bubble-Card#269]
Hardware - Generic x86-64
Core - 2023.12.3
Supervisor - 2023.12.0
Operating System - HAOS 11.2
Frontend -20231208.2
Bubble Card - v1.5.3

I'm running into an issue where I have service confirmations on tap actions contained within a bubble card popup. When I interact with the service confirmation popup, tapping either Yes or Cancel, the bubble card popup closes entirely and cannot be re-opened unless I open a different bubble card popup first. 

Specifically in my case, the workflow is:

Open Home Assistant Dashboard

1. Click/Tap on Vacuum Card --> Navigates to Vacuum Bubble Card Popup
2. Click/Tap on card to run service --> Confirmation Popup Opens ("Are you sure?")
3a. Click/Tap on CANCEL --> Service does not run --> Confirmation Popup closes --> Vacuum Bubble Card Popup closes, returns to main dashboard
3b. Click/Tap on OK --> Service runs --> Confirmation Popup closes --> Vacuum Bubble Card Popup closes, returns to main dashboard
4. Click/Tap on Vacuum Card --> Nothing happens
5. Click/Tap on Thermostat Card --> Navigates to Thermostat Bubble Card Popup
6. Close Thermostat Bubble Card Popup --> Return to Main dashboard
7. Click/Tap on Vacuum Card --> Navigates to Vacuum Bubble Card Popup

I'm not sure what could be causing this. The behavior occurs on both desktop and mobile devices. Happy to provide screenshots/yaml if that would help.

**Comment by fcassata** [comment]
I think I'm running into the same thing with the edit item dialog on the todo list card in a pop-up. Did you ever find a workaround for this?

**Comment by Clooos** [comment]
Hi! Have you tried to add `close_by_clicking_outside: false` in your YAML? That should fix your issues.

**Comment by fcassata** [comment]
> Hi! Have you tried to add `close_by_clicking_outside: false` in your YAML? That should fix your issues.

Thank you! Of course that fixes it :)
