### ISSUE TITLE
BUG:   v1.6.0-beta 4 --> Does not honor Tap/Double Tap actions

### ISSUE THREAD

**Issue by fireheadman** [Clooos/Bubble-Card#271]
When using Beta version, was unable to use the Tap/Double Tap actions as described in your github documenation.
Simply does not work.

I reverted back to latest stable version, v1.5.3 and this does work as expected, however now I am back to dealing with issues on non-centered cards and other issues.

Hoping this is a quick fix.

**Comment by Clooos** [comment]
Hi, this is fixed in the latest beta!

https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.0-beta.5
