### ISSUE TITLE
unable to  pass arguments to a script from within a pop-up card.

### ISSUE THREAD

**Issue by thingray** [Clooos/Bubble-Card#277]
I use pop-up card triggered by a binary sensor state. The cards pop up as expected.  Wanted  to use the double tap  action to call a service to reset the sensor state ( sort of an acknowledge). When used in the pop-up card itself , no arguments are passed to  the script. ( the script checks for missing argument).  When I use the same  syntax on a button card or image-entity card, it works as expected.

HA 2023.10.5 running in a container on a NAS.  Bubble card V 1.5.3

The script I use comes from 
https://community.home-assistant.io/t/how-to-manually-set-state-value-of-sensor/43975/8f
From  rodpayne :
#==================================================================================================
#  python_scripts/set_state.py 
#==================================================================================================

#--------------------------------------------------------------------------------------------------
# Set the state or other attributes for the entity specified in the Automation Action
#--------------------------------------------------------------------------------------------------

inputEntity = data.get('entity_id')
if inputEntity is None:
    logger.warning("===== entity_id is required if you want to set something.")
else:    
    inputStateObject = hass.states.get(inputEntity)
    inputState = inputStateObject.state
    inputAttributesObject = inputStateObject.attributes.copy()

    for item in data:
        newAttribute = data.get(item)
        logger.debug("===== item = {0}; value = {1}".format(item,newAttribute))
        if item == 'entity_id':
            continue            # already handled
        elif item == 'state':
            inputState = newAttribute
        else:
            inputAttributesObject[item] = newAttribute
        
    hass.states.set(inputEntity, inputState, inputAttributesObject)

here is  the code that works:
    cards:
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#soussol'
            icon: mdi:fireplace
            trigger_entity: binary_sensor.notif_poele
            trigger_state: 'on'
            state: sensor.ewelink_poele_temperature_2
            name: Sous sol
            entity: binary_sensor.notif_poele
            theme: darkmode
            trigger_close: true
            text: Bois
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: call-service
              service: python_script.set_state
              data:
                entity_id: binary_sensor.notif_poele
                state: 'off'
            icon: mdi:fan
            name: Poele
            show_state: true

But when I try to use  that specific section with tap_action our double tap action in the pop-card 
            tap_action:
              action: call-service
              service: python_script.set_state
              data:
                entity_id: binary_sensor.notif_poele
                state: 'off'
The script returns :
2024-01-04 19:41:16.686 WARNING (SyncWorker_16) [homeassistant.components.python_script.set_state.py] ===== entity_id is required if you want to set something.

Which points to the argument is not passed.  Tried various combination of quotes, double quotes, nothing helps.  The work around is obviously to use another card under the pop-up. So no big issue, I just dunno if it is an intended behavior or an issue. But it had me banging my head for awhile. :)

**Comment by Clooos** [comment]
Hi, I guess that this issue in on my side. I will take a look!

**Comment by thingray** [comment]
Hi, using a button card in a pop-card, tap action works as stated in ' here is the code that works'.  So it seems related specifically to  tap actions in the pop-up card itself, if that makes sense.

**Comment by Clooos** [comment]
Hi, is this possible by any chance that this issue is now fixed? I haven't tried but a lot of the code has changed since.
