### ISSUE TITLE
1.6.0 release :  ' ' undefined and ' ' false errors

### ISSUE THREAD

**Issue by snootched** [Clooos/Bubble-Card#278]
Hello - thanks for all your great work on this project, I've been tracking for a long time and really enjoy it.
I upgraded 1.6.0b5 to final today and the console is spammed with the messages in the attached picture.
The page eventually becomes so unusable and have to navigate away and refresh.

Initially I thought this was because I was using optimized mode, and made the switch back to normal with the upgrade.
Seems this is not the case - as I can consistently recreate the issue by flipping back and forth between 1.6.0b5 and 1.6.0 final (while maintaining regular mode)

Happy to help and get any additional information if I can.

![image](https://github.com/Clooos/Bubble-Card/assets/11273374/478a3602-5aa0-480f-95f0-70b2030cd501)

Thanks!

**Comment by Clooos** [comment]
This is already fixed! Thanks!

https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.2

**Comment by snootched** [comment]
Amazing work - thank you!
