### ISSUE TITLE
Pop-up always show up if "Top margin on mobile" missing the "px" string

### ISSUE THREAD

**Issue by huythach83** [Clooos/Bubble-Card#28]
If in the card settings, the "Top margin on mobile" has the value "0" instead of "0px", the card will always show up like this
![image](https://github.com/Clooos/Bubble-Card/assets/11812299/c246e32d-2c6d-4fcd-a94d-249133a2fbed)

The correct display should be like this:
![image](https://github.com/Clooos/Bubble-Card/assets/11812299/c13bc609-ef93-4de2-93b6-623932121a04)

**Comment by Clooos** [comment]
It's now fixed, thanks again!
https://github.com/Clooos/Bubble-Card/releases/tag/v0.0.1-beta.6
