### ISSUE TITLE
Feature Request: Localization

### ISSUE THREAD

**Issue by Nazze** [Clooos/Bubble-Card#30]
Hi

Localizations of states not working.
I took screenshots of the weather state. Bubble card simply prints out the state as is. Other cards use the localized version of the entity state.

Bubble very simple example:
![Bubble](https://github.com/Clooos/Bubble-Card/assets/33813707/e601303a-e265-48c4-9acf-d3c205f2f88f)

Weather-forecast card:
![Standard](https://github.com/Clooos/Bubble-Card/assets/33813707/a66aa2cf-eb03-4253-8bee-50c8126e45c9)

I love bubble-cards! I'd love to see it evolve. :) 

KR
Nazze

**Comment by Clooos** [comment]
Hi and thanks for the feedback, indeed there is still no localization anywhere in my code but it will come in the beta.

**Comment by Clooos** [comment]
This is now possible in the new beta, see here :
https://github.com/Clooos/Bubble-Card/releases/tag/v0.0.1-beta.9

**Comment by Nazze** [comment]
Works for me. Beta 9 is awesome. Everything else works for me, too, and it seems to be much smoother than before. Thanks @Clooos 🥳🙌🏻
