### ISSUE TITLE
Feature request: Close the pop-up When sliding it down

### ISSUE THREAD

**Issue by sky-future** [Clooos/Bubble-Card#31]
There should be a possibility to close the pop up when sliding it down from the top. So you can navigate even faster than clicking on the cross.

**Comment by Clooos** [comment]
This is now a new feature, thanks!
https://github.com/Clooos/Bubble-Card/releases/tag/v0.0.1-beta.6

**Comment by psi-4ward** [comment]
This does not for me, do I need any special attributes?

**Comment by Clooos** [comment]
I'm planning to improve this feature a lot, but I still don't know when.
