### ISSUE TITLE
Main dashboard card is showing in front of horizontal button stack

### ISSUE THREAD

**Issue by doenau** [Clooos/Bubble-Card#32]
when using on a mobile device (iphone14 in this example), the main cards in the dashboard are now sitting in front of the horizontal button stack.
screenshot example attached.
currently running beta 5
![image](https://github.com/Clooos/Bubble-Card/assets/112148640/5a8be486-bcfb-48cb-93d3-94ffdc153b2f)

great cards though - thank you :D

**Comment by Clooos** [comment]
Hi, is this card the last one on your dashboard?

**Comment by doenau** [comment]
I had cards in this order:

1. Horizontal Buttons Stack
2. Vertical Stack (main/only card for the view)
3. Popup
4. Popup
5. Popup

I moved the Vertical Stack (main/only card for the view) to be the last card, but still have the issue.

**Comment by Clooos** [comment]
I'm sorry I've not explained well, your horizontal buttons stack must be the last one in your view. This should fix this issue.

**Comment by doenau** [comment]
Thanks. I must have read the documentation wrong. 
This is fixed - though the main card still needs some sort of bottom margin so that it scrolls past the horizontal stack - but this probably isn't your issue 👍🏼
![IMG_3191](https://github.com/Clooos/Bubble-Card/assets/112148640/d4a122fe-872f-4978-ac38-d81c1a178bab)

**Comment by Clooos** [comment]
For fixing this issue can you try adding one or more empty-column Bubble Card right after your vertical stack? If this work I will add the ability to edit the height of that card.

**Comment by doenau** [comment]
It doesn't appear to change visually by either...Adding another row to my vertical stack with the empty column cars OR adding separate empty column bubble card after vertical stack. 
But yes, perhaps an adjustable height will fix it.

**Comment by Clooos** [comment]
I'm closing this issue, but for now you can probably add a new height with card-mod to the empty column, like that (not tested):

card_mod:
  styles: |
    ha-card {
      height: 100px !important;
    }

**Comment by doenau** [comment]
> I'm closing this issue, but for now you can probably add a new height with card-mod to the empty column, like that (not tested):
> 
> ```
> card_mod:
>   style: |
>     ha-card {
>       display: block;
>       height: 100px !important;
>     }
> ```

This works. Thanks 👍🏼
Keep up the great work!

**Comment by Brouwertje** [comment]
Are you using a layout card on the dashboard? When I removed my Layout card the issue was gone.
