### ISSUE TITLE
Scrolling inside bubblecard har stopped working

### ISSUE THREAD

**Issue by radhoo2k10** [Clooos/Bubble-Card#334]
Bubble card: v1.6.2
Core: 2024.1.1
Supervisor: 2023.12.0
Operating System: 11.3
Frontend: 20240104.0
Lastest android app.
Same issue on web browser.
Has worked until today. Did upgrade the Core and Supervisor today. 

https://github.com/Clooos/Bubble-Card/assets/78762281/f7091aa4-5f95-450f-9f56-93b0da1feb78

https://pastebin.com/XmWTaCjz
https://pastebin.com/NuaEQtsi

**Comment by Clooos** [comment]
Hi and thanks for your feedback! Could you try remove your custom cards one by one from that pop-up to see if one of them could cause that? Because I don't have this issue on my setup.

**Comment by radhoo2k10** [comment]
Hi.

Changed the pop-up card to this:

`type: vertical-stack
cards:
  - type: custom:bubble-pop-up
    hash: '#stue'
    name: Stue
    icon: mdi:sofa
    tap_action:
      action: more-info
    auto_close: '15000'
  - type: custom:bubble-card
    card_type: separator
    name: Lys
    icon: mdi:ceiling-light-multiple
  - type: custom:bubble-card
    card_type: separator
    name: Lys
    icon: mdi:ceiling-light-multiple
  - type: custom:bubble-card
    card_type: separator
    name: Lys
    icon: mdi:ceiling-light-multiple
  - type: custom:bubble-card
    card_type: separator
    name: Lys
    icon: mdi:ceiling-light-multiple
  - type: custom:bubble-card
    card_type: separator
    name: Lys
    icon: mdi:ceiling-light-multiple
  - type: custom:bubble-card
    card_type: separator
    name: Lys
    icon: mdi:ceiling-light-multiple
  - type: custom:bubble-card
    card_type: separator
    name: Lys
    icon: mdi:ceiling-light-multiple
  - type: custom:bubble-card
    card_type: separator
    name: Lys
    icon: mdi:ceiling-light-multiple
  - type: custom:bubble-card
    card_type: separator
    name: Lys
    icon: mdi:ceiling-light-multiple
  - type: custom:bubble-card
    card_type: separator
    name: Lys
    icon: mdi:ceiling-light-multiple
  - type: custom:bubble-card
    card_type: separator
    name: Lys
    icon: mdi:ceiling-light-multiple
  - type: custom:bubble-card
    card_type: separator
    name: Lys
    icon: mdi:ceiling-light-multiple
`

Still the same problem. Will create a new tab with only one button and one pop-up card.

**Comment by radhoo2k10** [comment]
Tested this in a new tab. https://pastebin.com/yMxhTK9e
Still the same result.

**Comment by radhoo2k10** [comment]
https://github.com/Clooos/Bubble-Card/assets/78762281/c74c356d-8e6e-4615-a60b-56a24a5cf7e0

If I scroll down alot, then it works as expected, but I can't X out of the pop-up card.

**Comment by radhoo2k10** [comment]
Solved it.
Removed bubble card from resources:
![image](https://github.com/Clooos/Bubble-Card/assets/78762281/5144f8b8-ab88-4efd-9487-6a73ab3d9dce)

I had it there from the first version. Removed it and removed the card. Restarted HA. Installed bubblecard again. Now it is working.

**Comment by Clooos** [comment]
I'm glad that you fixed it! I had totally no ideas on how to fix that 😅

**Comment by Clooos** [comment]
Have you tried the new v1.6.3? It's possible that this is fixed.

**Comment by radhoo2k10** [comment]
Updated to 1.6.3 and it works for now. Will try it for a couple of days to check if it holds.
