### ISSUE TITLE
Custom element doesn't exist: button-card

### ISSUE THREAD

**Issue by H3XXdev** [Clooos/Bubble-Card#338]
Desktop 
 - OS: Windows
 - Browser: Edge
 - Version: 120.0.2210.91

Smartphone
 - Device: iPhone 13 Pro Max
 - OS: iOS 17.2.1
 - Browser:  Home Assistant Companion App
 - Version 2013.12.1

Hello,
After update bubble-card to 1.6.2 and changed in configuration.yaml to:
```
frontend:
  extra_module_url:
    - /hacsfiles/Bubble-Card/bubble-pop-up.js?v=1.6.2
```

and after restart HA, i have an error "custom element doesn't exist: bubble-card".
I have cleared Windows browser cache and HA Companion APP but didn't help.
What should I do to give it back to work ? 

Thank you! 🍻

**Comment by Boo1098** [comment]
@H3XXdev I'm having this issue as well. What did you do to resolve it?

**Comment by Clooos** [comment]
Since the latest updates of Home Assistant, with the v1.6.x versions the optimized mode is now obsolete. So you can remove it from your extra modules and in your pop-ups in YAML just replace `custom:bubble-pop-up` to `custom:bubble-card` then add `card_type: pop-up`.

It's a LOT easier now 🍻

**Comment by H3XXdev** [comment]
okay, this was helpfull, thank You.
I have one more question, do You know maybe how to remove the gap's ?

![image](https://github.com/Clooos/Bubble-Card/assets/45357516/44a91c67-ec02-46ee-978a-7318e88ed3ae)

I can't get the right way to remove the gaps between cards

**Comment by Clooos** [comment]
There is no large gap like in your screenshot in Bubble Card, your issue is not related to this project 😅
