### ISSUE TITLE
The popup card does not mute the camera feed's sound

### ISSUE THREAD

**Issue by joaopedros2** [Clooos/Bubble-Card#344]
I have an issue on my dashboard using the popup card and my cameras.

I'm using the 'frigate-hass-card' and have it set up to automatically start the live stream of the camera.

When I open the HA companion app, the camera sound remains active without opening the popup.
Even if I open and then close the popup, the issue persists.

I can only mute the sound by changing dashboards or completely closing the HA app.

Is there any way to prevent this?

**Comment by Clooos** [comment]
Hi, I'm aware of that issue but it should works with the default camera cards. But I will try to find how to fix that.

**Comment by joaopedros2** [comment]
With the latest version v1.6.3, the issue seems to be resolved.

Do I still need to specify the version in the link for bubble-pop-up.js in configuration.yaml?

**Comment by Clooos** [comment]
Glad that it's fixed! You can remove `bubble-pop-up.js` and replace your pop-ups from `custom:bubble-pop-up` to `custom:bubble-card`, the optimized mode is obsolete since the latest releases of Home Assistant.
