### ISSUE TITLE
"Custom element doesn't exist" on Google Nest Hub

### ISSUE THREAD

**Issue by KazemaRyukuro** [Clooos/Bubble-Card#345]
Hello, I have the problem that I can no longer use the Bubble Cards on my Google Nest Hub. I get the error message "custom element doesn't exist". All other third-party cards work as usual.

**Comment by Clooos** [comment]
Hi, take a look here 🙂
https://github.com/Clooos/Bubble-Card/issues/338

**Comment by bartzwederlander** [comment]
Same issue here, i cast to my nest hubs and since updating that doesn.t work. I already have type: custom:bubble-card
            card_type: pop-up, never had otherwise. I downgraded tot version 1.5.3 and now it's working fine again when casting. On the desktop it worked fine all the time, problems with the newer version only happened when casting the dash

**Comment by Clooos** [comment]
I will have to investigate on that issue, I really don't know why it's not working anymore.

**Comment by Clooos** [comment]
Could you try to reinstall it directly on the Nest Hub? If it works that way I might have an idea on how to fix that easily.

**Comment by Clooos** [comment]
Sorry if I wasn’t clear enough, what I mean is can you try to reinstall it in HACS directly on the Nest Hub, because when you do that you are sure that the cache is cleared on that device. If it's just a cache issue it will be easy for me to fix that.

**Comment by bartzwederlander** [comment]
i'm not an expert, i don't know what you mean bij install in HACS directly on the nest hub. I did reinstall bubble 1.6.4 in hacs now, but i have no idea how i could install something on the hub. The dashboard works fine on my desktop, but when casting it to the hub it gives an error and shows all vertical stacks in 1 page. I have no idea how i could force clear a cache in the hub itself

**Comment by Clooos** [comment]
Do you have HACS installed on you Home Assistant? Or did you do a manual installation?

**Comment by bartzwederlander** [comment]
i have hacs installed, but after installing bubble in hacs it did not show up, so i added - url: /hacsfiles/Bubble-Card/bubble-card.js
      type: module     in my configuration.yaml. same thing for mushroom, button card and expander card which i installed via HACS but did not show up untill i added the lines in the cfg and rebooted. all 4 cards work fine

**Comment by Clooos** [comment]
Ho so it's working now on your Nest Hub?

**Comment by bartzwederlander** [comment]
No, on the desktop the dashboard with bubble pop up works fine, but when casting the same dash to the nest hub there it gives error message "custom element doesn't exist" on the location of every horizontal stack button and shows all vertical stacks at the same time in one screen

**Comment by Clooos** [comment]
I misunderstood your answer, but this is strange that you had to add it this way to make it works. I will release a new beta soon that could maybe fixes your issue 🤞

**Comment by ahattest** [comment]
Same issue, I have bubble card installed trough Hacs in the normal way.

**Comment by cromelex** [comment]
Hi, I have the same issue with this. Basically, the issue only happens when casting the dashboard, the cards only show the error "custom element doesn't exist".

I installed with HACS but have also added manually in resources (something that I've seen suggested as a workaround for this error).

Happy to test further when you release a beta.

**Comment by Clooos** [comment]
Hi everyone! Here is a test version that I really hope could fix this issue, just install it with the [Without HACS](https://github.com/Clooos/Bubble-Card?tab=readme-ov-file#without-hacs) installation type.

All my fingers are crossed because I don't have a Nest Hub unfortunately 🤞

I can't wait for your feedback on this!

[Bubble Card Nest Hub test version.zip](https://github.com/Clooos/Bubble-Card/files/14296974/Bubble.Card.Nest.Hub.test.version.zip)

**Comment by cromelex** [comment]
Thanks. I've installed and will report back in a few days - there is no button to wipe the cache on the Nest Hub, so I can't see any effect immediately.

**Comment by Clooos** [comment]
Any new feedback after testing it? The new v1.7.1 contains the fixes I've applied in this test version posted above for everyone who wants to test this version.

https://github.com/Clooos/Bubble-Card/releases/tag/v1.7.1

**Comment by Clooos** [comment]
I'm still clueless... but I will not give up!

**Comment by cromelex** [comment]
I will try and reboot the nest again (and Hass) or otherwise change the dashboard URL tomorrow to try and force an update on case it's a cache issue, and will let you know.

By the way, the home assistant cast FAQ page says this, which I assume you looked at already but will say it just in case:

_Some custom cards rely on things that are only available in the normal Home Assistant interface. This requires an update by the custom card developer.

If you're a custom card developer: the most common mistake is that LitElement is extracted from an element that is not available on the page._

**Comment by cromelex** [comment]
Tried again today in a new dashboard so there wouldn't be caching issues. Still get the "Custom element doesn't exist".

**Comment by tdlamey** [comment]
I'm also experiencing this issue. My bubble popup cards look fine on my Chrome browser on PC, but I get the `Custom element doesn't exist: bubble-card.` message when casting to my Nest Hub Max.

I took a look at my [HA system logs](https://my.home-assistant.io/redirect/logs/) and I see the following error being logged when I start casting.

```
Logger: frontend.js.latest.202402071
Source: components/system_log/__init__.py:306
First occurred: 10:49:28 AM (6 occurrences)
Last logged: 3:41:55 PM

Uncaught error from Chrome 118.0.0.0 on Chromecast 1.56.500000 TypeError: Cannot convert undefined or null to object /hacsfiles/Bubble-Card/bubble-card.js:1:16782 /hacsfiles/Bubble-Card/bubble-card.js:520:30201
```

Looks like bubble-card.js has an issue with a type conversion / null reference.

I'd love to be able to use the bubble cards on my casting dashboard, they seem like they'd be a great addition. I hope this helps :)

**Comment by Clooos** [comment]
Hi everyone, I've released the v2 in beta and I wanted to know if it was possible that this issue was fixed?

By the way here is the link to the full changelog:
https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.1

**Comment by cromelex** [comment]
> Hi everyone, I've released the v2 in beta and I wanted to know if it was possible that this issue was fixed?
> 
> By the way here is the link to the full changelog: https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.1

I have just installed the new beta.2 and will report on this issue within the next few days.

Thanks

**Comment by cromelex** [comment]
Can confirm it still doesn't work. 
Same error as before.

**Comment by Clooos** [comment]
Finger crossed, I've worked on this in the last beta!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.5

**Comment by cromelex** [comment]
Issue still showing for me this morning with the beta5.

**Comment by Clooos** [comment]
Can I send you a dev release? It would help me to get a more detailed error.

**Comment by Clooos** [comment]
Sorry for the delay, here it is! This version is basically the same as the latest one but the logs will be much more relevant to fix this issue.

Thank you in advance for your help!

[Bubble Card v2.0.4 - Dev.zip](https://github.com/user-attachments/files/15837280/Bubble.Card.v2.0.4.-.Dev.zip)

**Comment by dmanfield** [comment]
Can confirm seeing the exact same error using v2.0.4 nothing new in the logs

**Comment by Clooos** [comment]
No error in the HA logs for frontend.js?

**Comment by dmanfield** [comment]
Give me a few may need to tweak some things. But this is what I get currently. 

`Logger: frontend.js.latest.202406280
Source: components/system_log/__init__.py:333
First occurred: 3:17:29 PM (1 occurrences)
Last logged: 3:17:29 PM

Uncaught error from Chrome 122.0.0.0 on Chromecast 1.56.500000 TypeError: Cannot convert undefined or null to object /hacsfiles/Bubble-Card/bubble-card.js:1:65544 /hacsfiles/Bubble-Card/bubble-card.js:1116:1271`

**Comment by Clooos** [comment]
Thank you! Do you have this error with the dev version or with the regular version?

**Comment by Shayne55434** [comment]
Any updates on this? I'm running version 2.1.1 and I have the same issue on my Google Hub.

**Comment by Clooos** [comment]
I'm still waiting for someone to help me on this, in my previous message I explain how someone can install the dev version. I really need the HA logs for that error.

**Comment by Shayne55434** [comment]
> I'm still waiting for someone to help me on this, in my previous message I explain how someone can install the dev version. I really need the HA logs for that error.

Ah. I figured that was an older version. I'd be happy to help. This weekend is a bit busy but, I should be able to get things sorted on Monday. Then I'll get you the logs.

Thanks for all the awesome work you've put into this and the amazing support you provide!

**Comment by immuu** [comment]
Hi @Clooos,  I installed the dev version. Only error message i found was this: 

```
Log details (ERROR)
Logger: frontend.js.modern.202408061
Source: components/system_log/__init__.py:333
First occurred: 8:53:08 AM (1 occurrences)
Last logged: 8:53:08 AM

Uncaught error from Chrome 122.0.0.0 on Chromecast 1.56.500000 TypeError: Cannot convert undefined or null to object eval (src/editor/bubble-card-editor.ts:10:27) ./src/editor/bubble-card-editor.ts (/local/bubble-card.js:329:1) __webpack_require__ (/local/bubble-card.js:413:41) eval (src/bubble-card.ts:11:87) ./src/bubble-card.ts (/local/bubble-card.js:19:1) __webpack_require__ (/local/bubble-card.js:413:41) /local/bubble-card.js:453:37 /local/bubble-card.js:455:12
```

I hope it helps. If not, please let me know where I can find the extra logging.

**Comment by Clooos** [comment]
This is perfect thank you! I will be finally able to fix that issue!

**Comment by Shayne55434** [comment]
> This is perfect thank you! I will be finally able to fix that issue!

Fantastic! Terribly sorry I couldn't get you the logs myself. Work for a bit crazy and then I've been busy with life.

Let me know if there's a beta version you'd like tested!

**Comment by Shayne55434** [comment]
Hello. Just checking to see if you need anything to get this fixed. Loving the progress you're making with everything!

**Comment by Clooos** [comment]
I have everything I need, I'm just focused on some pop-up issues for now, but I will definitely work on this one soon.

I will release a test version here as soon as I have a fix.

**Comment by Clooos** [comment]
I really hope that this is fixed this time 🤞

https://github.com/Clooos/Bubble-Card/releases/tag/v2.2.2

**Comment by immuu** [comment]
I updated the bubble card and rebooted both home assistant and nest hub. I still got this error: 

```
Logger: frontend.js.modern.202408090
Source: components/system_log/__init__.py:333
First occurred: 9:36:09 PM (1 occurrences)
Last logged: 9:36:09 PM

Uncaught error from Chrome 122.0.0.0 on Chromecast 1.56.500000 TypeError: Cannot convert undefined or null to object /hacsfiles/Bubble-Card/bubble-card.js:1:82010 /hacsfiles/Bubble-Card/bubble-card.js:1201:1270 /hacsfiles/Bubble-Card/bubble-card.js:1201:1274
```

Not sure if this can still be some cache issue or is this not yet fixed? Any hints for testing?

**Comment by Clooos** [comment]
Try again later, I don't know how the Nest Hub cache works but it's possible that it is cleared periodically. 

If it's still don't work I will try again.

**Comment by cromelex** [comment]
I've installed the latest version and I'll give it a try over the next few days to see if it fixed the issue.

I'm not sure how the cache works with the Google Cast services.

I tried just now on my Android TV (same casting functionality) and I get the same Custom element doesn't exist l, with V2.2.2

**Comment by Clooos** [comment]
Oh there is the same functionality on Android TV!? I have one! I will do my tests on it then! 🎉

**Comment by cromelex** [comment]
> Oh there is the same functionality on Android TV!? I have one! I will do my tests on it then! 🎉

Yes. It's just the Google Cast functionality. 
In the Home Assistant mobile app, go to Media, select a dashboard and then on the bottom you should be able to select a device to cast to.

Casting a dashboard to a TV is by no means optimal (it doesn't look good at all in my experience), but it should work for the sake of the test. Exact same error between the TV and the Google Nest in my case

**Comment by Clooos** [comment]
Finally 🎉

![IMG_20240816_225734](https://github.com/user-attachments/assets/eeec5f4d-9566-4575-ad95-3dbf217e321f)

**Comment by Clooos** [comment]
For the impatient ones.

[bubble-card.js.zip](https://github.com/user-attachments/files/16641722/bubble-card.js.zip)

**Comment by cromelex** [comment]
Fantastic! 
This will make my Nest Hub so much more useful. The screen is quite small but being able to use the bubble pop-ups will add a lot of flexibility to it!

**Comment by Clooos** [comment]
I've tested again and this is breaking the editor, but I will fix that.

**Comment by deeziboi** [comment]
> I've tested again and this is breaking the editor, but I will fix that.
> 
> Edit: This one is the one.
> 
> [bubble-card.js.zip](https://github.com/user-attachments/files/16641918/bubble-card.js.zip)

Unfortunately, I'm getting the same "custom element doesn't exist: bubble-card." error when trying to cast to my Nest Hub. I'm unsure if it's something with the cache as I can't find a way to clear the Hub's. I'll post an update if anything changes with mine throughout the day. Thanks!

**Comment by Clooos** [comment]
On my setup I've tried directly from my browser, just clear your browser cache then try again.

**Comment by Clooos** [comment]
Any news @deeziboi ?

**Comment by deeziboi** [comment]
> Any news @deeziboi ? Can someone confirm that it is working? You can install this [test version](https://github.com/Clooos/Bubble-Card/issues/345#issuecomment-2294330551) with the "Without HACS" method [here](https://github.com/Clooos/Bubble-Card/?tab=readme-ov-file#installation) (remove it first from HACS). Just make sure that you see v2.2.3 in the editor.

Sorry I was busy most of the day yesterday. I haven't dug into it too deeply but I did try to cast to one of my Nest Hubs again this morning before heading out and still got the same error. 

Let me know if there's anything else I can try to help get it working. Thanks!

**Comment by Clooos** [comment]
Have you checked if you have v2.2.3 in the editor?

**Comment by Shayne55434** [comment]
> Have you checked if you have v2.2.3 in the editor? Because I've just tried and this is still working on my Android TV.

It works! 🥳🎉 Thank you!

**Comment by Clooos** [comment]
Hi, this is issue is now finally fixed in the new release! 🍻

https://github.com/Clooos/Bubble-Card/releases/tag/v2.2.3
