### ISSUE TITLE
Pop Up Trigger Input Boolean not working

### ISSUE THREAD

**Issue by simensus** [Clooos/Bubble-Card#348]
Hi,

The Pop Up Trigger is still not working oin my dashboard. Tried also diffrent pop up cards!
I tried a input_boolean and a light entitie. Both triggers are not working!

![Bildschirmfoto 2024-01-09 um 13 13 50](https://github.com/Clooos/Bubble-Card/assets/101661986/f4b12a64-7bf0-4e01-b944-3e320cb8528c)

**Comment by Clooos** [comment]
Hi and thanks for the feedback!

 I've just fixed it, I will release a new version today 🙂

**Comment by Clooos** [comment]
I've just released it:
https://github.com/Clooos/Bubble-Card/releases/tag/v1.6.4
