### ISSUE TITLE
Integration conflict

### ISSUE THREAD

**Issue by rozza591** [Clooos/Bubble-Card#35]
It might be worth adding to the documentation that the 'Home Assistant Swipe Navigation' frontend app seems to stop the horizontal button stack from being able to scroll. 

I was banging my head against a wall for a few hours until I realised I still had it installed from an old dashboard.

**Comment by Clooos** [comment]
Thanks! I've added this here:
https://github.com/Clooos/Bubble-Card#custom-components-conflict

**Comment by WarC0zes** [comment]
Hi,
it's fix for bubble-card; https://github.com/zanna-37/hass-swipe-navigation/releases/tag/v1.13.0

Fixed 🐛
Android TV Card and Bubble Card have been added to swipe exceptions thanks to [@Nerwyn](https://github.com/Nerwyn) (https://github.com/zanna-37/hass-swipe-navigation/pull/60, closes https://github.com/zanna-37/hass-swipe-navigation/issues/61)

**Comment by Clooos** [comment]
Great news! Thanks 🥳
