### ISSUE TITLE
Divide by zero in Slider sometimes produces NaN for brightness/volume

### ISSUE THREAD

**Issue by MrEbbinghaus** [Clooos/Bubble-Card#350]
**Describe the bug**
When sliding the slide you sometimes get an error:
`Failed to call service light/turn_on. Expected int for dictionary value @ data['brightness']`

**To Reproduce**
1. Create a button for a light with type slider.
2. Slide the slider a couple of times.

**Expected behavior**

**Screenshots**
<img width="552" alt="image" src="https://github.com/Clooos/Bubble-Card/assets/2965273/7cccb980-8de3-420f-9bc6-be287fe5cf32">

**Desktop:**
 - OS: macOS
 - Browser: Brave (Chromium 120)
 - Version [e.g. 1.6.2]

**Additional context**
I've checked the debugger and it seems like it is caused by a divide by zero in `updateRange`.

```javascript
function updateRange(x) {
    const rect = rangeSlider.getBoundingClientRect();
    const position = Math.min(Math.max(x - rect.left, 0), rect.width);
    const percentage = position / rect.width;
    if (entityId.startsWith("light.")) {
        brightness = Math.round(percentage * 255);
    } else if (entityId.startsWith("media_player.")) {
        volume = percentage;
    }

    rangeFill.style.transition = 'none';
    rangeFill.style.transform = `translateX(${percentage * 100}%)`;
}
```

https://github.com/Clooos/Bubble-Card/blob/main/src/cards/button.ts#L250

<img width="681" alt="image" src="https://github.com/Clooos/Bubble-Card/assets/2965273/a7b191a2-605c-48ed-a19a-39a9e0c855a7">

I don't know why sometimes the rangeSlider is 0 in every dimension.

**Comment by Clooos** [comment]
This issue should be finally fixed in the v2 beta!

Here is the link to the full changelog:
https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.1
