### ISSUE TITLE
popup option box not loading on desktop (mini climate card)

### ISSUE THREAD

**Issue by Pel1can111** [Clooos/Bubble-Card#351]
Seem to be having an issue where the popup option dialog to control climate devices wont load on desktop. This works fine on mobile (iOS). Clicking the button just does nothing. The example image below show the menu that wont load.

![Untitled](https://github.com/Clooos/Bubble-Card/assets/60351053/d88dccb8-228e-4d6d-a97e-a92a963d4bc8)

**Comment by Clooos** [comment]
Hi, can you tell me if this issue is still here in the v2 beta?

Here is the link to the full changelog:
https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.1

**Comment by Pel1can111** [comment]
It appears to still be broken on desktop. I have tried firefox and edge with the same result as before.

**Comment by Pel1can111** [comment]
Not sure if it was intentional but my issue has been solved in the lastest beta. :)

**Comment by Vansmak** [comment]
im just using a input toggle instead for now but want a way to remove or hide the .bubble-close-button

**Comment by Clooos** [comment]
> to piggy back here, i also notice popup only working on mobile. what i noticed on desktop it only shows if i use a bubble card like horizontal button card to call it #. If i use another card, like custom button card or mushroom chip card and tap action navigate # then it only works on mobile app and mobile browser.
> 
> this will pop up the vertical stack card but only on mobile
> 
> ```
> custom_fields:
>   queue:
>     card:
>       type: custom:mushroom-chips-card
>       chips:
>         - type: action
>           icon: m3s:queue-music-outlined-filled
>           tap_action:
>             action: navigate
>             navigation_path: '#queue'
> ```
> 
> this works on both
> 
> ```
> type: custom:bubble-card
> card_type: horizontal-buttons-stack
> button_type: name
> name: Queue
> show_name: true
> show_icon: false
> hash: '#queue'
> 1_link: '#queue'
> ```

This issue is totally different from this one, this is an issue from Mushroom. 

Can you open an issue on its GitHub? You can explain that I suspect that the navigate action don't fire the "location-change" event like the other default cards. And to be sure, have you updated Mushroom?

**Comment by Clooos** [comment]
> Not sure if it was intentional but my issue has been solved in the lastest beta. :)

This is intentional, I'm glad that you confirmed this! 🥳
