### ISSUE TITLE
Margin not correct with Horizontal buttons stack 

### ISSUE THREAD

**Issue by myhrmans** [Clooos/Bubble-Card#352]
**Describe the bug**
When cards take up more then the screen area Im not able to see the full bottom card.

**To Reproduce**
1. Fill area with cards
2. Add horizontal button stack
3. See if bottom stack covers bottom card - and you cant scroll down

**Expected behavior**
There should be a margin enough at the bottom so I can scroll or see the full card.

**Screenshots**
<img width="686" alt="image" src="https://github.com/Clooos/Bubble-Card/assets/14261388/462738e2-d57e-432a-8c62-2c480f7ea631">

![Screenshot_20240110_133120_Home Assistant.jpg](https://github.com/Clooos/Bubble-Card/assets/14261388/c529dae7-07e4-4912-b9c3-8d045918800e)

Version is 1.6.4

**Comment by myhrmans** [comment]
Found in another issue:

`type: custom:bubble-card
card_type: empty-column
card_mod:
  style: |
    ha-card {
      display: block;
      height: 100px !important;
    }
`
Fixed it for me, maybe put into documentation?

**Comment by Clooos** [comment]
This issue is finally fixed in the v2 beta!

Here is the link to the full changelog:
https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.1
