### ISSUE TITLE
Pop Up Trigger not closing

### ISSUE THREAD

**Issue by simensus** [Clooos/Bubble-Card#354]
Next Problem with the Pop Up Trigger:

Its opening now with the trigger, but when the state changes its not closing the popup!

**Comment by Clooos** [comment]
Damn! I will fix that then, thanks for the feedback!

**Comment by rogferd** [comment]
Possibly the same issue... Bubble Card 1.6.4. Popup does not respond to click or tap on the popup "X" close button.

**Comment by Clooos** [comment]
Hi, I've just released a new version that should fix that issue 🤞

https://github.com/Clooos/Bubble-Card/releases/tag/v1.7.0
