### ISSUE TITLE
bubble card closes when i want to change the date on a datatime input field

### ISSUE THREAD

**Issue by liamwibo** [Clooos/Bubble-Card#360]
Hi I use the bubble card for a lot off things and one of the is using it for an event scheduler.
this on itself works like indented until I want to create an event I use date time input fields to choose my start and end time.
When want to change the date it pops up the little calendar and to choose a day. but as soon as I interact with the popup to change the date the popup card goes down. is there a way for the bubble popup card to stay open while in interact with the date and time input field.

**To Reproduce**
Steps to reproduce the behaviour:
1. make an datatime input field
2. put the datetime input field in a bubble popup card using a vertical stack
3. Try to interact with the datetime input field
4. The bubble popup card goes down

**Expected behaviour**
I want the bubble card to stay open while i am changing the date and only go down when i click the close button or swipe it away

**Screenshots**
![image](https://github.com/Clooos/Bubble-Card/assets/60398653/e28a60b5-0cba-452f-9fb3-6402f2b1c7a5)
![image](https://github.com/Clooos/Bubble-Card/assets/60398653/06a9b667-c3ed-48f0-bf95-747fb96c59b6)

On the second screenshot I interacted with the calendar and the popup card went down.
Sorry if there is anything wrong with my Bug report this is my first time making one.
Thank you in advance

**Comment by Clooos** [comment]
Hi! Your bug report is perfect, thanks! I will fix that as soon as I can!

**Comment by liamwibo** [comment]
> Hi! Your bug report is perfect, thanks! I will fix that as soon as I can!

thank you for responding so quick. looking forward to the fix

**Comment by Clooos** [comment]
Hi, I've just released a new version that fix that issue!

https://github.com/Clooos/Bubble-Card/releases/tag/v1.7.0
