### ISSUE TITLE
Popup card not working good anymore

### ISSUE THREAD

**Issue by skank01** [Clooos/Bubble-Card#361]
Hi
I'm experiencing havy problems.
Im on latest version.
I think it was quite good 2 versions ago
But now, its heavy, not loading good anymore

On my laptop/browser its good
On my android phone, using companion app,
Its sloooooow, then scrolling in the popup is hell !
Buttons arent fully loaded, and scrolling is true hell

Cleared cache, but doesnt fix it, any idea?

**Comment by skank01** [comment]
To add stuff
I tried to use the normal mode, and the optimized mode, no difference

Popup card on phone,  isnt loading good
![image](https://github.com/Clooos/Bubble-Card/assets/53368406/4cf8168c-b2d4-4558-9b2b-509fd5dc5200)
![image](https://github.com/Clooos/Bubble-Card/assets/53368406/cff1a354-0862-4706-ad74-af71db39079b)


But on laptop and tablet, its working as expected
![image](https://github.com/Clooos/Bubble-Card/assets/53368406/d28a5d8b-75b8-4fe7-b8a0-9fd037bbb441)


Tried on different phones with the app, always the same

**Comment by joaopedros2** [comment]
I having problems too. My feed cameras not working with sound

**Comment by Clooos** [comment]
Hi and thank you for your feedback, are you using card-mod in your pop-ups? And also have you tried to set the background blur to 0?

**Comment by skank01** [comment]
I removed some popups and now the card is working again, i think it was too heavy to load...

**Comment by Clooos** [comment]
Do you have/had pop-ups with cameras?

**Comment by skank01** [comment]
Yes 1 popup with 3 cameras

**Comment by clutch70** [comment]
Smells like the DOM thing in #370

**Comment by Clooos** [comment]
Hi, I've just released a new version that that should fix that issue 🤞

https://github.com/Clooos/Bubble-Card/releases/tag/v1.7.0
