### ISSUE TITLE
Mini Media Player - pop up - stretch/aspect issue

### ISSUE THREAD

**Issue by BristolBEAT** [Clooos/Bubble-Card#364]
I have an issue with the 'mini media player' and the pop up card. When I switch on my STB (SkyQ) it stretches the whole pop up card off of the screen. Is there a way to set the aspect? Let me know if you want me to email image examples.

Note: this issue does not happen with any other view, only bubble card pop ups.

![Mini Media Player Off](https://github.com/Clooos/Bubble-Card/assets/109667579/bd2a6648-d08f-47a4-951e-a2ce6b056d55)
![Mini Media Player On](https://github.com/Clooos/Bubble-Card/assets/109667579/8d85a970-1399-4b18-b1b2-2ee45558e184)

**Comment by holt3000** [comment]
I'm having the same issue

**Comment by Clooos** [comment]
This issue should be fixed in the next beta, I just need a bit more time to release it as I have some other issues to fix.

**Comment by BristolBEAT** [comment]
I created a temporary fix by putting the mini media player into a 'grid' type.

square: false
type: grid
cards:
  - artwork: material
    entity: media_player.sky_q_mini
    hide:
      icon_state: false
      power_state: false
      source: false
      volume: true
    info: scroll
    name: SkyQ
    shortcuts:
      buttons:
        - icon: mdi:chevron-up
          id: channelup
          type: skyq
        - icon: mdi:chevron-down
          id: channeldown
          type: skyq
        - icon: null
          id: sky
          name: Sky
          type: skyq
        - icon: mdi:home-outline
          id: home
          type: skyq
        - icon: mdi:record-rec
          id: record
          type: skyq
        - icon: mdi:television-guide
          id: tvguide
          type: skyq
        - icon: mdi:keyboard-return
          id: dismiss
          type: skyq
        - icon: mdi:information-variant
          id: i
          type: skyq
        - icon: mdi:arrow-right-thick
          id: right
          type: skyq
        - icon: mdi:arrow-left-thick
          id: left
          type: skyq
        - icon: mdi:arrow-up-thick
          id: up
          type: skyq
        - icon: mdi:arrow-down-thick
          id: down
          type: skyq
        - icon: null
          id: select
          name: Select
          type: skyq
      columns: 6
      hide_when_off: true
    type: custom:mini-media-player
    toggle_power: false
columns: 1

**Comment by Clooos** [comment]
This issue is now fixed in the last beta 🎉
