### ISSUE TITLE
custom:swipe-card compatibility

### ISSUE THREAD

**Issue by martinargalas** [Clooos/Bubble-Card#366]
**Describe the bug**
It seems there is a problem with **custom:swipe-card** compatibility. All the items defined with such card, are still visible after bubble card popups. 
Swipe card GitHub (https://github.com/bramkragten/swipe-card?tab=readme-ov-file)

**To Reproduce**
1. Create a custom:swipe-card card on a dashboard
2. Create a custom:bubble-card popup on the same dashboard
3. Click on the bubble card to make it show the popup overlay (which should be so far clear, without any cards)
4. Swipe card is visible on the overlay of the bubble card

**Expected behavior**
I would expect anything that is "under" the overlay of the bubble card to NOT be visible on the bubble card popup

**Screenshots**
- Default dashboard. Some of the cards are defined with custom:swipe-card, some are not.
![image](https://github.com/Clooos/Bubble-Card/assets/148718741/3c621cbe-dca9-4fb0-9277-c3012491d68f)

- After clicking on Heating bubble card, I should not see any cards from the dashboard. They should be blurred, but they are not.
![image](https://github.com/Clooos/Bubble-Card/assets/148718741/f609d19e-b666-4e00-aa5c-a489d67eae8c)

**Desktop (please complete the following information):**
 - OS: Win11
 - Chrome

I realise this is probably not a bug of the Bubble-card, but it seems to prevent a usage of these two great cards together. Maybe it could still be fixed?

Thank you! 🍻

**Comment by Clooos** [comment]
This issue is now fixed in the last beta.

**Comment by martinargalas** [comment]
Great job! Just tried it out and confirming this is working.
