### ISSUE TITLE
Entity search resetting after few seconds

### ISSUE THREAD

**Issue by jamesarm97** [Clooos/Bubble-Card#37]
If I add a bubble card to a vertical stack and try and type in a partial name in the Entity field so it will display a filtered list for searching, that list will reset and show all entities if you do nothing for a few seconds and makes it really hard to find an entity when you have hundreds and don't know the exact name.

**Comment by Clooos** [comment]
Hi, this issue was normally fixed in the last beta, what beta version have you installed?
