### ISSUE TITLE
Opening a dashboard with mulitple custom:bubble-card shows every single card for a short time

### ISSUE THREAD

**Issue by 0verEngineer** [Clooos/Bubble-Card#370]
**Describe the bug**
When i open a dashboard with multiple bubble-cards and a horizontal-buttons-stack as last one i can see every single bubble-card in this view pop up once on loading for a short amount of time until either the default card is shown or no card (if no default). This happens on mobile and the web and looks very bad.
It is especially frustrating if i had the app opened and a bubble-card shown, put the app in the background, wait a bit and then reopen the app to see that it loads all cards and flickers and then it goes to the default. The bubble-card shown before the app was put in the background should be the active one in this case.

**To Reproduce**
1. Open a dashboard with multiple bubble-cards
2. See error

**Expected behavior**
1. Loading the cards should not flicker every card in your face.
2. After the app was in the background and is reopened the same card should be shown.

**Screenshots**
I will add a video if this behavior is not reproducible or not known

**Desktop (please complete the following information):**
 - OS: Fedora 39 KDE
 - Browser: Firefox
 - Version: 1.6.4

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7 Pro
 - OS: CalyxOS 5.3.0 (Android 14)
 - Browser: Home Assistant Companion App
 - Version: 1.6.4

**Comment by Clooos** [comment]
Hi and thank you for your feedback, can you tell me on what Home Assistant version you are? Because this issue should not happen in the latest version of HA.

**Comment by 0verEngineer** [comment]
Core 2024.1.5
Frontend 20240104.0

**Comment by reset18** [comment]
Yes, the same problem also happens to me with a version of Bubble card (I don't remember which version).

**Comment by HAlover99** [comment]
I have the same problem.
HA version: 2024.1.3
Bubble-card 1.6.4

**Comment by clutch70** [comment]
So I had this problem too, but I actually think it's a little bigger than just a flicker. After updating to 1.6.4 I got the flicker thing, but also noticed the bandwidth on my kiosks spiked. I have several webrtc cards on the pop-ups, which makes me feel like all the cameras are still loaded in the DOM after the page finishes loading.

**Comment by clutch70** [comment]
This is still not fixed, same behavior in 1.7.3.

Please re-add 1.5.3 to the release list in HACS. That was the last time I was stable.

**Comment by Clooos** [comment]
Hi, have you installed the `bubble-pop-up-fix.js`? This is explained in the documentation.

**Comment by clutch70** [comment]
Yes, bubble-pop-up-fix.js has been in place. I went and got the latest revision of it from 1.7.3, restarted a fully kiosk tablet, and still have the same behavior.

**Comment by clutch70** [comment]
Rolling back to 1.5.3 and clearing cookies/cache/storage in fully kiosk restored desired behavior.

**Comment by clutch70** [comment]
Worth noting, changing the version tag at the end of the dashboard's JS resource got the companion app to get in line without having to blow it away and totally set all the smartphone stuff back up.
