### ISSUE TITLE
icon doesn't override entity picture on button card used for media volume control

### ISSUE THREAD

**Issue by FrankJaco** [Clooos/Bubble-Card#375]
Since upgrade to v1.6.4 my volume controls show a small image of the media instead of the icon that I established. I am aware the feature to show the entity-picture was added in this version, but I have an icon defined which should override the image according to the documentation.

Here is what I see:

![image](https://github.com/Clooos/Bubble-Card/assets/79318542/e86a5cb8-2fe7-4d14-9d7c-b52bd6879bc2)

What I expect to see in the button card is below.  As I use the "Sofa" icon to identify the Living Room volume control, it is important to me to show the icon, not the image of the album art.

![image](https://github.com/Clooos/Bubble-Card/assets/79318542/c9b71f6b-0852-41b9-93c0-09348e412ff3)

Below you can see the gui setting for the bubble slider:

![image](https://github.com/Clooos/Bubble-Card/assets/79318542/ae1e5ebb-01c8-4f14-ac9b-b73fa20074c3)

Here is the yaml:

    card:
      type: custom:bubble-card
      card_type: button
      entity: media_player.living_room_speakers
      button_type: slider
      name: ' '
      icon: mdi:sofa-outline
      show_state: false

The ability to show the entity-picture is a nice feature!  Just not in this use-case.

fj

**Comment by Clooos** [comment]
Hi and thanks for your feedback! Indeed this is forced for now, I will add a toggle to change that behavior.

**Comment by Clooos** [comment]
Hi, I've added this possibility in the v2 beta!

Here is the link to the full changelog:
https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.1
