### ISSUE TITLE
Bubble card not closing

### ISSUE THREAD

**Issue by robotsmarthomes** [Clooos/Bubble-Card#380]
Hi Cloos,

We are experiencing an issue after the last update. 

Cloisng the bubble card by pressing the 'x' has been a bit glitchy since the last recent update. Mobile and Desktop. 

the version we are running is the latest version V1.6.4

**Comment by Clooos** [comment]
Hi, I've just released a new version that I hope fixes that issue 🤞

https://github.com/Clooos/Bubble-Card/releases/tag/v1.7.0
