### ISSUE TITLE
Bubble card did not work since a couple of weeks

### ISSUE THREAD

**Issue by flo2126** [Clooos/Bubble-Card#382]
I have 4 buttons and only one will open the bubble card since weeks.
Velux is the only on which will open. 

`type: custom:bubble-card
card_type: horizontal-buttons-stack
1_link: '#fav'
1_name: Favoriten
1_icon: mdi:home-heart
2_link: '#muell'
2_name: Müll
2_icon: mdi:trash-can-outline
3_link: '#velux'
3_name: Velux
3_icon: phu:tilt-window-closed
4_link: '#szenen'
4_name: Szenen
4_icon: mdi:lightbulb-auto-outline
is_sidebar_hidden: true
`

Facoriten Card:

`type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#fav'
    name: Favoriten
    icon: mdi:home-heart
    entity: light.signify_netherlands_b_v_lwa009_light
    state: sensor.climate_wohnzimmer_temperature
    auto_close: '12000'
    tap_action:
      action: toggle
  - type: horizontal-stack
    cards:
      - type: custom:bubble-card
        card_type: button
        entity: switch.rocket
        button_type: switch
        name: Rocket Espresso
        icon: mdi:coffee-maker-outline
      - type: custom:bubble-card
        card_type: button
        entity: switch.signify_netherlands_b_v_lom007_switch
        name: Drucker
        icon: mdi:printer
  - type: horizontal-stack
    cards:
      - type: custom:bubble-card
        card_type: button
        entity: switch.tasmota_4
        button_type: switch
        name: Pumpe Zisterne
        icon: mdi:water
      - type: custom:bubble-card
        card_type: button
        entity: input_boolean.heizungsthermostate_on
        name: Heizung Auto
        icon: mdi:thermostat-auto
  - type: horizontal-stack
    cards:
      - type: custom:bubble-card
        card_type: button
        entity: scene.theo_nachtlicht
        button_type: switch
        name: Nachtlicht Theo
        icon: mdi:lightbulb-night-outline
      - type: custom:bubble-card
        card_type: button
        entity: switch.hp_dock
        button_type: switch
        name: HP Docking Station
        icon: mdi:laptop
  - type: horizontal-stack
    cards:
      - type: custom:bubble-card
        card_type: button
        entity: switch.fritz_box_7590_ax_wi_fi_fritz_box_gast
        name: Gast Wlan
        icon: kuf:it_router
  - type: conditional
    conditions:
      - condition: state
        entity: switch.fritz_box_7590_ax_wi_fi_fritz_box_gast
        state: 'on'
    card:
      type: picture
      image: https://demo.home-assistant.io/stub_config/t-shirt-promo.png
      image_entity: image.fritz_box_7590_ax_fritz_box_gast
`

Mull Card

`type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#muell'
    name: Müll
    icon: mdi:trash-can-outline
    entity: light.signify_netherlands_b_v_lwa009_light
    state: sensor.climate_wohnzimmer_temperature
    auto_close: '12000'
    tap_action:
      action: toggle
  - square: false
    type: grid
    cards:
      - type: custom:mushroom-title-card
        title: M ü l l
    columns: 1
  - cards:
      - entity: sensor.abfallrestmuell
        icon_color: grey
        due_color: FireBrick
        icon_size: 35px
        hide_before: -7
        type: custom:garbage-collection-card
      - entity: sensor.abfallgelber_sack
        icon_color: Gold
        due_color: Gold
        icon_size: 35px
        hide_before: -7
        type: custom:garbage-collection-card
      - entity: sensor.abfallaltpapier
        icon_color: FireBrick
        due_color: FireBrick
        icon_size: 35px
        hide_before: -7
        type: custom:garbage-collection-card
      - entity: sensor.abfallspermuell
        icon_color: orange
        due_color: orange
        icon_size: 35px
        hide_before: -7
        type: custom:garbage-collection-card
    type: vertical-stack
`

**Comment by flo2126** [comment]
![Bildschirmfoto 2024-02-12 um 07 30 31](https://github.com/Clooos/Bubble-Card/assets/135869813/d98ff3da-de0b-40fa-85a5-391c9a76892f)
![Bildschirmfoto 2024-02-12 um 07 30 45](https://github.com/Clooos/Bubble-Card/assets/135869813/156c873c-323c-43fc-9b20-31a9233519ef)

**Comment by Clooos** [comment]
Hi! A new version will come soon, I hope that it will fixes your issue. I've worked A LOT on the pop-ups stability and everything should be perfect now 🤞

**Comment by Clooos** [comment]
Hi, I've just released the new version, please tell me if it's fixed 🤞

https://github.com/Clooos/Bubble-Card/releases/tag/v1.7.0

**Comment by Clooos** [comment]
I'm closing this, this issue should be fixed in the v2 beta.
