### ISSUE TITLE
Blank card with mini-media-player until click/tap

### ISSUE THREAD

**Issue by murkumurdok** [Clooos/Bubble-Card#384]
**Describe the bug**
When I bring up a card using the [mini-media-player](https://github.com/kalkih/mini-media-player) custom card, the bubble card initially shows up blank until I click into/tap on the card, then all of the buttons show up.  This behavior does not happen on other cards, including other custom cards.

**To Reproduce**
Tap on card using mini-media-player custom card

**Expected behavior**
I expect the card to open normally like other cards

**Screenshots**
See screen recording.  The first three cards open normally, but the problematic cards are Family Room Receiver and Gym Receiver--both use the mini media player custom cards.  Their code is both identical except for the entities.

https://github.com/Clooos/Bubble-Card/assets/26509777/b1f53553-c7ca-4a3d-86a3-2e83453fa7a0

**Desktop (please complete the following information):**
 - OS: Safari on MacOS

**Smartphone (please complete the following information):**
 - Device: iPhone 13, Macbook Pro M1
 - OS: iOS 17.2.1
 - HA Companion App
 - Version: latest

**Additional context**

See yaml [here](https://pastebin.com/EQh26Pvh) for cards

Thank you! 🍻

**Comment by Clooos** [comment]
Hi, I've just released a new version that I hope fixes that issue 🤞

https://github.com/Clooos/Bubble-Card/releases/tag/v1.7.0

**Comment by murkumurdok** [comment]
> Hi, I've just released a new version that I hope fix that issue 🤞
> 
> https://github.com/Clooos/Bubble-Card/releases/tag/v1.7.0

I would say that your update 99% fixed the issue.  Now, when I pull up the bubble card, it will instead flash for a half-second, but then the card will display without user intervention as it should.  See below for another video example.  For my purposes, this is quite fine and I don't have a problem with it, but I'll leave the issue open just in case you want to investigate that brief flash earlier.  Thanks for your hard work!

https://github.com/Clooos/Bubble-Card/assets/26509777/31e41aaf-36d1-475d-a5e1-82229f1b3f15

**Comment by Clooos** [comment]
Thanks for your feedback! Could you share your YAML for that pop-up so that I can check what's wrong?

**Comment by murkumurdok** [comment]
> Thanks for your feedback! Could you share your YAML for that pop-up so that I can check what's wrong?

Sure, see here: https://pastebin.com/EQh26Pvh

**Comment by villmatt** [comment]
Experiencing the same issue. If @murkumurdok can confirm, for me this is only replicable on WebKit. Unable to reproduce on desktop chrome

**Comment by murkumurdok** [comment]
> Experiencing the same issue. If @murkumurdok can confirm, for me this is only replicable on WebKit. Unable to reproduce on desktop chrome

Confirmed, same.

**Comment by Clooos** [comment]
This issue should be fixed in the v2 beta, can you confirm this?

Here is the link to the full changelog:
https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.1

**Comment by murkumurdok** [comment]
Hi, sorry I didn't get a chance to check the beta, but I just installed 2.0.1 and the issue appears to be fixed.  I appreciate your work.
