### ISSUE TITLE
background color button horizontal

### ISSUE THREAD

**Issue by kiloptero** [Clooos/Bubble-Card#386]
hi guys! who is using bubble cards? with the last update my button has a weird color. Normally when every lights or entity is off.. cocina button shows with a black background and with high opassity.. any idea?![image](https://github.com/Clooos/Bubble-Card/assets/35468634/6eadb67f-fa0a-4346-bd48-fe8204d90255)

**Comment by Clooos** [comment]
Hi, I've changed that in the new release for making it more visible on some setups. But indeed that color should be the same as your background. Have you made any modification to the style?

**Comment by kiloptero** [comment]
no;( just update the front end on hacs and restart



Andres Roepke Del Solar.
Ingeniero Civil Industrial
Ingeniero Electronico
Mobile 88196932

**Comment by kiloptero** [comment]
![image](https://github.com/Clooos/Bubble-Card/assets/35468634/94a6e4df-911f-4276-95ee-77b2765f6545)


lights on

**Comment by kiloptero** [comment]
there was some legacy code

my mistake!
