### ISSUE TITLE
Styling horizontal button card

### ISSUE THREAD

**Issue by telegrambeans** [Clooos/Bubble-Card#388]
Since the latest version, the styling doesn't work properly for horizontal button stack anymore. 

![IMG_20240215_091037](https://github.com/Clooos/Bubble-Card/assets/13040847/19290149-8233-4aa9-b2da-66d515eaa7c4)

The background is overwritten by the active entity and thus does not remain transparent.

**Comment by telegrambeans** [comment]
Before that:

![fully-screenshot (10)](https://github.com/Clooos/Bubble-Card/assets/13040847/d297a729-daf6-4771-8804-199c11075d9d)

**Comment by Clooos** [comment]
Hi! I'm sorry, this was a small breaking change that I forgot to mention.

Here is how to change the background color now:

styles: |
  .kitchen > .color-background {
    background-color: ${hass.states['light.kitchen'].state === 'on' ? 'blue' : 'red'} !important;
  }

**Comment by telegrambeans** [comment]
Can I remove the border in the same way?

**Comment by Clooos** [comment]
It should be possible yes, try `border: none !important`.

**Comment by dnestico** [comment]
This doesn't work on buttons that don't have the hash link

> Hi! I'm sorry, this was a small breaking change that I forgot to mention.
> 
> Here is how to change the background color now:
> 
> ```yaml
> styles: |
>   .kitchen > .color-background {
>     background-color: ${hass.states['light.kitchen'].state === 'on' ? 'blue' : 'red'} !important;
>   }
> ```
