### ISSUE TITLE
Pop-up initialization fix with other Front End Lines

### ISSUE THREAD

**Issue by prestonsmartuk** [Clooos/Bubble-Card#389]
Hi,

I followed this https://github.com/Clooos/Bubble-Card#pop-up-initialization-fix and it appears to work when just using this code (thank you). 

However, I have other lines in under my Front End, so if those lines are prior to this fix entry, then the fix doesn't work. 

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/custom-brand-icons.js
    - /local/card-mod.js
    - /hacsfiles/Bubble-Card/bubble-pop-up-fix.js

**Comment by Clooos** [comment]
Hi, have you tried putting it in the first position?

**Comment by prestonsmartuk** [comment]
Hey, yes I have. Still same thing

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/Bubble-Card/bubble-pop-up-fix.js
    - /local/custom-brand-icons.js
    - /local/card-mod.js

**Comment by Clooos** [comment]
I've just looked at my config and on mine the fix is just after card-mod.js and it's working correctly. Could you try to just remove `/local/custom-brand-icons.js` to see if there is not a conflict with it?

**Comment by prestonsmartuk** [comment]
Tried that, didn't change anything. I think it could be this line themes: !include_dir_merge_named themes conflicting with your fix. But then I'm not 100% what your fix does, I know when I used to load the iOS companion app, it would 'flicker' at the bottom of the home page, as it was loading up the bubble cards in the background.

Yes I rebooted Home Assistant.

**Comment by prestonsmartuk** [comment]
Ok I can definitly confirm that line themes: `!include_dir_merge_named themes` is conflicting with your fix. 

Removing the themes line, the bubble pop up loading issues I was having are gone from Android & iOS companion apps, and also Chrome Browser

**Comment by Clooos** [comment]
Really interesting, but I have that line too at the same place in my config. I don't even remember what it is for, I guess for the custom themes. But I will take a look at that, thanks for the info!

**Comment by prestonsmartuk** [comment]
Strange, but no worries at all. The code is for HACS themes, I was using the ios dark mode themes. 

Since your update and initialisation fix (plus me removing theme line) I've re-test performance on an iPhone 13 Mini, Honor Pad X9 tablet, iPlay 50 mini Pro NFE tablet - in companion apps and Fully Kiosk. It's has made a massive difference, so thank you! Keep up the great work, your card has the wife seal of approval ;)
