### ISSUE TITLE
Custom elemet Doesn't exist: bubble card

### ISSUE THREAD

**Issue by CR6-SE** [Clooos/Bubble-Card#390]
Hey there,

I have the above issue on the mobile app (android). 
Cleared the cache, but no luck. 
I used the latest Version 1.7

Best regards and thx for your work!

**Comment by CR6-SE** [comment]
Today IT IS working.  
Strange 😅

**Comment by Clooos** [comment]
It was probably a cache issue, glad that this is working now!
