### ISSUE TITLE
New Popup approach disables card-mod-theme

### ISSUE THREAD

**Issue by hellomarb** [Clooos/Bubble-Card#395]
I don't think it can be fixed, but perhaps it has to be added to the documentation: 
if you are using a `card-mod-theme` in your theme like 

```
card-mod-card: |
    .type-tile {
      background: red !important;
    }
``` 
it won't work anymore if a card is placed in a popup.

If you add it inside the card like

```
card_mod:
    style: |
      .type-tile {
        background: red !important;
      }
``` 
it still works without problems.

So global styles in your theme will break, specific customizations still work. Even cards rendered by `auto_entities` or `decluttered_card` get their custom styles applied, because they are rendered different.

That should added to the documentation, took me some time to realize what was the problem.

**Comment by Clooos** [comment]
Thanks for the info! I'm not sure that it can be fixed on my side but I will take a look at that.

**Comment by Clooos** [comment]
I've changed something related to that new approach, there was an other issue with it. It's even faster (again) now! 

I can't say for sure but maybe that it will fix that issue 🤞

**Comment by Clooos** [comment]
The new update is available!

**Comment by hellomarb** [comment]
I've tested it and for me it is not working :(

```
card-mod-card: |
    .type-tile {
      background: red !important;
    }
``` 

That is my test case in my custom theme and it is not working.
I even tested the file you posted here, same result.

Add a tile card on the dashboard and in a popup card, then you see it directly with the card_mod theme.

**Comment by hellomarb** [comment]
It is working again as expected, so it is finally fixed with the new approach 🍻
