### ISSUE TITLE
Gauge card missing text

### ISSUE THREAD

**Issue by liamstears** [Clooos/Bubble-Card#399]
I use gauge cards to display humidity and temperature, these work perfectly fine on normal dashboards and also work fine on 1.6.4 but somewhere in the 1.7.x changes these are broken

The gauge card all works apart from the main text, the main text just simply isn't there anymore, in my attached screenshot this would be the actual temperature and humidity. The text saying temperature and humidity is fine it's only the text that displays actual data that has vanished

Hope this can be resolved

![Screenshot_20240225_043627_Brave](https://github.com/Clooos/Bubble-Card/assets/67321276/83a16534-59ab-44fe-b69e-acca69c1f811)

**Comment by Legrand5382** [comment]
Yes same for me.

**Comment by Clooos** [comment]
Is this issue happening when you add this card in a pop-up? I guess that this is what you wanted to say. You can toggle background_update to true on this pop-up, this should works.

**Comment by liamstears** [comment]
> Is this issue happening when you add this card in a pop-up? I guess that this is what you wanted to say. You can toggle background_update to true on this pop-up, this should works.

Thank you for replying, this does work, however documentation says this is not recommended but also this was not required on earlier versions? If this works and will not cause issues however I am happy :-D

**Comment by Clooos** [comment]
I should add more details to the documentation about this. It is not recommended for certain pop-ups, especially those with cameras. However, in your case, it is fine. 

This feature was introduced to revert the previous behavior of the pop-ups, as I was aware it could break some cards.

**Comment by liamstears** [comment]
> I should add more details to the documentation about this. It is not recommended for certain pop-ups, especially those with cameras. However, in your case, it is fine.
> 
> This feature was introduced to revert the previous behavior of the pop-ups, as I was aware it could break some cards. But I'm still looking for a better solution, I will do my tests specifically with the gauge card now.

Thanks for the clarification however one of my popups does have a custom:frigate-card displaying a camera, could this be a potential issue? Everything does seem to be running fine/smoothly at the moment though...

P.s I've found the latest versions incredibly smooth and bug free (apart from this teething issue if course lol)

**Comment by Clooos** [comment]
If it works for you you don't have to worry, this is mainly for older devices and huge configurations.

**Comment by Nazze** [comment]
![IMG_9722](https://github.com/Clooos/Bubble-Card/assets/33813707/4d6d0fae-7210-475c-8a65-37c3f4b5dece)

Hi! I am having a similar issue, but background update does not solve it for me.

**Comment by iankaufmann** [comment]
Sorry to pile on here, but I found these threads today after experiencing the same issue.

It has been hard to pin down, because it only happens sometimes.  But when it does, I've found that the `svg.text` element has a viewBox of "0 0 0 0".  The value is actually there inside the `<text>` element, it just doesn't show because of the viewBox.  If I manually put a viewBox value in, it will show.

<img width="2802" height="490" alt="Image" src="https://github.com/user-attachments/assets/bb4e100b-9615-413a-b006-20cae2efb9ae" />


I see this in both Firefox and in the HA Companion app on MacOS and Android.  But again, it only happens *sometimes*.  When it happens, if I reload or "refresh" Lovelace, it works again for a while.

I also tried adding `background_update: true` to the popup cards and I have found that when I do that, this issue with the gauge cards actually happens 100% of the time.  For me, if background update is true, the gauge cards don't have text at all.  

I assume there is some kind of resize function that is supposed to run to determine the value for viewBox and it either gets stuck or doesn't run after the popup is open.

Edit - looks like it's here:
https://github.com/home-assistant/frontend/blob/a6d3041d599d02042e8857d06ec932933e1ea1dd/src/components/ha-gauge.ts#L153

Nothing fancy going on with the popup or gauge card config:

```
- type: custom:bubble-card
  card_type: pop-up
  hash: '#phone-myphone'
  entity: binary_sensor.myphone_interactive
  name: "My Phone"
  button_type: state
  show_state: false
  show_last_changed: true
```

```
- type: horizontal-stack
  cards:

    - type: gauge
      name: Battery Level
      unit: '%'
      entity: sensor.myphone_battery_level
      severity:
        red: 0
        yellow: 45
        green: 85

    - type: gauge
      name: Storage Used
      unit: '%'
      entity: sensor.myphone_internal_storage
      severity:
        green: 0
        yellow: 45
        red: 85
```

Another Edit - The more I look into this the more it looks like it's just a bug with the core card:
https://github.com/home-assistant/frontend/issues/11956

Bubble Card / Popup probably adds some layers of complexity to the issue, but it seems like this is something that needs to be handled from higher up.  I'll leave this here just in case others are going down the same rabbit-hole!

**Comment by liamstears** [comment]
> Sorry to pile on here, but I found these threads today after experiencing the same issue.
> 
> It has been hard to pin down, because it only happens sometimes. But when it does, I've found that the `svg.text` element has a viewBox of "0 0 0 0". The value is actually there inside the `<text>` element, it just doesn't show because of the viewBox. If I manually put a viewBox value in, it will show.
> 
> <img alt="Image" width="2000" height="490" src="https://private-user-images.githubusercontent.com/1100001/492051092-bb4e100b-9615-413a-b006-20cae2efb9ae.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM2OTEyNjMsIm5iZiI6MTc2MzY5MDk2MywicGF0aCI6Ii8xMTAwMDAxLzQ5MjA1MTA5Mi1iYjRlMTAwYi05NjE1LTQxM2EtYjAwNi0yMGNhZTJlZmI5YWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTExMjFUMDIwOTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2YyN2RhN2UzZTZkNTczMjc0NDVjNDVjNDY2NzIzYTMzYTA5YmNhOTgxYTc1MWIwYjJmNjA4NmIzM2E1ODEyZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.9IaAUFc7g6kuUuvoZprT3OfxcEQt7JGcs81TDJTteMk">
> I see this in both Firefox and in the HA Companion app on MacOS and Android. But again, it only happens _sometimes_. When it happens, if I reload or "refresh" Lovelace, it works again for a while.
> 
> I also tried adding `background_update: true` to the popup cards and I have found that when I do that, this issue with the gauge cards actually happens 100% of the time. For me, if background update is true, the gauge cards don't have text at all.
> 
> I assume there is some kind of resize function that is supposed to run to determine the value for viewBox and it either gets stuck or doesn't run after the popup is open.
> 
> Edit - looks like it's here: https://github.com/home-assistant/frontend/blob/a6d3041d599d02042e8857d06ec932933e1ea1dd/src/components/ha-gauge.ts#L153
> 
> Nothing fancy going on with the popup or gauge card config:
> 
> ```
> - type: custom:bubble-card
>   card_type: pop-up
>   hash: '#phone-myphone'
>   entity: binary_sensor.myphone_interactive
>   name: "My Phone"
>   button_type: state
>   show_state: false
>   show_last_changed: true
> ```
> 
> ```
> - type: horizontal-stack
>   cards:
> 
>     - type: gauge
>       name: Battery Level
>       unit: '%'
>       entity: sensor.myphone_battery_level
>       severity:
>         red: 0
>         yellow: 45
>         green: 85
> 
>     - type: gauge
>       name: Storage Used
>       unit: '%'
>       entity: sensor.myphone_internal_storage
>       severity:
>         green: 0
>         yellow: 45
>         red: 85
> ```
> 
> Another Edit - The more I look into this the more it looks like it's just a bug with the core card: [home-assistant/frontend#11956](https://github.com/home-assistant/frontend/issues/11956)
> 
> Bubble Card / Popup probably adds some layers of complexity to the issue, but it seems like this is something that needs to be handled from higher up. I'll leave this here just in case others are going down the same rabbit-hole!

Thanks for posting this

This issue has come back for me but seems to be that it's nearly all the time now that text doesn't appear

I did check and I have the same issue it is the ViewBox but how did you come to link this as a main/core issue?

I can successfully duplicate this issue without fail when using a popup card however the same gauge card works flawless when not in a popup, it's like the popup is adding some sort of processing on this which is causing this hiccup...

@Clooos I really hope you can take a look at this one again for me. To reproduce just create a new popup and add gauge card, I personally use gauge card pro and this issue is happening all the time but the gauge works flawlessly if I put it directly on the dashboard without a popup...

**Comment by HermesHonshappo** [comment]
I had this as well with the gauge card, and gauge pro card.
I am also noticing it on history-graph cards of a climate entity, and tile cards where the trend is displayed.
This is maybe similar to the bug here: https://github.com/Clooos/Bubble-Card/issues/1929
I have tested with the "Update cards in the background" toggled on in the popup setting, but there is no change.

**Comment by liamstears** [comment]
@Clooos 

I don't know what exactly changed/fixed it but updated to the latest 3.1.0 beta1 and installed bubble card tools and since restarting this issues seems to be resolved?

Not gonna argue but all gauges seem to load without issues at the moment...

**Comment by Clooos** [comment]
I forgot to mention this issue, but indeed v3.1.0 is fixing this bug! This is explained in the changelog 😄

**Comment by liamstears** [comment]
> I forgot to mention this issue, but indeed v3.1.0 is fixing this bug! This is explained in the changelog 😄

I missed that in the changelog, amazing as always @Clooos, bubble card is by far the best visual improvement ever made for home assistant and your support and progress has been outstanding, thank you!

**Comment by zoic21** [comment]
Hello,
I don't known why but this issue seem to come back : 

<img width="1206" height="2622" alt="Image" src="https://github.com/user-attachments/assets/56ccabff-5720-4a97-b2c6-c2b87a1eadd9" />

It's seem to happen only on mobile and not all the time, if I leave popup open, close app and open it again no issue.

**Comment by Clooos** [comment]
Hi! Have you updated to HA 2026.4? This issue is fixed with this version 👌

**Comment by zoic21** [comment]
> Hi! Have you updated to HA 2026.4? This issue is fixed with this version 👌

Yes I’am in 2026.4.1 and I also clear the cache (with debug menu)

**Comment by Clooos** [comment]
This doesn't looks like the new gauge card, the new one is more rounded and do works with pop-ups. Are you sure that you have the latest update? 

I just tried again to be sure and it is working on my side.

**Comment by HermesHonshappo** [comment]
I'm also in 2026.4.1, with the latest bubble card.
It was never fixed in my case. I just tested it again, and same behavior as the one I described here: https://github.com/Clooos/Bubble-Card/issues/1929#issuecomment-3567706275

**Comment by HermesHonshappo** [comment]
Just took a screenshot of a popup there:

<img width="400" alt="Image" src="https://github.com/user-attachments/assets/35f95948-c929-45bc-8ad4-13abf38fe331" />

**Comment by Clooos** [comment]
I realize I haven't updated since the HA 2026.4 beta on my test server, let me check that again.

Edit: Well ok, they've reverted that, the new one was much better 😅

Edit 2: I tried by disabling "Update cards in background" and it now works as expected on my side, do you have it enabled?

**Comment by zoic21** [comment]
Hello not for me I leave it by default at no

**Comment by Clooos** [comment]
Ok, I'm currently working on the pop-ups so I will do my best to fix that as well 👌

**Comment by Clooos** [comment]
Hi! This issue is now fixed for good on my side without "Update cards in background", I will do my best to release v3.2.0-beta tomorrow! 🍻

**Comment by zoic21** [comment]
Hello,
I just and it's perfect it's fix the issue.

Thank a lot for your work.
