### ISSUE TITLE
Background on corners of the card

### ISSUE THREAD

**Issue by tempus2016** [Clooos/Bubble-Card#4]
I am seeing some outlines on the corners of the bubble card.
<img width="513" alt="Screenshot 2023-08-28 at 21 02 54" src="https://github.com/Clooos/Bubble-Card/assets/40920327/b9ac0835-ad7f-4a1d-bf2a-eda51b2d3e60">

**Comment by Clooos** [comment]
Hi, thanks for pointing me this issue, it should be fixed now. Can you tell me if it's working?

**Comment by brpeterso** [comment]
> Hi, thanks for pointing me this issue, it should be fixed now. Can you tell me if it's working?

I have confirmed that beta 3 has removed the borders for me.
