### ISSUE TITLE
Mobile companion app: Top margin box doesn't seem to have any effect

### ISSUE THREAD

**Issue by caraar12345** [Clooos/Bubble-Card#40]
Hey, this is really awesome! 🤩 

I'm having a bit of trouble with the mobile top margin however; regardless of what I put into the box, it still hides under the header (it's acting as though it's not got any top margin at all).

However, this isn't a problem in Safari. If I open it there, it works fine. It's purely on the iOS Companion app that I'm seeing the problem which is really odd!

Any ideas?

**Comment by Clooos** [comment]
Hi and thanks! I'm also using the iOS Companion app on my iPad and I don't have this issue, can you share the code of your pop-up? But it's possible that this is related with an other issue that I'm fixing right now, the new beta is coming really soon.

**Comment by caraar12345** [comment]
New beta has sorted it 🚀

**Comment by Clooos** [comment]
Thanks! 😊 I'm glad that this is fixed now!
