### ISSUE TITLE
Blank/blurred screen shown when re-entering Home Assistant after a bubble card was open

### ISSUE THREAD

**Issue by larsfjaera** [Clooos/Bubble-Card#405]
**Describe the bug**
If I exit the Home Assistant app (also occurs on PC btw) whilst a bubble card is open and the reopen the app after a few minutes, the bubble card that was open can be seen for a small second followed by only seeing the blurred background from the bubble card. I have to tap the screen in order to be able to enter the main dashboard again. Please see the attached video.

**To Reproduce**
1. Open the Home Assistant app
2. Open a bubble card
3. Exit the app (no force closing) and do something else on the phone for a few minutes
4. Open the Home Assistant app and see the blurred background

**Expected behavior**
I would expect that the bubble card that was open would show properly - either immediately or followed by a reload. 

**Video**
https://github.com/Clooos/Bubble-Card/assets/17746989/87f5f4c4-3d66-486e-8e5f-24dd63c0a448

**Desktop (please complete the following information):**
 - OS: Mac OS Sonoma
 - Browser: FIrefox
 - Version 1.7.3

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: 17.1.1
 - Browser Home Assistant Companion App
 - Version 1.7.2

**Additional context**
I have tried changing the "Remember last page" setting on the iOS app without it making a difference. 

Thank you!

**Comment by Nazze** [comment]
HI! I am having the same issue! :-)

**Comment by rcjkierkels** [comment]
Hi. Same issue here

**Comment by elmattt** [comment]
same here ! iphone app

**Comment by Clooos** [comment]
Hi everyone, I'm back from vacation and I have also this issue on my setup. This is my priority for the next release.

**Comment by Clooos** [comment]
This issue should be fixed in the v2 beta!

Here is the link to the full changelog:
https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.1
