### ISSUE TITLE
Open pop up issue

### ISSUE THREAD

**Issue by YoranT** [Clooos/Bubble-Card#408]
I have a problem when i wanna open a pop up when i open it, it glitches and the screen is automatically refreshing and becomes black. Can somebody help me?

https://github.com/Clooos/Bubble-Card/assets/108663797/47c353e9-528a-4328-9988-85a870b95e6e

**Comment by Clooos** [comment]
Hi and thank you for your feedback, I'm aware of this issue and to temporary fix this you can reboot your iPhone, that should works flawlessly after that. 

But I'm on it, the next version should definitely fix that!

**Comment by YoranT** [comment]
Thank for the advice and great that it's getting fixed. I love the lovelace by the way! Thanks!

**Comment by Clooos** [comment]
This issue should be definitely fixed in the v2 beta! Can you confirm this?

And here is the link to the full changelog:
https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.1

**Comment by YoranT** [comment]
> This issue should be definitely fixed in the v2 beta! Can you confirm this?
> 
> 
> 
> And here is the link to the full changelog:
> 
> https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.1

I haven't noticed any of my problems before so i think its good now. Thanks! But i have discovered 2 new problems with the beta i think. 

![image](https://github.com/Clooos/Bubble-Card/assets/108663797/d52b311e-8d7c-4af9-bd45-944a7ff53fe4)

And 

https://github.com/Clooos/Bubble-Card/assets/108663797/928f55d8-b43c-4e76-9749-4376dbebb4de 

The pop ups are not in the middle anymore on safari they do but on chrome they don't

**Comment by Clooos** [comment]
Can you tell me if the last beta fix your issue?

**Comment by YoranT** [comment]
> Can you tell me if the last beta fix your issue?

Yes its fixed now, Thanks!
