### ISSUE TITLE
pop is only showing up after tap anywhere else (UI Lovelace Minimalist)

### ISSUE THREAD

**Issue by LukasHoermanns** [Clooos/Bubble-Card#41]
Hi, I am using UI Lovelace Minimalist for my main Dashboard and i would love to use your popups, but sadly the popups are only showing up after tapping anywhere on an empty spot after tapping the navigation button. Same when I directly enter the URL.
They are working perfectly fine on a Dashboard thats not from UI Lovelace Minimalist.

I hope its something that u can fix and is not up to UI Lovelace Minimalist.  :)

I am currently using the newest beta version 5.

**Comment by Clooos** [comment]
Hi and thanks for the feedback, this is a very weird issue because entering directly the URL should work in any case. Can you open an issue also in the UI Lovelace Minimalist repository?

**Comment by Clooos** [comment]
This should be fixed in the new beta :
https://github.com/Clooos/Bubble-Card/releases/tag/v0.0.1-beta.8
