### ISSUE TITLE
Not displaying values until the value of the sensor updates

### ISSUE THREAD

**Issue by guanaco0403** [Clooos/Bubble-Card#411]
**Describe the bug**
When I open a popup, the value of my gauges for example just doesn't display until th sensor updates the value, its kinda problematic

**To Reproduce**
1. Create a popup
2. add a gauge on an entity
3. save
4. restart the app
5. open the popup

**Expected behavior**
To instantly display the correct values 

**Screenshots**
![image](https://github.com/Clooos/Bubble-Card/assets/76651037/2e8612b3-7ac1-44a9-86f8-697893c73b43)

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy s20 5g
 - OS: Android 13
 - Browser Home Assistant Companion App
 - Version 2024.1.5-full

**Comment by guanaco0403** [comment]
the funny thing is that the gauge level is correct its just the value that isnt displayed

**Comment by guanaco0403** [comment]
oh i found that if i enable "Update cards in background" it works BUT its not recomended... ?

**Comment by Clooos** [comment]
Hi, this issue was already discussed here:
https://github.com/Clooos/Bubble-Card/issues/399

And like I said on that issue, if it works for you you don't have to worry about the "Not recommended" warning.
