### ISSUE TITLE
Invisible element block tapping the 2nd row

### ISSUE THREAD

**Issue by huythach83** [Clooos/Bubble-Card#413]
**Describe the bug**
When opening the popup, there is an invisible element that blocks the tapping of buttons on the 2nd row. To tap those buttons, the user has to tap the bottom of them. Using the browser developer tool, I can see that there is an invisible element that blocks the action.

![image](https://github.com/Clooos/Bubble-Card/assets/11812299/e7c605dd-fd3b-4e56-aabe-b55e7b64726b)

As you can see from the screenshot, that bubble-card::after blocks almost all the area of the 2nd row, making tapping any buttons on it difficult.

**Comment by Clooos** [comment]
Hi and thank you for your feedback! Indeed this element is for the top gradient, I have a separator in the top of all my pop-ups so I've never had this issue, but I will fix that in the next release.

As a temporary workaround you can add this to your pop-up YAML:

```yaml
styles: |
  bubble-card::after {
    pointer-events: none;
  }

**Comment by cuttydiamond** [comment]
Thanks, I was having the same issue and this fixed it!

**Comment by Clooos** [comment]
This is fixed in the v2 beta!

Here is the link to the full changelog:
https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.1
