### ISSUE TITLE
Gradient RHS of Horizontal Buttons Stack

### ISSUE THREAD

**Issue by paulsgale** [Clooos/Bubble-Card#416]
Maybe not a bug as such but more a minor issue with styling:

On the horizontal buttons stack at the right hand side there is a gradient. If the buttons fit within the horizontal space available and there is no scroll available, the gradient shouldn’t be shown as it messes up the look of the last button (see screen shots) and makes it look like there are other buttons to swipe to. Alternatively, if this is difficult to fix in the code, there could be a ‘hide edge gradient’ option maybe (feature request). 

![IMG_0446](https://github.com/Clooos/Bubble-Card/assets/30231717/24a05c34-dd6a-4b20-b1ec-2f53ac8336af)
![IMG_0445](https://github.com/Clooos/Bubble-Card/assets/30231717/987f64aa-291c-4ae3-ba4e-1988d3fee131)

These shots are from one of my Lenovo ThinkSmart View devices running portrait 1280x800 in Fully Kiosk Browser. 

Thanks

**Comment by Clooos** [comment]
Hi and thank you for your feedback! I was aware of that, and this issue has already been fixed by @brunosabot in its PR. We still need to do some additional work for the next release, and then we will release it in public beta to see if everything is stable 🙂

**Comment by pgale** [comment]
Great thanks. Any rough ETA on the beta?

**Comment by Clooos** [comment]
I would say within a week or two, but hopefully sooner 🤞

**Comment by Clooos** [comment]
This is fixed in the v2 beta!

Here is the link to the full changelog:
https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.1

**Comment by paulsgale** [comment]
Hi, you say it’s fixed but I’m not sure it is unless there’s an option to remove the gradient? So on one panel, I have four buttons which take up all the horizontal space but don’t go over, so there’s no scrolling enabled. The right hand side still has a gradient applied though. I can send an image if required. Thanks.
