### ISSUE TITLE
error with Enabling "Optional - Auto order (Presence/occupancy sensors needed)"

### ISSUE THREAD

**Issue by xyeoda** [Clooos/Bubble-Card#417]
**Describe the bug**
I ensured that ive updated to the latest version of the card via HACS and HA is running latest build too.

When i enable Auto Order the horizontal stack does not display. 

<img width="581" alt="Screenshot 2024-03-21 at 10 38 54 PM" src="https://github.com/Clooos/Bubble-Card/assets/31374940/772f7276-b649-4026-af68-45f01bdc1300">

**To Reproduce**
1. Go to horizontal stack and enable auto order
2. See error

If i turn it off then the display works just fine.

Code :
type: custom:bubble-card
card_type: horizontal-buttons-stack
auto_order: true
1_link: '#attic'
1_name: Attic
1_icon: mdi:home-roof
1_entity: light.attic_downlights_group
1_pir_sensor: binary_sensor.attic_everything_presence_one_occupancy
2_name: TV Room
2_link: '#tv'
2_entity: light.tvroomshellydimmer
2_icon: mdi:television
4_link: '#livingroom'
4_name: Living Room
4_icon: mdi:sofa
5_link: '#kitchen'
5_name: Kitchen
5_icon: mdi:chef-hat
5_entity: light.kitchen_downlight_group
6_link: '#childrens'
6_name: Animals
6_icon: mdi:baby-carriage
6_entity: light.childrens_room_downlight
width_desktop: 640px
3_name: Visitor
3_icon: mdi:doorbell-video
3_link: '#frontdoorbell'
4_entity: light.dining_downlights
5_pir_sensor: binary_sensor.kitchen_everything_presense_one_occupancy
7_link: '#master'
7_name: Master
7_icon: mdi:bed-king-outline
7_entity: switch.master_bedroom_downlights
8_link: '#wardrobe'
8_name: Wardrobe
8_icon: mdi:wardrobe-outline
8_pir_sensor: binary_sensor.wardrobe_presence_sensor_occupancy
4_pir_sensor: binary_sensor.living_room_fp1_presence
6_pir_sensor: binary_sensor.yeoda_home_childrens_room_ptz_motion
9_link: '#mastertoilet'
9_name: Master Toilet
9_icon: mdi:toilet
9_entity: switch.shellyplus2pm_mastertoilet_downlights
9_pir_sensor: binary_sensor.master_toilet_presence_sensor_occupancy
10_link: '#commontoilet'
10_name: Common Toilet
10_icon: mdi:toilet
10_entity: light.common_toilet_downlights
10_pir_sensor: binary_sensor.common_toilet_presence_sensor_occupancy
11_link: '#storeroom'
11_name: Storeroom
11_icon: mdi:file-cabinet
11_entity: switch.storeroom_shelly_plus_1_pm_switch_0
11_pir_sensor: binary_sensor.storeroom_presence_sensor_occupancy
12_link: '#energy'
12_name: Energy
12_icon: mdi:home-lightning-bolt-outline
13_link: '#overwatch'
13_name: Overwatch
13_icon: mdi:cctv
14_link: '#tracker'
14_name: Tracker
14_icon: mdi:crosshairs-gps
15_link: '#homeannouncement'
15_name: Home Announcements
15_icon: mdi:bullhorn-outline
rise_animation: false
is_sidebar_hidden: false
highlight_current_view: false
hide_gradient: false
2_pir_sensor: binary_sensor.tv_room_fp1_presence
3_pir_sensor: binary_sensor.front_door_visitor
7_pir_sensor: binary_sensor.master_everything_presence_one_occupancy

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser Chrome

Thank you! 🍻

**Comment by Clooos** [comment]
This issue should be fixed in the v2 beta!

Here is the link to the full changelog:
https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.1
