### ISSUE TITLE
Slider button triggers multiple haptic feedback in companion app

### ISSUE THREAD

**Issue by regystro** [Clooos/Bubble-Card#421]
**Describe the bug**
Sliding your finger right or left in a button slider (light entity), triggers multiple haptic feedback (vibration) in HA companion app (Android)

**Expected behavior**
No haptic feedback at all. Like when you click in the middle of the bar, instead of slide, to choose the brightness.

**Smartphone (please complete the following information):**
 - Device: Pixel 6a
 - OS: Android 14
 - Browser: Home Assistant Companion App
 - Version: 2024.1.5-full

**Additional context**
Just to rule out Companion App fault, I also tested with another slider (mushroom) and that does not happen.

**Comment by Clooos** [comment]
I tought it was cool, but I guess that that feedback can be different on other smartphones. I will change that.

**Comment by regystro** [comment]
I considered asking if it was done on purpose 🤣. I think it might be cool in some smartphones. Personally is a bit annoying in mine, but IMHO I'd let the user choose by making it optional.

BTW: thank you for Bubble Card. It's really great!!

**Comment by Clooos** [comment]
This is fixed in the v2 beta!

Here is the link to the full changelog:
https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.1

**Comment by Clooos** [comment]
Your issue is different of that one, but I'm planning to change the sliders behavior, what I have in mind will make them so more convenient to use.
