### ISSUE TITLE
Uncaught TypeError: t.popUp is null

### ISSUE THREAD

**Issue by danielholm** [Clooos/Bubble-Card#426]
Hi,

I very much like this card, however it seem to be freezing up my lovelave dashboard. My dashboard has been freezing on both desktop (firefox) and smart phones (iphone and android) for some time. Just after a few minutes, I have to restart the app, or close and reopen the web tab. Tried emptying cache.

I've been trying to debug this for a while and it seems like it is due to the Bubble card. Added the optimized js file without change. 

When loading the dashboard, having Firefox Inspector on, I get more than 99 issues regarding "Uncaught TypeError: t.popUp is null"

When removing Bubble card using HACS, the errors goes away, as well as the dashboard being a bit smother.

The full error is the following:
```
Uncaught TypeError: t.popUp is null
    r bubble-card.js:520
    setTimeout handler*updateBubbleCard/< bubble-card.js:520
    updateBubbleCard bubble-card.js:520
    set hass bubble-card.js:520
    value hui-stack-card.ts:106
    value hui-stack-card.ts:124
    value hui-stack-card.ts:113
    r fire_event.ts:76
    h create-element-base.ts:136
    promise callback*73765/h/< create-element-base.ts:134
    h create-element-base.ts:222
    c create-element-base.ts:179
    g create-card-element.ts:105
    value hui-stack-card.ts:105
    _cards hui-stack-card.ts:48
    value hui-stack-card.ts:47
    h create-element-base.ts:156
    promise callback*73765/h/< create-element-base.ts:152
    h create-element-base.ts:245
    c create-element-base.ts:179
    g create-card-element.ts:105
    value hui-view.ts:82
    _cards hui-view.ts:346
    value hui-view.ts:345
    value hui-view.ts:269
    value hui-view.ts:169
    performUpdate reactive-element.ts:1327
    scheduleUpdate reactive-element.ts:1261
    _$Ej reactive-element.ts:1233
    requestUpdate reactive-element.ts:1208
    _$Eu reactive-element.ts:946
    _ reactive-element.ts:931
    i hui-view.ts:59
    E scoped-custom-element-registry.js:385
    t scoped-custom-element-registry.js:236
    value hui-root.ts:862
bubble-card.js:520:1619
```

In the case that I am missing something, please excuse my ignorance and point me in the right path.

**Comment by Clooos** [comment]
Hi, the next release should definitely fix all performance issues 🤞

**Comment by danielholm** [comment]
Sounds amazing. Looking forward to it. And thank you!

Den lör 30 mars 2024 06:44Cloos ***@***.***> skrev:

**Comment by Clooos** [comment]
This issue should be fixed in the v2 beta!

Here is the link to the full changelog:
https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.1
