### ISSUE TITLE
bg background can't be a variable of a theme.

### ISSUE THREAD

**Issue by fablav76** [Clooos/Bubble-Card#428]
So bg_color: var(--contrast2) has no effect on background.
It's work only with rgb or hex colours.
Frustrating on light and dark themes.
I would like to have the same colour of my primary background colour.

**Comment by Clooos** [comment]
This is indeed an issue, I will fix that in the next release.

**Comment by Clooos** [comment]
I've released a new beta that fix that issue, here is the changelog:

https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.2
