### ISSUE TITLE
Bubble popup not compatible which custom:power-flow-card-plus

### ISSUE THREAD

**Issue by Bsector** [Clooos/Bubble-Card#429]
I use the custom:power-flow-card-plus card (https://github.com/flixlix/power-flow-card-plus) in a main grid on the dashboard.
When the bubble popup card is displayed, part of the custom:power-flow-card-plus card continues to be displayed.

![image](https://github.com/Clooos/Bubble-Card/assets/53239310/0fb6ceaf-3268-4619-ac47-e00c26f7e7ee)

Popup is view:

![image](https://github.com/Clooos/Bubble-Card/assets/53239310/3072152d-f97b-4d01-ab73-3bb8c1ea2b08)

 - OS: Windows 11
 - Browser chrome
 - Version 123

 - Device: Poco F3
 - OS: Android 13
 - Browser Home Assistant Companion App
 - Version 2024.1.5

Thank you!

**Comment by Clooos** [comment]
Hi, this issue is from that specific card, but the next beta release should fix that!

**Comment by Clooos** [comment]
This is fixed in the v2 beta!

Here is the link to the full changelog:
https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.1
