### ISSUE TITLE
UI-Lovelace-Minimalist Chips not blurred

### ISSUE THREAD

**Issue by idominiki** [Clooos/Bubble-Card#432]
Hi together!

I use UI-Lovelace-Minimalist integration / theme and have configured a top swipe-card with chips inside. 

When I open a popup, those chips aren't blurred. 
![image](https://github.com/Clooos/Bubble-Card/assets/62521486/af463975-ad20-4f6e-937a-fd2eb00ebaa1)
It looks a bit ugly. Can we improve this behavior?

Thanks!
Dominik

**Comment by Clooos** [comment]
Hi! This issue should be fixed in the release 🙂

**Comment by idominiki** [comment]
Thank @Clooos for the great work!
