### ISSUE TITLE
The main page does not go up to the end

### ISSUE THREAD

**Issue by abeksis** [Clooos/Bubble-Card#44]
Hey,
Thanks for the wonderful job you do.
There’s some bug - it’s not clear to me why it doesn’t work - or I do something wrong.

In the attached image (even from the cellphone it is the same), you can see the bottom I can’t go to what I built.

https://community-assets.home-assistant.io/original/4X/d/f/0/df0ffb47930331c4fc0b21673c0ef78c4af21753.jpeg

**Comment by Clooos** [comment]
Hi and thanks! So your issue is that you can't scroll at all? And can you tell me on what browser you are?

**Comment by Clooos** [comment]
Can you tell me if this is helping you?

https://github.com/Clooos/Bubble-Card/issues/32#issuecomment-1706397871

**Comment by abeksis** [comment]
yes ites ok new.

**Comment by aredon** [comment]
> Can you tell me if this is helping you?
> 
> https://github.com/Clooos/Bubble-Card/issues/32#issuecomment-1706397871

This solution works for mobile but I'll confirm on desktop that if your dashboard is long enough the bottom will be covered by the bubble cards.

**Comment by Clooos** [comment]
This is fixed in the v2 beta!

Here is the link to the full changelog:
https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.1
