### ISSUE TITLE
Button - light level incorrect intermediate level animation with HA grouped lights

### ISSUE THREAD

**Issue by pgale** [Clooos/Bubble-Card#442]
**Describe the bug**
I'm pretty sure this has been logged before but was hoping it had been fixed in v2 beta but still there.
With some lights that are grouped in a **group helper** in HA (Lights are Philips Hue via the official integration), when I set a light brightness level, the slider 'bounces' around and animates to an intermediate level before then animating to the final level. I expect this is the code reading the level mid-operation and animating to that level and then to the final level. Maybe this is due to the delay in Hue reporting back to HA mid-dim operation? It only happens once in between the start and end levels.

**To Reproduce**
Happens all the time and consistently when using HA grouped lights. It does not happen if the group is set on the Hue platform. That can be the solution in **some** cases but would be good to have grouped lights working if possible.

**Expected behavior**
The intermediate state should not be shown.

**Screenshots**
This screen recording shows the issue:
https://github.com/Clooos/Bubble-Card/assets/513044/78ff15d0-c636-4523-ae65-d43e9cff2254

**Desktop (please complete the following information):**
All devices - desktop and android devices show this behaviour.

Thanks for the work on this card and the v2 updates :)

**Comment by Clooos** [comment]
The cards you are showing in this video are not Bubble Cards, and indeed this issue is related to Hue, I have these too and this issue is already in Bubble Card. There is probably nothing that I can do.

**Comment by pgale** [comment]
Doh! My mistake, they're mushroom cards I think! I'm really stupid! lol
