### ISSUE TITLE
v2 Beta - duplicate cards shown in preview while editing

### ISSUE THREAD

**Issue by pgale** [Clooos/Bubble-Card#443]
Similar to v1 issue - a duplicate card shown in the preview when editing. In this case, it's a sonos card.

2.0.0 beta

<img width="518" alt="Screenshot 2024-04-14 093357" src="https://github.com/Clooos/Bubble-Card/assets/513044/0e929ee2-054d-451d-b1b8-e76cd3017dad">

**Comment by Clooos** [comment]
I really thought this was fixed! I will take a closer look at that!

**Comment by pgale** [comment]
Thanks - I've only seen it once so far when adding the Sonos card. Sonos card is a tricky one as it often cancels the popup when pressing some of its buttons. I guess it mush be doing something that interferes with your code.

**Comment by pgale** [comment]
You were right about the cache/reload. After a restart of HA, I added another vertical stack and added a sonos card - showed correctly this time.

Hopefully that has cheered you up as I know you said you'd put a lot of time into fixing that!

I'll report back if I see anything else weird.

Good job!

**Comment by Clooos** [comment]
Yeah! I was a bit disappointed when I saw your issue 😂

**Comment by pgale** [comment]
Sorry - I know that sinking feeling!
All good though :)
