### ISSUE TITLE
Incorrect version shown

### ISSUE THREAD

**Issue by pgale** [Clooos/Bubble-Card#444]
For v2.0.0 beta - the version info should show the correct version at the bottom of bubble cards in edit view. Currently shows v1.7.x

Not sure if you already have this on your list to fix?

Thanks.

**Comment by Clooos** [comment]
This explained your other issues, you are not in v2.0.0 😅 Apparently you need to clear your cache, did you updated with HACS?

**Comment by pgale** [comment]
Yes you are right. I cleared cache on the local browser but a restart got the correct version showing.
