### ISSUE TITLE
v2.0.0 beta 1 - vertical stack popup content not showing in editor

### ISSUE THREAD

**Issue by pgale** [Clooos/Bubble-Card#446]
I noticed that in the v2.0.0 beta 1 update that the content in popup vertical stacks isn't showing.

I did a restart just to be sure.

The popups actually seem to work OK but I guess there's some setting in the old bubble card configs that maybe the new version doesn't like?

I see this with existing vertical stacks and adding a new vertical stack with a single bubble card button within it. No preview of the contents either way.

https://github.com/Clooos/Bubble-Card/assets/513044/63cfc41a-9c9d-4203-b49a-6947f5bdc3a7

**Comment by Clooos** [comment]
Hi! This is not an issue but a new feature to declutter the editor for users with a lot of pop-ups, but indeed for pop-ups without a header it's more difficult to distinguish them. Do you have a suggestion to improve that?

**Comment by pgale** [comment]
Ah ok!

Well as you see, I don't use headers so it makes it difficult to see which block is which. 

Could there be a name entry for the block which is used instead of the header when one isn't used?

I think it's pretty important to have something there :)

**Comment by Clooos** [comment]
I think that this the best solution indeed. I will add that in the next beta.

**Comment by pgale** [comment]
Thanks - that would work.

On a related note, I did try just setting the header type to text but it still renders as a clickable button with click animation even though it's only text and there's nothing to actually do. Is that correct? I would probably expect it to not show the icon circle and not respond to clicks/taps. Unless there's some other reason for doing that?

**Comment by Clooos** [comment]
I've forgot to change that, thank you again for the feedback!

**Comment by pgale** [comment]
well as least ONE of my issues isn't related to me being an idiot! ;)

**Comment by Clooos** [comment]
I've a better idea to not add something in the editor that some users could not understand, if a pop-up has no header I will render it fully, or partially, I have to test what looks better.

**Comment by Clooos** [comment]
Yup I see what you mean, I will work on that, I really want to declutter that editor.

**Comment by pgale** [comment]
yeah - the work you've done to categorise the options is really nice - much cleaner :)

**Comment by Clooos** [comment]
I've released a new beta that changes that, here is the changelog:

https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.2

**Comment by pgale** [comment]
Thanks will take a look

**Comment by pgale** [comment]
I've had a look and there's no change to recognising vertical stacks - what am I missing?

**Comment by pgale** [comment]
Scrub that - a complete browser cache delete rather than a reload fixed - I see what you mean now - seems to work ok :)
