### ISSUE TITLE
Version 2.0.0 beta 1 - Back Button not working, Popups not closing

### ISSUE THREAD

**Issue by shpongledsummer** [Clooos/Bubble-Card#448]
First of all, thanks for this great card and especially all the new features!

I upgraded to the V2 beta 1 version today and noticed closing the popup by navigating back with the 'back button' is not working properly anymore. 

The popup itself closes after a short delay, but the background overlay remains visible. I tried deactivating the background overlay, which didn't help. I'm using the android companion app, but this also happens if I open HA in chrome.

**Comment by mfabiani53** [comment]
Same here, same issue..

**Comment by Clooos** [comment]
I will take a look at this, thank you for the feedback!
