### ISSUE TITLE
Black background on slider button and inability to add style 

### ISSUE THREAD

**Issue by c625v12** [Clooos/Bubble-Card#449]
**Describe the bug**
I have added a few slider buttons for some lights and the background of these sliders are black with 100% opacity. I have tried to add styles and change the opacity but every time I add any style to either the UI options or the yaml, it seems to break. 

It doesn't matter what I put into the style option, it will always make everything disappear and have no affect on anything else. 

Add a horizontal stack
Add a vertical stack in the horizontal stack
Add a bubble button or switch
Try to change the opacity style

**Expected behavior**
I expect to be able to change the opacity of the button

**Screenshots**
<img width="438" alt="Screenshot 2024-04-14 at 10 22 06 AM" src="https://github.com/Clooos/Bubble-Card/assets/36675818/e2912515-94c4-461a-a78b-0c9015e0d585">

**To Reproduce**
<img width="978" alt="Screenshot 2024-04-14 at 10 22 38 AM" src="https://github.com/Clooos/Bubble-Card/assets/36675818/751c2bff-09f0-4f33-ad2a-dc6828537271">

**Desktop (please complete the following information):**
 - OS: ios
 - Browser : firefox

**Additional context**
I have tried versions 1.7 to the 2.0 beta. All have the same behavior.

Thank you! 🍻

**Comment by Clooos** [comment]
Hi, to use the custom styles you need to target the elements you wants to change, here is for example how you can change the color of the background:

```yaml
.bubble-button-card-container {
  background-color: rgba(92, 83, 103, .5);
}
```

**Comment by c625v12** [comment]
Looks like it is actually related to my CSP on my reverse proxy. For some reason, when I try to change the style, it triggers a CSP violation. Not exactly sure why but wanted to let you know incase someone else comes across this issue.
