### ISSUE TITLE
Horizontal buttons stack hard reload issue

### ISSUE THREAD

**Issue by HenryKleinschmidt** [Clooos/Bubble-Card#45]
I setup the horizontal button stack today and when I navigate using it, it always hard reloads to the destination page. 
My own navigation buttons don't do that. I've attached a screen recording to visualize my issue. 

Does anybody else have this issue?

(It's kind of hard to see which buttons I pressed in the video but I always pressed the horizontal-button stack first and then my own colored buttons, hope that helps)

https://github.com/Clooos/Bubble-Card/assets/53699624/ea75d242-4ee1-4ed7-a89f-f370789eeeb8

**Comment by Clooos** [comment]
Hi, have you put your hash between ' ' like '#kitchen'? This should be the issue here.

**Comment by HenryKleinschmidt** [comment]
I think I'm abusing the horizontal stack then because I don't use the popup. I navigate to a dedicated view.

**Comment by Clooos** [comment]
Then it should work by adding your view like this: 'lovelace/your_view'. Tell me if it's working.

**Comment by HenryKleinschmidt** [comment]
Sadly that doesn't work. After clicking save it also removes the quotes. 
I attached another example video. Both buttons point to the same path. 

https://github.com/Clooos/Bubble-Card/assets/53699624/84e5eb4f-1cc3-4be5-8175-3b92e1dfacb8

**Comment by Clooos** [comment]
This is now fixed in the new beta :
https://github.com/Clooos/Bubble-Card/releases/tag/v0.0.1-beta.8
