### ISSUE TITLE
Errors again...

### ISSUE THREAD

**Issue by mfabiani53** [Clooos/Bubble-Card#450]
Registratore: frontend.js.latest.202404042
Fonte: components/system_log/__init__.py:320
Prima occorrenza: 13 aprile 2024 alle ore 13:13:41 (15 occorrenze)
Ultima registrazione: 17:08:02

Uncaught error from Chrome 123.0.0.0 on Windows 10 TypeError: Cannot read properties of undefined (reading 'state') /local/bubble-card.js:1042:14975 /local/bubble-card.js:1042:14780 /local/bubble-card.js:1042:15081 K.updateBubbleCard (/local/bubble-card.js:1042:17444) K.connectedCallback (/local/bubble-card.js:1042:124) apply (src/scoped-custom-element-registry.js:248:41) _addCardToColumn (src/panels/lovelace/views/hui-masonry-view.ts:257:15) Promise.all (src/panels/lovelace/views/hui-masonry-view.ts:238:11)
Uncaught error from Chrome 123.0.0.0 on Windows 10 TypeError: Cannot read properties of undefined (reading 'state') /local/bubble-card.js:1042:14975 /local/bubble-card.js:1042:14780 /local/bubble-card.js:1042:15081 K.updateBubbleCard (/local/bubble-card.js:1042:17444) K.connectedCallback (/local/bubble-card.js:1042:124) apply (src/scoped-custom-element-registry.js:248:41) createCardElement (src/panels/lovelace/editor/card-editor/hui-card-preview.ts:88:9) createErrorCardConfig (src/panels/lovelace/editor/card-editor/hui-card-preview.ts:55:13) update (src/reactive-element.ts:1329:13)
Uncaught error from Chrome 123.0.0.0 on Android 10 TypeError: Cannot read properties of undefined (reading 'state') /local/bubble-card.js:1042:14975 /local/bubble-card.js:1042:14780 /local/bubble-card.js:1042:15081 K.updateBubbleCard (/local/bubble-card.js:1042:17444) K.connectedCallback (/local/bubble-card.js:1042:124) apply (src/scoped-custom-element-registry.js:248:41) _addCardToColumn (src/panels/lovelace/views/hui-masonry-view.ts:257:15) Promise.all (src/panels/lovelace/views/hui-masonry-view.ts:238:11)
Uncaught error from Chrome 123.0.0.0 on Windows 10 TypeError: Cannot read properties of undefined (reading 'state') /hacsfiles/Bubble-Card/bubble-card.js:1042:14975 /hacsfiles/Bubble-Card/bubble-card.js:1042:14780 /hacsfiles/Bubble-Card/bubble-card.js:1042:15081 K.updateBubbleCard (/hacsfiles/Bubble-Card/bubble-card.js:1042:17444) K.connectedCallback (/hacsfiles/Bubble-Card/bubble-card.js:1042:124) apply (src/scoped-custom-element-registry.js:248:41) _addCardToColumn (src/panels/lovelace/views/hui-masonry-view.ts:257:15) Promise.all (src/panels/lovelace/views/hui-masonry-view.ts:238:11)

**Comment by Clooos** [comment]
Next time please reopen an issue instead of creating a new duplicate one. I've reopened your other issue.
