### ISSUE TITLE
No Sidebar - Broken Alignment on latest V2 update

### ISSUE THREAD

**Issue by prestonsmartuk** [Clooos/Bubble-Card#453]
On latest version of V2, with or without the following toggled "_**Optional - Fix when the sidebar is hidden on desktop (turn this to false if your sidebar is unmodified)**_" it has now become broken and pops are unaligned (i.e. not popping up from centre). Most of my pops are now appearing off the screen when viewing on my wall android tablet. The viewtype is Horizontal Layout and my popups are in a vertical stack. 

On the previous version, I had the sidebar toggled on as running this dashboard through Fullykiosk. Popups were aligned. 
Now with V2 they aren't aligned. I tried the Home Assistant app with a side bar, and they become aligned. But if I use the Home Assistant app and disable the side bar, they become unaligned.

**Comment by Clooos** [comment]
I will fix that, thank you for the feedback!

**Comment by Clooos** [comment]
This is fixed in second beta!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.2
