### ISSUE TITLE
Performance improvement: add transition-delay to backdrop

### ISSUE THREAD

**Issue by hellomarb** [Clooos/Bubble-Card#456]
I experienced some browser rendering hiccups with the current backdrop transition which is a combination out of a transformed popup and the backdrop and opacity transition in the background.

An improvement would be adding a `transition-delay` to `.bubble-backdrop` in the popup/styles.ts:

`transition-delay: 0.1s;`

So the browser don't have to blur the whole viewport and animate the transition, the animations are run much smoother on my iPhone to M1 and M2 Pro Macs in latest Chrome engines.

**Comment by Clooos** [comment]
I've released a new beta with your fix! Thanks again!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.2
