### ISSUE TITLE
Hopeful Improvement - Media Player Bubble Card

### ISSUE THREAD

**Issue by robotsmarthomes** [Clooos/Bubble-Card#457]
Hello,

Love the updates - working alot better - especially in the edit mode on HA. 

We haev just tried using the Media Player card. Functionality is good, but we find that the icons for the "next-previous-volume etc" are a bit small. 

It would be good if the Media Player card was almost double the height and the song information could be above and the buttons below it, and a bit larger

Thanks again

**Comment by Clooos** [comment]
Hi, I'm planning to add the possibility to choose for a larger layout for most of the cards, in the meantime what you want is doable with the custom styles.

**Comment by Clooos** [comment]
This is now possible in the latest betas with the new layouts!
