### ISSUE TITLE
Bubble card not showing up???

### ISSUE THREAD

**Issue by geidorei** [Clooos/Bubble-Card#459]
Installed via HACS, cache cleared, rebooted etc, but bubble card not showing?

Any ideas?

**Comment by chintito4ever** [comment]
Not OP but I am having similar issue, installed version 2.0.0beta2

![image](https://github.com/Clooos/Bubble-Card/assets/41648578/ead65582-9b51-4350-afd3-6577130a65a1)

**Comment by Clooos** [comment]
Bubble pop up was removed a few version before this one to improve the stability and to makes updates easier, you now have to replace this in all your pop-ups:
```yaml
- type: custom:bubble-pop-up
```
By this:
```yaml
- type: custom:bubble-card
   card_type: pop-up
```

**Comment by chintito4ever** [comment]
Thanks! that's fixed it.

**Comment by geidorei** [comment]
Hi folks - No errors, but will do some digging.... Thanks for the replies.

**Comment by Clooos** [comment]
Hi, any news about that issue? Can I close this?

**Comment by juliuswms** [comment]
Hello Guys, I seem to have the same problem. I installed bubble card today. Restarted HA, reinstalled bubble Card, tried different browsers but no luck... It doesn't show up in the search bar of the "Add Card" button. If i try adding the card manually:
```
- type: custom:bubble-card
  card_type: pop-up
```
I get this error:
`No card type configured`

**Comment by screem20056** [comment]
Im not sure if it is related but in my case the blur work but then the card is not showing up 
When i go to the edit mode i notice difference in those card that not show up it has a little x as shown in the screen shot it is like the card did not load up nicely ![SmartSelect_20240909_133551_Home Assistant.jpg](https://github.com/user-attachments/assets/a0adef3f-3396-4e4b-a2ae-359c9b1e57a5)

![Screenshot_20240909_133527_Home Assistant.jpg](https://github.com/user-attachments/assets/2edf7b08-c3b8-4dae-b219-47ab552e70e7)
