### ISSUE TITLE
2.0.0-beta: bubble-pop-up-container display:grid causing problems

### ISSUE THREAD

**Issue by hellomarb** [Clooos/Bubble-Card#460]
The change to `display:grid` for `.bubble-pop-up-container` breaks some custom cards like tabbed-card and they are rendering wider than their parent popup. Changing that back to `display:flex` fixes that.

Is there an obvious reason for `display:grid`?

**Comment by Clooos** [comment]
I will take a look at this, I don't remember why I've changed that.
