### ISSUE TITLE
v2.0.0 beta 2 horizontal stack button render issue

### ISSUE THREAD

**Issue by pgale** [Clooos/Bubble-Card#461]
v2.0.0 beta 2
Weird issue with the horizontal stack buttons dancing around. Cool effect ;) Makes it kind of hard to chase the button though!

Auto order is DISABLED. This happens in the editor and on the live dashboard in Firefox.

Android seems OK, MS Edge doesn't display the buttons AT ALL when the browser is resized wide.

Maybe something to do with CSS animation support between browsers?

https://github.com/Clooos/Bubble-Card/assets/513044/ffda5ae7-7075-44f8-8702-04b1766d4f04

In Edge:

![Screenshot 2024-04-16 172213](https://github.com/Clooos/Bubble-Card/assets/513044/414c23fa-dff2-4b4c-a762-369cac451826)

**Comment by Clooos** [comment]
And this issue was not here in the first beta?

**Comment by pgale** [comment]
I don't think so. Can't remember if I edited on my iPad which is fine or desktop though.

**Comment by paulsgale** [comment]
Have you seen the issue? Anything else you need?

**Comment by Clooos** [comment]
It's been 2 days that I'm stuck on an other issue, I still haven't had time to take a look at this one.

**Comment by paulsgale** [comment]
Ok no problem. Hope you get somewhere on the other issue!

**Comment by Clooos** [comment]
This issue is now fixed in the new beta!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.3

**Comment by pgale** [comment]
Tested and confirmed fixed for me :)

**Comment by Clooos** [comment]
🍻
