### ISSUE TITLE
Horizontal buttons stack Pop Up Buttons "render Problem"

### ISSUE THREAD

**Issue by peterthepeter** [Clooos/Bubble-Card#462]
I have a problem with the horizontal buttons stack in the beta (no matter if version 1 or 2).

When I press a button there and the pop-up opens, the content is empty and shifted. The whole app crashes on my iPhone and Ipad.
This happend with all pop Ups from the horizontal button stack.

I am attaching a picture of the current version 1.7.3 and the current beta.

![1_7_3](https://github.com/Clooos/Bubble-Card/assets/74273835/9b246bfe-a07e-4f7e-b4a7-d3eec2883b05)
![beta](https://github.com/Clooos/Bubble-Card/assets/74273835/cefafa16-5fbd-428b-9ca2-776324060a3c)

Code from horizontal buttons stack
```type: custom:bubble-card
card_type: horizontal-buttons-stack
2_link: '#vacuum'
2_icon: mdi:robot-vacuum
1_icon: mdi:movie
1_link: '#media_living_room'
margin: 13px
3_link: '#geschirrspueler'
3_icon: mdi:dishwasher
3_entity: switch.403060519689023725_bsh_common_setting_powerstate
2_entity: input_boolean.helfer_s50_cleaning
1_entity: media_player.lg_webos_tv_oled65b29la
rise_animation: true
4_link: '#bambu'
4_icon: mdi:printer-3d
is_sidebar_hidden: true
hide_gradient: true
auto_order: false`

**Comment by Clooos** [comment]
These issues should be fixed in the next beta, thank you for your feedback.

**Comment by Clooos** [comment]
This issue is now fixed in the new beta!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.3
