### ISSUE TITLE
Swipe to close card doesn't work any more?

### ISSUE THREAD

**Issue by jockebq** [Clooos/Bubble-Card#463]
On 1.7.3 all I have to do on iOS is swipe down to close the card. In 2.0 Beta 2 it doesn't work.
Has this feature been removed?

**Comment by Clooos** [comment]
Try to swipe down from the header, this is a bit different than before.

**Comment by jockebq** [comment]
> Try to swipe down from the header, this is a bit different than before.

Is it possible to have an option for the previous behavior? I really liked to be able to swipe anywhere!

**Comment by Clooos** [comment]
Well, I guess I will then 👌

**Comment by Clooos** [comment]
I've re-added this feature in the new beta! Here is the full changelog:

https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.3

**Comment by jockebq** [comment]
Works great, except it is not possible to swipe on some items (like the Vaccum Card map, even if it is locked).

**Comment by Clooos** [comment]
I'm not sure that something can be done for that, I guess that this issue was here on 1.7.3 as well?
