### ISSUE TITLE
Sub button does not show entity icon

### ISSUE THREAD

**Issue by marcokreeft87** [Clooos/Bubble-Card#465]
Sub button does not show entity icon.
The entity in question is of class motion so should show a motion icon

**Expected behavior**
Show the icon of the entity

**Screenshots**
![image](https://github.com/Clooos/Bubble-Card/assets/10223677/ecad48a9-d8c5-49b2-8225-1623c737f002)

**Informations (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Bubble Card version: /v2.0.0-beta.2
 - Home Assistant version [e.g. 2024.4.3]

**Comment by Clooos** [comment]
Thank you for the feedback, indeed I need to do some more work on the icons, this is already in my to-do list.

**Comment by marcokreeft87** [comment]
Love the feature tho. I created the exact same thing with a button type and mushroom Template in a stack in card haha

**Comment by marcokreeft87** [comment]
@Clooos I was looking through your code and the only difference I see in getting the icon is that you use 
```
_hass.states[entity]?.attributes[attribute]
```
and I use
```
stateObj.attributes.icon
```
But that should both work..

https://github.com/marcokreeft87/room-card/blob/master/src/entity.ts

**Comment by Clooos** [comment]
This issue is now fixed in the new beta!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.3
