### ISSUE TITLE
[BETA] - Sub-Button will be updated multiple times per second

### ISSUE THREAD

**Issue by svb91** [Clooos/Bubble-Card#473]
I see in my dev-tools that the div with the content of a sub_button will be updated multiple times per second.
The sub_button is inside a pop-up card - causing the performance to drop significantly.

A second bug is, that if the presence icon is "off" only a white circle is visible without any icon. If the presence sensor is "on" the circle is orange with the desired icon visible.

sub_button:
          - icon: mdi:bus
            entity: binary_sensor.og_aa_i_praesenz_presence
            show_icon: true
            force_icon: true
          - entity: sensor.og_as_h_heizung_temperature
            show_state: true
            show_icon: false

**Comment by Clooos** [comment]
Thank you for the feedback, I will work on that for the next beta!

**Comment by Clooos** [comment]
This is now fixed in the new beta!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.3
