### ISSUE TITLE
pop-up size 

### ISSUE THREAD

**Issue by cromelex** [Clooos/Bubble-Card#477]
I am having an issue with the pop-up since updating to v2.0.0 beta
This seems to happen only with my Fire10 Tablet running Fully Kiosk. In my browser it isn't an issue. I think the issue is with the **width_desktop** logic not being applied on a tablet?

`
type: custom:bubble-card
card_type: pop-up
hash: '#living-room-blinds'
name: Living Room Blinds
icon: mdi:blinds
close_on_click: false
auto_close: 20000
is_sidebar_hidden: true
width_desktop: 50%
margin: 0px

`

**Screenshots**
![PXL_20240420_174848770](https://github.com/Clooos/Bubble-Card/assets/96779452/23bcac10-cee7-4a18-85f3-3a98766d65df)

**Informations (please complete the following information):**
  - Browser Fully Kiosk on Fire10HD tablet
 - Bubble Card version v2.0.0-beta.2
 - Home Assistant version 2024.4.3

**Additional context**
I suppose the **width_desktop**  isn't being applied as the device is a tablet. I'd like to be able to apply it regardless so as to make it decently sized.
This wasn't an issue on the previous non-beta release.

Thanks!

**Comment by Clooos** [comment]
This issue should be fixed in the next beta release, there was indeed some issues with the pop-ups positioning that I've fixed.

**Comment by Clooos** [comment]
I'm not sure but I really hope that this is issue is now fixed!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.3

**Comment by cromelex** [comment]
This is now fixed with beta5

**Comment by Clooos** [comment]
Yeah!
