### ISSUE TITLE
Auto-Scrolling

### ISSUE THREAD

**Issue by JoshuaSeidel** [Clooos/Bubble-Card#479]
How do you turn it off?

**Comment by Clooos** [comment]
I will add this possibility really soon.

**Comment by JoshuaSeidel** [comment]
> This is now possible in the new beta!
> 
> https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.3

@Clooos i dont see any instruction on what to put to disable the auto scrolling of text?

**Comment by Clooos** [comment]
In the editor just go in the first section, here is for the button for example.

![image](https://github.com/Clooos/Bubble-Card/assets/36499953/aa447ba8-ebfe-4382-b872-338e851a4e82)

**Comment by JoshuaSeidel** [comment]
@Clooos what about straight in code? the editor doesnt work for my setup

**Comment by Clooos** [comment]
You can add this in YAML:

```yaml
scrolling_effect: false
```
