### ISSUE TITLE
Use bubble-card pop up as entity more-info

### ISSUE THREAD

**Issue by denisjankovic** [Clooos/Bubble-Card#481]
First of all, many thanks for this great work and excellent Home Assistant card.

I have a question: I'm not sure if it's possible, but I was wondering if in the future updates, you could consider adding the ability to use bubble-card pop-up as the entity more-info. I absolutely love the design of the bubble card pop-up and would like to replace the default Home Assistant one with it for more information.

The idea I had is to pass the entity as a parameter/variable to the popup. This way, we can dynamically create a customizable more-info popup, instead of creating one popup per entity in the view.

**Comment by Clooos** [comment]
Hi, you can do that if you use the Bubble Card buttons, just change the tap action on the icon to navigate to open a pop-up. 

But I'm not planning to do that the way you want it, I hope you will find my answer helpful anyway :)
