### ISSUE TITLE
local icon png not showing with new update

### ISSUE THREAD

**Issue by eric1090** [Clooos/Bubble-Card#482]
**Describe the bug**  
With the new update, all my local icon .png disapear , they are setup like this :  /local/photo/bulb-small.png

**Comment by eric1090** [comment]
here is a screenshot from my ipad :
![screenshot](https://github.com/Clooos/Bubble-Card/assets/126729085/1725f124-ebe4-4eeb-9acf-be3a5c5fdf71)

**Comment by Clooos** [comment]
Hi, I have removed this possibility because you can do that directly in Home Assistant by customizing the entity_picture, here's how:

https://www.home-assistant.io/integrations/homeassistant/#entity_picture

**Comment by Legrand5382** [comment]
Ok thank you, that’s perfect 😊

**Comment by Clooos** [comment]
You're welcome 🙂
