### ISSUE TITLE
Name of button getting cropped

### ISSUE THREAD

**Issue by eric1090** [Clooos/Bubble-Card#483]
Hi, 
With the new beta the name of all my button are getting cropped, when i use the same font size: (34px) i attached a screenshot of version 1.73 and latest beta.
also the top bar with the name of the popup  doesnt go to the top like before seem to not fill the screen, otherwise i love the beta,  its much faster and stable, thank you for your great work  and sorry my english is not very good :)
![screenshot-2](https://github.com/Clooos/Bubble-Card/assets/126729085/e524bc63-ae39-4e88-9e53-d101c484cca3)

**Comment by Clooos** [comment]
Hi! Can you tell me if you still have this issue in the latest beta?

**Comment by Legrand5382** [comment]
Hi,

i just try it and the issue is still there but I was able to fix it by having this line of code in the styling option, custom style of each button 
ha-card {font-size: 40px;}
.bubble-name-container { line-height: 24px;}

**Comment by Clooos** [comment]
Thank you for the feedback, this is probably the best to do in your case with your custom font-size 🙂
