### ISSUE TITLE
Horizontal Button Stack not working in Version 2

### ISSUE THREAD

**Issue by simensus** [Clooos/Bubble-Card#485]
hi,

since the Update to v2 the Horizontal Button Stack in one of my Dashboards is not working anymore. See the screenshot attached.
Ist been working in v 1.7.3
![IMG_1870](https://github.com/Clooos/Bubble-Card/assets/101661986/88369c12-e43e-4b24-98e3-7da6bcfe47c6)

**Comment by simensus** [comment]
On another device the error says: Cannot read properties of undefined (reading 'contains')

**Comment by Reason0209** [comment]
Exact same issue here, even in Beta5, thanks.

**Comment by Clooos** [comment]
I'm on it, I will release a new beta in a few days :)

**Comment by Clooos** [comment]
This issue should be fixed now, I'm waiting for your feedback 🤞

https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.6

**Comment by Reason0209** [comment]
First test looks positiv, great work!

**Comment by Clooos** [comment]
Finally 😃
