### ISSUE TITLE
Suggestion: Card height to default theme

### ISSUE THREAD

**Issue by zbuh** [Clooos/Bubble-Card#486]
This is a suggestion:

When mixing bubble card with Tile/Mushroom cards, we noticed the bubble card has a "hardcoded" height. For sure this can be customised in each card or on the theme.

But by default, it should use the value of the default theme, this way all the cards should look the same.

**Comment by Clooos** [comment]
Hi, Bubble Card is a condensed card collection, the point is to take the less space possible.

But I'm planning to add the possibility to change that, I just don't know when.
