### ISSUE TITLE
[bug] Cards can extend past the pop-up and get cut off

### ISSUE THREAD

**Issue by caraar12345** [Clooos/Bubble-Card#49]
Hello!

Sorry to bring another bug report -- at least it proves I'm using it in anger (and sorry I can't contribute...JS is not my friend 😂) 😄

It seems that if a card tries to extend past the viewport, it's able to. By this I mean I'm using the Mushroom media card for all media players which either truncates or marquees media titles if the card is too narrow to show the full thing. However, when the card is in the Bubble Card pop-up, it extends the canvas(?) within the pop-up to be as wide as it needs. This then means the full canvas for **all** the cards in the pop-up is also extended past the viewport. 

The screenshots below show what I mean better than I can explain it!

Let me know if there's any further info I can provide to help.

Cheers!
  
<details>
<summary>

### Pop-up card in edit mode
</summary>
<img width="515" alt="Popup card in edit mode, shows media title scrolling" src="https://github.com/Clooos/Bubble-Card/assets/6129428/0bb2ae23-9b15-4a3d-b5b9-d7edf8b3a257">
</details>

<details>
<summary>

### Pop-up card in view mode
</summary>
<img width="589" alt="Popup card in view mode, shows media title and all cards cutting off on the right hand side" src="https://github.com/Clooos/Bubble-Card/assets/6129428/ce06db32-3c8b-45c8-953d-1d80de522529">
</details>

**Comment by Clooos** [comment]
Well well well... this is new 😅 

Can you try to add this to your `card_type: pop-up` ?

styles: |
  #root.open-pop-up > * {
    max-width: 100% !important;
  }

**Comment by Clooos** [comment]
This is now fixed in the new beta :
https://github.com/Clooos/Bubble-Card/releases/tag/v0.0.1-beta.8
