### ISSUE TITLE
Bubble-Card and home-feed-card not Working

### ISSUE THREAD

**Issue by GunterAv** [Clooos/Bubble-Card#491]
Hello,

I have a [home feed card](https://github.com/gadgetchnnel/lovelace-home-feed-card) which I would like to display with a pop-up.
Everything is displayed correctly in the preview of the bubble card.
![Vorschau](https://github.com/Clooos/Bubble-Card/assets/87611027/2b892269-ee43-4b0e-8265-380a6b94a450)

However, the bubble card remains empty on the dashboard.
![Anzeige](https://github.com/Clooos/Bubble-Card/assets/87611027/9b149def-34d8-4632-836e-749f04c4979d)

My YML:
`  - type: custom:bubble-pop-up
    hash: '#Anrufliste'
    name: Anrufliste
    icon: mdi:phone-log
    is_sidebar_hidden: true
    bg_color: '#D8E9D7'
    margin: 0px
    bg_opacity: '50'
    bg_blur: 0
    shadow_opacity: '0'
    back_open: false
    width_desktop: 540px
  - type: custom:vertical-stack-in-card
    cards:
      - type: markdown
        content: Demo
      - type: custom:home-feed-card
        title: Anrufliste
        card_id: main_feed
        show_empty: false
        id_filter: ^home_feed_.*
        state_color: true
        history_days_back: 3
        entities:
          - entity: input_text.anrufliste1
            name: Fritz Box
            include_history: true
            more_info_on_tap: true
            max_history: 3
            content_template: '{{state}}'
      - type: markdown
        content: '#  <br />'
`

How do I manage to integrate the home-feed card into a bubble card?

Thank you and best regards
Gunter

**Comment by Clooos** [comment]
Hi, have you tried the latest beta? You can get it by going on "Redownload" on the Bubble Card HACS page, there is a toggle to display the beta release.

And don't worry, this one is totally stable.

**Comment by Clooos** [comment]
Can you try to toggle this?

![image](https://github.com/Clooos/Bubble-Card/assets/36499953/93d25d78-315a-4c0b-b452-0ba3d9317eed)

**Comment by GunterAv** [comment]
Hello,

yes, 

![Preview2](https://github.com/Clooos/Bubble-Card/assets/87611027/631f8ba4-6bd5-4b22-a228-419d7b87c2e6)

... but the result are the same...

![Preview1](https://github.com/Clooos/Bubble-Card/assets/87611027/66c298a3-9090-478e-b29a-5a8e5318a363)

Best regards
Gunter

**Comment by Clooos** [comment]
Thank you for the info, I will have to take a look at that.

**Comment by GunterAv** [comment]
Hello,

Hello,

also the same with Version: 2.0.0-beta.**8**
Preview:ok
Dashbord: empty

Best regards
Gunter

**Comment by GunterAv** [comment]
Hello,

also the same with Version: 2.0.0-beta.10
Preview:ok
Dashbord: empty

Best regards
Gunter

**Comment by Clooos** [comment]
Thank you for the feedback, I still don't understand why it's happening. I will need to try this card.

**Comment by GunterAv** [comment]
Hello,

thank you.
I use this card for my telephone call list as described here:

https://github.com/der8en/Fritz-Call-Monitor-Feed 

Best regards
Gunter

**Comment by GunterAv** [comment]
Hello,

i download Version Beta 12:
![V12](https://github.com/Clooos/Bubble-Card/assets/87611027/e8742a20-9eb8-42d1-913e-866c2d8f737a)



But if i add a New Bubble Card, i become Beta 10:
![new](https://github.com/Clooos/Bubble-Card/assets/87611027/f2ff5122-1810-4672-b490-564d7c2d0e8b)

Result the same:
Preview:ok
Dashbord: empty

Tanks and best regards
Gunter

**Comment by Clooos** [comment]
If you see beta 10 in the editor it means that you need to clear your browser cache to get the right version, your last test was on beta 10 and not 12.

**Comment by GunterAv** [comment]
Hello,
thanks.

But also with Version Beta 12:
Preview:ok
Dashbord: empty
![Unbenannt](https://github.com/Clooos/Bubble-Card/assets/87611027/682d74e4-5a0b-4d8d-9e11-06083cc262e2)


![Unbenannt1](https://github.com/Clooos/Bubble-Card/assets/87611027/3cf46be9-46ac-4286-83da-07a1747a3e0a)

Thanks and best regards
Gunter

**Comment by GunterAv** [comment]
Hello,

I have created a simple example for the [home-feed-card](https://github.com/gadgetchnnel/lovelace-home-feed-card)
with a calendar


`type: vertical-stack`
`cards:`
`  - type: custom:bubble-card`
`    card_type: pop-up`
`    hash: '#Test'`
`    name: Test for home-feed-card`
`    icon: mdi:ab-testing`
`    background_update: true`
`    close_on_click: false`
`    sub_button: []`
`    button_type: name`
`  - type: custom:vertical-stack-in-card`
`    cards:`
`      - type: custom:home-feed-card`
`        title: Home Feed`
`        card_id: main_feed1`
`        show_empty: true`
`        calendars:`
`          - calendar.geburtstage`
`        id_filter: ^home_feed1_.*`

Preview: OK 
See:
![Preview](https://github.com/Clooos/Bubble-Card/assets/87611027/93563353-0184-4602-baa8-618ceda28daa)

Dashboard: Empty
See:
![dashboard](https://github.com/Clooos/Bubble-Card/assets/87611027/cb63b9a6-b18a-455a-8510-96cb75c38e46)

Thank you for your continued help!

Best regards
Gunter

**Comment by Clooos** [comment]
Your issue should be finally fixed, I've tried this card and it was working on my side, can you confirm this? 🙂

https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-rc.1

**Comment by GunterAv** [comment]
Hello Clooos,

Sorry, on my site is the same with v2.0.0-rc1
Preview: OK
![preview](https://github.com/Clooos/Bubble-Card/assets/87611027/b86316b5-035a-4e7b-86d0-513196d4b200)

Dashboard: Empty
![dashboard](https://github.com/Clooos/Bubble-Card/assets/87611027/915d7201-54eb-4331-bea4-3ee13685c348)

Best regards 
Gunter

**Comment by Clooos** [comment]
Remove this, I've just tried and this is working 🙂

```yaml
  - type: custom:vertical-stack-in-card
    cards:
```

**Comment by GunterAv** [comment]
Hello Clooos,

thats it!
![dashboard](https://github.com/Clooos/Bubble-Card/assets/87611027/b563036e-5651-4545-9cb9-73c63159cf31)

Thank you so mutch!

Best regards 
Gunter

**Comment by Clooos** [comment]
You're welcome! 🎉
