### ISSUE TITLE
[v2.0.0-beta.6] call-service data keep losing

### ISSUE THREAD

**Issue by willliamchan** [Clooos/Bubble-Card#497]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests  
For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
It's about usage of call-service in bubble-card, it is no problem using YAML and define service and if any changes
that will be made next time using UI, pre-defined call-service data will be gone.

**To Reproduce**  
1. Add Bubble-Card button, define call-service with data using YAML, saved.
2. Edit the same card using UI, saved.
3. Settings in call-service are gone.

**Expected behavior**  
Perfect if we can search for available services, text box for data. Or can bubble card at least manage not to lose the call-service data when editing using UI?

**Screenshots**  

**Informations (please complete the following information):**  
 - OS: Windows 11
 - Browser: Edge
 - Bubble Card version v2.0.0-beta.6
 - Home Assistant version 2024.4.4

**Additional context**  

Thank you! 🍻

**Comment by Clooos** [comment]
Thank you for the feedback, someone already told me that and I will take a look at this in a few days (I have a pretty busy week). Hopefully the next release will be the true stable one! 🤞
