### ISSUE TITLE
[v2.0.0-beta.6] Pop-up display and style issues

### ISSUE THREAD

**Issue by GGSSDD** [Clooos/Bubble-Card#499]
**Hi, 
I have 3 Pop-ups in a subview, and one of them is displayed wrong (Main entrance) while the other 2 display as they should. Also I have CSS to remove the border radius for all the pop-ups, but it’s not working for the top of the card.** 

![IMG_1357](https://github.com/Clooos/Bubble-Card/assets/121240474/ae88622f-c566-4c70-8f00-f1fbc735d23d)
![IMG_1358](https://github.com/Clooos/Bubble-Card/assets/121240474/2cbea7c9-e7f2-425e-97e8-f0ecefe1af25)
![IMG_1359](https://github.com/Clooos/Bubble-Card/assets/121240474/c045a520-95c7-45a8-ae22-2f784e777d85)

**OS: iOS
Browser: Companion App
Bubble Card version: v2.0.0-beta.6
Home Assistant version: 2024.4.4**

Thank you!

**Comment by GGSSDD** [comment]
Hi,
I’ve fixed the pop-up with the display issue. Actually it was not quite a fix, I just deleted the card and added it again. Now it’s displaying as it should. I don’t know what was causing that issue. Anyway, is there any progress on the top of the card issue, being able to set the border radius to 0, there as well?
Thank you!

**Comment by Clooos** [comment]
Hi, I'm glad that you fixed your issue! 

To change the border-radius you can do that in the custom styles:
```yaml
.bubble-pop-up {
  border-radius: 20px !important;
}
```

**Comment by GGSSDD** [comment]
Unfortunately this is not working, even if I updated to the latest version and cleared the frontend cache:

```
.bubble-pop-up {
  border-radius: 0px !important;
} 
```
I used to have this before, but this is not working either for quite some time:

```
#root {
  border-radius: 0px !important;
} 
```

**Comment by Clooos** [comment]
I've just tried and I can confirm that this is working right after pasting this in the custom styles section:
```yaml
.bubble-pop-up {
  border-radius: 0px !important;
} 
```


![image](https://github.com/Clooos/Bubble-Card/assets/36499953/af4c56b0-cd84-4548-8f8f-659986b114a1)

**Comment by GGSSDD** [comment]
So it does indeed… meaning the issue’s on my end. Wonder what is causing this? I’ll keep looking into it.

Thanks!

**Comment by Clooos** [comment]
Keep me informed if you find what's causing this, this is weird indeed.

**Comment by GGSSDD** [comment]
It does work indeed, if you add a header, although in most of the cases I don't have a need for a header

**Comment by Clooos** [comment]
I've added this issue to my list, it will be fixed in the next release!

**Comment by GGSSDD** [comment]
Thank you! Really appreciate it!

**Comment by GGSSDD** [comment]
Yes, I can confirm that.

Thank you!

**Comment by Clooos** [comment]
You're welcome!
