### ISSUE TITLE
Popup, pops under

### ISSUE THREAD

**Issue by Ashpork** [Clooos/Bubble-Card#5]
On a dashboard with an entities card, containing both type: custom:bar-card and type: custom:multiple-entity-row, the popup pops under the entities card on iOS. On Desktop it's hit and miss if it works or not.

https://github.com/Clooos/Bubble-Card/assets/70691313/3038d708-615e-4231-9200-b85a4ae8a671

**Comment by lazyboy0172** [comment]
I have similar issue on desktop with custom:auto-entities card. Strangely, it works on mobile for me, but is hit or miss on desktop. One of my pop-up cards draws below the auto-entities card, and the other pop-up card draws above it.

**Comment by Clooos** [comment]
> I've realised it's to do with the order of the cards in the dashboard. If you put the popup cards after the other non-bubble cards in the lovelace view, then it'll always pop over rather than pop under.

Indeed, all pop-ups must be placed after all the other cards on your dashboard. I will document this to make it clearer.
