### ISSUE TITLE
Feature request (?) - or I have not found out how to do this, maaaaybe a bug?

### ISSUE THREAD

**Issue by promufa** [Clooos/Bubble-Card#502]
I am loving Bubble cards and the new relase with sub-buttons is just awesome!

What I am looking for is a way to have the button press do one action but the button colouring to be based off the state of a different entity.

Use case:
I have a RF ceiling fan that I am controlling though HA via a broadlink RF controller. I have mapped the Bubble card buttons to call the relevant remote.send_command scripts but I cannot see if the fan / light are on or off when not physically in the room.

![image](https://github.com/Clooos/Bubble-Card/assets/57601488/56d052e8-7a38-4a9d-9133-614042d1ce13)

I have also installed power meters (Shelly) in the fan so I have sensors to know whether the fan is on or off, and based on the power draw, I can also calculate the speed of the fan. The reported wattage is changing the state of individual boolean helpers:
![image](https://github.com/Clooos/Bubble-Card/assets/57601488/b36c944e-9c7d-4a6e-ba7b-ddf4ad85c569)

I have already tried having the bubble button assigned to the helper and the tap action to call the script, but it still does not seem to colour the button based on the state of the helper.

**Comment by Clooos** [comment]
Hi and sorry for the late answer, you can take a look at the template section in the documentation, I've added many examples on how you can achieve this.

**Comment by promufa** [comment]
Hi thanks for following up on this.
I did figure it out some time ago but forgot to add it to this thread.

I just had to set the input boolean as the main entity and call script on the buttoin settings,.
