### ISSUE TITLE
Horizontal button stack doesn't scroll on some browsers

### ISSUE THREAD

**Issue by pgale** [Clooos/Bubble-Card#505]
**Describe the bug**  
v2.0.0beta6 - I've now created extra buttons in the horizontal button stack but the stack doesn't scroll to give me access to the extra buttons. Locked solidly in place.

**Information (please complete the following information):**  

Happens on Android browser, Firefox on PC. It DOES work on iOS in the companion app.

**Comment by pascalosek** [comment]
Doesn’t work on my iOS companion app. 
It’s just centered. 

![IMG_0292](https://github.com/Clooos/Bubble-Card/assets/163521046/b31028ef-80f2-472f-bd90-b23c37ee709b)

**Comment by pgale** [comment]
Out of interest, how many buttons do you have?

**Comment by pascalosek** [comment]
Only these four. Before upgrade from the stable version it was working correctly.

**Comment by pascalosek** [comment]
> Doesn’t work on my iOS companion app. It’s just centered.
> 
> ![IMG_0292](https://private-user-images.githubusercontent.com/163521046/329764771-b31028ef-80f2-472f-bd90-b23c37ee709b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTA2ODgsIm5iZiI6MTcxNTU5MDM4OCwicGF0aCI6Ii8xNjM1MjEwNDYvMzI5NzY0NzcxLWIzMTAyOGVmLTgwZjItNDcyZi1iZDkwLWIyM2MzN2VlNzA5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QwODUzMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDYzMDVmYTljYWIxMDdlNjRlMWUzOTNjMzAyMTdiZGJhZThjYTNlNGJkZDk2ZTgyOWI2MWIwZGEyNDhkOTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rglb69lOoy-Qz0Fu_d2IWqA61HUQ_gyFD2ZwycXUpnI)

It seems to be too narrow. If I add 'name' to the first button, then it's enough wide and scrollable.

**Comment by pgale** [comment]
Are you saying that if the buttons extend far enough off the page that they ARE scrollable?

**Comment by pascalosek** [comment]
@pgale yeah, correct.

**Comment by pgale** [comment]
> @pgale yeah, correct. 

So in that case, it's probably more about the calculation of the button width which might be a slightly different issue. 

In my case above, I'm reporting where the buttons don't scroll regardless of the combined button width ie you can have 10 buttons that extend well off the page but they still don't scroll.

**Comment by pgale** [comment]
Just tried beta 8 and the issue still occurs. @Clooos can you confirm you have seen this and it's on the list to fix? Thanks :)

**Comment by Clooos** [comment]
I forgot about this one indeed, this will be fixed in the next release :)

**Comment by pgale** [comment]
Thanks :)

**Comment by pascalosek** [comment]
> > Doesn’t work on my iOS companion app. It’s just centered.
> > ![IMG_0292](https://private-user-images.githubusercontent.com/163521046/329764771-b31028ef-80f2-472f-bd90-b23c37ee709b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTA2ODgsIm5iZiI6MTcxNTU5MDM4OCwicGF0aCI6Ii8xNjM1MjEwNDYvMzI5NzY0NzcxLWIzMTAyOGVmLTgwZjItNDcyZi1iZDkwLWIyM2MzN2VlNzA5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QwODUzMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDYzMDVmYTljYWIxMDdlNjRlMWUzOTNjMzAyMTdiZGJhZThjYTNlNGJkZDk2ZTgyOWI2MWIwZGEyNDhkOTA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rglb69lOoy-Qz0Fu_d2IWqA61HUQ_gyFD2ZwycXUpnI)
> 
> It seems to be too narrow. If I add 'name' to the first button, then it's enough wide and scrollable.

Still occurs in beta9.
