### ISSUE TITLE
v2.0.0.beta7 - show_last_changed stopped working

### ISSUE THREAD

**Issue by willliamchan** [Clooos/Bubble-Card#506]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests  
For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
flag show_last_changed stopped working, instead using flag show_attribute help to enable/disble "last changed"

**To Reproduce**  

Adjust show_attribute between true/false, bubble card no longer honour param show_last_changed.

Thank you! 🍻

**Comment by Clooos** [comment]
This also fixed in the last beta, thank you again!
