### ISSUE TITLE
v2.0.0.beta7 - icon style instruction from beta6 breaking beta7

### ISSUE THREAD

**Issue by willliamchan** [Clooos/Bubble-Card#507]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests  
For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
![image](https://github.com/Clooos/Bubble-Card/assets/54702221/5191f78f-65aa-48f3-9d4f-7582f6a223c9)
The above instruction from Beta6 demonstrate icon style is breaking the formatting in Beta7. 

Style starts with "$" is no longer acceptable.

**Expected behavior**  

**Screenshots**  

**Informations (please complete the following information):**  
 - Bubble Card version [e.g. 2.0.0]
 - Home Assistant version [e.g. 2024.4.3]

**Additional context**  

Thank you! 🍻

**Comment by Clooos** [comment]
This is fixed in the new beta, thank you!
