### ISSUE TITLE
Haptic feedback is gone in 2.0.0-beta.8

### ISSUE THREAD

**Issue by pascalosek** [Clooos/Bubble-Card#509]
Hi!

In stable version v1.7.3 when I was using slider on my iPhone in Home Assistant app on iOS I got haptic feedback.
After upgrade to 2.0.0-beta.8 haptic feedback is gone. 

Is it a bug or haptic feedback was disabled?

**Comment by Clooos** [comment]
I was thinking the same, I will change these at the same time.

**Comment by pascalosek** [comment]
Sliders still don't have haptic feedback in beta9. Was it added already?

**Comment by pascalosek** [comment]
HACS didn't update bubble card from beta 8 to 10, but only 9. After manual update to 10, it works great.

**Comment by Clooos** [comment]
Yes for some reason the beta 10 is not updated correctly on HACS, but I'm glad that it works great now!
