### ISSUE TITLE
Frigate Card not filling column in pop-up

### ISSUE THREAD

**Issue by wraith1385** [Clooos/Bubble-Card#513]
When I put some frigate cards inside of my existing pop-ups they don't fill the full column like a picture glance card does, or like a frigate card does when I create one outside of the pop-up.  

**Screenshots**  

<img width="554" alt="Screenshot 2024-05-13 at 5 17 27 PM" src="https://github.com/Clooos/Bubble-Card/assets/1617434/0bff5322-b692-4a46-8de9-cd26af10b1e2">

**Informations (please complete the following information):**  
 - OS: MacOS
 - Browser Safari
 - Bubble Card version [2.0.0.8]
 - Home Assistant version 2024.5.3

**Comment by Clooos** [comment]
Have you tried adding a Frigate card in a vertical stack without the pop-up card? Is the behavior the same?

**Comment by wraith1385** [comment]
Looks like it's fine in a normal vertical stack.  
<img width="500" alt="Screenshot 2024-05-20 at 8 12 28 PM" src="https://github.com/Clooos/Bubble-Card/assets/1617434/3f07cd18-d738-40cc-a58d-b752b6e983ae">

**Comment by Clooos** [comment]
Interesting, thank you for the fast answer!

**Comment by wraith1385** [comment]
Fixed!  Thanks!
