### ISSUE TITLE
UI Edit doesn't work when a sub-button has an action to call a service

### ISSUE THREAD

**Issue by fellipute** [Clooos/Bubble-Card#514]
**Describe the bug**  
When I make one of the sub-buttons inside a button to call a service, for some reason I'm no longer able to edit the button using the UI, only through code.

**To Reproduce**  
1. Create a new bubble button
2. Insert a sub-button
3. On the Tap Action, call a service
4. Try to edit using the UI.

**Screenshots**  
![image](https://github.com/Clooos/Bubble-Card/assets/3584098/fffaa48d-4dcf-43b7-aeab-a4f1562a15ec)

![image](https://github.com/Clooos/Bubble-Card/assets/3584098/c2884dfe-4b8f-489d-82f0-311534b404f1)

**Informations (please complete the following information):**  
 - OS: Windows
 - Browser chrome
 - Bubble Card version Beta8
 - Home Assistant version 2024.5.3

**Additional context**  

Thank you! 🍻

**Comment by Clooos** [comment]
I will take a look at this, thank you for the feedback!

**Comment by Clooos** [comment]
This issue is now fixed in the latest beta 🥳 Thanks again for the feedback!
