### ISSUE TITLE
Horizontal Stack Card not editable

### ISSUE THREAD

**Issue by Breakingx** [Clooos/Bubble-Card#515]
Hey,

I can't edit the Horizontal Stack Card with the UI Mode. The button is not clickable.

![image](https://github.com/Clooos/Bubble-Card/assets/19574599/4a89fc77-0761-4562-bad6-b9ae64f9c37f)

**Comment by Clooos** [comment]
Hi, this issue is already fixed on my side, it will works in the next release.
