### ISSUE TITLE
Regression: Buttons set to Name/Text don't use Button Actions

### ISSUE THREAD

**Issue by electroflame** [Clooos/Bubble-Card#517]
**Describe the bug**  
The latest beta (or maybe the one before) seems to have removed the ability for Buttons to set Button Actions via the UI, and use Button Actions that were already set in the YAML.  Actions for tapping, etc. on the Icon itself works, but Button Actions for tapping the actual button don't work -- although they still trigger the animation and/or haptics.

**Expected behavior**  
That Button Actions tied to tapping/clicking the button would still work, as it makes buttons significantly less useful when only the Icon can trigger actions.

**Additional context**  
This definitely worked before, as I still have some buttons with the `button_action` YAML, but only Icon taps work now.

**Comment by Clooos** [comment]
Hi, I will change that, thank you for the feedback!

**Comment by Clooos** [comment]
This issue is now fixed in the latest beta 🥳 Thanks again for the feedback!
