### ISSUE TITLE
Setting colors in theme? 

### ISSUE THREAD

**Issue by mrgrlscz** [Clooos/Bubble-Card#519]
Is ` bubble-button-background-color ` the only color we can set at theme level?? Every other color seems to be hard-coded.
This causes different problems:
  - EVERY bubble-card I create needs color tweaks
  - this is a hudge problem for people using different themes, and no, I'm not the only one ^^
  - each bubble-card type (button, slider, media player etc...) needs different CSS tweaks
  - CSS tweaks don't follow the changes you do (like between beta4 and beta6), so cards colors are sometimes different from a version to another.

Maybe (I'm absolutely NOT a developer) something like :
`icon_color.is_active = var(--bubble-button-icon-color-active) if set else rgb(255,220,200)`

For:
- border radius 
- icon color  (when active and inactive) 
- icon background color  (when active and inactive) 
- button background color  **(fouded a background-color-2 reference in bubble-card.js)**
- slider background color (in case light switch and light color are from different entities, like with WLED multi segmented strips) 
- sub button icon color   (when active and inactive) 
- sub button icon background color  (when active and inactive) 
- opacity? 

This is what I do for now, here's part of my code and only works for bubble-button in switch mode, not sliders.

```
styles: |
  /* ####################### COMMON 1/3 ####################### */
  /* main_card */
  ha-card {
    --bubble-button-background-color: transparent !important;
  }
  ha-card > div > div {
    border-radius: var(--ha-card-border-radius) !important; 
  }
  ha-card > div > div > div {
    background-color: transparent !important;
  }

  /* text */
  div.bubble-name-container.name-container {
    color: var(--secondary-text-color);
  }
  .is-unavailable div.bubble-name-container.name-container {
    color: var(--warning-color);
  }
  .is-on div.bubble-name-container.name-container {
    color: var(--contrast);
  }

  /* sub_button */
  .bubble-sub-button-container > div {
    color: var(--primary-text-color) !important;  
    background-color: var(--surface0) !important;
    opacity: var(--alpha);
  }

  /* slider_radius */
  .range-fill {
    border-radius: 4px;
  }

  /* ####################### SPE SWITCH LIGHTS ####################### */

  /* icon_color */
  .bubble-icon-container.icon-container > ha-icon {
    transition: color 2s;
    color: ${state == 'on' ? 'var(--contrast)' : '' } !important;
  }

  /* icon_background */
  .bubble-icon-container.icon-container::after {
    transition: background 2s;
    background-color: var(--aqua);
  }

  /* button_background */
  .bubble-button-background {
    transition: background 2s;
    background-color: ${state == 'on' ? 'var(--aqua)' : '' } !important;
  }
```
Resulting in: (stock to the left, with the code above to the right)
![image](https://github.com/Clooos/Bubble-Card/assets/113037215/2ac5f82c-3895-4580-a2b5-e1ad6171712b)

And this pic is from another theme... 
![image](https://github.com/Clooos/Bubble-Card/assets/113037215/f8b359c2-04b3-4ec8-97d0-d204d8aafcc0)

I know you're already busy, and I'm a patient guy ;)
By the way you did great job, and even if I'll not use it for me (custom-layout) I think your recent 'section view' compatibility will push bubble-card over boundaries!!

**Comment by koleos6** [comment]
Yes , could be a nice évolution for easier adoption to allow the parameters of the theme in a bubble-card

**Comment by gbcatrinoiu** [comment]
+1

**Comment by Clooos** [comment]
This is in my mind for a long time, but I've added so many new features in the v2 that I had to stop somewhere.

But I will definitely add that possibility in the future.

**Comment by mrgrlscz** [comment]
Patience is the mother of all virtues!!
Again, congrats for your work.

**Comment by lforamitti** [comment]
I would like to get the same background for the bubble-card and all others cards, but the bubble-card show a black background and the other card use the default background-color.

![image](https://github.com/Clooos/Bubble-Card/assets/3219686/2fc8d971-dffb-4e0d-b702-2279d311dc25)

**Comment by ausfas** [comment]
> Is `bubble-button-background-color` the only color we can set at theme level?? Every other color seems to be hard-coded. This causes different problems:
> 
> * EVERY bubble-card I create needs color tweaks
> * this is a hudge problem for people using different themes, and no, I'm not the only one ^^
> * each bubble-card type (button, slider, media player etc...) needs different CSS tweaks
> * CSS tweaks don't follow the changes you do (like between beta4 and beta6), so cards colors are sometimes different from a version to another.
> 
> Maybe (I'm absolutely NOT a developer) something like : `icon_color.is_active = var(--bubble-button-icon-color-active) if set else rgb(255,220,200)`
> 
> For:
> 
> * border radius
> * icon color  (when active and inactive)
> * icon background color  (when active and inactive)
> * button background color  **(fouded a background-color-2 reference in bubble-card.js)**
> * slider background color (in case light switch and light color are from different entities, like with WLED multi segmented strips)
> * sub button icon color   (when active and inactive)
> * sub button icon background color  (when active and inactive)
> * opacity?
> 
> This is what I do for now, here's part of my code and only works for bubble-button in switch mode, not sliders.
> 
> ```
> styles: |
>   /* ####################### COMMON 1/3 ####################### */
>   /* main_card */
>   ha-card {
>     --bubble-button-background-color: transparent !important;
>   }
>   ha-card > div > div {
>     border-radius: var(--ha-card-border-radius) !important; 
>   }
>   ha-card > div > div > div {
>     background-color: transparent !important;
>   }
> 
>   /* text */
>   div.bubble-name-container.name-container {
>     color: var(--secondary-text-color);
>   }
>   .is-unavailable div.bubble-name-container.name-container {
>     color: var(--warning-color);
>   }
>   .is-on div.bubble-name-container.name-container {
>     color: var(--contrast);
>   }
> 
>   /* sub_button */
>   .bubble-sub-button-container > div {
>     color: var(--primary-text-color) !important;  
>     background-color: var(--surface0) !important;
>     opacity: var(--alpha);
>   }
> 
>   /* slider_radius */
>   .range-fill {
>     border-radius: 4px;
>   }
> 
>   /* ####################### SPE SWITCH LIGHTS ####################### */
> 
>   /* icon_color */
>   .bubble-icon-container.icon-container > ha-icon {
>     transition: color 2s;
>     color: ${state == 'on' ? 'var(--contrast)' : '' } !important;
>   }
> 
>   /* icon_background */
>   .bubble-icon-container.icon-container::after {
>     transition: background 2s;
>     background-color: var(--aqua);
>   }
> 
>   /* button_background */
>   .bubble-button-background {
>     transition: background 2s;
>     background-color: ${state == 'on' ? 'var(--aqua)' : '' } !important;
>   }
> ```
> 
> Resulting in: (stock to the left, with the code above to the right) ![image](https://private-user-images.githubusercontent.com/113037215/330596848-2ac5f82c-3895-4580-a2b5-e1ad6171712b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNjU5ODgsIm5iZiI6MTcyNzI2NTY4OCwicGF0aCI6Ii8xMTMwMzcyMTUvMzMwNTk2ODQ4LTJhYzVmODJjLTM4OTUtNDU4MC1hMmI1LWUxYWQ2MTcxNzEyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxMjAxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGNmNDFiN2RjNTYyNWFkZGVlM2Q5MGU5OTVmNjFhYzA3YTU1NGJlOWY1MzcyNGRjMGY1YTQ2NGIyZjljMTM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.I_YU59EM8xSD9fITDBG6UCQRxXmTNAezVoworw6azX0)
> 
> And this pic is from another theme... ![image](https://private-user-images.githubusercontent.com/113037215/330598267-f8b359c2-04b3-4ec8-97d0-d204d8aafcc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNjU5ODgsIm5iZiI6MTcyNzI2NTY4OCwicGF0aCI6Ii8xMTMwMzcyMTUvMzMwNTk4MjY3LWY4YjM1OWMyLTA0YjMtNGVjOC05N2QwLWQyMDRkOGFhZmNjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxMjAxMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjJiNDZiMGY3ZDkzZTBkYThmNTlkMzZkODVmODk5M2VjMWYzMzQ0MGI0OTBlODdhODlkMjg3MDQwZDAxY2Q1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.waDhL3Iba9lB-2sEqiET1QWICDGdxDNo9b9CWZzpdE8)
> 
> I know you're already busy, and I'm a patient guy ;) By the way you did great job, and even if I'll not use it for me (custom-layout) I think your recent 'section view' compatibility will push bubble-card over boundaries!!

This is exactly I have been looking for and have been spending the entire week. While Clooos has made the best card in HA I do not want to apply card level changes. Hope Clooos would get time to allow changes to switch, slider, lights background independently via theme under card-mod
