### ISSUE TITLE
Horizontal button stack overlaying each other

### ISSUE THREAD

**Issue by dnestico** [Clooos/Bubble-Card#52]
I don't know why this is happening I've tried clearing my browser cache and still but for some reason the buttons are overlaying each other when I add more than 2 and it looks like this. Please help.

<img width="540" alt="Screenshot 2023-09-14 at 4 50 05 PM" src="https://github.com/Clooos/Bubble-Card/assets/3034555/19f5fbcb-21a2-49a1-8077-44bf2ab5ba81">

```
type: custom:bubble-card
card_type: horizontal-buttons-stack
1_name: Davids Room
1_icon: hue:downstairs
1_entity: light.basement_lights
2_name: V/E Room
2_icon: hue:upstairs
2_entity: light.vally_esthers_room
3_name: Media
3_icon: mdi:music-circle
style: |
  ha-card {
    margin-bottom: 62px !important;
```

**Comment by Clooos** [comment]
Have you tried going in edit mode since? Because when you are in this mode the size of the buttons is automatically calculated and saved in your cache, this is needed for the auto order feature. So indeed clearing your cache will always do that, but I will try to find a way to fix that.

**Comment by dnestico** [comment]
Yea this screenshot was out of edit mode, I even made new button stack but it seems to always happen its very weird. Would love it resolved so I can use it!

**Comment by Clooos** [comment]
I've just tried your code and you just need to add links to fix this. But thanks for finding this issue, I will add an error if no link is added.

This is working:

```yaml
type: custom:bubble-card
card_type: horizontal-buttons-stack
1_name: Davids Room
1_icon: hue:downstairs
1_link: '#davids_room'
1_entity: light.basement_lights
2_name: V/E Room
2_icon: hue:upstairs
2_link: '#ve_room'
2_entity: light.vally_esthers_room
3_name: Media
3_icon: mdi:music-circle
3_link: '#media'
style: |
  ha-card {
    margin-bottom: 62px !important;
  }
```

**Comment by dnestico** [comment]
Genius, that did indeed fix it!

Now is it possible to remove the black shadow/background with card mod btw? Thanks

**Comment by Clooos** [comment]
Just add this, you don't even need card-mod :

```yaml
styles: |
  .horizontal-buttons-stack::before {
    display: none !important;
  }
```
