### ISSUE TITLE
Service Call GUI setup

### ISSUE THREAD

**Issue by muchcodesuchwow** [Clooos/Bubble-Card#522]
Hello,
Thank you for the nice Buttons. :)

I can select a service call as a tap action from GUI, eg. Mediaplayer subbutton or switch. 

But i cant select a script or service. Is that a Bug or a limitation of the HA GUI?

Is there a better way to call services from bubble cards? I have to select an entitity even tho I dont need one.

(I want to start an Internet radio from a button)

**Comment by s1mpleman** [comment]
I've been copying the yaml from other buttons, they still work. The only thing I don't seem to get when using scrpts on buttons is any user context.

**Comment by Clooos** [comment]
Hi, there is still some issues in the editor but I'm on it! I still have some work to do but a new (and hopefully the last one) beta is on the way!

**Comment by muchcodesuchwow** [comment]
> I've been copying the yaml from other buttons, they still work. 

Thank you for the suggestion

**Comment by Clooos** [comment]
This issue is now fixed in the latest beta 🥳
