### ISSUE TITLE
Hiding previous and power button of Mediaplayer does not work

### ISSUE THREAD

**Issue by muchcodesuchwow** [Clooos/Bubble-Card#523]
**Describe the bug**  
I want to hide the previous, next and power button in a Mediaplayer. Under the GUI are setting toggles, but these have no effect. Toggling these settings and saving the card results in only the next button removed. When opening the setup menu of the card again, the "Hide previous button" and "Hide power button" are disengaged.

**To Reproduce**  
1. Create new Mediaplayer card.
2. Select "Optional - Hide next button" and "Optional - Hide power button "
3. Save card
4. See no hiding

**Expected behavior**  
I expect the previous and power button to hide like the next button.

**Informations (please complete the following information):**  
 - Firefox 126
 - Bubble card beta v8
 - Home Assistant 2024.5.3

**Comment by Clooos** [comment]
Hi! I will take a look at this, thank you for the feedback!

**Comment by Clooos** [comment]
This issue is now fixed in the latest beta 🥳 Thanks again for the feedback!
