### ISSUE TITLE
Popup's don't display after some time

### ISSUE THREAD

**Issue by pgale** [Clooos/Bubble-Card#529]
Beta8. I'm running one of my dashboards on Android Go 11 with the latest available webview on my Lenovo ThinkSmart View tablets. This is within Fully Kiosk Browser. After some time or after the screen has been off and is turned back on, the popups when triggered, flash up and then disappear after a fraction of a second. 

This might be a tricky one to troubleshoot and specific to my setup but I wondered if anyone else has ever come across similar behaviour?

**Comment by Clooos** [comment]
They are a lot of compatibility issues with the pop-ups and Fully Kiosk Browser. 

@brunosabot worked on a PR directly on the Fully Kiosk Browser project and I hope that its next release will fix these issues.

For now, my recommended way to use Bubble Card is still the HA Companion app.

**Comment by pgale** [comment]
Companion app and fully kiosk single app?
8.1 popups works fine though, just A11 having this issue. Could well be something else though.

**Comment by Clooos** [comment]
I'm not sure to understand your last answer, but I've changed something and tested Fully Kiosk Browser and everything seems to works perfectly 🤞 I'm waiting a bit to see if there are no new issues before releasing it, if it's the case I will consider it as the stable one (finally!).

**Comment by pgale** [comment]
What I mean is that there are two versions of fully kiosk - 'Browser' and 'Single App'. The single app version runs an app and browser runs webview. I think the companion app which can run in the 'single app' version still uses the same webview so I'm guessing that performance and features would be the same.

**Comment by Clooos** [comment]
I was not aware of that, but I'm not sure of what I can do for that issue. The fix I've applied is more related to the centering issue on Fully Kiosk Browser.

**Comment by Clooos** [comment]
Hi again, I've just released a new beta and I've found some issues related to the pop-ups, with some luck it will fix your issue 🤞

https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0-beta.12

**Comment by pgale** [comment]
Thanks for your work on this.

I've been running beta 11 for a little while and I've not seen a recurrence of the issue so hopefully all good. I'll post again if I see it but looking good so far :)

**Comment by pgale** [comment]
Definitely not seen a recurrence so closing this. Working well :)

**Comment by Clooos** [comment]
Yeah!!!
