### ISSUE TITLE
Select card behaviour since 2.0.0-beta.9 

### ISSUE THREAD

**Issue by chris9208** [Clooos/Bubble-Card#539]
When including a 'mushroom-select-card' in a pop up, the drop down is disconnected from the card and its contents are hidden behind any following cards in the pop up. This only started from 2.0.0-beta.9, reverting to beta 8 returns to normal behaviour 

**To Reproduce**  
1. Open pop up
2. select drop down on 'mushroom-select-card'
3. Options hidden behind other cards

**Expected behavior**  
Options should be infront of other cards

**Screenshots**  

beta 8 normal behaviour
![IMG_1030](https://github.com/Clooos/Bubble-Card/assets/97855670/6b826f16-ef94-4b55-825b-979e1efd1bc9)
![IMG_1027](https://github.com/Clooos/Bubble-Card/assets/97855670/8e466b71-9a21-4b26-807e-84b7263a2153)

beta 9+ broken behaviour
![IMG_1028](https://github.com/Clooos/Bubble-Card/assets/97855670/aed16adf-553d-41d6-8880-edbdfb9c362c)
![IMG_1029](https://github.com/Clooos/Bubble-Card/assets/97855670/63484807-101c-4f81-bf42-3c4d68bd917f)

Thanks

**Comment by Clooos** [comment]
Hi, I will release a new beta in a few minutes that should fix this, thank you for the feedback!

**Comment by chris9208** [comment]
This problem (or something similar) seems to be back. As of 2.0.0 the drop down shows but isn't connected to the 'mushroom-select-card'. 

![IMG_1123](https://github.com/Clooos/Bubble-Card/assets/97855670/b185ee64-c009-4144-bdef-c1bc067f29a0)


In 2.0.4 the drop down is connected to the card again but only the first row shows, the second row is gradually more transparent, and any rows after that aren't visible.

![IMG_1121](https://github.com/Clooos/Bubble-Card/assets/97855670/f01b6720-5d1d-40da-b8d5-0fae13c136f6)


However, the drop down shows normally when conditions cards below it are visible.

![IMG_1122](https://github.com/Clooos/Bubble-Card/assets/97855670/a4426011-28cb-4d41-b762-0163ed4c431f)


Thanks again

**Comment by Clooos** [comment]
I will take a look at that, thanks for the feedback.

**Comment by Clooos** [comment]
I've just fixed it, I will release a new beta as soon as I can!

**Comment by Clooos** [comment]
Nothing like that, it was because of the gradient mask that is at the top and at the bottom of the pop-ups, its position was not fixed.

**Comment by Clooos** [comment]
This issue is now fixed in the new betas 🎉

https://github.com/Clooos/Bubble-Card/releases/tag/v2.1.0-beta.2
