### ISSUE TITLE
Popups don't hide properly on Home Assistant Version 2024.6.0b6

### ISSUE THREAD

**Issue by s1mpleman** [Clooos/Bubble-Card#545]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests  
For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
When upgrading to the latest home assistant beta, 2024.6.0.b6 as of writing, the cards don't hide anymore. 

**To Reproduce**  
Load the dashboard in 2024.6.0b6

**Expected behavior**  

**Screenshots**  

**Informations (please complete the following information):**  
 - OS: Windows and Home Assistant App.
 - Browser: Firefox, and Chrome, Android App. 
 - Bubble Card version: 
 - Home Assistant version: 2024.6.0b6

**Additional context**  
Started after updating to one of the latest beta's, just before the RC. Dunno if it's relevant but I checked on the home assistant frontend repo and they've just introduced some card visibility settings for each section panel. It had broken conditional cards on b2,3,4,6 but that's now resolved on b6. 

Thank you! 🍻
![image](https://github.com/Clooos/Bubble-Card/assets/5730731/59c020e1-0060-46e5-9e24-6172e414124d)
![image](https://github.com/Clooos/Bubble-Card/assets/5730731/c244c079-496f-4833-b640-b77c27a95f5f)

**Comment by Clooos** [comment]
Damn, I hope that this issue will be fixed on the Home Assistant side, I haven't tried the HA betas.

**Comment by s1mpleman** [comment]
I'll report back if one of the latest releases fixes it. 

I used to get it on earlier versions all the time after editing but a quick refresh cleared them.

**Comment by s1mpleman** [comment]
Just to report back, sadly I'm on the 2024.6.0 with the latest front end and the issue still persists. I've no idea how your hiding the cards but it's not just effected your card, I have a trash card that hides itself and that no longer does so. 

Rather annoying 😑. 

Congratulations on the none beta release btw I can open dropdowns again on mobile 😁

**Comment by Clooos** [comment]
I've tried the new release and I'm on it!

**Comment by Clooos** [comment]
This now fixed! Bad timing this update 😅

https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.2

**Comment by s1mpleman** [comment]
Absolutely amazing! Thank you! Confirmed on my browser.
