### ISSUE TITLE
[v2.0.0-rc.1] Minor issue with battery icon state

### ISSUE THREAD

**Issue by willliamchan** [Clooos/Bubble-Card#548]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests  
For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
When battery level is 100% and bubble card uses 90% full icon.

**Expected behavior**  
When battery is 100% to use mdi:battery instead of mdi:battery-90

Thank you! 🍻

**Comment by Clooos** [comment]
Hi, I was aware of that and this issue should be fixed it the new... v2 stable release! 🎉

https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.0

**Comment by Clooos** [comment]
I haven't changed anything related to this. This is really weird 😅

**Comment by Clooos** [comment]
<img width="626" alt="image" src="https://github.com/Clooos/Bubble-Card/assets/36499953/e1f77cc6-57ff-46c7-8a6d-5427ce8e8c87">

Well... sorry!

**Comment by Clooos** [comment]
And by the way is the battery icon issue correctly fixed?
