### ISSUE TITLE
Half blank card on desktop browser

### ISSUE THREAD

**Issue by TimBeekman** [Clooos/Bubble-Card#549]
**Describe the bug**  
![image](https://github.com/Clooos/Bubble-Card/assets/89469564/4059da52-7602-479a-bb1f-0e3d108aeef4)
You can see the alarm card is only displayed partly. I need to scroll to see the rest of the card. This only happens on desktop

This goes for any Bubble card i have,  no matter what cards are in the stack.

**Expected behavior**  
See this picture of my phone:
![image](https://github.com/Clooos/Bubble-Card/assets/89469564/d02c4e99-9776-4554-9f63-abcf09b95f46)

**Screenshots**  

**Informations (please complete the following information):**  
 - Browser: chrome
 - Bubble Card version: 2.0.1
 - Home Assistant version: 2024.6

**Comment by TimBeekman** [comment]
Update, it only happens when I use % in stead of px

**Comment by Clooos** [comment]
Indeed! Something has changed in the v2, you can use for example 50vh instead of 50% now, I've just changed that example in the editor and I will do the same in the editor.

Also if you want a fixed height for your pop-up (e.g. 400px) you can do this:

```yaml
    margin_top_mobile: calc(100vh - 400px)
    margin_top_desktop: calc(100vh - 400px)
```

**Comment by Clooos** [comment]
Any feedback on this?
