### ISSUE TITLE
Scrolling on a screen of bubble slider cards, activates the lights

### ISSUE THREAD

**Issue by MartinNygaardSchacht** [Clooos/Bubble-Card#55]
As seen here, I have a vertical stack card with 12 Bubble-button-slider cards. When on my mobile, and want to scroll down past them, it will activate the sliders I touch while scrolling. 
I know it is the main function of a slider, but is there anyway to change this behaving?

If the card could somehow limit the slide direction to only look for right to left movement?

- If I slide from right to left = slide on the card
- If i slide from top to button = scroll on the dashboard

See the video: [YouTube](https://youtube.com/shorts/RY_9exrceB0)

![Screenshot_20230918_104227_Home Assistant](https://github.com/Clooos/Bubble-Card/assets/83701734/66aac966-29cd-4f41-aef6-4b2afa86cb7f)

**Comment by Clooos** [comment]
Hi and thanks for the feedback! This is now fixed in the new beta :
https://github.com/Clooos/Bubble-Card/releases/tag/v0.0.1-beta.8

**Comment by MartinNygaardSchacht** [comment]
You rock - It works!
I am really amazed by how quick you fixed not just this, but 3 of of 3 points i had.
