### ISSUE TITLE
UI | Cover | change which service is called. ui doesn't reflect change

### ISSUE THREAD

**Issue by Symbiot78** [Clooos/Bubble-Card#550]
newest version of HA OS on VM.

I created a new dashboard to test sections
I added bubble card to test the cover.
I noticed you can override what service is called for open/close
I changed the close service. However in the UI editor I don't see my change.
Switching to yaml and I do see the change. 

![image](https://github.com/Clooos/Bubble-Card/assets/3314249/631e3a92-4eff-4a0e-bf4e-737f9971a163)

**Comment by Clooos** [comment]
Hi and thank you for your feedback!

This was indeed a very old issue, this is now fixed in v2.0.4!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.4
