### ISSUE TITLE
Bars are not filled in according to value

### ISSUE THREAD

**Issue by TimBeekman** [Clooos/Bubble-Card#551]
**Describe the bug**  
Bars are not filled in according to value:
![image](https://github.com/Clooos/Bubble-Card/assets/89469564/07c6ce25-d295-47e6-99be-59d6a8fbdd83)

**To Reproduce**  

**Expected behavior**  
The bars are filled in according to value:
![image](https://github.com/Clooos/Bubble-Card/assets/89469564/74be5a36-f058-40be-8ac9-5d777172eb84)

**Informations (please complete the following information):**  
 - Bubble Card version 2.0.1
 - Home Assistant version 2024.6

**Additional context**  
number domain does not work, input_number domain does work normal

Thank you! 🍻

**Comment by s1mpleman** [comment]
I have this myself, fans are very inconsistent and don't set state either.

**Comment by Clooos** [comment]
Hi, this is because the sliders are currently supporting only lights, covers, media players and input numbers so this is expected.

But I will add more supported entities soon!

**Comment by TimBeekman** [comment]
Closed as this is expected behaviour.

note: Looking forward to the update where this will be supported! :)

**Comment by Clooos** [comment]
Hi! I've added an experimental support for number entities in v2.0.2, can you tell me if it's working correctly?

https://github.com/Clooos/Bubble-Card/releases/tag/v2.0.2

**Comment by s1mpleman** [comment]
Fans are working great. I dunno if I like the slider been filled whilst it's off, maybe that could be a toggle? No dire need was just to mention. 

I tested numbers for you as well and they work fine. Correctly sets the correct number. Toggle doesn't work with it but that was to be expected. Maybe the toggle service call could reset to min/max of the number entity. 

Smashing work!
