### ISSUE TITLE
Bubble popup not extending past/over top bar.

### ISSUE THREAD

**Issue by Andrewpaps** [Clooos/Bubble-Card#558]
It seems that it is now impossible to have the popup extended over the top bar.
I remember this not being the case previously, unless there is a new setting I have missed and apologize if so.
This is great because it allows for slightly more screen real-estate on initial execution of the popup.

To Reproduce:
Create and execute bubble card popup

It seems to occur regardless of card position number in any given view.

Expected behavior:  
Option for popup to extend over top bar.

![image](https://github.com/Clooos/Bubble-Card/assets/71562383/3bd49568-84ac-4540-9034-975add19dfa4)

 - OS: Core on Ras Pi 4
 - Browser: Chrome
 - Bubble Card version: Latest (2.0.1)
 - Home Assistant version: Latest (2024.6.0)

**Comment by Clooos** [comment]
Hi! You can set `margin_top_mobile: -56px` and `margin_top_desktop: -56px` and it will works.

**Comment by Andrewpaps** [comment]
Excellent, that has replicated the desired behavior!

I might perhaps suggest adding this offset as a preset checkbox so other users may know. Or at least adding it to the documentation :)

Thanks again.

**Comment by Clooos** [comment]
This is already mentioned in the documentation 🤓

<img width="859" alt="image" src="https://github.com/Clooos/Bubble-Card/assets/36499953/aa432218-37e1-457e-8352-0a86835c14dd">

And in the editor 😇

<img width="472" alt="image" src="https://github.com/Clooos/Bubble-Card/assets/36499953/e7b7d122-25ac-4ed4-a5fd-0f896e4c4284">

**Comment by Andrewpaps** [comment]
So it is! Too good.
