### ISSUE TITLE
[Feature Request] Add posaibility of show only icon on Horizontal-button-stack

### ISSUE THREAD

**Issue by MartinNygaardSchacht** [Clooos/Bubble-Card#56]
I would really like the option to show only the icon on the horizontal button stack. It will allow for more icons/rooms on the stack, and if Propper icons are chosen, they can describe the button just as good as the name can. :-)

**Comment by Clooos** [comment]
Hi and thanks for the feedback! This is now fixed in the new beta :
https://github.com/Clooos/Bubble-Card/releases/tag/v0.0.1-beta.8

**Comment by MartinNygaardSchacht** [comment]
Wauw - just works. I am amazed!
