### ISSUE TITLE
Bubble theme: Invisible cover position value in "more info"-dialog

### ISSUE THREAD

**Issue by normand198** [Clooos/Bubble-Card#561]
**Describe the bug**  
If you open the "more info"-dialog for any cover and use the slider to change the cover position, the value for new position is not visible. This happens if Bubble theme is set as default theme.

**To Reproduce**  
1. Set Bubble theme as default theme in profile
2. Open the "more info"-dialog of any cover
3. Change cover position by dragging the slider
4. The value is not visible

**Expected behavior**  
Change font color of position value in more-info dialog

**Screenshots**
when Bubble theme is set (value not visible)
<img width="598" alt="bug_dark" src="https://github.com/Clooos/Bubble-Card/assets/79875327/93b744ad-acb5-47da-bb95-e2f5a9b5ba1b">  

when default theme is set (value is visible)
<img width="598" alt="nobug_light" src="https://github.com/Clooos/Bubble-Card/assets/79875327/838b917c-d4dd-4668-906f-5c7b97a4fada">

**Informations (please complete the following information):**  
 - OS: iOS 17.5.1 / macOS 14.5
 - Browser: Safari / Home Assistant app
 - Bubble Card version: 2.0.1
 - Home Assistant version: 2024.5.5

Thank you! 🍻

**Comment by nagtegaal** [comment]
I can reproduce the behaviour and see exact the same thing. It's a theme/bubble-card thing...

**Comment by Clooos** [comment]
Thank you for the feedback guys, I will have to take a look at this but Bubble Card is taking too much of my time 😅
