### ISSUE TITLE
Media Player: missing option for volume up/down

### ISSUE THREAD

**Issue by hanneshier** [Clooos/Bubble-Card#562]
**Describe the bug**  
I have a media player entity that juts support volume up/volume down, but not set volume. So when I use the media player card and want to control the volume via the slider, I get an error message that its not supported.

**To Reproduce**  
1. Have media player without slider volume control
3. Use Bubble Card Media Player
4. Try to edit volume

**Expected behavior**  
Possibility to toggle between slider and volume up/down buttons

**Informations (please complete the following information):**  
 - OS: all OS
 - Browser: all Browser
 - Bubble Card version 2.0.0
 - Home Assistant version: 2024.6

**Additional context**  
Not applicable

Thank you! 🍻

**Comment by Clooos** [comment]
Hi! You can add sub-buttons for that with `tap_action` set to `call-service` and `media_player.volume_up` / `media_player.volume_down`.
