### ISSUE TITLE
Incorrect subview display on devices via the home assistant application.

### ISSUE THREAD

**Issue by Bimb0** [Clooos/Bubble-Card#564]
Incorrect subview display on devices via the home assistant application. Viewing through the web works, but the application lacks a subview, and the slider does not work for scrolling, only on clicking.

Bubble card: `v2.0.1`
HA version:

> Core - `2024.6.1`
> Supervisor - `2024.06.0`
> Operating System - `12.3`
> Frontend - `20240605.0`

Display via the web
![Snímka obrazovky 2024-06-08 o 10 30 42](https://github.com/Clooos/Bubble-Card/assets/116139901/41c45d66-462b-443e-a485-c8f8c90dfd5f)

Display in the application
![867E8ED1-2472-4219-9746-0077A6CEE1F0_1_201_a](https://github.com/Clooos/Bubble-Card/assets/116139901/3d8b684e-889d-4225-807a-95206b56e5a3)

type: custom:layout-card
layout_type: masonry
layout: {}
cards:
  - type: custom:bubble-card
    card_type: separator
    name: Garáž
    icon: ''
    card_layout: normal
    sub_button:
      - entity: sensor.xiaomi_teplomer_garaz_temperature
        show_icon: true
        show_background: false
        show_name: false
        show_state: true
      - entity: sensor.xiaomi_teplomer_garaz_humidity
        show_name: false
        show_state: true
        show_icon: true
        show_background: false
    columns: 1
    rows: 1
  - type: custom:bubble-card
    card_type: button
    entity: switch.sonoff_5v_switch_garazova_brana_5vswitch_garazova_brana
    show_name: false
    show_icon: true
    scrolling_effect: false
    force_icon: true
    show_state: false
    show_last_changed: false
    show_attribute: false
    name: Garážová brána
    sub_button:
      - name: ''
        show_icon: true
        show_background: true
        show_name: true
        show_state: true
        show_attribute: false
        attribute: friendly_name
        entity: binary_sensor.sonoff_contact_sensor_garazova_brana_contact
    styles: ''
  - type: custom:bubble-card
    card_type: button
    button_type: slider
    entity: light.tradfri_driver_10w_umyvadlo_garaz
    name: Svetlo nad umývadlom
    icon: phu:smart-power-strip
    force_icon: false
    show_state: false
    show_last_changed: false
    show_attribute: false
    sub_button:
      - entity: light.tradfri_driver_10w_umyvadlo_garaz
        show_name: false
        show_state: false
        show_last_changed: false
        show_attribute: true
        attribute: brightness
        show_icon: true
        show_background: false
        tap_action:
          action: none
  - square: false
    type: grid
    cards:
      - type: custom:bubble-card
        card_type: button
        styles: |-
          styles: |
            .bubble-icon {
              color: white !important;
            }
        1_link: Kuchyna
        1_name: Kuc
        button_type: switch
        entity: light.sonoff_dualr3_garaz_garaz_v_strede
        sub_button:
          - entity: binary_sensor.sonoff_dualr3_garaz_switch2
            show_name: true
            show_state: false
            icon: mdi:toggle-switch-variant-off
            tap_action:
              action: none
            name: Vypínač
            show_attribute: false
        show_name: true
        show_state: false
        show_icon: true
        scrolling_effect: false
        force_icon: false
        show_last_changed: false
        show_attribute: false
        name: Svetlo v strede
        icon: phu:ceiling-square
        tap_action:
          action: toggle
        double_tap_action:
          action: none
        hold_action:
          action: more-info
        button_action:
          tap_action:
            action: none
          double_tap_action:
            action: none
          hold_action:
            action: none
        card_layout: normal
      - type: custom:bubble-card
        card_type: button
        styles: |-
          styles: |
            .bubble-icon {
              color: white !important;
            }
        1_link: Kuchyna
        1_name: Kuc
        button_type: switch
        entity: light.sonoff_dualr3_garaz_garaz_vzadu
        sub_button:
          - entity: binary_sensor.sonoff_dualr3_garaz_switch1
            show_name: true
            show_state: false
            icon: mdi:toggle-switch-variant-off
            tap_action:
              action: none
            name: Vypínač
            show_attribute: false
        show_name: true
        show_state: false
        show_icon: true
        scrolling_effect: false
        force_icon: false
        show_last_changed: false
        show_attribute: false
        name: Svetlo vzadu
        icon: phu:ceiling-square
        tap_action:
          action: toggle
        double_tap_action:
          action: none
        hold_action:
          action: more-info
        button_action:
          tap_action:
            action: none
          double_tap_action:
            action: none
          hold_action:
            action: none
        card_layout: normal
    columns: 2

**Comment by Clooos** [comment]
Hi, this looks like a cache issue, have you tried to clear it?

**Comment by Bimb0** [comment]
Thanks, it helped, now it works on both iOS and android

**Comment by Clooos** [comment]
You're welcome! 🎉
