### ISSUE TITLE
Cannot close pop-up by navigating to # inside the pop-up

### ISSUE THREAD

**Issue by mrcharlesiv** [Clooos/Bubble-Card#579]
Sometimes, I can close the pop-up by navigating to the #, but in others, it won't work. Is it possible to allow the navigate action to close the pop-up no matter how it's called?

These do not work:

  - type: custom:mushroom-chips-card
    chips:
      - type: template
        tap_action:
          action: navigate
          navigation_path: '#lights'
        icon: mdi:lightbulb-alert
      - type: action
        tap_action:
          action: navigate
          navigation_path: '#lights'
        icon: mdi:arrow-down

This does work:

type: custom:button-card
name: Cancel
show_icon: false
tap_action:
  action: navigate
  navigation_path: '#appletv'

**Comment by Clooos** [comment]
Hi! I've just tried and this is working for me, do you have updated Mushroom to the latest version?

**Comment by Clooos** [comment]
I've just tried and this is working for me in the v2.2.2 (that I haven't released yet, but it works now!).
