### ISSUE TITLE
Sub buttons and sub button configuration options not visible/available on Desktop Chrome

### ISSUE THREAD

**Issue by jnrollins** [Clooos/Bubble-Card#580]
**Description:**
The option to create and configure sub buttons is not available in desktop Chrome version 126.0.6478.62. Sub buttons configured through the mobile app or in a different browser (Firefox) are not visible in desktop Chrome.

**To Reproduce**  
1. Configure a sub button
2. View dashboard with sub button in Chrome browser

**Expected behavior**  
Sub buttons are visible and can be configured.

**Screenshots**  
Chrome:
![chrome](https://github.com/Clooos/Bubble-Card/assets/7774666/e7569db7-c36e-4985-aa4e-0f2e9552efb2)

Firefox:
![firefox](https://github.com/Clooos/Bubble-Card/assets/7774666/04774dc5-aac6-4ff2-a21f-a83e1a22c6d6)
(Mobile app also works.)

Missing config options in Chrome:
![missing config options](https://github.com/Clooos/Bubble-Card/assets/7774666/4f8ef91e-4874-4edd-a2ad-0382dfa9015b)

Available in Firefox:
![available in firefox](https://github.com/Clooos/Bubble-Card/assets/7774666/4cb6ce6f-dc04-4318-9288-999aac391306)

**Information:**  
 - OS: Windows 10
 - Browser Chrome v126.0.6478.62
 - Bubble Card version v2.0.3
 - Home Assistant version 2024.6.1

**Comment by jnrollins** [comment]
Didn't notice that two different versions are showing based on what browser I am using. I suppose that would be the actual issue.

**Comment by Clooos** [comment]
That was a cache issue, it happens sometimes with HACS.
