### ISSUE TITLE
I can't change the background color of button.

### ISSUE THREAD

**Issue by zyi840449** [Clooos/Bubble-Card#581]
When I use the following sample code, the switch background will turn green when turned on; but then immediately change to the system default orange.

type: custom:bubble-card
card_type: button
entity: switch.test
name: Test
styles: |
  .bubble-button-card-container {
    background-color: ${state === 'on' ? 'green' : 'red'} !important;
  }

**Comment by iSalah** [comment]
Same issue.
@zyi840449 did you fix it ?
