### ISSUE TITLE
Slider for Volume of Media Player is not working (Denon AVR)

### ISSUE THREAD

**Issue by benane** [Clooos/Bubble-Card#586]
**Describe the bug**  
With the Slider Card for Media Player (in my case Denon AVR). When I try to move the slider, volume goes down to 0% and stays there. Volume change via the device controll works as ususal

**To Reproduce**  
1. Go to Slider Button for Media Player
2. Click somwhere along the slider bar
3. See error: Volume drops to 0% and slider also represents this value

**Expected behavior**  
Volume should change according to the slider position

**Informations (please complete the following information):**  
 - OS: macOs and iOS
 - Browser Safari and Arc
 - Bubble Card version 2.0.3
 - Home Assistant version 2024.5.5

Thank you! 🍻

**Comment by Clooos** [comment]
Hi! I also have a Denon AVR and I had your issue once and a reboot of Home Assistant or the Denon AVR fixed it (I don't remember which one).

Indeed it was also working with the device control so there is probably something I can do but I haven't had this issue ever since.
 
I will have to take a closer look at this but I hope that this issue will come back, to help me understand what's wrong.

**Comment by KlumzyKlein** [comment]
I have a similar issue but with all media devices. Volume control via a slider will either set volume to 0% or 100%. Volume control works fine in "more-info" page and via Media Player Card. On version 2.0.4

**Comment by KlumzyKlein** [comment]
Is this in the works or do you want me to raise an issue with more specifics of my bug?

**Comment by Clooos** [comment]
I still have to take a closer look at this, I'm able to reproduce it so that's a good start.

**Comment by Shasdo** [comment]
As @KlumzyKlein stsated, I confirm that I have the same problem with Google Cast integration and my different model of Google home.

The slider under 50% sets volume to 0; over 50% to 100%. Using the volume slider in the info menu works fine.

**Comment by KlumzyKlein** [comment]
Issue persists for me in beta 2.10-beta3

**Comment by Clooos** [comment]
Thank you for the feedback, like I said in the other issue, have you tried to clear your cache?

**Comment by Tehral** [comment]
same with sonos on phone and pc

**Comment by Clooos** [comment]
I will take a closer look at this, I was almost sure this was fixed 😅

**Comment by Clooos** [comment]
This issue should be fixed now, can anyone can confirm this?

https://github.com/Clooos/Bubble-Card/releases/tag/v2.1.1

**Comment by KlumzyKlein** [comment]
This is fixed for me in v2.1.1 :)
