### ISSUE TITLE
Can't resize icon in separator

### ISSUE THREAD

**Issue by Sensorn** [Clooos/Bubble-Card#593]
When trying to make the icon bigger in a separator it just movies down on the bubble card, keeping the same size.

Phone OS: Android 14
OS in HA: 12.3
Version of bubble card: 2.0.4

![Screenshot_20240618_225758_Home Assistant](https://github.com/Clooos/Bubble-Card/assets/168321218/2979fcb1-6e89-4e83-af6e-0721508a2681)

**Comment by Clooos** [comment]
Hi!

Indeed this is not working, I've just tried. I will take a look at this.

But here is a workaround:

```yaml
.bubble-icon {
  --mdc-icon-size: 50px !important;
  height: 50px !important;
  width: 50px !important;
}
```

**Comment by Clooos** [comment]
This issue is fixed in the new betas, you can now just add:

```yaml
.bubble-icon {
  --mdc-icon-size: 50px !important;
}
```
