### ISSUE TITLE
Missing: Open voice assistant tap action

### ISSUE THREAD

**Issue by hanneshier** [Clooos/Bubble-Card#595]
**Describe the bug**  
There is no way to open the voice assistant from a bubble card. I would like to add a sub-button for opening the voice assistant, but as far as I know, there is no way for doing that. The guide for [Starting Assist from your dashboard](https://www.home-assistant.io/voice_control/start_assist_from_dashboard/) mentions a dedicated Assist tap-action, but that is not implemented in Bubble-Card

**Expected behavior**  
Add an additional tap action for opening Assist (like e.g. the default button card).

**Informations (please complete the following information):**  
 - OS: all
 - Browser: all
 - Bubble Card version: 2.0.4
 - Home Assistant version 2024.6

Thank you! 🍻

**Comment by Clooos** [comment]
Hi!

Indeed this option is not available in the editor but this is just something I forgot to add. I will add it in the editor for the next release.

In the meantime you can add this in YAML:

```yaml
tap_action:
  action: assist
button_action:
  tap_action:
    action: assist

**Comment by Clooos** [comment]
This is now possible to select this action directly in the editor, thank you again for the feedback!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.1.0-beta.2
