### ISSUE TITLE
Feature request: auto populate name and icon from entity detail

### ISSUE THREAD

**Issue by MartinNygaardSchacht** [Clooos/Bubble-Card#60]
This is a simple one, but can simplify configuration and setup a lot.

Suggestion:
If name and icon are left blank, it will adopt the name and icon of the entity - just lige an official HA card does. 
As soon as user inputs something different, it will of cource overwrite the name and icon from the entity.

Pro-suggestion: 
Could even auto populate the same name to the hash ;-)

These are the setting i would like to be able to leave blank:
![image](https://github.com/Clooos/Bubble-Card/assets/83701734/66c42048-48cd-4d2d-ad49-c1d5ad75a8f2)

And this is the entity settings for light.bedroom, where I suggest it should adopt its details from.

**Comment by Clooos** [comment]
Hi, this is indeed the default behavior for buttons but I've not added that to the pop-ups. I will do that for the next release.

**Comment by Clooos** [comment]
This is now possible in the new beta, see here :
https://github.com/Clooos/Bubble-Card/releases/tag/v0.0.1-beta.9
