### ISSUE TITLE
Sub Buttons wont show up in IOS companion app

### ISSUE THREAD

**Issue by ntallfellow** [Clooos/Bubble-Card#602]
Describe the bug
Sub button on IOS 17 do not show up. Using newest version of bubble-card. 

To Reproduce

Create a separator with a sub button sensor entity
Open your iPhone app running IOS 17

Expected behavior
Sub button to show up

Screenshots
`type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: separator
    name: Notifications
    icon: mdi:bell-badge
    sub_button:
      - icon: mdi:bell-cog-outline
        show_name: false
        show_attribute: false
        tap_action:
          action: navigate
          navigation_path: '#notifications'
        double_tap_action:
          action: navigate
          navigation_path: '#notifications'`

Informations (please complete the following information):

OS: IOS 17
Browser: HA App
Bubble Card version: 2.0.4
Home Assistant version: 2024.6.4

**Comment by Clooos** [comment]
Hi, this is a cache issue, you can go to your Home Assistant settings, then navigate to Companion App > Debug > Clear Frontend Cache (or something similar), then refresh the page or restart the app.
