### ISSUE TITLE
Button slider read-only mode - feature request

### ISSUE THREAD

**Issue by DaveP317** [Clooos/Bubble-Card#604]
(I'm adding this issue so that I can do a pull request to implement the feature myself.)

In my use-cases, I have a dashboard configured with bubble button cards in slider mode, where the sliders indicate the battery charge level or fuel/water tank level. The values are derived from input_number elements, but they should be treated as read-only status reporting. No amount of clicking or dragging the slider will change the actual amount of fuel that's in the tank, etc.

Cloos suggested adding a new button type for this. Fundamentally, it should behave exactly like a slider, but it should ignore click-and-drag operations, and it should provide handling options for taps that are similar to other modes for the buttons/icons/sub-buttons.

**Comment by jb1228** [comment]
You can set the slider percentage via CSS. 

Edit the card, go to "Styling Options" > "Custom Styles", and add this text: 
``` css
.bubble-range-fill {
  transform: translateX(${hass.states['sensor.water_tank_level'].state}%) !important;
}
```
You can use the value from any entity state, attribute, etc. This will also prevent changing it via clicking/dragging, essentially making it read-only. Just remember to add the `!important` property.

**Comment by DaveP317** [comment]
I finally got around to testing this, it's a very interesting idea. It doesn't do the job of making an input_number read-only, but it does allow a regular sensor to be displayed as a slider, which is quite handy.

It also doesn't allow me to set an action when tapping the button (I'd like it to pull up the history graph).

I still think I want to implement something that is a read-only hybrid between a slider and a regular button, but thanks for the clever idea!

**Comment by Just666Me** [comment]
My Home Screen which shows the main information from my shutters is now loaded with BubbleCard Sliders.  Top !!
From time to time it happens, when I scroll on the Home Screen, that I open or close a shutter, as they are in full edit mode.
Would be awesome, if you could implemet this to the slider similar as you offer it with "Tab action", to set it to "no action"

**Comment by barryvdh** [comment]
Thanks for this! I was looking at this also. For my use-cases:
 - Heatpump current fan percentage (slider showing based on the percentage)
 - Heatpump current power output (slider based on the max output)

**Comment by Just666Me** [comment]
After the latest update, I was hopeful that the read-only mode for sliders had been implemented.
Recently, I have tried many different approaches, but the slider either remains editable or is not visible at all, showing only the attribute, such as 40%.

@DaveP317 : as this request was assigned to you, do you think you will implement this in the near future?
Thank you for your support.

**Comment by MrBearPresident** [comment]
@Just666Me Have you seen this #928 ?
Is this able to solve your need?

**Comment by Just666Me** [comment]
Thank you very much @MrBearPresident for your suggestion.
When I integrate my Shutter/cover entity "cover" instead of your "sensor" into your Progressbar, no bar is visible in the "bubble card."
![grafik](https://github.com/user-attachments/assets/86e99afa-ccdb-4c69-bb62-569d34810393)

However, as soon as I replace my cover with a battery sensor, the "bubble card" works, and the bar (e.g., 90%) is visible, properly colored green, and non-interactive.
I suspect that HA displays a card with any cover as interactive.

**Comment by MrBearPresident** [comment]
You would need a custom style like this: 
<sub>(Replace the entities with yours and if the attributes are different don't forget these)</sub>
```
:host{
    --color-ok: #36A1D3AA ;
    --color-bar: var(--color-ok);
    --color-background: var(--bubble-button-main-background-color, var(--bubble-main-background-color, var(--background-color-2, var(--secondary-background-color))));
}

.bubble-button-card-container {
    background: linear-gradient(
  to right, 
  var(--color-bar) 0%, 
  var(--color-bar) ${Math.round(hass.states['cover.test_cover_cover'].attributes.current_position)}%,
  var(--color-background) ${Math.round(hass.states['cover.test_cover_cover'].attributes.current_position)}%,
  var(--color-background) 100%
) !important;
```
![2024-12-12_11-08-35](https://github.com/user-attachments/assets/fb9a835b-d1e5-4fa3-b5aa-d9183ea27c39)

**Comment by DaveP317** [comment]
Hey, unfortunately life changes are preventing me from getting started on
this in the near future. I still have it in my todo list, but it might not
be until January or February.
