### ISSUE TITLE
Sub-button "show state' option greyed out with Name /Text button type

### ISSUE THREAD

**Issue by M1cN** [Clooos/Bubble-Card#606]
When i create the Name / Text button in the sub-button i cannot toggle the show (state / last-changed / attribute) options.

1. Select button type Name / Text
2. Add a sub-button
3. Select sub-button entity
4. Try to toggle show entity state

**Screenshots**  

![image](https://github.com/Clooos/Bubble-Card/assets/7816672/70706c29-a147-4225-81f5-2b09f2961cf7)

![image](https://github.com/Clooos/Bubble-Card/assets/7816672/b4f8e14b-ea3b-48bd-9ec6-efdc63874cf5)

**YAML**  
"When I added 'manual' in the YAML code, it worked! Just found that out while creating this issue.
```

**Comment by Clooos** [comment]
Hi, indeed this is something I need to fix!

**Comment by Clooos** [comment]
This issue is now fixed in the new betas 👌

https://github.com/Clooos/Bubble-Card/releases/tag/v2.1.0-beta.2
