### ISSUE TITLE
Latest Beta (HA 2024.7.0bX) Breaks Pop ups

### ISSUE THREAD

**Issue by s1mpleman** [Clooos/Bubble-Card#607]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
After spinning up the latest beta, they've added a new tab to cards called "Layout". Now none of my pop ups work... 

I've attempted to nuke cache to no avail. 

They're still hiding aha this time

**To Reproduce**  

**Expected behavior**  
Not break my cards after update

**Screenshots**  
Edit Screen:
![image](https://github.com/Clooos/Bubble-Card/assets/5730731/87bd6f04-e0d3-459c-a031-714418a8ab6c)
![image](https://github.com/Clooos/Bubble-Card/assets/5730731/8488e97c-59f0-4058-a097-1a076b51f696)
Opened a pop up
![image](https://github.com/Clooos/Bubble-Card/assets/5730731/b529ef2a-1683-46ac-b283-2741ff77c732)

**YAML**  
If applicable, add any relevant YAML code.

```yaml
Your code here

```

**Informations (please complete the following information):**  
 - OS: [e.g. iOS] Windows, Android
 - Browser/App: [e.g. chrome, safari] Firefox, Chrome, Android Home Assistant
 - Bubble Card version: [e.g. 2.0.4] latest 2.0.4
 - Home Assistant version: [e.g. 2024.6.4] latest 2024.7.0b3

**Additional context**  

Thank you! 🍻

**Comment by jaburges** [comment]
I have the same error on 2024.6.4
Core: 2024.6.4
Supervisor: 2024.06.2
Operating System: 12.4
Frontend: 20240610.1

Screen just applies the opacity, but does show popup
same on mobile

**Comment by Clooos** [comment]
Damn, what did they do this time! 😅

I will take some time to update it and try that.

**Comment by s1mpleman** [comment]
> Damn, what did they do this time! 😅
> 
> I will take some time to update it and try that.
> 
> Edit: This issue is my top priority and I will try to fix it today.
> 
> Edit 2: I've just updated to 2024.7.0b5 and this is working correctly for me, did they fixed it? Can anyone confirm this?

Seems I jumped on this one a bit too soon, yeah confirmed it's back working again woop! Thanks for letting me know!
