### ISSUE TITLE
Pop-up trigger issue

### ISSUE THREAD

**Issue by pgale** [Clooos/Bubble-Card#609]
v2.0.4

I originally started this as a discussion but believe it should be an issue.

Using the pop-up trigger does trigger the pop-up. However, if you somehow navigate away from the popup by closing it or pressing another pop-up button, the sync of the pop-up is then broken. This can then cause a whole load of problems if trying to re-trigger the pop-up via an animation as the pop-up boolean specified is already set as ON. Setting it to ON again obviously doesn't work to show the pop-up again and any animation calling the pop=up doesn't work.

I'm developing an alarm clock animation that relies on showing a pop-up when the alarm is ringing. I can cludge the close button by removing it but I still have the horizontal button stack which allows this behaviour to happen and the pop-up to break. Having thought about this and tried adding work-arounds, I think the most logical option to resolve this is to better link the pop-up to the trigger entity and when a pop-up set with a trigger is closed or navigated away from by using another trigger, the entity should be set to OFF. This would get towards a stateful popup system and better resolve these issues.

I guess this would be best as an option for boolean toggle entities in case someone is using an entity that shouldn't be modified by the pop-up.

**Comment by Clooos** [comment]
Hi, indeed I guess that the best option would be to add the ability to trigger an action when the pop-up is closed/opened.

Something like `open_action:` and `close_action:`.

**Comment by pgale** [comment]
Hi Clooos, yes that would be super flexible and allow for all kinds of other possibilities :) 

Are you able to properly track the close option though if someone navigates away from the dashboard rather than just closing it using the various methods we have now (close button, swipe down or the other navigate options within the dashboard)? Would that cause any issues?

**Comment by Clooos** [comment]
Indeed I will need to try that use case.

Oh and by the way, this is totally unrelated but I followed a GitHub guide for my ThinkSmart View and I realized it was from you! Small world 😁 Thanks a lot for that, it was really clear and well done!

![IMG_20240629_155059](https://github.com/Clooos/Bubble-Card/assets/36499953/0c10f69b-b50c-4553-8871-1c1cdb6da31f)

**Comment by pgale** [comment]
Great, I look forward to that option. It'll complete the design of my alarm clock on two of my ThinkSmart Views :)

Glad you got on with the flashing guide, they are great devices. A few small niggles here and there but all have been manageable. I've got seven now and that's where I stop! 🤣 I know someone else bought 12 of them for all locations around his house. Great for showing pop-ups for cameras and key events. Really brings HA to life. 

Bubble card is at the heart of my dashboards and works great for organising all the extra controls and detail I need. The TSV just needs a bit more memory I think. The pop-ups work better on Lineage 15.1 but are still a little slow. But that's a downside of this device. Still can't grumble at the absolutely amazing value though! 😁

**Comment by Clooos** [comment]
Indeed I had some issues with the pop-ups in some cases and I'm not sure that I will be able to optimize these even more (even if I will probably try again 🤓).

For now I've replaced the dashboard from the photo to a new view just for that room and it's probably even better to use it like this.

**Comment by Clooos** [comment]
I've just found a massive memory leak in the sub-buttons, this was slowing down the pop-ups a lot! It's now working perfectly on the ThinkSmart View!

**Comment by pgale** [comment]
Oooh, fabulous. Are you releasing a beta?

**Comment by Clooos** [comment]
I'm fixing some other issues then I will 🙂

**Comment by pgale** [comment]
New beta is definitely smoother when animating on the pop-ups :)

**Comment by Clooos** [comment]
Hell yeah! And I can't be happier about that!

By the way, I will probably add the new pop-up open/close actions in this v2.1 beta.

**Comment by pgale** [comment]
Great - that will be fabulous :)

**Comment by Clooos** [comment]
I've just added this feature and that works even when you navigate to an other view!

This allows to use any of the HA actions directly, I still need to add this part in the editor.

I can now confirm that this feature will be available in v2.1.0-beta.2 🥳

**Comment by pgale** [comment]
That sounds fab. Looking forward to trying it.

**Comment by Clooos** [comment]
Done! 🎉

https://github.com/Clooos/Bubble-Card/releases/tag/v2.1.0-beta.2

**Comment by pgale** [comment]
Excellent thanks. The new beta has loads of juicy new stuff :)
