### ISSUE TITLE
What layout view is used in the example screenshots?

### ISSUE THREAD

**Issue by dopeytree** [Clooos/Bubble-Card#61]
I dont understand which layout view is used to achieve a similar look to the examples.

If I use something like mason how do you get the separators to cross between the 2 stacks?

Thanks

**Comment by Clooos** [comment]
Hi! This was indeed something that was missing in the documentation, you can now find it here:

https://github.com/Clooos/Bubble-Card#full-example

**Comment by dopeytree** [comment]
Ace thanks 😀
