### ISSUE TITLE
Pop-up Broken when including Auto-Entities card since last update (v2.0.4)

### ISSUE THREAD

**Issue by marcportlock77** [Clooos/Bubble-Card#610]
Since updating to Bubble Card v2.0.4 a few days ago, any pop-up card which included as part of it's vertical stack an Custom:Auto-Entities Card, when triggered will blur the background but fails to actually show the pop-up itself.

I use pop-ups heavily throughout my dashboard and they all work fine, except now for those that contain an auto entities card. It also was working fine before the update.

**Comment by Clooos** [comment]
Hi, this is probably a cache issue, sometimes after an update it's better to clear it because the HA cache is not always correct.

**Comment by marcportlock77** [comment]
yes am running the latest updates. Core: 2024.6.4 Supervisor: 2024.06.2 Operating System: 12.4 Front lend: 20240610.1

**Comment by Clooos** [comment]
Thank you for the details, one more question but do you have tried to revert to a previous version and is this working? If yes what is the last working version?

**Comment by marcportlock77** [comment]
Must have been related to update 2024.6.4 as I’ve just updated to 2024.7 and it’s working fine again now.

**Comment by Clooos** [comment]
Great! Glad that it's working again!
