### ISSUE TITLE
v2.1.0-beta.1 issue in preview panel with input_select button

### ISSUE THREAD

**Issue by pgale** [Clooos/Bubble-Card#613]
**Describe the bug**  
When in the editor and after having added a bubble card select button, if testing in the preview panel, after selecting an entry in the list, it closes the editor without saving and loses any modifications in that session.

**Screenshots**  

https://github.com/Clooos/Bubble-Card/assets/513044/d4f9b6cc-66c5-439e-b61e-263f217b173e

**Informations (please complete the following information):**  
 - OS: Windows 11
 - Browser/App: Firefox
 - Bubble Card version: 2.1.0-beta.1
 - Home Assistant version: 2024.6.4

**Comment by Clooos** [comment]
This is now fixed on my side, thank you for the feedback!

**Comment by pgale** [comment]
Thanks. Just adding more bubble card buttons to dashboards. I'll raise more if I come across anything.

**Comment by Clooos** [comment]
This is now fixed 👌

https://github.com/Clooos/Bubble-Card/releases/tag/v2.1.0-beta.2

**Comment by pgale** [comment]
Fab!
