### ISSUE TITLE
Visual Editor appears to be broken on Home Assistant frontend 2024.7.3

### ISSUE THREAD

**Issue by KlumzyKlein** [Clooos/Bubble-Card#618]
Visual Editor appears broken since the HA 2024.7.3 update today. 
Regardless of whether viewing GUI or YAML, the preview is cropped.

![image](https://github.com/Clooos/Bubble-Card/assets/100074802/9e3fff4a-ede9-4f75-827f-e7221d878a79)

**Comment by Clooos** [comment]
I'm already on it, you can try the v2.1.0-beta.1.

https://github.com/Clooos/Bubble-Card/releases/tag/v2.1.0-beta.1

**Comment by KlumzyKlein** [comment]
Hi @Clooos, 

Thank you for the quick response and also the quick action on this.

v2.1.0-beta.1 fixed the issue for the most part, but still a bit off:

Cards seem to overlap in Sections:
![image](https://github.com/Clooos/Bubble-Card/assets/100074802/4a67f3b6-dab9-4377-a572-3f4c3bb22461)

First card in Vertical Stack appears to now overlap the top of the pop-up:
![image](https://github.com/Clooos/Bubble-Card/assets/100074802/888e5351-20c2-45a8-8936-ec0a5cfbde4a)

P.S. Congratulations on becoming a father!

**Comment by Clooos** [comment]
This is because of your custom styles, the one that removes the header. But I will add the ability to remove it in a clean way 👌

**Comment by Arthoxer** [comment]
Hi Clooos,

i have the same problem. Also with the new beta:

![image](https://github.com/Clooos/Bubble-Card/assets/142784080/106f510e-9d26-4f5d-a7e8-d1d374bd4276)

**Comment by KlumzyKlein** [comment]
> This is because of your custom styles, the one that removes the header. But I will add the ability to remove it in a clean way 👌

Good shout, forgot about that, I'm using this style to remove the header:
```
.pop-up > :first-child 
{ display: none !important; }
```

The majority of my pop-ups have this button image at the top in the same layout, so for now I have worked around it for now by adding a 10% margin-top padding to the card:
```
    card_mod:
      style: |
        img { 
          width: 100%!important; 
          height: 100%!important; 
          padding: 0px!important;
        }
        ha-card{
          margin-top: 10%!important;      
          }
```

**Comment by KlumzyKlein** [comment]
> Hi Clooos,
> 
> i have the same problem. Also with the new beta:
> 
> ![image](https://private-user-images.githubusercontent.com/142784080/346267156-106f510e-9d26-4f5d-a7e8-d1d374bd4276.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNjY4MDQsIm5iZiI6MTcyMDI2NjUwNCwicGF0aCI6Ii8xNDI3ODQwODAvMzQ2MjY3MTU2LTEwNmY1MTBlLTlkMjYtNGY1ZC1hN2U4LWQxZDM3NGJkNDI3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNlQxMTQ4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjY5ZGFiNmFmNzBiMTQ1OGNkY2M5NDg5MDk4NmVmYTJmZDMzN2JmMmZmOGMwNzY4OWZhNDgxNTM0YzI1NmQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s9z49iWaFfF1K0BafpXMMWuGsNcitytG7oqwl47kODw)

Are you using a Sections View? I just checked and I get the same issue for a Masonary View, but Sections View works fine. 

I believe the integration recommends Sections anyways.

**Comment by Clooos** [comment]
I'm on it, I will release a new beta really soon!

**Comment by Clooos** [comment]
This is now fixed in the latest beta 👌

https://github.com/Clooos/Bubble-Card/releases/tag/v2.1.0-beta.2

**Comment by KlumzyKlein** [comment]
This has done the job, amazing work, thanks again.
