### ISSUE TITLE
Nested Popups broken

### ISSUE THREAD

**Issue by Blueion76** [Clooos/Bubble-Card#619]
Nested popups seem to be broken on 2024.7.0 - If I trigger a nested popup the background just blurs and no cards load. 

Tested on iPhone mobile app and Chrome on Mac.

**Comment by Clooos** [comment]
Hi, can you provide the requested informations? Like your YAML, screenshot... Because I'm not sure to understand what you mean by "nested pop-up".

**Comment by Blueion76** [comment]
> Hi, can you provide the requested informations? Like your YAML, screenshot... Because I'm not sure to understand what you mean by "nested pop-up".

No problem, I'll get you that in a little bit. Issue seems to be a duplicate of an older issue (#99)

Here's a screenshot until I can get you that YAML.![image](https://github.com/Clooos/Bubble-Card/assets/128919662/9a539959-7722-410e-8589-6562c3681a69)

For context, I have a popup for each room in my areas view then I have a popup inside of that room popup for tv remote / Alexa / etc. - the screenshot is after I press on the "nested" popup.

**Comment by Blueion76** [comment]
I seemed to fix the issue by putting all my nested popups on the main page my primary popups are on. Closing this.

**Comment by Clooos** [comment]
Glad to ear that! This is indeed the recommended way 👌
