### ISSUE TITLE
Feature request: behaviour of clicking a horizontal button stack to close a pop-up card

### ISSUE THREAD

**Issue by moostmartijn** [Clooos/Bubble-Card#62]
I just created a quick mobile dashboard with these Bubble cards and I absolutely love it! Except for this one simple thing;

Everytime I want to close a pop-up card after opening it by clicking the horizontal button stack, I'm clicking the button again and expect it to close the pop-up card, but it does not. The only way is to click the X in the upper right corner. 

If possible, can you change the behaviour of the horizontal button to close a pop-up card when it's open, after clicking on the desired button again? That would be a great change! 

Thanks in advance.

**Comment by MrSaiclops** [comment]
+1 to this. I'm not sure how, but this principle is so engrained in me that I reflexively clicked the button again in an attempt to close the stack. I think it would go a long way for making the interface intuitive.

**Comment by Clooos** [comment]
Hi and thanks for your feedback! This now a default feature in the new v1.0.1:
https://github.com/Clooos/Bubble-Card/releases/tag/v1.0.1
