### ISSUE TITLE
How to create multiples states for background-colors ?

### ISSUE THREAD

**Issue by Plop** [Clooos/Bubble-Card#623]
Hi,

I'm trying to set multiples possibilities for the background-color of a custom bubble-card and a button.

Using ```styles: |
  .bubble-button-background {
    opacity: 1 ;
    background-color: ${state === 'nul' ? 'red' : 'green' }; ;
  }```, how could I add two or more state conditions ?

Thanks

**Comment by arthanoss** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_operator#conditional_chains

```js
function example() {
  return condition1 ? value1
    : condition2 ? value2
    : condition3 ? value3
    : value4;
}
```
e.g.
```js
${(state === "cool") ? "blue" : (state === "heat") ? "red" : "gray"}
```

**Comment by Plop** [comment]
Thanks a lot !
