### ISSUE TITLE
Minor: Background around pop-up does not adjust to iOS system theme (dark/light mode)

### ISSUE THREAD

**Issue by Nazze** [Clooos/Bubble-Card#627]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
When iOS changes from dark to light (or from light to dark) mode, the dashboard requires a refresh. Otherwise the background remains in old mode. See Screenshots.

**To Reproduce**  
1. iOS is in dark mode
2. Open a pop-up
3. See the background around the pop-up is dark
4. iOS changes to light mode
5. The background around the pop-up is still dark
6. Refresh the dashboard
7. The background around the pop-up is light now

**Expected behavior**  
The background around a pop-up should adjust to the system mode

**Screenshots**  
Before refresh (wrong)
![Before refresh](https://github.com/Clooos/Bubble-Card/assets/33813707/8333c569-1209-4212-b9af-b7b5d7f3cf7e)

After refresh (right)
![After refresh](https://github.com/Clooos/Bubble-Card/assets/33813707/b59bc848-376a-4d97-bf2d-60da7ba8abf5)

**YAML**  
If applicable, add any relevant YAML code.

```yaml
Your code here
```

**Informations (please complete the following information):**  
 - OS: iOS 17.5.1
 - Browser/App: HA Companion app 2024.6
 - Bubble Card version: 2.1.0-beta 1
 - Home Assistant version: 2024.6.4

**Additional context**  

Thank you! 🍻

**Comment by Clooos** [comment]
Hi again, this is a really old issue that I'm aware of, I will need to work on it indeed 😅

**Comment by Nazze** [comment]
No worries, I think it is not super urgent 😇😁

**Comment by Clooos** [comment]
Hi, this is issue is now finally fixed!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.2.3
