### ISSUE TITLE
"Error in generating button custom templates" spamming console error.

### ISSUE THREAD

**Issue by nkkfs** [Clooos/Bubble-Card#628]
**Describe the bug**  
When using Bubble Card I saw that in console there is constantly repeating error sounds like:
"Error in generating button custom templates: TypeError: Cannot read properties of undefined (reading 'attributes')"
more context below 
https://pastebin.com/Zxz1wdHm

**Informations (please complete the following information):**  
 - OS: [e.g. iOS] Windows 11 23H2 
 - Browser/App: [e.g. chrome, safari] Brave
 - Bubble Card version: [e.g. 2.0.4] exist on 2.0.4 and 2.1.0beta2.
 - Home Assistant version: [e.g. 2024.6.4] 2024.7.0

**Additional context**  
Could I have messed something up or failed to add some value and that's why I get such a recurring (and spamming the console) error?

Thank you! 🍻

**Comment by Clooos** [comment]
Hi! Indeed like the error says this is because of one of your custom template inside of a button, your entity might be unavailable.

If you don't find how to fix it, you can share it and I will try to help you.

**Comment by nkkfs** [comment]
Yeah, I'm so sorry. That was my mistake, some I've didn't change some template in button about weather...
