### ISSUE TITLE
Select Card not refreshing when input_select updated elsewhere

### ISSUE THREAD

**Issue by KlumzyKlein** [Clooos/Bubble-Card#631]
When selecting an option on a Select Card (including as a Sub Button), it remembers that selection.
If I update the input_select entity from another card or via an automation / script, then this change is not reflected on the Select Card.

E.g.  
The example below are mushroom and bubble select cards mapped to the same input_select entity:

Defaulted input_select to "Pink"
![image](https://github.com/Clooos/Bubble-Card/assets/100074802/b4843fea-64c0-4fe3-963f-06acb96c5fe4)

Set input_select via the Bubble Card to "Nightlight" - works fine, both update
![image](https://github.com/Clooos/Bubble-Card/assets/100074802/06341ea4-7c02-4085-a948-6974d4215e47)

Set input_select via the Mushroom Card to "Dim Red" - only mushroom updates, Bubble retains it's previous value. 
![image](https://github.com/Clooos/Bubble-Card/assets/100074802/423f1fc4-10df-4aa8-8334-27f13549ce0d)

**Comment by Clooos** [comment]
Thank you for the feedback, I will take a look at this!

**Comment by Clooos** [comment]
This issue is now fixed in the new betas 🥳

**Comment by KlumzyKlein** [comment]
Sorry just re-tested this one, also not fixed in beta 3. Tested with Select Card and Sub-Card. The Cards do update when I do a page refresh, but not before that.

**Comment by Clooos** [comment]
I've just released the v2.1.0-beta.4 🙂

**Comment by KlumzyKlein** [comment]
> I've just released the v2.1.0-beta.4 🙂

Ahh sweet, give me a bit and will do some testing.

**Comment by Clooos** [comment]
Oh sorry I've just realized that it was not fixed indeed 😅

**Comment by KlumzyKlein** [comment]
> Oh sorry I've just realized that it was not fixed indeed 😅

Can confirm, still an issue on beta 4

**Comment by Clooos** [comment]
I've just fixed it correctly this time, just waiting a bit for more feedbacks then I will probably release it as a stable release this time 🤞

**Comment by Clooos** [comment]
This is now fixed in the latest release!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.1.0

**Comment by KlumzyKlein** [comment]
Can confirm, fixed in 2.1.0 :)
