### ISSUE TITLE
Feature request: popup not need for name, icon, entity...

### ISSUE THREAD

**Issue by nelsonamen** [Clooos/Bubble-Card#64]
The popup with ONLY close option 
Thanks

**Comment by tempus2016** [comment]
You can use styles to hide this.  Enter any name for the name and icon boxes then add this to your style
```
    styles: |
      #header-container > div { 
        display: none !important; 
        }
      ha-card {
      float: right !important;
      }
```
<img width="1353" alt="Screenshot 2023-09-25 at 19 57 59" src="https://github.com/Clooos/Bubble-Card/assets/40920327/10b4789d-7207-4c43-9b81-731bd4d3f7fa">
<img width="1353" alt="Screenshot 2023-09-25 at 19 58 13" src="https://github.com/Clooos/Bubble-Card/assets/40920327/ccc4d27a-7d93-4a1d-b39d-40340f803e5d">

**Comment by Clooos** [comment]
This will be a native feature in the next release, but I'm working on a massive update and it's taking a bit more time than usual.

**Comment by Clooos** [comment]
This is now possible in the new beta, see here :
https://github.com/Clooos/Bubble-Card/releases/tag/v0.0.1-beta.9
