### ISSUE TITLE
popups not centered in kiosk mode

### ISSUE THREAD

**Issue by Paga777** [Clooos/Bubble-Card#640]
popup windows appear off-center in kiosk mode. all work fine in normal mode.
is there a way to solve this problem?
Thank you

**Comment by pgale** [comment]
You need to give significantly more info.

I'm running kiosk mode in Fully Kiosk Browser and with header and side bar disabled and all is fine.

**Comment by Clooos** [comment]
Just update kiosk mode, this is a known issue that is now fixed.

**Comment by Paga777** [comment]
hi,
this is an example of a popup in  normal mode on my pc
![2](https://github.com/Clooos/Bubble-Card/assets/114150669/c613a5b3-5909-4299-b4ed-aa031829361b)


and how it appears on a wall-mount monitor in kiosk mode
![IMG_4193](https://github.com/Clooos/Bubble-Card/assets/114150669/f160c025-9286-4dc2-b998-2d7138cfb13c)

any idea?

ps. kiosk mode is  already updated to 6.0.1

**Comment by Clooos** [comment]
Have you cleared the cache of the app that is running on your tablet?

**Comment by Paga777** [comment]
I cleared the chrome cache and now it works. you are my new idol.
Thank you

**Comment by Clooos** [comment]
You're welcome! 😁
