### ISSUE TITLE
Suggestion: Please add input select

### ISSUE THREAD

**Issue by pdwonline** [Clooos/Bubble-Card#642]
Love the bubble card! but could not get it integrating with a input select. Would it be possible to add a dropdown menu from a sub button based on an input_select entity?

**Comment by Clooos** [comment]
Hi, this is already coming, you can already try the beta if you want. Here are the changelog:

https://github.com/Clooos/Bubble-Card/releases/tag/v2.1.0-beta.1

https://github.com/Clooos/Bubble-Card/releases/tag/v2.1.0-beta.2

**Comment by pdwonline** [comment]
Great! Tnx!
