### ISSUE TITLE
Little vertical scrollbars on bubble-card on Safari Browser Mac (v2.1.0-beta.2)

### ISSUE THREAD

**Issue by tm8** [Clooos/Bubble-Card#644]
Hello,

In the Safari browser on the Mac, you can see a small vertical scrollbar on the left-hand side. In the dashboard, as well as e.g. in the header of a popup.

The problem persists even if I reset all customisations. Bubble-Card has already been reinstalled without success.

Software alles auf dem neusten Stand, Bubble-Card v2.1.0-beta.2

See screenshots.
Chrome
![chrome-1](https://github.com/Clooos/Bubble-Card/assets/5777801/ad6d4bc0-b6ef-4714-b1b7-a77b158d33c7)
![chrome-2](https://github.com/Clooos/Bubble-Card/assets/5777801/25beabc2-4920-48e6-847e-27bdaf5ce61b)

Safari

![safari-1](https://github.com/Clooos/Bubble-Card/assets/5777801/35562e49-bc94-44f9-b557-4fede4efbf97)
![safari-2](https://github.com/Clooos/Bubble-Card/assets/5777801/f4807372-32d9-4140-ba35-fce1c0523c28)

**Comment by Clooos** [comment]
This is now fixed in the latest release!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.1.0
