### ISSUE TITLE
Icon Tap Action not working with Media Card and Select Sub Button

### ISSUE THREAD

**Issue by schmierlappe** [Clooos/Bubble-Card#653]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  

**To Reproduce**  
When you have a select button in a media bubble card the tap action on icon is not working anymore

**Expected behavior**  
Popup should work

**Screenshots**  

I‘m on phone. Can provide code later if needed

**YAML**  
If applicable, add any relevant YAML code.

```yaml
Your code here
```

**Informations (please complete the following information):**  
 - OS: iOS, Browser
 - Browser/App: Chrome
 - Bubble Card version: latest beta
 - Home Assistant version: Latest

**Additional context**  

Thank you! 🍻

**Comment by Clooos** [comment]
Hi and thank you for the feedback! I've just fixed this issue, this fix will be available in the next release.

**Comment by Clooos** [comment]
This is now fixed in the latest release!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.1.0

**Comment by schmierlappe** [comment]
can confirm that is working now. Thx amazing custom-card
