### ISSUE TITLE
Bug unexpected token v2.1.0

### ISSUE THREAD

**Issue by Theandone90** [Clooos/Bubble-Card#656]
Hello,

Sibc ethe update in v2.1.0, i have had token and CSS errors.
And the pop-ups no longer work.
They no longer open

![image](https://github.com/user-attachments/assets/09833c13-f7d2-4573-aaad-aaf291d12ca5)

**Comment by Clooos** [comment]
Hi, can you take a look at your browser console? Then can you send me the errors you have?

**Comment by Theandone90** [comment]
The white rectangle is my domain.

![image](https://github.com/user-attachments/assets/4d23c3f5-9153-4e52-bc23-1d8bb2a41ccb)

**Comment by Clooos** [comment]
Thank you, can you send me the YAML of these cards?

**Comment by Theandone90** [comment]
Yes, but my card hasn't changed since i upgrated v2.1.0

type: custom:bubble-card
card_type: button
button_type: state
entity: person.alice
button_action:
  hold_action:
    action: none
  double_tap_action:
    action: none
  tap_action:
    action: none
hold_action:
  action: none
double_tap_action:
  action: none
tap_action:
  action: more-info
show_attribute: false
attribute: editable
show_last_changed: true
force_icon: false
sub_button:
  - entity: sensor.iphone_alice_battery_level
    tap_action:
      action: none
    show_attribute: false
    attribute: device_class
    icon: ''
    show_name: false
    show_state: true
    show_last_changed: false
    show_icon: true
    show_background: false
  - entity: sensor.iphone_alice_connection_type
    tap_action:
      action: none
    show_background: false
    show_name: false
    show_state: false
    show_attribute: true
    attribute: Cellular Technology
styles: |-
  .icon-without-state {
    --mdc-icon-size: 20px;
  }

  .bubble-button-background {
    background: ${hass.states['device_tracker.iphone_alice'].state === 'home' ? '#4CAF50' : '#CE3818'} !important;
  }

  .bubble-sub-button-1 {
    color: ${hass.states['sensor.iphone_alice_battery_level'].state <= '020' ? '#CE3818' : 'none'} !important;
  }

  .bubble-sub-button-1, .bubble-sub-button-2 {
    font-weight: bold;
  }
card_layout: large

**Comment by Clooos** [comment]
Hi, do you still have this issue?
