### ISSUE TITLE
Sub-button timer countdown not updating (static)

### ISSUE THREAD

**Issue by DrNRG** [Clooos/Bubble-Card#657]
Bug:
If I add timer for a state button with attribute "remaining", the timer value is reflected on change of the timer, but there is no countdown/update.

I have noticed the same issue with HA cards. Entity does not do countdown vs Entities which does. Not sure if this is a change in HA? I noticed there was a post in May on this topic, but I am not sure if this is a new issue, hence a new bug report

Bubblecard 2.1 (but 2.04 had same issue)

HA Core
2024.7.2

Supervisor
2024.06.2

Operating System
12.4

Frontend
20240710.0

Thanks for a great card mod and congrats on your fatherhood!!

Example code where timer.climate does not update once activated.

**type: custom:bubble-card
card_type: button
button_type: state
entity: timer.climate
show_icon: true
show_name: false
show_attribute: true
attribute: remaining
force_icon: true
show_state: false
show_last_changed: false
**

**Comment by MrBearPresident** [comment]
This is actually HA's fault. 
If you check in developers tools -> state -> specific timer.
Then you can see the "remaining" attribute doesn't update. 

See #937 for an example of how it is possible.

**Comment by MrBearPresident** [comment]
Duplicatie of #511
Closing this so you can follow progress(none for the moment) on that issue.

See #937 for the workaround
