### ISSUE TITLE
failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.

### ISSUE THREAD

**Issue by tcarroll177** [Clooos/Bubble-Card#658]
Recently updated the bubble card and now I have the issue: failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.

The bubbles will not show on my main screen anymore, just this error.  See images below. Any suggestions?

<img width="475" alt="Screenshot 2024-07-16 at 10 20 42 AM" src="https://github.com/user-attachments/assets/beb9e18b-d45f-499f-9544-ab76672a7af5">

<img width="998" alt="Screenshot 2024-07-16 at 10 21 00 AM" src="https://github.com/user-attachments/assets/c8be9baa-d8c2-48b4-ad25-54799dd7c20a">

**Comment by Clooos** [comment]
Hi, do you still have this issue in the latest release?
