### ISSUE TITLE
[v2.1.0] Templates in Header of popup do not work

### ISSUE THREAD

**Issue by amstermk** [Clooos/Bubble-Card#664]
I want to change icon and or sub-button icon under certain conditions in the header of a popup. I’m using the following code for the icon:

`${icon.setAttribute("icon", hass.states['switch.fritz_box_6591_cable_kdg_wi_fi_clamargast'].state === 'on' ? 'mdi:wifi' : 'mdi:wifi-off')} `

When I include this code in the “Custom Styles / Templates” section of the header of the popup then save and then try to call up the popup nothing happens. The popup stays hidden or better does not appear. When removing the code the popup works again as it should.

This template used to work in the versions before v2.1.0.

Informations:
- IOS
- app
- Bubble Card version: 2.1.0
- Home Assistant version: 2024.7.3

**Comment by Clooos** [comment]
Hi! Can you check in your browser console if you have any error?

**Comment by Clooos** [comment]
Hi again, I've just tried and it seems that this issue is now fixed in the new betas, can you confirm this?

**Comment by amstermk** [comment]
Hi, yes It’s working again! Thanks!
