### ISSUE TITLE
Pop-up Header Overlapping UI in Dashboard Edit Mode

### ISSUE THREAD

**Issue by NdR91** [Clooos/Bubble-Card#666]
**Describe the bug**  
In the dashboard edit mode, the header of the pop-up window overlaps with the Home Assistant UI, obstructing the proper functioning of the editor menu. This issue makes it difficult to use the menu options effectively.

**To Reproduce**  
1. Edit the Dashboard
2. Place a popup card in the right corner of the screen
3. Click on the three dots-menù

**Expected behavior**  
The pop-up header should not overlap with the UI, allowing unobstructed access to the editor menu.

**Screenshots**  
![image](https://github.com/user-attachments/assets/60055a0c-c4b7-4611-80e6-7544d6814934)

**Informations (please complete the following information):**  
 - OS: MacOS Sonoma (14.5)
 - Browser/App: Safari
 - Bubble Card version: 2.1.0
 - Home Assistant version: 2024.7.3

Thank you for looking into this issue 🍻

**Comment by Clooos** [comment]
Hi and thank you for your feedback, this issue will be fixed in the next release!

**Comment by Clooos** [comment]
This issue is now fixed!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.2.0
