### ISSUE TITLE
Vertical scrollbars on bubble-card on Safari Browser Mac (v2.1.0) [Reopen #644]

### ISSUE THREAD

**Issue by mari0k** [Clooos/Bubble-Card#670]
Hey, 
just wanted to let you know that issue #644 is not resolved in latest version. At least not on my end.

**Describe the bug**  
Horizontal and vertical scrollbars on `button` and `pop-up` cards. 
Only on desktop version of Safari. Mobile is fine.

**Expected behavior**  
no scrollbars.

**Screenshots**  
See #644 

**Informations (please complete the following information):**  
 - OS: macOS
 - Browser/App: Safari
 - Bubble Card version: 2.1.0
 - Home Assistant version: 2024.7.3

**Additional context**  
I suspect these lines introduced 3 weeks ago with commit [611a14c](https://github.com/Clooos/Bubble-Card/commit/611a14cd42f29273d3263e4cacd1ec02c4b8ab53) to cause the issue: 
https://github.com/Clooos/Bubble-Card/blob/d01567fb01c9db36294e8d1f438267896f3c3ae2/src/cards/button/styles.ts#L20-L23

Especially the first of those lines. When changing overflow to `hidden` or disabling that style in developer console, the scrollbars disappear and card renders as expected.

Also please note that `scrollbar-width: none;` is not supported on Safari and thus has no effect, see https://caniuse.com/mdn-css_properties_scrollbar-width_none

**Comment by nayzm** [comment]
Can confirm, having the same issue here. 

```
Safari: 18.0 (20619.1.22.11.3)
macOS: 15.0 Beta 4 (24A5298h)
HA: 2024.7.3
Bubble Card: 2.1.0
```

**Comment by Clooos** [comment]
Hi guys and thank you for the feedback, I had to change some CSS styles for the new select sub-button and I can confirm that I'm able to reproduce this issue on Safari as well.

This will be fixed in v2.1.1 🙂

**Comment by Clooos** [comment]
This is now fixed!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.1.1

**Comment by mari0k** [comment]
That is great news. I can confirm that scrollbars are gone in the latest release v2.1.1. Thank you so much for the quick fix. 

And congratulations on becoming a dad. Wishing you all the joy and wonder in this new chapter of your life. Enjoy every moment!

**Comment by Clooos** [comment]
Thank you! 😊
