### ISSUE TITLE
Issue when/Support for Nesting Collapsable Cards within a PopUp

### ISSUE THREAD

**Issue by akeslo** [Clooos/Bubble-Card#672]
**Describe the bug**  
Pop-up does not display when there is a card of type: custom:collapsable-cards

https://github.com/RossMcMillan92/lovelace-collapsable-cards

**To Reproduce**  

Nest above card within a popup.  The popup will work on save but if you refresh the UI the popup never shows up but the background becomes blurred.  I see the following error in the web browser console: _Unchecked runtime.lastError: The message port closed before a response was received._

**Expected behavior**  
Popup should open every time without issue. 

Below works after save but not on reload:
<img width="531" alt="image" src="https://github.com/user-attachments/assets/421f3bdb-cefb-4476-a7a1-a6b6a5073fd0">

**Screenshots**  
<img width="1481" alt="image" src="https://github.com/user-attachments/assets/f408434f-796d-41df-92f9-80b70d2559e6">

**YAML**  
`type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#Utility'
    hide_backdrop: true
    name: Utility
    show_header: false
    background_update: false
  - type: custom:bubble-card
    card_type: separator
    name: Utility
    icon: mdi:heating-coil
  - type: custom:bubble-card
    card_type: button
    entity: light.ceiling_entryway
    name: ''
    show_state: true
    show_last_changed: false
    show_attribute: false
    sub_button: []
    button_type: slider
  - type: custom:bubble-card
    card_type: button
    entity: group.utilityroom
    name: Utility Room - Ceiling
    show_state: true
    show_last_changed: false
    show_attribute: false
    sub_button: []
    button_type: switch
  - type: custom:collapsable-cards
    title: Automated
    buttonStyle: 'background-color: black; font-weight: bold; color: white'
    cards:
      - type: entities
        entities:
          - entity: switch.outside_entryway
          - entity: switch.tp_link_switch_powerstrip
          - entity: switch.dream_machine_powerstrip
          - entity: switch.modem_powerstrip
          - entity: switch.home_assistant_powerstrip
          - entity: switch.lutron_powerstrip
          - entity: switch.casaos_powerstrip
          - entity: switch.flood_switch_always_on
        show_header_toggle: false
`

**Informations (please complete the following information):**  
 - OS: Mac OS
 - Browser/App: Chrome
 - Bubble Card version: 2.1.0
 - Home Assistant version: 2024.7.3

Thank you! 🍻

**Comment by Clooos** [comment]
Hi and thank you for the feedback. Have you tried with `background_update: true`?

**Comment by akeslo** [comment]
> Hi and thank you for the feedback. Have you tried with `background_update: true`?

Yes I have

**Comment by Clooos** [comment]
I don't know what I can do then, there is probably a compatibility issue with that card. 

You should open an issue on this card's GitHub.

**Comment by akeslo** [comment]
Ok thanks for taking a look. I found a good alt in expander-card so all is working fine now.
