### ISSUE TITLE
Icon and name disabling in pop-up header doesnt work

### ISSUE THREAD

**Issue by nkkfs** [Clooos/Bubble-Card#676]
**Describe the bug**  
When changing features in header section of pop-up card, option "Optional - Show icon" and "Optional - Show name" doesn't work.
**To Reproduce**  
1. Add pop-up card.
2. Navigate to header settings.
3. Choose any button type.
4. Give it any name.
5. Try to disable "Show name" and "Show icon".

**Expected behavior**  
It just should enable and disable name of pop-up header name/icon.

**Screenshots**  
https://imgur.com/iJoQIPn

**Informations (please complete the following information):**  
 - OS: doesn't matter
 - Browser/App: Firefox
 - Bubble Card version: 2.1.1
 - Home Assistant version: 2024.7.4

Thank you! 🍻

**Comment by Clooos** [comment]
Hi! I'm already aware of this issue, this will be fixed in the next release 🙂

**Comment by Clooos** [comment]
This issue is now fixed, I forgot to mention it.
