### ISSUE TITLE
"Unknown" Attribute State when light is at 0% or off

### ISSUE THREAD

**Issue by cOOnStar** [Clooos/Bubble-Card#677]
Hi,

i may have found a bug. I integrated Philips Hue into HA and used it with the bubble card and the slider.

As an optional attribute I have additionally displayed the brightness, and when the light is off, unknown appears and not 0% or off as the state

![SmartSelect_20240731_104202_Home Assistant](https://github.com/user-attachments/assets/f771ae92-49ef-48c5-b7b9-8cc93c3a80fd)

![Screenshot_20240731_104833_Home Assistant](https://github.com/user-attachments/assets/b97226d2-58ef-41d7-8d59-6c8d076170e5)

Best regards

Calvin

**Comment by cOOnStar** [comment]
Informations:

Bubble Card version: 2.1.1
Home Assistant version: 

Core: 2024.7.4
Supervisor: 2024.06.2
Operating System: 12.4
Frontend: 20240710.0

**Comment by Clooos** [comment]
Hi and thank you for the feedback, I will fix that in the next release 🙂
