### ISSUE TITLE
CSS coding vanishes

### ISSUE THREAD

**Issue by TheShai1** [Clooos/Bubble-Card#678]
Put in the work to get multiple bubble cards just the way i want them and without doing anything, the CSS coding just vanishes. Followed the github on styling them and it worked and then just gone. For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  

**To Reproduce**  

**Expected behavior**  

**Screenshots**  

**YAML**  
If applicable, add any relevant YAML code.

```yaml
Your code here
```

**Informations (please complete the following information):**  
 - Browser/App: [e.g. chrome, safari]
 - Bubble Card version: [e.g. 2.0.4]
 - Home Assistant version: [e.g. 2024.6.4]

**Additional context**  

Thank you! 🍻

**Comment by Clooos** [comment]
Hi, can you please provide more details by editing your issue? If I don't know how to reproduce this it will be difficult for me to fix that.

**Comment by Clooos** [comment]
I see that you use card_mod, take a look at the documentation, in the styling section I explain how to do custom styles.

**Comment by TheShai1** [comment]
I tried it and it didn't change anything using the .bubble-card-container and others; but I'll try again.

**Comment by Clooos** [comment]
First remove `card_mod:` then you will have to replace your Jinja templates with JS templates, I've provided many examples in the doc.
