### ISSUE TITLE
Spacing between rows is to big (bigger than the examples)

### ISSUE THREAD

**Issue by pdwonline** [Clooos/Bubble-Card#680]
too much space between the rows make the car a bit clumbsy. See my card below:

<img width="275" alt="afbeelding" src="https://github.com/user-attachments/assets/640b40fa-0227-4faf-a955-dcd16370a52f">

However, The example shows a much smaller row space:
<img width="193" alt="afbeelding" src="https://github.com/user-attachments/assets/47ba78cd-9672-4035-9eaf-69ad91395f87">

**Comment by Clooos** [comment]
Hi, you need to change your cards layout to `large`, you can do that in the editor.
