### ISSUE TITLE
Card backgrount not visible in dark mode.

### ISSUE THREAD

**Issue by pdwonline** [Clooos/Bubble-Card#681]
I am using dark mode. Unlike the example, the backround color is not visible. Here is my card:

<img width="338" alt="afbeelding" src="https://github.com/user-attachments/assets/a44a8a01-4149-49fe-a61d-f6881add6739">

versus the example: 
<img width="193" alt="afbeelding" src="https://github.com/user-attachments/assets/0e3b7f74-a2a1-45b9-bb05-a32a3704f15f">

**Comment by Clooos** [comment]
What background? Your screenshot seems normal.

**Comment by Clooos** [comment]
If you want that color you can try my own theme, here it is:

https://github.com/Clooos/Bubble
