### ISSUE TITLE
Style for button in horizontal buttons stack not applying

### ISSUE THREAD

**Issue by CZonin** [Clooos/Bubble-Card#683]
**Describe the bug**  
When applying a style to a button in a horizontal buttons stack, the changes do not take effect.

**Expected behavior**  
Styling will be applied to the desired button.

**Screenshots**  
![Screenshot 2024-08-04 210402](https://github.com/user-attachments/assets/bb785eb8-fcdf-4e96-b709-dd35653ce8c0)

**YAML**  
```
type: custom:bubble-card
card_type: horizontal-buttons-stack
1_link: '#vacuum'
1_name: Vacuum
1_icon: mdi:robot-vacuum
styles: |2-
  .vacuum > .color-background {
    background-color: blue !important;
  }
```

**Informations (please complete the following information):**  
 - OS: Android, Windows
 - Browser/App: Official app, Chrome
 - Bubble Card version: 2.1.1
 - Home Assistant version: 2024.7.4

**Comment by madkatz01** [comment]
Also having the same issue, any fix?
