### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by DrSpaldo** [Clooos/Bubble-Card#7]
Any chance of a brief instruction sheet?

The first time the visual editor worked, now it doesn't, so I am not sure what to put in for the config

**Comment by labaland** [comment]
I would love one too!!

**Comment by brpeterso** [comment]
This would be great. Would love to see some examples to see what's available outside of the GUI options, if available.

**Comment by Clooos** [comment]
It will come, I had to fix the first issues, I will work on that today. But everything in available in the GUI, no hidden settings.

**Comment by Clooos** [comment]
It's done! Take a look at it and if something is unclear don't hesitate to open a new issue.

**Comment by DrSpaldo** [comment]
> It's done! Take a look at it and if something is unclear don't hesitate to open a new issue.

Nice, thanks
