### ISSUE TITLE
pop-up opening only after clicking anywhere else

### ISSUE THREAD

**Issue by tinkerberlin** [Clooos/Bubble-Card#70]
Hi there - yes, this is pretty much exactly the same issue that was reported in #41 . 

However, for me the setup is:
- clickable area in an HA Floorplan card (e.g. the area enclosing the kitchen).
-  click on that area opens a pop-up that includes some controls for that specific room. (e.g. spotify)

The URL updates immediantly when I click on the defined area. However, the pop-up only opens after I then also click anywhere that isn't otherwise clickable.  

Also:
- closing through clicking outside the pop-up card does not work.
- closing through hitting ESC only works when then clicking on non-clickable areas outside the card (reverse of the main issue re: opening the pop-up).

Let me know if you'd like to see any specific code / example implementation. 

Thank you!

**Comment by Clooos** [comment]
This should be fixed in the new beta :
https://github.com/Clooos/Bubble-Card/releases/tag/v0.0.1-beta.9

Please report back if it's working.
