### ISSUE TITLE
Light slider and secondary input select

### ISSUE THREAD

**Issue by hadeshimself** [Clooos/Bubble-Card#702]
If I create a light slider and include my scenes input select it's moving the slider when I click on the drop box.

![Screenshot 2024-08-12 at 16 39 49](https://github.com/user-attachments/assets/4549eca7-76db-4288-b0a2-bb61f98f45a2)

**Comment by Clooos** [comment]
Thank you for the feedback, I will take a look at that!

**Comment by Clooos** [comment]
This issue is now fixed!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.2.1
