### ISSUE TITLE
Bubble backdrop hides when closing an overlapping popup.

### ISSUE THREAD

**Issue by EarthEclipse** [Clooos/Bubble-Card#703]
**Bug description** 
If there exists a popup which contains a trigger that displays another popup, if the user navigates back (such that the 2nd popup is closed, and the 1st popup is visible), when the 2nd popup closes, the backdrop is hidden although there is still one popup displayed.

**To Reproduce**  
1. Create:
-  two popups: #A and #B
- a button on the dashboard that navigates to #A
- a button inside #A that navigates to #B
2. Click the button on the dashboard
3. Click the button from inside #A
4. Navigate back (browser back)
5. See error

**Expected behavior**  
The backdrop should remain visible as long as there's a popup being displayed.

**Screenshots**  
1. First popup open:
 ![1](https://github.com/user-attachments/assets/70f97f6d-8bd7-441e-a48c-88477e5172cc)
2. 2nd popup open:
 ![2](https://github.com/user-attachments/assets/95760edf-3535-4a11-82e8-609ad4c19adf)
3. After back press:
 ![3](https://github.com/user-attachments/assets/ce8cb7c5-12d8-4d6e-bdc2-a4bdfecceb9f)

**Informations**  
 - Browser/App: Google Chrome, Electron app, Android Home Assistant app
 - Bubble Card version: 2.2.0
 - Home Assistant version: 2024.7.3

Thank you! 🍻

**Comment by Clooos** [comment]
Hi and thank your for the feedback!

This issue should be now fixed!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.2.1

**Comment by LedLeoHA** [comment]
> Hi and thank your for the perfectly detailed feedback!
> 
> This issue should be now fixed!
> 
> https://github.com/Clooos/Bubble-Card/releases/tag/v2.2.1

Hey! It seems like this exact issue is now a lot more noticable after updating to 2.2.1 on mobile devices. About 70% of the time popups don't appear and only instead blur the background. It happens even more often if the actions are done rapidly.
Attaching the video recording of this issue

https://github.com/user-attachments/assets/a7934353-20a3-474d-b1ec-61ac32a881dd

**Comment by Clooos** [comment]
Wow, I was not expecting that 😅 I'm on it!

**Comment by Clooos** [comment]
I'm praying 🙏 

https://github.com/Clooos/Bubble-Card/releases/tag/v2.2.2

**Comment by EarthEclipse** [comment]
Uf, now the first popup is not displayed anymore when navigating back . :(
(I used the first popup to display the living room, and the second popup to display the remote from that tv; when hitting back I would return to the living room popup)

**Comment by LedLeoHA** [comment]
> Wow, I was not expecting that 😅 I'm on it!

Just informing - Tested after the update, and update seems to have fixed it. It's a bit slower than on 2.2.1. (By slower i mean there is a micro-stutter sometimes when it pops up), But it's 100% now working
