### ISSUE TITLE
V. 2.2.0 - Subbutton with select-entity - Tap on subbutton opens menu and in addition does tap action of main icon

### ISSUE THREAD

**Issue by amstermk** [Clooos/Bubble-Card#704]
When you have a select entity in a sub-button and tap on it to open the menu it will not only open the menu but in addition also perform the tap action of the main icon.

Following code to reproduce:

![IMG_0214](https://github.com/user-attachments/assets/e0b66a96-39ae-4233-88b7-dcafbff82bd4)

**Comment by Clooos** [comment]
Hi! Indeed I've made a mistake in the v2.2.0. This issue is already fixed on my side, just wait for the next release 🙂

**Comment by Clooos** [comment]
This issue is now fixed!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.2.1
