### ISSUE TITLE
bubble card closing after closing browser mod popup on top.

### ISSUE THREAD

**Issue by liamwibo** [Clooos/Bubble-Card#706]
**Describe the bug**  
Hi first of all sorry for opening 2 issues in a row but i have been very active in designing my mobile dashboard lately and bubble card is a big part of my dashboard so thats why i have been discorvering these issues a lot more. That being said the bug is a bug with a custom component "browser mod" so if you don't address issues with custom components you can just close this issue. The bug is if you open a popup with browser mod on top of a bubble card popup and then close the browser mod popup the bubble also close with it.

**To Reproduce**  
1: create a bubble card popup with a button card or any card that can act as a button like custom button card.
2: in the button add a tap action  with action: fire-dom-event.
3: configure your popup to whatever you want 
4: click the button with the tap action you created and the popup should appear on top
5:  close the browser mod popup card and the bubble popup card should close with it

**Expected behavior**  
If i close the browser mod popup card by clicking below or above or on the x browser mod popup that the bubble card popup stays open after the browser mod popup is closed

**Screenshots**  
![beforepng](https://github.com/user-attachments/assets/9307353e-f45c-42c7-ae26-b3be200dd0ce)
this is when the browser popup card is open and you can see the bubble card behind it.

![after](https://github.com/user-attachments/assets/37dfcb6c-e106-4ac2-a446-19a1d8bc79f8)
and this is after i pressed the x on the browser popup card and the bubble card also closed.

**YAML**  

```yaml
very long yaml for the whole button card but specific parts can be provided if needed.
```

**Informations**  
 - OS: does this on every platform
 - Browser/App: firefox
 - Bubble Card version: 2.2.0 latest
 - Home Assistant version: 2024.8.1

**Comment by Clooos** [comment]
Hi, you can just turn off this feature in your pop-up settings, tell me if works for you.

![Screenshot_2024-08-13-12-21-07-698_io homeassistant companion android~2](https://github.com/user-attachments/assets/9458d3e5-5cd5-4e73-9c65-b2ea5c83626c)

**Comment by liamwibo** [comment]
thx that fixed the issue
