### ISSUE TITLE
Sub button click on slider moves the slider value

### ISSUE THREAD

**Issue by alex-phillips** [Clooos/Bubble-Card#707]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
When you have a slider type button and have sub buttons in it, clicking the sub button also bubbles up the event to the slider and changes its value.

**To Reproduce**  
1. Create a new button with type slider
2. Add a sub button
3. Click on the sub button

**Expected behavior**  
Clicking a sub button performs the sub button action and does not move the slider.

Thank you! 🍻

**Comment by Clooos** [comment]
Hi and thank you for the feedback, you are the fourth to open this issue 😅

But I'm already on it, I will release a new version really soon!

**Comment by alex-phillips** [comment]
Ah, sorry. I should have searched first. I'll close this issue if there are other's existing.

Loving the project, great work!

**Comment by Clooos** [comment]
This issue is now fixed!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.2.1
