### ISSUE TITLE
Incompatibility with Kiosk Mode

### ISSUE THREAD

**Issue by pspfreak** [Clooos/Bubble-Card#71]
When paired with Kiosk Mode, you are unable to edit bubble cards, even if you add ?disable_km to the URL. The header returns, and you can enable edit mode, however the popup bubble cards all show as blank. The only way to actually edit the card is to go into the raw configuration editor and disable kiosk mode from there.

**Comment by tinkerberlin** [comment]
Not a developer, but can you expand: I am using the pop-up cards with kiosk and they work just fine (apart from some shenanigans around not opening immediantly...)

**Comment by adrienvsj** [comment]
@Clooos I can confirm that I have the same incompatibility problem with https://github.com/NemesisRE/kiosk-mode
Normally, I can see all my cards with the following settings: http://homeassistant.local/accueil-mobile/home?edit=1&disable_km
But with vertical card and bubble card pop-ups I get the following result:
![image](https://github.com/Clooos/Bubble-Card/assets/12349073/a2bb6010-b573-46da-b88e-cfc3a36344d8)

If I remove the disable_km parameter from my url and keep only edit=1, I get the right result:
![image](https://github.com/Clooos/Bubble-Card/assets/12349073/67c96abe-c1af-4188-ab53-9cb38d3acc6d)

**Comment by Clooos** [comment]
Thanks for your feedbacks! This is now fixed in v1.0.0!
