### ISSUE TITLE
Silder ignores climate entity temperature step

### ISSUE THREAD

**Issue by lichenophile** [Clooos/Bubble-Card#715]
**Describe the bug**  
Generic climate entities have a attribute determining the step/resolution. Mine is configured to 0.5c steps, however the slider allows for selecting 0.1c increments/decrements. (this might effect climate entities other than generic climate, I don't have any to test)

**To Reproduce**  
Steps to reproduce the behaviour:
1. create a button card slider
2. ad a generic climate entity with a target temp step greater than 0.1c
3. try the slider
4. observer that 0.1c adjustments are possible

**Expected behaviour**  
In my case, I expect to to rise by 0.5c increments. Alternatively, being able to configure the increment step for the card specifically (overriding the entities attribute setting) would be very handy.

Bubble Card v2.2.1
Core 2024.8.1
Supervisor 2024.08.0
Operating System 13.0
Frontend 20240809.0

**Comment by Clooos** [comment]
Hi, this issue is now fixed! Thank you for the feedback!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.2.2
