### ISSUE TITLE
"Show name" option does not work if "Text scrolling effect" is off

### ISSUE THREAD

**Issue by apfffr** [Clooos/Bubble-Card#718]
**Describe the bug**  
"Show name" option does not work if "Text scrolling effect" is off

**To Reproduce**  
1. Card type button (switch, slider)
2. Go to Button settings
3. Enter something in "Optional - Name"
4. Set "Text scrolling effect" to off
5. Switch "Show name"-Setting
6. Nothing will happen, name still shown
7. Set "Text scrolling effect" to on
8. Switch "Show name"-Setting
9. Name will show/hide as expected

**Expected behavior**  
Show/hide name can be set no matter is text scrolling is active or not

**Informations (please complete the following information):**  
 - OS: Windows 10
 - Browser/App: Chrome
 - Bubble Cardv2.2.1
 - Home Assistant version:
  - Core 2024.8.1
  - Supervisor 2024.08.0
  - Operating System 12.4
  - Frontend 20240809.0

Thank you! 🍻

**Comment by Clooos** [comment]
Damn, I was sure that it was fixed, I will take a look!

**Comment by nagtegaal** [comment]
The "Show name" toggle isn't working at all...

**Comment by Clooos** [comment]
Hi again, this issue will be fixed in the next release 👌

**Comment by bakman2** [comment]
Is there any update available ?

I want to be able to hide the name, in case of a 'button' one could then actually make a horizontal stack with the normal bubble button which looks nicer than the horizontal  stack option, which has a different/inconsistent styling compared to the rest of the options.

eg:

<img width="283" alt="image" src="https://github.com/user-attachments/assets/94d400d5-5d87-40dc-98e1-ca1f2623a1d9">

eg. if name is hidden, then they should be equally aligned.
