### ISSUE TITLE
Pop up window not covering elements with high z-index

### ISSUE THREAD

**Issue by tigers75** [Clooos/Bubble-Card#723]
**Describe the bug**  
When calling a pop up window some of the underling icons still show in front of the pop-up.
I have a picture entity that has elements with z-index defined, and sometimes they show up in front of the pop-up:
This happens with elements with a z-index of 5, i found out it varies with the zoom or with the operating system/browser used.
Changing the z-index to 1 seems to fix it, at least with any reasonable zooming in.

**To Reproduce**  
1. Create a picture elements card with some icons with a z-index of 5
2. Call a bubbles pop-up
3. [zoom in on certain browsers]

**Expected behavior**  
The pop up should stay in front on anything else

**Screenshots**  

![1](https://github.com/user-attachments/assets/1eb411f6-ceee-4f90-aced-082c573f6e6b)
This is with normal (100% zoom on Chrome, 4K resolution screen): there are icons blurred as it should be (in the bottom left corner of the image)

![2](https://github.com/user-attachments/assets/dbde32ca-3308-4ffd-9f36-f9036f406650)
This happens when zooming in in the same setup as above: some icons pierce thru the pop-up and show up in front of everything.
The same thing happens without the need to zoom on the iOS app (standard HA app, iPAD pro). Everything is fine on Android official app on S23 Ultra

**Additional context**  
The icons are still fully functional: I can click on it and the tap_action get executed, this can be annoying if they are in front of a button in the pop-up.

Thank you! 🍻

**Comment by Clooos** [comment]
Hi and thank you for the feedback, does it happens when your pop-ups are placed after all your other cards?

**Comment by tigers75** [comment]
Yes, as per instructions the vertical-stacks with the popups are after all the other cards.
No other particular option is selected, this is the YAML of the pop-up card:
`type: custom:bubble-card
card_type: pop-up
hash: '#antifurto-casa'
show_header: true
scrolling_effect: false
show_name: false
show_icon: true
icon: mdi:alarm-light
name: Antifurto casa`

Just notice that setting z-index to 1 fixed this for me, in fact I have no need to keep the z-index that high I just gave myself some space for the future. I think it's a quite specific user case.

**Comment by Clooos** [comment]
In that case this is expected, the pop-ups have a z-index of 5 as well, higher z-index cover some default HA elements like the more info panel and I can't change that for that reason.

I will close this because there is nothing that I can do without breaking essential features.
