### ISSUE TITLE
"Edit entity card" is empty

### ISSUE THREAD

**Issue by kris-tant** [Clooos/Bubble-Card#726]
I have been joyfully using bubble cards in my dashboard (Dwains Dashboard) in home assistant. I aways could easily change the standard card to bubble cards and configure it to my needs.
Since s month (or so), I get an empty "Edit entity card" (see below) when changing my standard card, and also when reconfiguring my active bubble cards. I have the same issue for different browsers and my entire system is up-to-date. 

![image](https://github.com/user-attachments/assets/b23b3c0b-eeae-4f95-adca-d91f3c23afc4)

Any suggestions or solutions?    
Thank you! 🍻

**Comment by Clooos** [comment]
Hi, I really don't know what is happening here. Can you take a look at your browser console to see if there is any error related to Bubble Card?

**Comment by kris-tant** [comment]
I tried every browser, on my computer, on my mobile, and even in de HA app. The Edit entity card is always empty. To illustrate the issue, I made a recording from my HA app (both trying to add a bubble card and to edit an existing one). I'd love to get this solved because I like the bubble cards very much.
https://github.com/user-attachments/assets/c59beceb-3baf-4311-b6f0-ddd02b31a238

**Comment by Clooos** [comment]
I understand your problem, but can you take a look at your browser console (this is where the logs are) like I said? If you don't know how, take a look on Google, this is the best way for me to know what is happening here.

**Comment by kris-tant** [comment]
OK, I have never used this before. I don't know which info is useful. Here I provide you a screenshot (I need to figure out how to copy this) 
![image](https://github.com/user-attachments/assets/56b6070e-2b6a-4d2f-8b82-dfadb0f80fb5)

**Comment by Clooos** [comment]
Almost, I need the console part now.

**Comment by kris-tant** [comment]
OK, in the console, I see a lot of red. I don't know how I can copy efficiently, so I continue with screenshots. I don't think that everything is related to bubble cards. I thought my dashboard was well-built ;)
![image](https://github.com/user-attachments/assets/3b254f2a-eb8a-479c-a08c-05e67288997b)
...
![image](https://github.com/user-attachments/assets/2ec8cbce-0b46-4021-829a-37c2cbcf0bb0)

**Comment by Clooos** [comment]
Perfect thank you! Like I thought it's because you are using the Dwains dashboard, the required component to display the editor is missing in it.

A solution would be to edit your cards without it then adding them in YAML on your dashboard.

**Comment by kris-tant** [comment]
But how come it worked before in Dwains dashboard (DD)? I added the bubble cards in DD about a year go, and the UI showed me all the options. The workaround (which I have to find out/try) seems less convenient, and I believe DD is rather popular.

**Comment by Clooos** [comment]
Interesting, I will take a look a look at that.

**Comment by kris-tant** [comment]
Great. I noticed a typo - I inserted the bubble cards in DD without problems about HALF year ago. Therefore I was surprised that it not work anymore a few weeks ago.

**Comment by Clooos** [comment]
The last release was 2 weeks ago and my last comment too. To be honest this issue is not my priority right now, I have many other issues 😅
