### ISSUE TITLE
Background cover until bottom of screen

### ISSUE THREAD

**Issue by pdwonline** [Clooos/Bubble-Card#729]
See this screenshot:

<img width="361" alt="afbeelding" src="https://github.com/user-attachments/assets/70b1c8b8-bfe6-4fbf-8b95-48dbd8e88fa2">

The background is stretched until the bottom of the screen. No special css tweaks applied

**Comment by Clooos** [comment]
Hi, this is expected, but you can change the size of your pop-up with these settings in the editor.

<img width="474" alt="image" src="https://github.com/user-attachments/assets/669535b1-28a4-421b-be87-41bd3fb9ca4d">

This is in `Styling options` > `Pop-up styling`.
