### ISSUE TITLE
Entity Details in Pop-Up does also close the Pop-Up when closing the detailed Entity

### ISSUE THREAD

**Issue by mzwanzi** [Clooos/Bubble-Card#731]
**Describe the bug**  
If i click on a entity inside a Pop-Up and it opens for example a history graph and i close the history graph, the whole Pop-Up is closing - this just happens on desktops, on my mobile phone the Pop-Up is still open after closing the history graph.

**To Reproduce**  
1. Go to 'entity inside PopUp'
2. Close the History Graph
4. Pop-Up is also closing

**Expected behavior**  
After closing a detailed Graph or anything else within a Pop-Up card, the Pop-Up should still be opened.

**YAML**  
If applicable, add any relevant YAML code.

```
- type: custom:bubble-card
    card_type: pop-up
    hash: '#office'
    name: Office
    icon: mdi:desk
    show_icon: true
    scrolling_effect: true
    show_state: false
    bg_color: var(--primary-background-color)
    styles: |
      .bubble-button-background {
        background: var(--card-background-color);
      },
      .bubble-close-button {
        background: var(--card-background-color);
      }
    sub_button:
      - entity: sensor.shellyplusht_office_temperature
        show_state: true
        show_icon: false
        show_background: false
        show_last_changed: false
        show_attribute: true
```

**Informations (please complete the following information):**  
 - OS: MacOS
 - Browser/App: tested on Brave and Firefox
 - Bubble Card version: since 2.2.2 (2.2.1 works on any browsers)
 - Home Assistant version: 2024.8.2

Thank you! 🍻

**Comment by Clooos** [comment]
Hi, you can disable this to fix this issue on that pop-up.

![image](https://github.com/user-attachments/assets/7aa1f4f1-c094-4495-8a6c-57b2205877e3)

**Comment by mzwanzi** [comment]
Hi,

yes this works, but now of course its no longer possible to close Pop-Ups by clicking outside.

so that's a bit struggle for me, loved to handle it in both ways 😄

**Comment by Clooos** [comment]
You're right, the issue here is that I have to add an exception for each panels that are open from a pop-up, but I will add that one as well.

**Comment by mzwanzi** [comment]
Thank you very much!! really love your cards - great work!! 🍻

**Comment by Clooos** [comment]
This issue should be fully fixed now 🤞

https://github.com/Clooos/Bubble-Card/releases/tag/v2.2.4

**Comment by cerahmed** [comment]
Came here to discuss the exact same issue on the latest Bubble Card release.
@Clooos - would you mind taking a look? The more-info and specifically more usable confirmation dialog now close the pop up. I wish this could be fixed.

I will look into fixing it using card mod z-index as a workaround for now if that could work.
