### ISSUE TITLE
Allow sensor info

### ISSUE THREAD

**Issue by wb5xo** [Clooos/Bubble-Card#74]
Enhancement to allow bubbles to display sensor info and not just toggle switches. 

![image](https://github.com/Clooos/Bubble-Card/assets/106778974/0d4b151f-3057-4db9-be7d-38c82d45cc16)

**Comment by Clooos** [comment]
This is now possible in the new beta, see here :
https://github.com/Clooos/Bubble-Card/releases/tag/v0.0.1-beta.9
