### ISSUE TITLE
Hitting escape on desktop does not close popup

### ISSUE THREAD

**Issue by wookash** [Clooos/Bubble-Card#742]
Hitting escape on desktop does not close popup if the popup is triggered from the mushroom-chips-card or mushroom-person-card and mushroom-template-card

**To Reproduce**  
1. Go to your dahsborad
2. Click on any of the mushroom cards I mentioned
3. Click on the card to open popup
4. Try closing popup by hitting escape

**Expected behavior**  
Popup closes

**Informations (please complete the following information):**  
 - OS: macOS
 - Browser/App: brave
 - Bubble Card version: 2.2.3
 - Home Assistant version: 2024.8.2

**Additional context**  
Not sure if it's only related to these cards, other cards, including bubble cards (e.g. switch, etc.) seem to work as expected

Thank you! 🍻

**Comment by Clooos** [comment]
Hi, indeed I've removed that feature by mistake! I will fix that in the next release

**Comment by Clooos** [comment]
In fact this issue was a bit different than what I thought but it should be now fixed!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.2.4

**Comment by wookash** [comment]
It works beautifully  - just checked 2.2.4. Thank you for a quick fix! closing this bug
