### ISSUE TITLE
Card Layout "Large" - different sizes for Button & Select

### ISSUE THREAD

**Issue by mptr8956** [Clooos/Bubble-Card#743]
When changing the Styling Option for A Button and a Select Card to "Large" the Select card is way too big. See screenshot:

![image](https://github.com/user-attachments/assets/1bb19cdf-c702-4c56-b5a2-e6f8ab166930)

**Comment by Clooos** [comment]
Hi, it seems that I forgot to adapt this one. Thank you for the feedback!

**Comment by Clooos** [comment]
This issue is now fixed! Thanks again!

https://github.com/Clooos/Bubble-Card/releases/tag/v2.2.4
