### ISSUE TITLE
attribute and last-changed are'nt separated if show_state=false

### ISSUE THREAD

**Issue by mrgrlscz** [Clooos/Bubble-Card#757]
Here, everything is OK
![image](https://github.com/user-attachments/assets/9d649a1c-122f-4438-b6ff-f1ced3e1aea3)
But when i set show_state to false:
![image](https://github.com/user-attachments/assets/e605c3cd-1b04-4e6a-8955-7efdfb252792)
You can see that there's no separator between attribute (3) and last changed (il y a 22mn) values.

**Comment by Clooos** [comment]
Hi and thank you for the feedback! I will fix that in the next release 👌
