### ISSUE TITLE
Add styling to horizontal-button-stack

### ISSUE THREAD

**Issue by dnestico** [Clooos/Bubble-Card#76]
Hi I see you added new styling but not sure how to use it for the horizontal-button-stack. I'd just like to add a grey color when the light is off so that way the background isn't just blank/empty.

```
type: custom:bubble-card
card_type: horizontal-buttons-stack
1_name: Davids Room
1_icon: hue:downstairs
1_entity: light.basement_lights
1_link: '#basement'
2_name: V/E Room
2_icon: hue:upstairs
2_link: '#vallyesther'
2_entity: light.vally_esthers_room
3_icon: mdi:music
3_link: '#media'
4_icon: mdi:weather-partly-cloudy
4_link: '#weather'
5_icon: mdi:home-automation
5_link: '#automation'
6_icon: mdi:account-cog
6_link: /profile
style: |
  ha-card {
    margin-bottom: 65px !important;
  .horizontal-buttons-stack::before {
    display: none !important;
  }
```

<img width="492" alt="Screenshot 2023-09-28 at 5 11 41 PM" src="https://github.com/Clooos/Bubble-Card/assets/3034555/c31c63ce-ee00-43f1-b8bb-0f0492cda42f">

**Comment by Clooos** [comment]
Hi and thanks again for your feedbacks! In the new v1.0.1 you can now select the class of each buttons, like `.vallyesther` in your custom style:
https://github.com/Clooos/Bubble-Card/releases/tag/v1.0.1

**Comment by dnestico** [comment]
Not sure why this isn't working:

<img width="496" alt="Screenshot 2023-10-06 at 4 45 17 PM" src="https://github.com/Clooos/Bubble-Card/assets/3034555/43019c68-b6c9-4543-89ab-7d83bac8cd07">


```
type: custom:bubble-card
card_type: horizontal-buttons-stack
1_name: Davids Room
1_icon: hue:downstairs
1_entity: light.basement_lights
1_link: '#basement'
2_name: V/E Room
2_icon: hue:upstairs
2_link: '#vallyesther'
2_entity: light.vally_esthers_room
3_icon: mdi:music
3_link: '#media'
4_icon: mdi:weather-partly-cloudy
4_link: '#weather'
5_icon: mdi:home-automation
5_link: '#automation'
6_icon: mdi:account-cog
6_link: /profile
style: |
  ha-card {
    margin-bottom: 65px !important;
  .horizontal-buttons-stack::before {
    display: none !important;
  }
  .basement {
    background-color: ${state === 'off' ? 'darkblue'} !important;
  }
  .vallyesther {
    background-color: ${state === 'off' ? 'pink'} !important;
  }
```

**Comment by Clooos** [comment]
You forgot a } at ha-card.

**Comment by dnestico** [comment]
It doesn't seem to agree unfortunately...  code has been working fine "style" this whole time but changing it to "styles" and adding the "}" breaks it..

<img width="580" alt="Screenshot 2023-10-06 at 11 11 45 PM" src="https://github.com/Clooos/Bubble-Card/assets/3034555/e72ad9ce-e1b8-40e6-8d8f-35f930942de1">


```
type: custom:bubble-card
card_type: horizontal-buttons-stack
1_name: Davids Room
1_icon: hue:downstairs
1_entity: light.basement_lights
1_link: '#basement'
2_name: V/E Room
2_icon: hue:upstairs
2_link: '#vallyesther'
2_entity: light.vally_esthers_room
3_icon: mdi:music
3_link: '#media'
4_icon: mdi:weather-partly-cloudy
4_link: '#weather'
5_icon: mdi:home-automation
5_link: '#automation'
6_icon: mdi:account-cog
6_link: /profile
styles: |
  ha-card {
    margin-bottom: 65px !important;
  }
  .horizontal-buttons-stack::before {
    display: none !important;
  }
  .basement {
    background-color: ${state === 'off' ? 'darkblue'} !important;
  }
  .vallyesther {
    background-color: ${state === 'off' ? 'pink'} !important;
  }
```

**Comment by Clooos** [comment]
This is weird, you must have an integration that conflicts and breaks it, but I can confirm that it's `styles` like in my documentation to have the JS templates, `style` is for card-mod, this is why it's partially working without the "s". 

If you find what the conflict was can you reply back so I can document that?

**Comment by dnestico** [comment]
Oh I was hoping to just do one condition because I only want the fixed color when the light is off, when the light is on I want it to be the normal same color as the light in the room and not fixed, I guess that's not gonna work with JS templates like card_mod, unless maybe there is a variable I can use that will make it follow the light color when on, just like button_card has a light variable?

**Comment by Clooos** [comment]
In that case, this should work :
```yaml
background-color: ${hass.states['light.cuisine'].state === 'off' ? 'darkblue' : ''} !important;

**Comment by dnestico** [comment]
Confirmed! This works, thanks.

<img width="583" alt="Screenshot 2023-10-07 at 1 27 24 PM" src="https://github.com/Clooos/Bubble-Card/assets/3034555/0704227f-1e70-4cb7-a893-3fa966668dc6">

**Comment by Clooos** [comment]
You're welcome! 😀

**Comment by Golfhuisje** [comment]
Thank you so much! This helpt me a lot. I to have now the buttons with the style and love it!

So for the buttons I have added this code under styles (I have used the same example):
ha-card {
    margin-bottom: 65px !important;
  }
  .horizontal-buttons-stack::before {
    display: none !important;
  }
  .basement {
    babackground-color: ${hass.states['light.cuisine'].state === 'off' ? 'darkblue' : ''} !important;
  }

But once I create a bubble card, for example, to switch my lamps in de living room (the pop-up card) How can I change that collar as well? I'm a noob in home assistant by the way. But I tries the same code, like this:
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#Boven'
    button_type: name
    name: Boven
    icon: mdi:bed
    card_layout: large
    styles: |
      ha-card {
        margin-bottom: 65px !important;
      }
      .horizontal-buttons-stack::before {
        display: none !important;
      }
      .Boven {
        background-color: ${hass.states['light.gang_boven_groep'].state === 'off' ? 'lightblue' : ''} !important;
      }

But this is nog working. And I have changed horizontal-buttons-stack into vertical-stack
