### ISSUE TITLE
More touch-friendly sliders

### ISSUE THREAD

**Issue by danielwis** [Clooos/Bubble-Card#764]
First and foremost, thanks for all your fantastic work here! I found this project a few days ago and am already redoing my dashboard to use bubble cards everywhere. However, there is one thing that I feel is missing. Hopefully this is not a duplicate issue (I tried searching the tracker but couldn't find anything).

Currently, the slider in the slider card follows the finger/thumb exactly. This is a bit annoying when working with smaller percentages, as it's hard to hit values like 5% or 1% exactly. If the new value were calculated as `old_value - (first_touch_pos - curr_touch_pos)` instead of just `curr_touch_pos` as it seems to be now, the increase/decrease would depend on how much the finger has moved instead of where it is located. In my opinion this makes for a better experience on phones and other smaller screens, but if there are cases in which the current behaviour makes more sense, perhaps this could at least be added as a configuration option?

Thanks in advance!

**Comment by Clooos** [comment]
Hi, actually I'm already working on this, the sliders in the next release are going to be easier to use.

**Comment by danielwis** [comment]
Oh, that's great! I'm looking forward to it :D

**Comment by firstchair** [comment]
Also having some issues with changing the brightness while using the slider
https://github.com/user-attachments/assets/d11febb7-dd01-424e-bbdd-c1fa81cf1a87
Looking forward to this update and thanks for all the great work!
