### ISSUE TITLE
Sub-button: icon animation ?

### ISSUE THREAD

**Issue by schumi2309** [Clooos/Bubble-Card#765]
Is it possible to put an animation on an icon in the sub_button?

like for example for a fan:

styles:
   icon:
       - animation: rotating 1.5s linear infinite

thank you to you.

**Comment by jleach87** [comment]
Yes, you can. You have to apply the styling on the main bubble card, not in the sub-button editor. Here's an example of a fan that spins and turns blue when on.

`.bubble-sub-button-5 > ha-icon {
  color: ${hass.states['fan.bedroom_floor_fan'].state === 'on' ? 'rgb(33, 150, 243)' : ''} !important;
}
.bubble-sub-button-5 > ha-icon {
  animation: ${hass.states['fan.bedroom_floor_fan'].state === 'on' ? 'slow-rotate 2s linear infinite' : ''};
}
@keyframes slow-rotate {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}`

**Comment by jleach87** [comment]
Yes, you can. You have to apply the styling on the main bubble card, not in the sub-button editor. Here's an example of a fan that spins and turns blue when on.

```
.bubble-sub-button-5 > ha-icon {
  color: ${hass.states['fan.bedroom_floor_fan'].state === 'on' ? 'rgb(33, 150, 243)' : ''} !important;
}
.bubble-sub-button-5 > ha-icon {
  animation: ${hass.states['fan.bedroom_floor_fan'].state === 'on' ? 'slow-rotate 2s linear infinite' : ''};
}
@keyframes slow-rotate {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
``` 

```

**Comment by Clooos** [comment]
Thank you for answering him! This is indeed the way 👌

**Comment by abwino** [comment]
Hi folks, any ideas why my sub button icon won't animate? 

`.bubble-sub-button-1 > ha-icon {  color: ${hass.states['binary_sensor.breakfast_room_ct_yard_door_sensor_opening'].state === 'on' ? 'red' : 'green'} !important; }
.bubble-sub-button-1 > ha-icon {  animation: ${hass.states['binary_sensor.breakfast_room_ct_yard_door_sensor_opening'].state === 'on' ? 'blink 1.5s ease infinite' : ''} !important; }
@keyframes blink {
  50% opacity: 0;}
${subButtonIcon[0].setAttribute("icon", hass.states['binary_sensor.breakfast_room_ct_yard_door_sensor_opening'].state === 'on' ? 'mdi:door-open' : 'mdi:door-closed')}
`

**Comment by HarryD67** [comment]
Try:

@keyframes blink {
    50% { opacity: 1 };
 }

**Comment by abwino** [comment]
@HarryD67 Thanks for your help, it worked with Opacity 0 in the end. The code was correct but there was something up with the editor maybe, I typed the code in from scratch and it started working!
