### ISSUE TITLE
Popup option not working 

### ISSUE THREAD

**Issue by dnestico** [Clooos/Bubble-Card#77]
The new trigger the popup with entity state is awesome I love it, but the option to automatically close the popup when the state turns off or changes isn't working or staying checked on unfortunately.

I check it on and save
![Screenshot_20230928-173708.png](https://github.com/Clooos/Bubble-Card/assets/3034555/41b54c60-4985-4ac6-a8da-05bbd7bb9437)

Go back and it's unchecked and not working
![Screenshot_20230928-173719.png](https://github.com/Clooos/Bubble-Card/assets/3034555/447aab4e-6138-4be8-9e67-fd5e3f69ea32)

**Comment by Clooos** [comment]
Thanks for the feedback, I will fix that in the next release, for now just add this in YAML mode:
```yaml
trigger_close: true
```

**Comment by dnestico** [comment]
Alright thanks I added that and I think it works, maybe a little too well with frigates weird detection sometimes causing it to popup for a few seconds then going down again haha, I'll have to make some adjustments in frigate itself to perfect this but does the job kinda at least. 👍
