### ISSUE TITLE
Using a slider triggers errors when using with ZigBee lights

### ISSUE THREAD

**Issue by michaelarnauts** [Clooos/Bubble-Card#785]
**Describe the bug**  
When using a slider and dragging, the change in brightness is immediately executed multiple times per second. This causes issues with ZigBee lights that can't handle so many changes per second.

This would be fixed when the change is only triggered when releasing the slider instead of doing this many times per second. Could this be made configurable?

**To Reproduce**  
1. Drag over a slider that is linked to a light with brightness control.
2. Move up and down a bit
3. See error from ZHA.

**YAML**  
If applicable, add any relevant YAML code.

```yaml
Your code here
```

**Informations (please complete the following information):**  
 - OS: Android
 - Browser/App: Home Assistant App
 - Bubble Card version: 2.2.4
 - Home Assistant version: 2024.09.1

**Additional context**  

Thank you! 🍻

**Comment by Clooos** [comment]
Hi, this issue will be fixed in the next release 👌
