### ISSUE TITLE
Custom text as attribute / second line

### ISSUE THREAD

**Issue by zimbo86** [Clooos/Bubble-Card#786]
It would be cool when using a button type switch or type name a string for the second line could be specified without using an attribute.

![image](https://github.com/user-attachments/assets/9c6d3248-c9c2-4f76-aa8e-ad5f4d204e40)

like:
``` 
show_customtext: true
customtext: "Press to start cleaning"
```

**Comment by Clooos** [comment]
Hi, this is already possible, take a look at the template section in the documentation, there is a template that allows you to modify the state 🙂

![image](https://github.com/user-attachments/assets/02d6fcda-86fb-45a5-8f4e-eb02e067d9c0)

**Comment by zimbo86** [comment]
this is massive!
thank you.
