### ISSUE TITLE
Error on Android HA App

### ISSUE THREAD

**Issue by idarius** [Clooos/Bubble-Card#79]
Hello, 

after the beta 9 install, my dashboard on android (with the official ha app) take many seconds to show up.
Same things for the popups, they come several seconds after the clic.
There is also no color on any button.

Here is an error in the logs :

`Logger: frontend.js.latest.202309110
Source: components/system_log/__init__.py:269
First occurred: 10:06:53 (1 occurrences)
Last logged: 10:06:53

Uncaught error from Chrome WebView 117.0.0.0 on Android 13 RangeError: Maximum call stack size exceeded BubbleCard.history.pushState (/hacsfiles/Bubble-Card/bubble-card.js:1:145) BubbleCard.history.pushState (/hacsfiles/Bubble-Card/bubble-card.js:1:145) BubbleCard.history.pushState (/hacsfiles/Bubble-Card/bubble-card.js:1:145) BubbleCard.history.pushState (/hacsfiles/Bubble-Card/bubble-card.js:1:145) BubbleCard.history.pushState (/hacsfiles/Bubble-Card/bubble-card.js:1:145) BubbleCard.history.pushState (/hacsfiles/Bubble-Card/bubble-card.js:1:145) BubbleCard.history.pushState (/hacsfiles/Bubble-Card/bubble-card.js:1:145) BubbleCard.history.pushState (/hacsfiles/Bubble-Card/bubble-card.js:1:145) BubbleCard.history.pushState (/hacsfiles/Bubble-Card/bubble-card.js:1:145) BubbleCard.history.pushState (/hacsfiles/Bubble-Card/bubble-card.js:1:145)`

**Comment by Clooos** [comment]
Hi and thanks for your feedback, this issue should be fixed in the new beta. Can you tell me if you still have this issue?
https://github.com/Clooos/Bubble-Card/releases/tag/v0.0.1-beta.11

**Comment by idarius** [comment]
Just updated, seems perfect for now ! 
Thx a lot for your work, its really easy to do a nice dashboard with your cards, i love it :)

**Comment by Clooos** [comment]
Yeah! 🥳
