### ISSUE TITLE
Unit display fault on optional show attribute

### ISSUE THREAD

**Issue by jerome6994** [Clooos/Bubble-Card#793]
Good morning,

I have just made a map with the temperature at which I want to display the humidity in addition with Optional - Show attribute but the % unit is not displayed even though I have the value on the device 
![image](https://github.com/user-attachments/assets/63fda805-7771-4d0d-902d-8e632ce8af87)

On the other hand, if I reverse it and put the humidity as the main sensor and the temperature as the secondary one, no problem.
it's the same with pressure
![image](https://github.com/user-attachments/assets/ac24affd-97c8-4991-b074-d4c9ef1671db)

in addition to not taking into account the units it also does not take into account rounding if you put a number after the decimal point or 0. Here is my sensor that I use
![image](https://github.com/user-attachments/assets/393d3e6b-83cb-48ce-91ef-a29f573a5f95)

```
type: custom:bubble-card
card_type: button
button_type: state
entity: sensor.temp_ch_parents_temperature
name: Température
card_layout: large
styles: |
  .bubble-button-card-container {
    background-color: ${state < 15 ? 'rgba(68, 154, 223, 1)' : state < 22 ? 'rgba(93, 157, 82, 1)' :  state < 25 ? 'rgba(243, 169, 60, 1)' : 'rgba(177, 70, 87, 0.7)' } !important;
  }
  .bubble-icon {
    color: ${state < 15 ? 'rgba(68, 154, 223, 1)' : state < 22 ? 'rgba(93, 157, 82, 1)' :  state < 25 ? 'rgba(243, 169, 60, 1)' : 'rgba(177, 70, 87, 0.7)' } !important;
    opacity: 1 !important;
  }
show_attribute: true
attribute: humidity
```

**Informations (please complete the following information):**  
 - OS: iOS
 - Browser/App: chrome
 - Bubble Card version: 2.2.4
 - Home Assistant version: 2024.9.1

Thank you! 🍻

**Comment by Mystically11** [comment]
Try disabling "Text scrolling effect" and see if that does anything

if that doesn't work, in the meantime, you can style it to fit your needs:
```
${card.querySelector('.bubble-state').innerText = 
  (state + " °C") + 
  (' • ' + (hass.states['sensor.temp_ch_parents_temperature'].attributes.humidity))} !important
```

**Comment by jerome6994** [comment]
I disabled "Text scrolling effect" but no particular effect

![image](https://github.com/user-attachments/assets/2de09e8d-3486-4987-b7aa-5f2657ba74da)

I made the suggested changes but apparently without success.
![image](https://github.com/user-attachments/assets/ed46b308-21cd-4bfd-994e-7d8f90acf140)

`type: custom:bubble-card
card_type: button
button_type: state
entity: sensor.temp_ch_parents_temperature
name: Température
scrolling_effect: false
show_attribute: true
attribute: humidity
styles: |
  ${card.querySelector('.bubble-state').innerText = 
    (state + " °C") + 
    (' • ' + (hass.states['sensor.temp_ch_parents_temperature'].attributes.humidity))} !important
`
