### ISSUE TITLE
Pop up for left hander

### ISSUE THREAD

**Issue by hawkeye100** [Clooos/Bubble-Card#796]
Great card - pop up really cool, except the 'close' button (X) is always on the right?

Maybe I have missed a config somewhere - there are many ;-) - if not, how about an option to have the close button at top left for us lefties please.

Obviously not urgent or a bug,  but would be helpful please.
Thanks

**Comment by Clooos** [comment]
Hi! Here is how you can change its position, but indeed I should add this option directly in the editor 👌

https://github.com/Clooos/Bubble-Card/discussions/721#discussioncomment-10377489

**Comment by hawkeye100** [comment]
Many thanks - missed that post when I looked. Have used it now and it works well. Thanks (and for prompt reply)

**Comment by Clooos** [comment]
You're welcome!
