### ISSUE TITLE
"Last changed" shows a time in the future

### ISSUE THREAD

**Issue by RmigD** [Clooos/Bubble-Card#798]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

**Describe the bug**  
"last changed" timestamp is 1 hours in the future

**To Reproduce**  
In button settings, activate: Optional - Show last changed

**Expected behavior**  
I expect the indication of the last changed time to be "1 second ago" instead of "in 3599 seconds"

**Screenshots**  
![Capturebc](https://github.com/user-attachments/assets/2331e3d9-b3a4-40b9-b1c2-c6032dc43349)
![Capturebc22](https://github.com/user-attachments/assets/f169b18a-fb1d-4565-b776-2a527ad4743f)

**YAML**  
If applicable, add any relevant YAML code.

```yaml
Your code here
```

**Informations (please complete the following information):**  
This only happens on my PC. Not on my laptop or on my phone. I can conceive it might be an issue with my browser, but I can't imagine what.
**Additional context**  

Thank you! 🍻

**Comment by RmigD** [comment]
This was caused by a timezones misconfiguration that (weirdly) only manifested via the home assistant docker image.

**Comment by MrBearPresident** [comment]
@RmigD Thanks for the feedback and for closing.
