### ISSUE TITLE
Major performance and battery life issues with 2.3.0-beta1

### ISSUE THREAD

**Issue by Kev1000000** [Clooos/Bubble-Card#799]
**Describe the bug**  
Using 2.3.0-beta 1 and a Dashbaord using popups, my device gets very warm and drains battery life when using the new bubble-card-based Dashboard.

**To Reproduce**  
Simply use the Dashboard that is driven by bubble cards.

**Expected behavior**  
The device to perform as well as non-bubble-card dashboards.

**Informations (please complete the following information):**  
 - OS: Android
 - Browser/App: HA Companion App
 - Bubble Card version: 2.3.0-beta1
 - Home Assistant version:2024.9.2

**Additional context**  
I have only begun using bubble card starting with 2.3.0-beta 1, so I cannot determine if this just started or has always been the case.  My device is a Samsung S23.

Thank you! 🍻

**Comment by Clooos** [comment]
Hi, there is a known performance issue in the editor that I need to fix, but beside that I have a very complex full Bubble Card dashboard that runs perfectly on an old iPad.

Can you take a look at your browser console on your computer to see if there is some errors?

**Comment by Kev1000000** [comment]
I did have a few errors in the console from old cards I had installed.  Removed those and have not seen any performance improvements.  Interestingly, I cannot get the blur to disable at all, regardless of choosing to hide backdrop, blur to 0, etc.  Trying to see if removing the blur would help.

**Comment by Clooos** [comment]
You need to disable it on your first pop-up, then you need to refresh your page.

**Comment by Kev1000000** [comment]
Ahh, OK, that worked!  Performance does seem to have improved with no blur and no bg, will continue to test.

**Comment by Clooos** [comment]
Hi, I've worked on this issue in the new beta, can you tell me if it's better now?

https://github.com/Clooos/Bubble-Card/releases/tag/v2.3.0-beta.2

**Comment by Kev1000000** [comment]
Unfortuantely, the high GPU and stuttering still exists on beta 2.

Here is a CPU/GPU graph while using my dashboard.  On a dashboard that includes a bubble card popup, by GPU hovers around 15% even when no popup is enabled.  When I do pop up a bubble card, even when it isn't animating (which you can see in the thermostat popup), my GPU spikes to 50%+

Dashboards that don't have popups fall to <= 5% GPU usage even when navigating in/out of them.

https://github.com/user-attachments/assets/30c59b59-d4f7-4ca3-8c96-2e6a3dca52ed

**Comment by Clooos** [comment]
Thank you for the detailed feedback! Bubble Card use some advanced CSS styling, like the blurred background that you can see behind of the pop-ups, I've seen that you have disabled the backdrop blur, this is a good start. But have you tried to set the pop-up blur to 0 in the editor?

I will also take a look to understand why there is a spike when no pop-ups are shown.

**Comment by Kev1000000** [comment]
Yep!  The popup blur is set to 0 for all popups in the editor.

**Comment by Clooos** [comment]
Thanks for the details, I will take a look 👌

**Comment by Kev1000000** [comment]
You're a champion, thank you!

**Comment by Clooos** [comment]
One more thing, can you check your browser console to see if there is errors? I don't think so but just to be sure.

**Comment by Kev1000000** [comment]
Just wanted to let you know that beta4 seems to have resolved my stuttering and performance drops with bubble card!  Thank you!

**Comment by Clooos** [comment]
You can't imagine how happy I'm to read that!
