### ISSUE TITLE
Bug: pop-up card header comes too high, gets stuck below lovelace header on mobile

### ISSUE THREAD

**Issue by lazyboy0172** [Clooos/Bubble-Card#8]
On mobile, when invoking a pop-up card it extends past the top of my view and under the dashboard's nav bar, making it impossible to see the header text or exit with the 'X'. A back gesture on android still is able to close the card.

https://github.com/Clooos/Bubble-Card/assets/57650025/3b7f18ec-bb06-4948-bd1e-449c4ff95e44

**Comment by samuel9554** [comment]
@lazyboy0172 In my case I added a margin-top of 60px in the popup

![image](https://github.com/Clooos/Bubble-Card/assets/10778993/1c931581-235f-4425-ac11-9769136b1253)

**Comment by lazyboy0172** [comment]
Good call-out. 60 was a good value for myself as well, I've edited my cards for that for now. Probably can close this bug as a result, but I'd have the default either set to something like 60 or change this behavior just so that with default options users don't experience this

**Comment by Clooos** [comment]
It was indeed an issue, it's now fixed in beta 2 and 0px means that the pop-up cover 100% of the screen, like it was supposed to be.

**Comment by Clooos** [comment]
It was indeed an issue, it's now fixed in beta 2 and 0px means that the pop-up cover 100% of the screen, like it was supposed to be.
