### ISSUE TITLE
No dropdowns or popups are invoked when invoked from a component within a Bubble Card

### ISSUE THREAD

**Issue by alxstojanovic** [Clooos/Bubble-Card#816]
**Describe the bug**  
Trying to open a dropdown menu from a component that invokes it on desktop does not cause the dropdown to be invoked.
This happens only if the dropdown component is inside a bubble card popup on desktop, regardless of browser or operating system.

**To Reproduce**  
1. Invoke a bubble card popup that has a dropdown component in it
2. Click on the dropdown component to attempt to invoke a dropdown, or popup
3. Observe that nothing happens

Note: On Mac, if you use magic mouse's tap to zoom feature and spam-click the dropdown like a lunatic, it sometimes invokes a dropdown, but somewhere random on the page...

**Expected behavior**  
Any dropdowns or popups should be invoked normally

**Screenshots**  
Had to downconvert this screen recording because of githubs 10mb limit... -_-

https://github.com/user-attachments/assets/45f98d1c-acc3-4d01-829b-72a4c7053dea

**YAML**  
YAML provide-able upon request

**Informations (please complete the following information):**  
 - OS: agnostic
 - Browser/App: agnostic
 - Bubble Card version: 2.2.4
 - Home Assistant version: 2024.9.3 (reproducible since 2024.9.1 - I just didn't know where to report an issue :) )

**Additional context**  
None at the moment.

**Comment by Clooos** [comment]
Hi, I've fixed a similar issue a few days ago, it should fix your issue as well 🤞

I will try to release the new beta soon.

**Comment by Clooos** [comment]
Hi, I've worked on this issue in the new beta, can you tell me if it's working now? 🤞

https://github.com/Clooos/Bubble-Card/releases/tag/v2.3.0-beta.2

**Comment by alxstojanovic** [comment]
Hiya, the issue is resolved in beta2! Many thanks!

From: Cloos ***@***.***>
Date: Friday, October 4, 2024 at 17:31
To: Clooos/Bubble-Card ***@***.***>
Cc: Aleksandar Stojanovic ***@***.***>, Author ***@***.***>
Subject: Re: [Clooos/Bubble-Card] No dropdowns or popups are invoked when invoked from a component within a Bubble Card (Issue #816)

Hi, I've worked on this issue in the new beta, can you tell me if it's working now? 🤞

https://github.com/Clooos/Bubble-Card/releases/tag/v2.3.0-beta.2
