### ISSUE TITLE
stack card for popup creates new collumn

### ISSUE THREAD

**Issue by jeroenvdd** [Clooos/Bubble-Card#82]
Hi,

I have a slight issue; when my pop up cards are slightly bigger,
they change my layout from 2 to 3 columns, (having an 'empty' column outside of edit mode as a result)

is there any way to mitigate this?

**Comment by Clooos** [comment]
Hi, in each of my rows I'm using horizontal-stacks, take a look at my exemple in the documentation. This should fix your issue.

**Comment by jeroenvdd** [comment]
> Hi, in each of my rows I'm using horizontal-stacks, take a look at my exemple in the documentation. This should fix your issue.

hmn i don't really see an example of how this is fixed in documentation,

do you mean i need to nest my 'pop up stack' cards in another stack card?

**Comment by jeroenvdd** [comment]
to be more clear:
this is how my dashboard is presented:
![image](https://github.com/Clooos/Bubble-Card/assets/6975276/3ea630d8-7ef9-43d0-b472-313fcb87e70e)

and this is what it looks like in edit mode:
![image](https://github.com/Clooos/Bubble-Card/assets/6975276/d00d6f5d-8441-4e60-a631-0baf9b67ad08)

**Comment by Clooos** [comment]
I misunderstood your question, this is indeed more clear like that. Have you try to put your pop-ups after all your other cards?

**Comment by jeroenvdd** [comment]
yeah i've fixed it now by forcing all cards of a collumn into one huge vertical stack :)
