### ISSUE TITLE
Pop up on mobile 

### ISSUE THREAD

**Issue by Tmatz27** [Clooos/Bubble-Card#821]
I'm having issues where my pop ups get triggered but display nothing. But if I switch to a different dashboard then come back the pop up operates as expected. 
I've force closed the mobile app and cleared cache and it first time to the dashboard the pop up window does not work

**Comment by Clooos** [comment]
Hi, I will release a new beta soon, there is a feature that is broken at the moment (Update pop-up in background) that I've fixed and this could solve your issue. I still don't know why but some pop-ups have difficulties to display when combined with some custom cards.

By the way can you send me the YAML of this pop-up?

**Comment by Tmatz27** [comment]
I have a 1 page dashboard with a lot of popups haha. The dashboard whole yaml is huge! I can send more if you want but here is one of the popups giving issues.

`type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: '#plex'
    name: ''
    force_icon: true
    show_header: true
    bg_color: '#000000'
  - type: custom:auto-entities
    filter:
      exclude:
        - state: unknown
        - state: unavailable
        - state: 'off'
      include:
        - entity_id: '*plex*session*'
          options:
            entity: this.entity_id
            type: custom:button-card
            variables:
              entity: this.entity_id
            custom_fields:
              picture:
                card:
                  type: picture
                  image: |
                    [[[
                      if (states[variables.entity].attributes.grandparent_thumb != ''){
                        return "https://plexdat.duckdns.org/api/v2?apikey=b0290a1b933f4388b590a3a2422c66e5&cmd=pms_image_proxy&img=" + states[variables.entity].attributes.grandparent_thumb + "&amp;width=300&amp;height=450&amp;fallback=poster&amp;refresh=true";
                      } else {
                        if (states[variables.entity].attributes.thumb != ''){
                          return "https://plexdat.duckdns.org/api/v2?apikey=b0290a1b933f4388b590a3a2422c66e5&cmd=pms_image_proxy&img=" + states[variables.entity].attributes.thumb + "&amp;width=300&amp;height=450&amp;fallback=poster&amp;refresh=true"                    
                        } else {
                          return states['sensor.' + states[variables.entity].attributes.user + '_session_thumbnail'].state
                        }
                      } 
                    ]]]
                  card_mod:
                    style: |
                      ha-card {
                        box-shadow: 0;
                        border-radius: 0;
                        margin: 5px 0 0 -5px;
                      }
                      ha-card img {
                        min-height: 100px;
                        min-width: 100px;
                      }
              bar:
                card:
                  type: custom:bar-card
                  entities:
                    - entity: this.entity_id
                  attribute: progress_percent
                  unit_of_measurement: '%'
                  positions:
                    icon: 'off'
                    indicator: 'off'
                    name: inside
                  height: 19px
                  color: |
                    [[[
                       if (states[variables.entity].state == 'playing') {
                      return '#2986cc';
                    } else if (states[variables.entity].state == 'paused') {
                     return '#e49f29';
                    } else {
                     return '#000000'; // Default color if neither playing nor paused
                    }
                    ]]]
                  card_mod:
                    style: |-
                      ha-card {
                        --ha-card-background: none;
                        border: none;
                        box-shadow: none;
                      }
                      ha-card #states {
                        padding: 0;
                      }
                      bar-card-currentbar, bar-card-backgroundbar {
                        border-radius: 5px;
                        left: 0;
                      }
                      bar-card-name {
                        margin-left: 3%;
                        text-shadow: 1px 1px 1px #0003;
                      }
                      bar-card-value {
                        margin-right: 3%;
                        text-shadow: 1px 1px 1px #0003;
                      }
              user: |
                [[[
                  return "<b>" + states[variables.entity].attributes.user + "</b>"
                ]]]
              title: |
                [[[
                  if (states[variables.entity].state == 'playing') {
                    return "<ha-icon icon='mdi:play' style='width: 15px; height: 15px; position: relative; top: -2px;'></ha-icon> " + states[variables.entity].attributes.full_title;
                  } else {
                    if (states[variables.entity].state == 'paused') {
                      return "<ha-icon icon='mdi:pause' style='width: 15px; height: 15px; position: relative; top: -2px;'></ha-icon> " + states[variables.entity].attributes.full_title;
                    } else {
                      return states[variables.entity].attributes.full_title;
                    }
                  }

                ]]]
              stream_label: <b>Stream</b>
              stream: |
                [[[
                  return states[variables.entity].attributes.video_resolution + " > " + states[variables.entity].attributes.transcode_decision + " > " +states[variables.entity].attributes.stream_video_resolution + ""
                ]]]
              product_label: <b>Product</b>
              product: |
                [[[
                  return states[variables.entity].attributes.product
                ]]]
              media_detail: |
                [[[
                  if(states[variables.entity].attributes.media_type == 'movie') {
                    return "<ha-icon icon='mdi:filmstrip' style='width: 15px; height: 15px; position: relative; top: -2px;'></ha-icon> (" + states[variables.entity].attributes.year + ")";
                  } else {
                    return "<ha-icon icon='mdi:television-classic' style='width: 15px; height: 15px; position: relative; top: -2px;'></ha-icon> S" + states[variables.entity].attributes.parent_media_index + " • E" + states[variables.entity].attributes.media_index;
                  }
                ]]]
              bandwidth_label: <b>Bandwidth</b>
              bandwidth: |
                [[[
                  var bytes = states[variables.entity].attributes.bandwidth * 1000;
                  var sizes = ['Bytes', 'Kbps', 'Mbps', 'Gbps', 'Tbps'];
                  if (bytes == 0) return 'n/a';
                  var i = parseInt(Math.floor(Math.log(bytes) / Math.log(1000)));
                  if (i == 0) return bytes + ' ' + sizes[i];
                  return (bytes / Math.pow(1000, i)).toFixed(1) + ' ' + sizes[i];
                ]]]
            card_mod:
              style: |
                ha-card {
                  box-shadow: 0;
                  padding: 0;
                  margin: 0;
                  border: 0;
                }
                ha-card #container {
                margin: 5px 0 0 0;
                }
                #name {
                  display:none;
                }
            styles:
              card:
                - height: 100x
                - padding: 0
              custom_fields:
                bar:
                  - text-transform: capitalize
                  - font-size: 13px
                user:
                  - text-align: end
                  - font-size: 15px
                title:
                  - text-align: start
                  - font-size: 13px
                stream:
                  - text-transform: capitalize
                  - text-align: start
                  - font-size: 13px
                product:
                  - text-transform: capitalize
                  - text-align: start
                  - font-size: 13px
                player:
                  - text-transform: capitalize
                  - text-align: start
                  - font-size: 13px
                location:
                  - text-transform: uppercase
                  - text-align: start
                  - font-size: 13px
                media_detail:
                  - text-transform: uppercase
                  - text-align: start
                  - font-size: 13px
                bandwidth:
                  - text-transform: capitalize
                  - text-align: start
                  - font-size: 13px
                product_label:
                  - text-transform: uppercase
                  - text-align: end
                  - font-size: 10px
                player_label:
                  - text-transform: uppercase
                  - text-align: end
                  - font-size: 10px
                stream_label:
                  - text-transform: uppercase
                  - text-align: end
                  - font-size: 10px
                location_label:
                  - text-transform: uppercase
                  - text-align: end
                  - font-size: 10px
                bandwidth_label:
                  - text-transform: uppercase
                  - text-align: end
                  - font-size: 10px
              grid:
                - grid-template-areas: |
                    "picture product_label product"
                    "picture player_label player"
                    "picture stream_label stream"
                    "picture location_label location"
                    "picture bandwidth_label bandwidth"
                    "picture bar bar"
                    "picture title title"
                    "picture media_detail user"
                - grid-template-columns: 1fr 60px 3fr
                - grid-gap: 5px 10px
    card:
      type: vertical-stack
    card_param: cards
  - type: custom:upcoming-media-card
    entity: sensor.radarr_radarr_upcoming_media
    title: Upcoming Movies
    date: ddmmyy
    clock: 12
    max: 10
    image_style: fanart
    hide_empty: true
    hide_flagged: true
    flag: true
    text_shadows: true
    box_shadows: true
    enable_transparency: true
    collapse: flag=true
    filter: >-
      {{ 'flag=true' if not title in states.sensor.tautulli_watched.state else
      'flag=false' }}
    sort_by: release
    sort_ascending: true
    enable_tooltips: true
  - type: custom:upcoming-media-card
    entity: sensor.sonarr_upcoming_media
    title: Upcoming TV
    date: ddmmyy
    clock: 12
    max: 6
    image_style: fanart
    hide_empty: true
    hide_flagged: true
    flag: true
    text_shadows: true
    box_shadows: true
    enable_transparency: true
    collapse: flag=true
    filter: >-
      {{ 'flag=true' if not title in states.sensor.tautulli_sonarr_watched.state
      else 'flag=false' }}
    sort_by: release
    sort_ascending: true
    enable_tooltips: true
title: Plex
'

**Comment by Clooos** [comment]
Probably an incompatibility with custom:upcoming-media-card, I hope the new beta will fix this issue.

**Comment by Tmatz27** [comment]
[Maid Dashboard YAML.txt](https://github.com/user-attachments/files/17191212/Maid.Dashboard.YAML.txt)

Attached is my full dashboard YAML. I have a ton of custom cards in there to make it easy to navigate on a phone. The only issue currently is the Plex/Upcoming Show/Movie cards on the 1st page of the dashboard. I have the same popup on page 2 and it works fine or if i go to a completely different dashboard open thing then go back to the main dashboard it works as expected. I can replicate this on Android devices and windows. After the update ill let you know what if its fixed! if there is anything else i can do let me know im here to help were i can!

**Comment by Clooos** [comment]
Perfect, I will do my best to release the new beta this week 🤞

**Comment by BaerHub** [comment]
i can confirm this problem also occurs in combination with custom:button-card.
i also noticed, if i clear the custom styles section, its working again and all buttons show up.

the problem only occurs on my nspanels, not on my smartphone and not on windows/chrome

**Comment by Clooos** [comment]
Hi again! The new beta is here, can anyone try to toggle this?

<img width="523" alt="image" src="https://github.com/user-attachments/assets/b91f2b0a-6352-4b26-85a3-337195a415fe">

Then refresh the page to be sure 🤞

https://github.com/Clooos/Bubble-Card/releases/tag/v2.3.0-beta.2

**Comment by Tmatz27** [comment]
Ive been testing it and it didnt make any changes for me personally. I did notice that if the pop up doesnt "pop up" that if i edit the dashboard it shows it "open" in the pop up card. If i close it from there the card operates normally again. I tried to implement the auto close after so many milliseconds it works but no matter what i put in that block it just closes after 1 second. I increased the milliseconds and it makes no changes.

**Comment by Clooos** [comment]
Thank you for the feedback! Can you check if you have any Bubble Card error in your browser console?

**Comment by Tmatz27** [comment]
I am not seeing any errors specifically for bubble cards. If there was a way for me to increase the force closing of the card to say 3 mins I think that would fix my issue. if I go into edit mode and force close the card it opens fine after that. or if I go to a different dashboard and come back.

**Comment by Tmatz27** [comment]
I'm still experiencing an issue with a specific pop-up card on my default dashboard that doesn't display correctly. Here's a breakdown of the problem:

Symptoms: When I click the pop-up, the screen becomes blurry, and the pop-up appears off to the bottom of the other cards, partially hidden behind the blurred screen. Additionally, a strange white "X" appears on the left side of the pop-up, which isn't normally there.

Conditions:

This issue only occurs on the default dashboard.
If I switch to another dashboard and then back to the default one, the pop-up works as expected.
This happens across all platforms (Mobile, Tablet, Chrome, Firefox).
The default dashboard has 13 other pop-ups that work correctly.
Troubleshooting Steps Taken:

I enabled the forced close option, but it did not resolve the issue.
I also tested the latest beta version, but the problem persists.
Would appreciate any guidance on how to resolve this!

![Screenshot 2024-10-23 145055](https://github.com/user-attachments/assets/e9c834b5-4d8f-43b4-9e05-9e9c9ae0b1ef)

**Comment by Tmatz27** [comment]
The attached picture above is what i see when i click the non-working popup. You can see the popup turns the screen blurry and you can see the pop up in the bottom left of the screen. If i click off this dashboard and come back it opens normally

**Comment by Clooos** [comment]
Oh I didn't realized that this was you! I have more than enough infos then! 👌

I will need to try to reproduce your pop-up on my setup to see what's wrong. Your YAML is probably the only thing I really need and you've already send it. 

I'm sorry but with all these issues I'm getting lost sometimes 😅

**Comment by Tmatz27** [comment]
I totally understand! If there is anything i can do to help let me know!

**Comment by Tmatz27** [comment]
Just an update tried the new beta and it did not fix the issue that I was experiencing.

**Comment by EinfachHans** [comment]
I think i have a similar issue. This is what it looks like when i freshly open the app and trigger a popup:

![image](https://github.com/user-attachments/assets/7ffb6102-7135-4165-a361-5e0b9a406a3d)

Then i have to wait a longer time and after some minutes the popup appears:

![image](https://github.com/user-attachments/assets/18f2c45d-5e7f-47fe-b627-da3d581d7c26)

Before a popup once is loaded correctly, i have the problem with **every** popup. After one is loaded, every popup seems to work.

**Comment by Clooos** [comment]
Hi, can you try the version I posted here?

https://github.com/Clooos/Bubble-Card/issues/356#issuecomment-2465005943

I explain how to install it a few comment before that one, I really hope that this version fix your issue as well 🤞

**Comment by EinfachHans** [comment]
@Clooos `v2.3.0-beta.5` seems to fix this bug for me. Thank you very much! 😊

**Comment by Clooos** [comment]
Nice! And you're welcome! 😁

I will release it soon on HACS, probably today 🤞
