### ISSUE TITLE
v2.3.0-beta.2 Fan slider not responding

### ISSUE THREAD

**Issue by grrygh** [Clooos/Bubble-Card#838]
Fan slider is not responding in v2.3.0-beta.2

After downgrading back to v2.2.4, it works again.

Thanks!

**Comment by Clooos** [comment]
Thank you for the feedback, I will test that!

**Comment by Clooos** [comment]
Hi! Can you tell me if this issue is fixed for you in v2.3.4-beta.1? 🤞

**Comment by grrygh** [comment]
> Hi! Can you tell me if this issue is fixed for you in v2.3.4-beta.1? 🤞

Hi, yes, the issue has been resolved.
