### ISSUE TITLE
Horizontal button stack doesn't render properly after closing a pop-up

### ISSUE THREAD

**Issue by mailuminatti** [Clooos/Bubble-Card#84]
First  - thank you for creating this amazing set of cards, it's looking fantastic. 
I'm giving it a try on a new dashboard, and the horizontal button stack is not rendering properly after closing a pop-up:

This is how the dashboard looks before opening the pop-up
<img src="https://github.com/Clooos/Bubble-Card/assets/46273278/7ece5c64-c325-4aa9-b1e7-6857e27f1cc6" width="300">

This is while is open:
<img src="https://github.com/Clooos/Bubble-Card/assets/46273278/a049b1ee-75aa-4ad4-865e-8759335c3478" width="300">

And this is after closing the pop-up:
<img src="https://github.com/Clooos/Bubble-Card/assets/46273278/346729a3-6b3f-41be-8c0a-dcf1b0e015af" width="300">

(note how the horizontal stack is not rendered properly)
I noticed that this only happens in the mobile app, and not on the web browser.

If it helps:
Home Assistant 2023.9.2
Supervisor 2023.09.2
Operating System 10.5
Frontend 20230911.0 - latest

Home Assistant android app version:
2023.9.2-full

Happy to provide with any additional information you might need!

**Comment by Clooos** [comment]
Hi and thanks for your feedback, is your horizontal buttons stack the last card on your dashboard? If not can you try this and tell me if it's fixed?

**Comment by mailuminatti** [comment]
That fixed it! Thank you so much for your quick response 🙂
Might be worthy adding this in the [Horizontal buttons stack](https://github.com/Clooos/Bubble-Card#horizontal-buttons-stack) docs

**Comment by Clooos** [comment]
I tought that it was already mentioned, but it's now the case! Thanks!

https://github.com/Clooos/Bubble-Card#horizontal-buttons-stack
