### ISSUE TITLE
Sub Header in Background

### ISSUE THREAD

**Issue by MorreMor** [Clooos/Bubble-Card#842]
what can i do, the sub header is after opening pop up always in background and blurry
![Uploading Bildschirmfoto 2024-10-08 um 06.21.33.png…]()

**Comment by MorreMor** [comment]
<img width="602" alt="Bildschirmfoto 2024-10-08 um 06 21 41" src="https://github.com/user-attachments/assets/f128c1cd-78cb-4502-965f-f4db0ff284b0">

**Comment by MorreMor** [comment]
![Uploading Bildschirmfoto 2024-10-08 um 06.21.33.png…]()

**Comment by MorreMor** [comment]
<img width="532" alt="Bildschirmfoto 2024-10-08 um 06 24 44" src="https://github.com/user-attachments/assets/4febc3d5-d42a-4403-a57e-799f5e523f07">

**Comment by Clooos** [comment]
Hi, you can go to your top most pop-up in the editor, then toggle this. Don't forget to refresh your page after that.

![Screenshot_2024-10-08-06-44-25-463_io homeassistant companion android-edit](https://github.com/user-attachments/assets/ab46f431-9a02-4167-a78a-4b80a76009d1)
