### ISSUE TITLE
Slider for controlling thermostat does not work anymore

### ISSUE THREAD

**Issue by Kroesss** [Clooos/Bubble-Card#849]
**Describe the bug**  
I am using a Bubble Card slider to control my thermostat (connected to HA with a OTGW). This has worked well, but I noticed today it does not anymore. The card will show the set temperature, so it reads fine, but when I slide the bar to change the temperature, I get an error on the bottom of the dashboard that says (in Dutch, so some words might not be exactly this):
"Action climate/set_temperature could not be executed. expected float for dictionary value @ data['temperature']"

The temperature is then obviously not set, and after a little time, the bar goes back to the set temperatur.

I can still change the temperature with the HA native thermostat-card, so that part is working as normal. I don't know exactly when this behavious started (I don't change my temperature every day, as the normal routine is done through a schedule on the physical thermostat itself). I therefore don't really know wheter it was an update of Bubble Card, or maybe an update of HA itself that changed something in an entity.

I have tested with a new card, that is extremely basic for this:
```yaml
type: custom:bubble-card
card_type: button
button_type: slider
entity: climate.thermostaat
show_state: false
```

**Informations:**  
 - Home Assistant Core 2024.10.2
 - Home Assistant Supervisor 2024.10.0
 - Bubble Card version 2.2.4
Installed on a NUC in a proxmox VM

**Comment by Clooos** [comment]
Hi! I'm already on it, this will be fixed for the next beta! 👌

**Comment by Kroesss** [comment]
You're a legend!

I have Bubble cards installed through HACS, so I don't think I'm getting beta's, but as long as it is fixed, I'll happily wait until the next stable where it is in :)

**Comment by Clooos** [comment]
You can get the betas in HACS, just go to the Bubble Cars page in HACS, then click on the menu, the on Re-download, you will be able to pick the betas from there.

**Comment by returnofthem** [comment]
Hey @Clooos, was this fixed in one of the betas?

I'm having the same problem in the release branch so just tried with v2.3.0-beta.4 but I'm still seeing the same error.

This is the details of my thermostat:
```
hvac_modes:
  - heat
  - auto
min_temp: 5
max_temp: 30
preset_modes:
  - Kitchen-diner
  - Lounge
  - Master bedroom
  - Spare room
  - Heating off
  - Master bedroom - early start
current_temperature: 16.6
temperature: 13
hvac_action: idle
preset_mode: Lounge
setpoint: null
bosch_state: idle
low_battery: false
friendly_name: Lounge
supported_features: 17
```

Loving your work!

**Comment by Kroesss** [comment]
@Clooos I did not have time to check beta 3, but I installed beta 4 and this issue still exists.

I can control my thermostat with the new climare-card, so I don't know if you plan on fixing this or if the fix is "use the dedicated climate card"? Both are perfectly fine by me, but if you do plan on fixing it, I will keep my slider-card so I can test it for you :)

**Comment by Clooos** [comment]
Hi, I'm definitely planning to fix this issue, I was sure that it was fixed, but I will try again for the next release 🙂

**Comment by Kroesss** [comment]
No worries! I'll keep both cards on my dashboard then so I can test for you after a release.

**Comment by Kroesss** [comment]
@Clooos Sorry for the delay, but this is now fixed in beta 5. I see you are already on beta 7, but I did not have time to report it here beforehand...

**Comment by Clooos** [comment]
Thank you for the feedback!
