### ISSUE TITLE
 Idea: Secondary line on Bubble card type Button

### ISSUE THREAD

**Issue by jerome6994** [Clooos/Bubble-Card#854]
Good morning 

I don't want to report a bug but suggest an idea for improvement. 

Is it possible to add a secondary line to the button Switch type card (this is the one I use in my example) to display the room temperature and humidity in a bit of the same style as it? is it possible to do this on Mushroom?
Of course, we must also be able, depending on the temperature values, to write the text in color or the background of the zone and other possible and useful customs?

what I have on Mushrom
![image](https://github.com/user-attachments/assets/7401c45d-ccce-4f2f-8051-922e8be30761)

What I have at the moment on bubble card.
Either you can slide sub-buttons for temperature and humidity for example as shown in the arrow 
either we add a line with possible entities based on the Mushroom principle
![image](https://github.com/user-attachments/assets/64380653-90b6-443e-bd65-24bf300bfb12)

In this way on room cards we can maximize the information on a home page and then if we need more details we go to the view page

which gives us a single viable card for a PC, tablet and mobile dashboard and that’s optimization

**Comment by Clooos** [comment]
Hi! You can already do that with custom templates, take a look at the examples in the documentation, there is one that explain how to change the text in a button, this allows exactly what you want 👌

Also next time please open a new discussion for that kind of request.
