### ISSUE TITLE
Pop-ups/Buttons not being contained within designated card area

### ISSUE THREAD

**Issue by ASimpleTechie** [Clooos/Bubble-Card#86]
I'm sorry to be a pain but I just cannot figure this out.

I have my pop up cards and horizontal button stack sitting in a vertical stack with other cards on the left of my tablet dashboard.

I cannot figure out how to get the buttons and the pop ups to stay within the area of the vertical stack.

This image below shows the buttons sprawled across the bottom of the dashboard when I want them contained within the area that the other cards are.
![Screenshot_20231001-012349_Fully Kiosk Browser_012534~2](https://github.com/Clooos/Bubble-Card/assets/85463735/0bd437be-e6e9-4690-90af-2ed866d548b0)

I would like the buttons to be scrollable from within the width of that panel (same width as the weather card).

I would also like the pop ups to stay within the same area when they are open, but instead they pop up in the centre (please see image below)

![Screenshot_20231001-012400_Fully Kiosk Browser_012529~2](https://github.com/Clooos/Bubble-Card/assets/85463735/6e34375b-79c6-4dc4-9c45-6ce38163f71b)

I am unsure what I need to do to achieve this.

I am really liking the look and features of this card so I really want to figure this out. Thank you for your constant hard work.

**Comment by Clooos** [comment]
Hi! Just add this to your `pop-up` to remove the centering of the pop-up, but you will need to edit its `width_desktop` too to fit your column (something like 500px).

```yaml
styles: |
  #root {
    left: inherit !important;
  }
```

**Comment by ASimpleTechie** [comment]
Thanks! Do I add it to each individual pop-up within the stack?

**Comment by Clooos** [comment]
You can probably just add your cards in horizontal-stacks, tell me if it's what you are looking for.
