### ISSUE TITLE
Climate Card

### ISSUE THREAD

**Issue by willliamchan** [Clooos/Bubble-Card#862]
Hi Clooos

Nice job! I haven't really start it yet but I've got a feeling I can remove quite a number of custom selects that built for climate!

Quick one for you tho, can you please advise what do I need to change so climate card resume honouring my custom styling? I tried to replace .bubble-button-card-container to .bubble-climate-container and seems not doing the trick.

```
.bubble-button-card-container {
  background: ${hass.states['climate.lounge_radiator_cloud'].state !== 'off' ? '#a15750' : ''} !important;
}

${state !== 'off' ? icon.setAttribute("icon",
"mdi:radiator") : icon.setAttribute("icon",
"mdi:radiator-off")};
```
![image](https://github.com/user-attachments/assets/3763a6a2-36e9-4b1b-a021-088c1fe395d6)

**Comment by Clooos** [comment]
Hi! I've just tried and it works with:

```yaml
.bubble-color-background {
  background: ${state !== 'off' ? '#a15750' : ''} !important;
}
```

I've changed the structure a bit for that card, I understand that this is a bit harder to know what are the variables to edit across the cards. I really can't wait to release my new video about the stylings! This video will make things a lot clearer for a lot of users 🙂
