### ISSUE TITLE
Button color & Icon color missing for HVAC Dry & Heat/Cool mode in Climate card.

### ISSUE THREAD

**Issue by gandhiarpit** [Clooos/Bubble-Card#863]
**Describe the bug**  
When HVAC Dry mode or Heat/Cool mode is selected in Climate card, it is missing the icon & background color. As seen below

**To Reproduce**  
1. Select Dry mode or Heat/Cool mode in the climate bubble control
2. HVAC turns ON, but the colors are missing.

**Expected behavior**  
Appropriate different Color should be applied to Icon & Button similar to other modes of HVAC

**Screenshots**  
<img width="260" alt="Bubble_climate_card" src="https://github.com/user-attachments/assets/caf698f6-b30d-425c-9b53-194e6b787483">

**Informations (please complete the following information):**  
 - OS: iOS
 - Browser/App: Chrome/Firefox
 - Bubble Card version: v2.3.0-beta.3
 - Home Assistant version: [e.g. 2024.10.3]

**Additional context**  
Also, for Heat/Cool mode will it change the color depending on if it is heating or cooling? Mushroom card changes the icon based on what HVAC is doing.

Thank you! 🍻

**Comment by gandhiarpit** [comment]
Thanks. I can confirm this works fine now.

**Comment by gandhiarpit** [comment]
My initial observation, based on comparing it with Mushroom card. The heat/cool mode on my HVAC changes which mode it is in real time to maintain the target temperature. So it could be either heating or cooling or only fan ON. As you can see in below screenshots, check the mushroom card updating the icon based on what HVAC is doing. Maybe this can be added to bubble climate card? Like update the color of the button to display the mode?

Currently, bubble climate card doesn't tell me what HVAC is doing. But mushroom card tells me either it's cooling or heating or only fan. 

Maybe a feature request? This is not a bug, but really good to have for visual confirmation of what HVAC is actually doing.

<img width="559" alt="Bubble climate card" src="https://github.com/user-attachments/assets/c446d6e8-676a-4eea-9885-0ff3af1e227b">

**Comment by Clooos** [comment]
Hi again, this makes sense, I've changed that behavior so that the color of the card change accordingly 👌

I will release a new beta soon, probably today 🤞

**Comment by szamfirov** [comment]
@Clooos, don't want to raise another issue for something very similar but I just noticed on the latest beta (v2.3.0-beta.8) that when `state_color` is set to `true` and you set your entity to `heat_cool`, this completely breaks the card with an error "Assignment to constant variable". Not sure if it was from the recent state changes but just wanted to surface this here:

![Screenshot 2024-11-24 at 20 22 45](https://github.com/user-attachments/assets/3a838016-3d40-4887-be9b-f8afddaa5740)


It errors out on the "default" case [here](https://github.com/Clooos/Bubble-Card/blob/main/src/cards/climate/helpers.ts#L26) somewhere. Please let me know if I can provide more details somehow.

**Comment by Clooos** [comment]
Thanks for the feedback, that was a typo in my code! 😅

Simple fix 👌

**Comment by szamfirov** [comment]
Good to hear. I just saw it as well - the `=` instead of `===` is probably what breaks things :)

**Comment by Clooos** [comment]
Exactly, just by reading the error you sent I knew it was that before looking at my code 😄
