### ISSUE TITLE
Sub Button Media Player Icons Opposite to convention

### ISSUE THREAD

**Issue by schmuy** [Clooos/Bubble-Card#874]
Media player icons typically display the action performed by pressing the button.  If media is Paused, then Play icon is displayed.  If playing, then pause icon is displayed.

Bubble Card does the opposite in sub buttons,  when playing, play is displayed; when paused, pause is displayed.

Gets confusing when working between different systems.

**Comment by Clooos** [comment]
Hi! I will check that, can you also add the YAML that you use for that card?

**Comment by schmuy** [comment]
I just went looking at my YAML and realized I was looking at the wrong spot and this one's 100% on me
