### ISSUE TITLE
[v2.3.0-Beta2] Popup background has an odd black shadow appearing on the top left and top right corners without any reason for it to be there

### ISSUE THREAD

**Issue by alxstojanovic** [Clooos/Bubble-Card#879]
**Describe the bug**  
When opened, on any device, popups draw a weird semi-shadow on the top left and top right corners/shoulders of the popup. 
This happens on any device, any browser, any theme, with or without custom backgrounds. I am aware that each popup draws a bit of a shadow behind it to make it stand out a bit more from the surroundings, but it looks like the shadow is somehow encroaching on the corners.

It looks like the popup is trying to blurr the background, but there is no reason for the two corners to have these shadows. This happens even if I try it on a fully white background.

**To Reproduce**  
1. Go to any popup on any device on any browser
2. Observe the top left and top right corners

**Expected behavior**  
No shadow on the corners.

**Screenshots:**
![Screenshot 2024-10-29 at 11 44 30](https://github.com/user-attachments/assets/65fa99b9-cdfa-41d9-9d5e-2fc5003a573a)
![Screenshot 2024-10-29 at 11 45 09](https://github.com/user-attachments/assets/5e3d0f85-705e-404d-9917-cfc98b24c59a)

**YAML**  
Available if requested.

**Informations (please complete the following information):**  
 - OS: ANY
 - Browser/App: ANY
 - Bubble Card version: v2.3.0-Beta2
 - Home Assistant version: inclined to say ANY, but here's my set:
Core 2024.10.4
Supervisor 2024.10.3
Operating System 13.2
Frontend 20241002.4

**Additional context**  
Keep up the great work, bubble card rocks :D

**Comment by Clooos** [comment]
Hi and thank you for your feedback, indeed I've noticed it as well. This is because I had to move the blurred background to another container to fix a dropdown issue. But this shouldn't be too difficult to fix.

**Comment by Clooos** [comment]
This issue was fixed in v2.3.0-beta.4, I'm closing this 🙂 

Thanks again for the feedback!
