### ISSUE TITLE
The entire window shifts up when the sub-button is opened.

### ISSUE THREAD

**Issue by mrgrlscz** [Clooos/Bubble-Card#882]
Hi Clooos! When i click on a select sub-button, the dropdown makes the entire column shifts up...
I placed two instances of the dashboard side by side to show the issue:
![Capture d’écran 2024-10-30 003929](https://github.com/user-attachments/assets/92dfddec-c8cd-47cb-abcd-f91a24c26822)
![Capture d’écran 2024-10-30 004041](https://github.com/user-attachments/assets/8a05c519-721d-455a-9c86-ab5266348a23)
Any chance you fix this before 2025? ;)

**Comment by Clooos** [comment]
Hi, what do you use for that column? Is that a basic section view? I can fix it before 2025 if you help me a bit more, I'm unable to reproduce it with the few details you provided.

**Comment by mrgrlscz** [comment]
I'm the worst beta-tester ever...
Problem is due to `custom:stack-in-card`
Your climate card is OK... so sorry for wasting your time!

**Comment by Clooos** [comment]
Don't worry, glad that you found what was causing this issue!
