### ISSUE TITLE
Adding duration in the Sub Button does not show the time remaining but instead shows the set time.

### ISSUE THREAD

**Issue by rajp1503** [Clooos/Bubble-Card#885]
So I have a timer that I want the subbutton to show when active. The optional setting "optional - show attribute" is selected and the button shows the set time but not the remaining. Is this a bug?

![image](https://github.com/user-attachments/assets/ef7e1d99-fea3-409a-b664-bd471ee19e55)

**Comment by Clooos** [comment]
Hi! This is not really a bug and I'm aware of this, in fact the Home Assistant cards handle this attribute directly in the frontend.

This is more a missing Bubble Card feature, but this is already in my to-do list 👌

**Comment by Clooos** [comment]
I still don't know, I'm working mostly alone on this project so this is not easy to really have any ETA on the upcoming features. But this will come 🙂
