### ISSUE TITLE
v2.3.0-beta.4 no longer applying --bubble-accent-color to elements

### ISSUE THREAD

**Issue by tiagof** [Clooos/Bubble-Card#888]
As the title says.
Something changed from beta.3 to beta.4 and --bubble-accent-color (which I was changing in my theme file) is not longer applied to any of the elements.

Just today I created a PR #887  to apply this var to the media play/pause button since it seemed (to me) that it was missing, and now with beta.4 it completely missing.

Didn't find any mention to it being removed in the changelogs, so maybe a bug?

Cheers

**Comment by Clooos** [comment]
Hi! This is weird because I haven't changed anything about that in my code. Are you sure that you've reloaded your theme correctly?

**Comment by tiagof** [comment]
I just did "re-download" in HACS's bubble card page and rebooted home assistant... and the accent color was changed. 

I'm gonna check further and provide more details. 

Thx
