### ISSUE TITLE
Bug: back button 

### ISSUE THREAD

**Issue by scalt** [Clooos/Bubble-Card#89]
Open the pop-up. Click on a button in the pop-up that is used for navigating to another page. Now go back to the previous page. Sometimes the pop-up automatically opens. Sometimes the buttons to open a popup don't work anymore. 

This is due to the fact that the back button in subviews or the back button in mushroom card call the history back function m. This will open the url with the #xyz and therefore conflicts with that back. As a user I don't won't to see the pop-up when I go back, but I want to see the parent screen.

**Comment by Clooos** [comment]
Hi and thanks for your feedback! You can now change this behavior in the new v1.0.1:
https://github.com/Clooos/Bubble-Card/releases/tag/v1.0.1
