### ISSUE TITLE
Underscore removing from list select

### ISSUE THREAD

**Issue by Clooos** [Clooos/Bubble-Card#890]
### Discussed in https://github.com/Clooos/Bubble-Card/discussions/889

<div type='discussions-op-text'>

<sup>Originally posted by **mk89pwnz** October 30, 2024</sup>
Would it be possible to show select without it?

![image](https://github.com/user-attachments/assets/4bc67046-a3c6-4eb7-96a0-d857cbc0bcbf)

Entity state shows it without underscore</div>

**Comment by jdpoccorie** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
