### ISSUE TITLE
v2.3.0-beta.4 - Unable to close a pop-up by clicking background.

### ISSUE THREAD

**Issue by willliamchan** [Clooos/Bubble-Card#891]
For any feature request you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/feature-requests

For any question you can open a new discussion here:  
https://github.com/Clooos/Bubble-Card/discussions/categories/q-a

1. click to open a pop-up.
2. click the top to close a pop-up. (if the current background is another card, it launches what's in the background directly)

**Expected behavior**  
1. click to open a pop-up.
2. click background to close a pop-up, regardless if it's empty or not, it should just close the current pop-up

**Informations (please complete the following information):**  
 - OS: iOS 18.1
 - Browser/App: App
 - Bubble Card version: v2.3.0-beta.4
 - Home Assistant version: 2024.10.4

**Comment by jdpoccorie** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by Clooos** [comment]
Hi! I guess that you haven't re-added the pop-up blurred backdrop, take a look a the latest changelog.

This is expected, for example on my setup I don't have the blurred backdrop because I have a menu at the top of my view, and when I open a pop-up, I like to be able to click on that menu.
