### ISSUE TITLE
v2.3.0-beta.4 - Bug background

### ISSUE THREAD

**Issue by Bsector** [Clooos/Bubble-Card#895]
Hello,

Here is a problem I observed using v2.3.0-beta.4:

- Pop-up with image in the background do not appear in the pop-up, but in the editor the background is correct.
![Captura de tela 2024-11-01 150936](https://github.com/user-attachments/assets/63575670-676b-4f3b-8478-cb5080d73f37)
![Captura de tela 2024-11-01 154622](https://github.com/user-attachments/assets/b419ebcd-1a09-4ddf-bf87-875e5c7f09e3)

Here's the custom style I use:

  .bubble-pop-up {
    transition: transform 0.3s ease;
    background: center / cover no-repeat url("/local/epellis_theme/blue.jpg") fixed;
    border-radius: 12px 12px 0 0;
    box-sizing: border-box;
    margin-left: var(--custom-margin);
    left: 7px;
    z-index: 5 !important;
    bottom: calc(-56px - var(--custom-height-offset-mobile));
    backdrop-filter: var(--custom-popup-filter);
    -webkit-backdrop-filter: var(--custom-popup-filter);
    box-shadow: 0px 3px 8px 0px rgba(255, 174, 66, 0.35) !important;
    border-radius: 20px;
    border-style: solid;
    border-width: 1px;
    border-color: rgba(255, 255, 255, 0.35) !important;
  }

Thank you! 🍻

**Comment by Clooos** [comment]
Hi! Indeed I changed something in the previous release, this will be a breaking change for some users that use that kind of custom styles. I just fixed the editor to reflect the same styling, I will also add a note about it in the changelog.

Wait for the next release, there will be a new class named `.bubble-pop-up-background`.
