### ISSUE TITLE
Pop-up does not open with state trigger

### ISSUE THREAD

**Issue by marcedale** [Clooos/Bubble-Card#900]
First of all, many thanks for Bubble-Card. It is awesome.

**Describe the bug**  
I have my surveillance camera in a pop-up. The pop-up opens easily using a button. My goal was for the pop-up to open automatically as soon as the surveillance camera detects motion. But the pop-up does not open on motion.

**YAML**  
`type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#kameraklingel"
    auto_close: "60000"
    trigger_entity: binary_sensor.turklingel_erkennung
    trigger_state: Erkannt
    open_action:
      action: call-service
      target:
        entity_id: camera.turklingel
      service: camera.turn_on
      service_data:
        entity_id: camera.turklingel
    close_action:
      action: call-service
      target:
        entity_id: camera.turklingel
      service: camera.turn_off
      service_data:
        entity_id: camera.turklingel
    show_header: true
    card_layout: normal
    button_type: state
    entity: sensor.turklingel_person_name
    name: Türklingel
    show_attribute: false
    close_by_clicking_outside: false
    close_on_click: false
    width_desktop: 768px
    margin_top_mobile: "-25px"
    margin_top_desktop: "-25px"
    trigger_close: true
  - type: custom:webrtc-camera
    entity: camera.turklingel
    ui: true
    style: >-
      video {width: 400px, height: 100%} .mode, .screenshot, .fullscreen,
      .pictureinpicture {display: none}`

**Informations (please complete the following information):**  
 - OS: Android / Windows
 - Browser/App: chrome / fully kiosk
 - Bubble Card version: 2.2.4
 - Home Assistant version: 2024.10.3

**Comment by Clooos** [comment]
Hi! I see that you use a binary sensor for your trigger, so the `trigger_state` can only be `on` of `off` and not `trigger_state: Erkannt`.

**Comment by marcedale** [comment]
Thank you!
