### ISSUE TITLE
Section card widths

### ISSUE THREAD

**Issue by scargill** [Clooos/Bubble-Card#918]
Not sure if this is a bug or me.

My HA is entierly composed of sections. Each section automaticallt shows tiles - 2 wide unless deliberately altered.

When I make the vertical stack - bbubble card below it, then my various tiles under that - the tiles end up the full width. AS the idea was to save screen space, this doesnt work for me unless someone can tell me how to replacate a section inside the vertical stack. I tried adding a section and that failed. Any ideas?

**Comment by Clooos** [comment]
Hi! You can create a horizontal stack to put two cards on the same line, this is what I do in my pop-ups.

**Comment by scargill** [comment]
> Hi! You can create a horizontal stack to put two cards on the same line, this is what I do in my pop-ups.

I tried that - didn't work at first rty so I used a grid - worked perfectly...  thanks for quick feedback...

``
  - type: grid
    columns: 2
    square: false
``
