### ISSUE TITLE
Climate card is missing

### ISSUE THREAD

**Issue by Youri3246** [Clooos/Bubble-Card#921]
Hi,

Is it possible that the climate card is missing when i download version v2.3.0-beta.6.
When I test it on version v2.3.0-beta.5, it is there, so it seems to be related to the new beta version.
It seems that when I download the new beta release, it downloads an old version of the bubble card (v2.2.4). Picture attached.

![Schermafbeelding 2024-11-16 002521](https://github.com/user-attachments/assets/73dab97f-e1a1-452e-9c6c-1d47318f8018)

**Comment by Clooos** [comment]
Hi, I just checked and new beta is the right one, I don't understand why you have this issue.

**Comment by Youri3246** [comment]
That is very strange. If I download beta 5, everything is fine, but when I download beta 6 with HACS, it says version 2.2.4.

**Comment by Clooos** [comment]
Maybe an issue with HACS, is it up to date?

**Comment by Youri3246** [comment]
I double-checked everything: cleared the cache, deleted HACS, reinstalled it, and tried again, but it directly downloads version 2.2.4 instead of 2.3.0-beta.6.

I also tried it with a clean installation.

If possible, please check again. :)

**Comment by Clooos** [comment]
I did, this version is the right one, you are the only one to raise this issue. I truly have no idea of why you got back to v2.2.4 when you pick v2.3.0-beta.6.

**Comment by Clooos** [comment]
This seems to be the same issue:

![Screenshot_2024-11-16-12-21-31-653_com reddit frontpage](https://github.com/user-attachments/assets/d999727d-3ebb-4f84-bad7-81f7d741a9a6)

**Comment by Youri3246** [comment]
That did the trick. I don't know why, but after installing beta 4, cleaning the cache, reloading the front end, and then installing beta 6, it works now. Thanks for looking into it! I appreciate your help. :)

![image](https://github.com/user-attachments/assets/d3e47bec-6359-4a0e-89dc-47cbcf6fdaea)

**Comment by Clooos** [comment]
You're welcome, this is still weird 😅

**Comment by cromelex** [comment]
Ah this is so weird.

So I had the issue with beta7, installed via HACS.

Redownloaded and went to beta6, that fixed the missing climate card. 

Redownloaded beta7, cleared cache... and now it is showing up again.
