### ISSUE TITLE
Climate temperature +/- in steps of 1 instead of 0.5?

### ISSUE THREAD

**Issue by gjwjr** [Clooos/Bubble-Card#930]
**Describe the bug**
Climate temp change only possible in 0.5 increments.

**Expected behavior**
Would be great to be able to change temp in increments of 1 as most AC units do not support 0.5.

**Screenshots**
<img width="532" alt="Screenshot 2024-11-16 at 14 41 54" src="https://github.com/user-attachments/assets/d3534efe-fe0e-401e-a55f-d4d0ad53e462">

**Comment by brpeterso** [comment]
Maybe have an option to set the degree step level. I have a hot tub I like to set at 5 degree increments.  An awesome option for this card would be to default to 1 for F and 0.5 for C, and then the user can customize step level as needed.

**Comment by Clooos** [comment]
Hi! This should be fixed in the v2.3.0-beta.6, have you tried it? It should now correctly take the default step attribute of your climate entity.

**Comment by gjwjr** [comment]
Yeh I just tried the latest Beta today, it's using 0.5 increments instead of 1.

**Comment by Clooos** [comment]
Can you send me what you have when you go here in the dev tools?

![Screenshot_2024-11-16-16-57-19-509_io homeassistant companion android](https://github.com/user-attachments/assets/a0168e07-d537-463c-bbd1-9db4cac232af)

**Comment by gjwjr** [comment]
Ahh it looks like the integration sets it to 0.5!

<img width="1076" alt="Screenshot 2024-11-16 at 16 00 38" src="https://github.com/user-attachments/assets/3ffcb05e-7807-4215-9d87-0af0508e2074">

**Comment by Clooos** [comment]
This make sense then 🙂

**Comment by gjwjr** [comment]
Thanks for clarifying, love bubble card btw!
