### ISSUE TITLE
v2.3.0-beta.7 Climate card sub button HVAC modes reappears on edit

### ISSUE THREAD

**Issue by nzottmann** [Clooos/Bubble-Card#934]
As my thermostats only support the modes heat and off, I use the icon of the climate card to toggle modes and removed the sub button for the HVAC mode selection.
When I click on the card in frontend edit mode, the button reappears.

Frontend before clicking edit card, without button:
![image](https://github.com/user-attachments/assets/eed8084b-65ae-46d8-9aad-e453947ca750)

After clicking the edit popup opens, with the button back on the card:
![image](https://github.com/user-attachments/assets/01e8f45c-13e2-4f44-a356-8080c46ee274)

**Comment by Clooos** [comment]
Hi, indeed that is what happens when the card is created and that there is no sub-button added. In your case just configure it as you wish, remove it then save. Indeed if you edit it again it will reappear, but I haven't found a better way for the card initialization.

**Comment by nzottmann** [comment]
I understand, I will handle it like that. Just thought this was a bug.

Thank you for your work!
