### ISSUE TITLE
v2.3.0-beta.7 About call-service setting

### ISSUE THREAD

**Issue by zyi840449** [Clooos/Bubble-Card#935]
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: button
    button_type: name
    name: Reload all Yaml
    icon: mdi:progress-upload
    tap_action:
      action: call-service
      service: homeassistant.reload_all
      target: {}

When I press the button, the following message appears:
not a valid value for dictionary value @ data['target']['entity_id']. got 'undefined'

This problem did not occur until upgrading to v2.3.0-beta.7

**Comment by Clooos** [comment]
Damn, I will take a look, I probably know what is happening here 😅

**Comment by Clooos** [comment]
The new beta is here, take a look at the changelog first 🙂  

Everything should works as expected now:

https://github.com/Clooos/Bubble-Card/releases/tag/v2.3.0-beta.8
