### ISSUE TITLE
[2.3.0-beta7 ] disable clickable areas from lower layer when popup is displayed

### ISSUE THREAD

**Issue by KipK** [Clooos/Bubble-Card#938]
**Describe the bug**  
I'm testing latest beta. 
It's clearly better on a performance perspective.

However I see a little UX issue.
when pop-up is open, the clickable items on the dashboard below are still active.

**To Reproduce**  

When we click outside the pop-up to close it, if there's some buttons / entity / whatever on this area, it will automatically click on it. 

**Expected behavior**  
Clicks shoud be disabled for layers above the pop-up ( as a lightbox ) 

**Screenshots**  

https://github.com/user-attachments/assets/7aae4594-7f1e-4f82-b806-0473da5c0ebc

**Comment by Clooos** [comment]
Hi! Indeed there was a breaking change in the fourth beta and you are not the first who missed it. But I will change this for not confusing everyone too much, instead I will add a darker backdrop, without any blur, then I will add the possibility to have it blurred or to don't have any backdrop at all (this is what you have now).

Here's how you can re-add it in the meantime:

![Screenshot_2024-11-18-19-40-22-290_com android chrome-edit](https://github.com/user-attachments/assets/f3696f02-f8bf-49cc-a1e3-58aae22513e3)

**Comment by KipK** [comment]
I saw that, but even without blur effect I think we shouldn't be able to click on above layer. 
As example I've activated the alarm while closing a popup but not noticed it. Was a bit surprise when it started to shout in the house 😅
I'll readd the blur then

**Comment by Clooos** [comment]
In fact there are some users who wants to be able to click beside them, for example some of them have there own menu (like me 😇).

![Screenshot_2024-11-18-20-00-12-810_io homeassistant companion android-edit](https://github.com/user-attachments/assets/656aab17-c495-43a8-8e9d-391efc2e1df0)

But indeed this shouldn't be the default behavior, that's why I will change that and allow more options.

**Comment by Clooos** [comment]
The new beta is here and the pop-up backdrop is back by default, it is just not blurred by default anymore.

Take a look at the changelog if you want to add back the blur:

https://github.com/Clooos/Bubble-Card/releases/tag/v2.3.0-beta.8
