### ISSUE TITLE
v2.3.0-beta.7 Delayed temperature change wrong start value

### ISSUE THREAD

**Issue by nzottmann** [Clooos/Bubble-Card#942]
The delayed temperature change is a very good feature, as my z-wave thermostats need 1-2 seconds to apply a new setpoint. Now I can click the+ or - button fast multiple time until the new desired setpoint is reached, before that, I had to wait 1-2s every 0.5°, which was annoying.

I observed something which I think is a bug in the delay feature. After changing the setpoint in one frontend browser window, the change does start from a from (chached?) point in a second window, for example on mobile. Sometimes after loading the window, the change even starts at 0°.

Video shows it better than describing:

https://github.com/user-attachments/assets/f4e186de-eab9-4b3c-bd8b-bb28d1656cbb

**Comment by Clooos** [comment]
Hi! Nice catch! I will take a look at this!

**Comment by Clooos** [comment]
The new beta is here and everything should works as expected now 🙂 

https://github.com/Clooos/Bubble-Card/releases/tag/v2.3.0-beta.8

**Comment by nzottmann** [comment]
I can confirm it works as expected with beta.8, thank you!

**Comment by Clooos** [comment]
Thank you for the feedback! 😄
