### ISSUE TITLE
v2.3.0-beta.7 Button labels showing as text below buttons

### ISSUE THREAD

**Issue by gjwjr** [Clooos/Bubble-Card#943]
**Describe the bug**  
The title/label of buttons appears below the buttons as text for some reason. This did not happen in V2.24.

**Expected behavior**  
No text

**Screenshots**  
<img width="576" alt="Screenshot 2024-11-19 at 17 34 48" src="https://github.com/user-attachments/assets/a75b79bc-c26f-4805-b3a2-526b9bbf3513">

**Comment by Clooos** [comment]
Hi! I don't recommend to use these labels, instead use the new heading card or the Bubble separator, I have disabled their visibility for the pop-ups and I will do the same all the other cards.

**Comment by gjwjr** [comment]
Hi, I think you have misunderstood. The lines of text that you can see in the screenshot are being pulled from the button's name. On that screenshot I have the 2 white buttons at the top and then the 3 room buttons below, nothing else. So it seems that the text below is for some reason just showing all of the button's names.

<img width="441" alt="Screenshot 2024-11-22 at 16 36 11" src="https://github.com/user-attachments/assets/4bccfe1f-05a9-4eb6-bfbf-52d6ade9e009">

**Comment by Clooos** [comment]
That's very weird, you are the first with this issue. Can you share one of these button's YAML?

**Comment by gjwjr** [comment]
I just had a look at the YAML and realised I still had some info from "decluttering card", it seems that this was causing the issue as I have deleted it and the text has gone now. My bad!

**Comment by gjwjr** [comment]
Sure, here you go!

`kiosk_mode:
  non_admin_settings:
    kiosk: true
    ignore_entity_settings: true
  entity_settings:
    - entity:
        input_boolean.kiosk_mode: 'on'
      hide_header: true
    - entity:
        input_boolean.kiosk_mode: 'off'
      hide_header: false
views:
  - title: Home
    cards:
      - type: vertical-stack
        cards:
          - type: custom:mushroom-chips-card
            chips:
              - type: action
                tap_action:
                  action: navigate
                  navigation_path: '#vacuum-nspanel'
                icon: mdi:robot-vacuum
              - type: action
                tap_action:
                  action: perform-action
                  perform_action: input_boolean.toggle
                  target:
                    entity_id: input_boolean.kiosk_mode
                icon: mdi:arrow-collapse-up
            alignment: center
            card_mod:
              style: |
                ha-card {
                  --chip-background: #fefefe;
                  --color: black;
                  margin-bottom: 10px !important;
                }
          - square: false
            type: grid
            cards:
              - type: custom:bubble-card
                card_type: button
                button_type: name
                name: Living Room
                styles: |-
                  .bubble-button-card-container {
                      background: #393b3d !important;
                    }
                  .bubble-icon-container {
                      background: #FFB996;
                    }
                  .bubble-icon {
                      color: black !important;
                      opacity: 1;
                    }
                icon: mdi:sofa-single
                tap_action: {}
                button_action:
                  tap_action:
                    action: navigate
                    navigation_path: '#living-room-nspanel'
                  hold_action: {}
              - type: custom:bubble-card
                card_type: button
                button_type: name
                name: Dining Room
                styles: |-
                  .bubble-button-card-container {
                      background: #393b3d !important;
                    }
                  .bubble-icon-container {
                      background: #C63C51;
                    }
                  .bubble-icon {
                      color: black !important;
                      opacity: 1;
                    }
                icon: mdi:table-furniture
                tap_action: {}
                button_action:
                  tap_action:
                    action: navigate
                    navigation_path: '#dining-room-nspanel'
              - type: custom:bubble-card
                card_type: button
                button_type: name
                name: Office
                styles: |-
                  .bubble-button-card-container {
                      background: #393b3d !important;
                    }
                  .bubble-icon-container {
                      background: #FAB12F;
                    }
                  .bubble-icon {
                      color: black !important;
                      opacity: 1;
                    }
                icon: mdi:chair-rolling
                tap_action: {}
                button_action:
                  tap_action:
                    action: navigate
                    navigation_path: '#office-nspanel'
                  hold_action: {}
            columns: 2
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#living-room-nspanel'
            show_header: true
            button_type: name
            name: Living Room
            icon: mdi:sofa
            show_icon: true
            show_name: true
            margin: 7px
            margin_top_mobile: '-56px'
            bg_blur: '20'
            shadow_opacity: '0'
            bg_opacity: '90'
            styles: |

              .bubble-icon {
                color: black !important;
                opacity: 1;
              }
              .bubble-icon-container {
                background: #FFB996;
              }
            card_layout: large
          - type: custom:bubble-card
            card_type: button
            button_type: slider
            name: All Lights
            entity: light.living_room_lights
            icon: mdi:lightbulb
            sub_button:
              - name: Brightness
                icon: mdi:fridge-outline
                show_icon: false
                show_background: false
                show_attribute: true
                attribute: brightness
              - name: Toggle button
                icon: mdi:power
                tap_action:
                  action: toggle
            styles: |
              .bubble-range-fill { 
                background: linear-gradient(90deg, rgba(228,0,108,1) 0%, rgba(85,0,244,1) 100%) !important;
                opacity: 1 !important;
              }
              .bubble-icon-container {
                background: none;
              }
              .bubble-icon {
                color: white !important;
              }
              .bubble-sub-button-2 {
                color: ${state === 'on' ? 'black' : 'red'} !important;
              }
          - type: custom:bubble-card
            card_type: button
            button_type: slider
            name: Ceiling Lights
            entity: light.living_room_ceiling_lights
            icon: mdi:lightbulb
            sub_button:
              - name: Brightness
                icon: mdi:fridge-outline
                show_icon: false
                show_background: false
                show_attribute: true
                attribute: brightness
              - name: Toggle button
                icon: mdi:power
                tap_action:
                  action: toggle
            styles: |
              .bubble-range-fill { 
                background: linear-gradient(90deg, rgba(201,87,0,1) 0%, rgba(221,2,109,1) 100%)!important;
                opacity: 1 !important;
              }

              .bubble-icon-container {
                background: none;
              }
              .bubble-icon {
                color: white !important;
              }
                .bubble-sub-button-2 {
                color: ${state === 'on' ? 'black' : 'red'} !important;
              }
          - type: custom:bubble-card
            card_type: button
            button_type: slider
            name: Ambient Lights
            entity: light.living_room_ambient_light
            icon: mdi:lightbulb
            sub_button:
              - name: Brightness
                icon: mdi:fridge-outline
                show_icon: false
                show_background: false
                show_attribute: true
                attribute: brightness
              - name: Toggle button
                icon: mdi:power
                tap_action:
                  action: toggle
            styles: |
              .bubble-range-fill { 
                background: linear-gradient(90deg, rgba(201,87,0,1) 0%, rgba(221,2,109,1) 100%)!important;
                opacity: 1 !important;
              }

              .bubble-icon-container {
                background: none;
              }
              .bubble-icon {
                color: white !important;
              }
                .bubble-sub-button-2 {
                color: ${state === 'on' ? 'black' : 'red'} !important;
              }
          - square: false
            type: grid
            cards:
              - type: custom:bubble-card
                card_type: button
                name: Open Blind
                icon: mdi:roller-shade
                entity: input_button.living_room_blind_open
                tap_action:
                  target: {}
                  action: none
                styles: ''
              - type: custom:bubble-card
                card_type: button
                name: Close Blind
                icon: mdi:roller-shade-closed
                entity: input_button.living_room_blind_close
                tap_action:
                  target: {}
                  action: none
                styles: ''
            columns: 2
          - type: custom:bubble-card
            card_type: media-player
            name: TV
            hide:
              play_pause_button: true
              next_button: true
              previous_button: true
            icon: mdi:television
            styles: ''
            entity: media_player.sony_kd_55a8_3
        title: Living Room
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#vacuum-nspanel'
            show_header: true
            button_type: name
            name: Vacuum
            icon: mdi:robot-vacuum
            show_icon: true
            show_name: true
            margin: 7px
            margin_top_mobile: '-56px'
            bg_blur: '20'
            shadow_opacity: '0'
            bg_opacity: '90'
            styles: |

              .bubble-icon {
                color: black !important;
                opacity: 1;
              }
              .bubble-icon-container {
                background: #FF77B7;
              }
            card_layout: large
          - type: custom:bubble-card
            card_type: button
            entity: script.vacuum_room_all
            name: All Rooms
            button_action:
              tap_action:
                action: toggle
            tap_action:
              action: none
            show_last_changed: false
            show_state: true
            show_attribute: false
            force_icon: false
            styles: ''
            icon: mdi:home
          - square: false
            type: grid
            cards:
              - type: custom:bubble-card
                card_type: button
                name: Kitchen
                icon: mdi:fridge
                entity: script.vacuum_room_kitchen
                tap_action:
                  target: {}
                  action: none
                styles: ''
              - type: custom:bubble-card
                card_type: button
                name: Hallway
                icon: mdi:door
                entity: script.vacuum_room_hallway
                tap_action:
                  target: {}
                  action: none
                styles: ''
              - type: custom:bubble-card
                card_type: button
                name: Living Room
                icon: mdi:sofa-single
                entity: script.vacuum_room_living_room
                tap_action:
                  target: {}
                  action: none
                styles: ''
                button_type: switch
                show_last_changed: false
                show_state: false
              - type: custom:bubble-card
                card_type: button
                name: Dining Room
                icon: mdi:table-furniture
                entity: script.vacuum_room_dining_room
                tap_action:
                  target: {}
                  action: none
                styles: ''
                button_type: switch
                show_last_changed: false
                show_state: false
            columns: 2
        title: Vacuum
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#dining-room-nspanel'
            show_header: true
            button_type: name
            name: Dining Room
            icon: mdi:table-furniture
            show_icon: true
            show_name: true
            margin: 7px
            margin_top_mobile: '-56px'
            bg_blur: '20'
            shadow_opacity: '0'
            bg_opacity: '90'
            styles: |

              .bubble-icon {
                color: black !important;
                opacity: 1;
              }
              .bubble-icon-container {
                background: #C63C51;
              }
            card_layout: large
          - type: custom:bubble-card
            card_type: button
            button_type: slider
            name: All Lights
            entity: light.dining_room
            icon: mdi:lightbulb
            sub_button:
              - name: Brightness
                icon: mdi:fridge-outline
                show_icon: false
                show_background: false
                show_attribute: true
                attribute: brightness
              - name: Toggle button
                icon: mdi:power
                tap_action:
                  action: toggle
            styles: |
              .bubble-range-fill { 
                background: linear-gradient(90deg, rgba(228,0,108,1) 0%, rgba(85,0,244,1) 100%) !important;
                opacity: 1 !important;
              }
              .bubble-icon-container {
                background: none;
              }
              .bubble-icon {
                color: white !important;
              }
              .bubble-sub-button-2 {
                color: ${state === 'on' ? 'black' : 'red'} !important;
              }
          - type: custom:bubble-card
            card_type: button
            button_type: slider
            name: Ceiling Lights
            entity: light.dining_room_spots
            icon: mdi:lightbulb
            sub_button:
              - name: Brightness
                icon: mdi:fridge-outline
                show_icon: false
                show_background: false
                show_attribute: true
                attribute: brightness
              - name: Toggle button
                icon: mdi:power
                tap_action:
                  action: toggle
            styles: |
              .bubble-range-fill { 
                background: linear-gradient(90deg, rgba(201,87,0,1) 0%, rgba(221,2,109,1) 100%)!important;
                opacity: 1 !important;
              }

              .bubble-icon-container {
                background: none;
              }
              .bubble-icon {
                color: white !important;
              }
                .bubble-sub-button-2 {
                color: ${state === 'on' ? 'black' : 'red'} !important;
              }
          - type: custom:bubble-card
            card_type: button
            button_type: slider
            name: Pendant Light
            entity: light.hue_filament_bulb_1_3
            icon: mdi:lightbulb
            sub_button:
              - name: Brightness
                icon: mdi:fridge-outline
                show_icon: false
                show_background: false
                show_attribute: true
                attribute: brightness
              - name: Toggle button
                icon: mdi:power
                tap_action:
                  action: toggle
            styles: |
              .bubble-range-fill { 
                background: linear-gradient(90deg, rgba(201,87,0,1) 0%, rgba(221,2,109,1) 100%)!important;
                opacity: 1 !important;
              }

              .bubble-icon-container {
                background: none;
              }
              .bubble-icon {
                color: white !important;
              }
                .bubble-sub-button-2 {
                color: ${state === 'on' ? 'black' : 'red'} !important;
              }
        title: Dining Room
      - type: vertical-stack
        cards:
          - type: custom:bubble-card
            card_type: pop-up
            hash: '#office-nspanel'
            show_header: true
            button_type: name
            name: Office
            icon: mdi:chair-rolling
            show_icon: true
            show_name: true
            margin: 7px
            margin_top_mobile: '-56px'
            bg_blur: '20'
            shadow_opacity: '0'
            bg_opacity: '90'
            styles: |

              .bubble-icon {
                color: black !important;
                opacity: 1;
              }
              .bubble-icon-container {
                background: #FAB12F;
              }
            card_layout: large
          - type: custom:bubble-card
            card_type: button
            button_type: slider
            name: All Lights
            entity: light.office
            icon: mdi:lightbulb
            sub_button:
              - name: Brightness
                icon: mdi:fridge-outline
                show_icon: false
                show_background: false
                show_attribute: true
                attribute: brightness
              - name: Toggle button
                icon: mdi:power
                tap_action:
                  action: toggle
            styles: |
              .bubble-range-fill { 
                background: linear-gradient(90deg, rgba(228,0,108,1) 0%, rgba(85,0,244,1) 100%) !important;
                opacity: 1 !important;
              }
              .bubble-icon-container {
                background: none;
              }
              .bubble-icon {
                color: white !important;
              }
              .bubble-sub-button-2 {
                color: ${state === 'on' ? 'black' : 'red'} !important;
              }
          - type: custom:bubble-card
            card_type: button
            button_type: slider
            name: Office Lights
            entity: light.hue_white_light_1
            icon: mdi:lightbulb
            sub_button:
              - name: Brightness
                icon: mdi:fridge-outline
                show_icon: false
                show_background: false
                show_attribute: true
                attribute: brightness
              - name: Toggle button
                icon: mdi:power
                tap_action:
                  action: toggle
            styles: |
              .bubble-range-fill { 
                background: linear-gradient(90deg, rgba(201,87,0,1) 0%, rgba(221,2,109,1) 100%)!important;
                opacity: 1 !important;
              }

              .bubble-icon-container {
                background: none;
              }
              .bubble-icon {
                color: white !important;
              }
                .bubble-sub-button-2 {
                color: ${state === 'on' ? 'black' : 'red'} !important;
              }
          - type: custom:bubble-card
            card_type: button
            button_type: slider
            name: Porch Lights
            entity: light.hue_white_light_1_2
            icon: mdi:lightbulb
            sub_button:
              - name: Brightness
                icon: mdi:fridge-outline
                show_icon: false
                show_background: false
                show_attribute: true
                attribute: brightness
              - name: Toggle button
                icon: mdi:power
                tap_action:
                  action: toggle
            styles: |
              .bubble-range-fill { 
                background: linear-gradient(90deg, rgba(201,87,0,1) 0%, rgba(221,2,109,1) 100%)!important;
                opacity: 1 !important;
              }

              .bubble-icon-container {
                background: none;
              }
              .bubble-icon {
                color: white !important;
              }
                .bubble-sub-button-2 {
                color: ${state === 'on' ? 'black' : 'red'} !important;
              }
          - type: custom:bubble-card
            card_type: climate
            entity: climate.153931628537763_climate
            sub_button:
              - name: HVAC modes menu
                select_attribute: hvac_modes
                state_background: false
                show_arrow: true
                show_background: true
                show_attribute: false
                show_last_changed: false
                show_state: false
                show_name: false
                show_icon: true
            icon: ''
            show_state: false
            show_last_changed: false
        title: Office
`

**Comment by Clooos** [comment]
I see this is my mail but not here:

![Screenshot_2024-11-22-19-17-09-389_com google android gm-edit](https://github.com/user-attachments/assets/c691f6cf-a34c-41d0-a253-d865d6cdac3f)

Is it fixed or not? Because I highly suspect that something is wrong in your setup, there is nothing in my code that can do something like on your screenshot.

**Comment by gjwjr** [comment]
I deleted my comment shortly after I posted it as I realised that the issue continued even after removing the YAML code for decluttering card. I am now just using bubble card and the issue persists.

**Comment by Clooos** [comment]
Try with a new view to see if the issue persist. Also I can see "Vacuum" on your screenshot and you don't have any vacuum Bubble Card, this label is coming from your mushroom chip card.

This is the proof that this issue is definitely not coming from Bubble Card. I'm closing this, but check if all your custom cards are up-to-date because I don't see what can be wrong in your config.

But I hope that you will find a way to fix that 🙂
