### ISSUE TITLE
Feature request....swip to close popups.

### ISSUE THREAD

**Issue by jgeorge1983** [Clooos/Bubble-Card#950]
Sorry nothing to fancy, just a simple swipe down on a pop up to close.  Hopefully it's not already there and I've missed it

**Comment by Clooos** [comment]
It's already there and you missed it 😁

You probably haven't swiped long enough, you can also change the distance to slide in the new betas.

You can also swipe from the pop-up header.

**Comment by jgeorge1983** [comment]
Got it, apologies fir wasting your time

**Comment by Clooos** [comment]
Don't worry, I've added way too many features in these pop-ups, so it's not always easy to find out about everything 🫠
