### ISSUE TITLE
v2.3.0-beta.7 Cover buttons are disabled

### ISSUE THREAD

**Issue by vtracsd** [Clooos/Bubble-Card#951]
Any chance you can add the option to enable all the cover buttons? The prior version has all the buttons enabled. My shades don't support position state so it can't tell whether it's open or closed. With the current beta, the up button is disabled while the shade is closed or one of the buttons will be disabled while it's half open/closed.

**Comment by vtracsd** [comment]
In case anyone needs to get the cover buttons functionality back. Add this to the custom cover style.

`
.bubble-button.disabled {
    opacity: 1 !important;
    pointer-events: auto !important;
    cursor: pointer !important;
}
`

**Comment by vtracsd** [comment]
The HA card buttons are opposite of the bubble card. Down disabled, up enabled on HA card vs Down enabled, up disabled on bubble.

**Comment by vtracsd** [comment]
An option to enable both icons is preferable since some of my shades are stateless.

I think HA is using the current_position attribute to determine which icon to disable. If current_position == 0, disable down button, 100 disables the up button. HA enables both buttons if current_position attribute is not present. The entity state itself is "unknown".

**Comment by Clooos** [comment]
I will check for what is the best way to handle that use case, there is probably no need for an option.
