### ISSUE TITLE
Questions about translation or select list

### ISSUE THREAD

**Issue by zyi840449** [Clooos/Bubble-Card#958]
As shown in the photo, some items are displayed in English because they are not included in the system's built-in translation vocabulary.

Is there a way to customize the name of the option?
Or can these options be set not to be displayed?
![translate](https://github.com/user-attachments/assets/9d5bd6fb-8e18-4291-8497-d575553e00a8)

**Comment by npstewart87** [comment]
Wouldn't that have to do with your thermostat integration itself? 

I pulled mine up in Dev Tools and the modes appear to be listed there, although im not sure what would happen if they were updated..
<img width="661" alt="sceeenshot climate" src="https://github.com/user-attachments/assets/ed7f2ab4-7757-4899-8a93-806cc9d87b12">

See attached.

**Comment by Clooos** [comment]
Hi! There is a way to do that with a (complex) custom template, I've shared how on my new Patreon page.

Here is the announcement link:
https://www.reddit.com/r/BubbleCard/comments/1h11vm5/hi_everyone/

And sorry for not making this free, working on templates takes time. I really hope you understand! 😊
