### ISSUE TITLE
About the location of the select list

### ISSUE THREAD

**Issue by zyi840449** [Clooos/Bubble-Card#959]
If the select card is positioned too close to the bottom edge of the screen, the option list will extend beyond the bottom edge of the screen and be truncated.

Maybe you could create an option to decide whether the list should appear above or below the button?

Picture 1 is what it looks like on a computer using Chrome. It's normal.
Picture 2 is what it looks like on the iOS app, the list truncated.
![1](https://github.com/user-attachments/assets/e1c54e8d-22ae-4030-90e7-69da059f2b29)
![2](https://github.com/user-attachments/assets/30d1650b-29a5-4e03-9bea-5152f224c867)

**Comment by Clooos** [comment]
Hi! It's supposed to be the case already, I just tried and it works for me, if the list don't have enough space below it opens above. Do you have some custom styles or something that could breaks it?

![Screenshot_2024-11-25-10-38-47-672_io homeassistant companion android-edit](https://github.com/user-attachments/assets/bfec2b52-0a62-498c-b508-6e4be2533548)

**Comment by zyi840449** [comment]
> Hi! It's supposed to be the case already, I just tried and it works for me, if the list don't have enough space below it opens above. Do you have some custom styles or something that could breaks it?
> 
> ![Screenshot_2024-11-25-10-38-47-672_io homeassistant companion android-edit](https://private-user-images.githubusercontent.com/36499953/389467191-bfec2b52-0a62-498c-b508-6e4be2533548.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NDMwNzgsIm5iZiI6MTczMjU0Mjc3OCwicGF0aCI6Ii8zNjQ5OTk1My8zODk0NjcxOTEtYmZlYzJiNTItMGE2Mi00OThjLWI1MDgtNmU0YmUyNTMzNTQ4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDEzNTI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwMGY1NzNlN2QyMDE4NWJmMDNlNjYyOTI2NzcyY2M0ZjgwOGMwZWZlMTc2OWZjYzVkZTdiYTIyZTU2ZDMzMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.B1bFOH39CY6Fl5wDAIa4HY2R7Nl-cLX2wguura3yI5A)

I have an interesting discovery, when I set it like this:
margin_top_mobile: **40%**
iOS app: Option list appears below the button, and is truncated.
Android app: Option list appears above the button, normal.

when I set it like this: 
margin_top_mobile: **42%**
iOS app: Option list appears above the button, normal.
Android app: Option list appears below the button, and is truncated.

when I set it like this: 
margin_top_mobile: **315px**
iOS app and Android app, all normal !

**Comment by Clooos** [comment]
I don't recommend to use percentage in the pop-ups, have you tried with `40vh` instead?

**Comment by zyi840449** [comment]
> margin_top_mobile: **40%**
> iOS app: Option list appears below the button, and is truncated.
> Android app: Option list appears above the button, normal.

I just tried 40vh, and the result is the same as 40%:
iOS app: Option list appears below the button, and is truncated.
Android app: Option list appears above the button, normal.

But at least I've solved the immediate problem: using px as unit.
