### ISSUE TITLE
Close Button does not remove hash from url

### ISSUE THREAD

**Issue by TinyShark** [Clooos/Bubble-Card#96]
Updated to v1.0.1 and the close button no longer removes the hash from the url. It does close the popup however.

This means that it can occur where you have to click twice on a horizontal-stack button to bring back the popup.

![ezgif com-video-to-gif (1)](https://github.com/Clooos/Bubble-Card/assets/23080224/9878d622-a8ea-45d0-a471-9d5bd6c4f783)

**Comment by Clooos** [comment]
Thanks! It's now fixed in 1.0.2!
https://github.com/Clooos/Bubble-Card/releases
