### ISSUE TITLE
Z-index too low when used with other custom cards

### ISSUE THREAD

**Issue by TinyShark** [Clooos/Bubble-Card#97]
Some custom cards set their own Z-index e.g Swipe-Card has a z-index of 1.

Bubble popup is also z-index:1 and causes popup items to go behind other elements.

Would it make sense for a popup to have a higher z-index?

![ezgif com-video-to-gif (2)](https://github.com/Clooos/Bubble-Card/assets/23080224/454ad304-0cfd-4a77-97b2-b1e9ac95f53d)

**Comment by Clooos** [comment]
Hi, an higher z-index than 1 will break a lot of features, for exemple the default HA more info panel is on z-index 1. Just one question but are your vertical-stack/pop-up right before your horizontal-buttons-stack? All pop-ups needs to be after all other cards to be displayed correctly.

**Comment by TinyShark** [comment]
You are quite right! I did read your docs, but that slipped past me 😄

Solved by changing order of bubble card. Thanks.

**Comment by TinyShark** [comment]
You are quite right! I did read your docs, but that slipped past me 😄

Solved by changing order of bubble card. Thanks.
