### ISSUE TITLE
Popups are the same transparency as dashboard cards with transparent themes, which makes everything hard to read.

### ISSUE THREAD

**Issue by nomonkeynodeal** [Clooos/Bubble-Card#98]
I fixed this with card_mod and a mod card to change the background color of each popup menu, but I have several dozen of these across several dashboards and it's getting crazy managing them all. Plus when you use a mod card, you can't edit cards in the GUI.

I've tried a lot of a workarounds. I have been editing the iOS theme for a couple hours and I've gotten nowhere. Apparently 'ha-card-background' sets the background color of all cards no matter what. There doesn't appear to be a way to differentiate between cards on the dash and popup menus.

I tried Popup Backdrop Filter in HACS, but it doesn't seem compatible. Also Frosted Cards. I have also been wondering if I could apply card_mod the dashboard cards and not the popup cards, but I haven't found a way to do this.

There are a lot of options here: the background could be blurred, or dimmed. Or the card itself could have its background blurred. Or we could find a way to differentiate between cards on the dash and cards in a popup without the need for card_mod CSS in every popup so their opacities could be set separately.

Any ideas?

**Comment by Clooos** [comment]
Hi and thanks for your feedback. Can you tell me what is the theme you are using? I will take a look at that.

**Comment by nomonkeynodeal** [comment]
I tried a lot of them, but the main two are:

https://github.com/basnijholt/lovelace-ios-dark-mode-theme
https://github.com/orickcorreia/caule-themes-pack-1

Both available in HACs.

**Comment by jondavidsson** [comment]
First, thanks for a really cool card!

Continuing on the above, the separator line also have an opacity which make it almost invisible on a lot of themes.

I've never made any card for HA and have no idea how the structure is, but there would probably be great if there in some way a lot of the hard coded css could be made into global variables for the bubble card so it would be easier to adjust for different themes.

The same is also for the margins of the horizontal-stack. The margins for me is a little bit off, leaving a gap on the right side of the screen. I've tried to fix this but it seems like the horizontal stack is regenerated and hence all the styling is overwritten. 

Thanks again for great work!

**Comment by Clooos** [comment]
@jondavidsson I agree and this is in my plans, for the gap this depend of the themes, I've added a margin variable to fix that:

<img width="848" alt="image" src="https://github.com/Clooos/Bubble-Card/assets/36499953/773b4f2a-dc51-49b3-b4ff-3fbf75e71ca2">

**Comment by jondavidsson** [comment]
> @jondavidsson I agree and this is in my plans, for the gap this depend of the themes, I've added a margin variable to fix that:
> <img alt="image" width="848" src="https://user-images.githubusercontent.com/36499953/273566586-773b4f2a-dc51-49b3-b4ff-3fbf75e71ca2.png">

Great to hear about your plans! Since my time is extremely limited (small children) I'll sit in the boat and wait for the updated releases 😀

Also, thanks for the pointers to the manual. I've missed that update 🤦🏻‍♂️ 😆

**Comment by Clooos** [comment]
There is now a lot more styling options directly available in the GUI editor in the v1.1.0 🥳
https://github.com/Clooos/Bubble-Card/releases/tag/v1.1.0
