### ISSUE TITLE
Nested Popups not working anymore on Desktop

### ISSUE THREAD

**Issue by Nazze** [Clooos/Bubble-Card#99]
Hi

I am using nested popups (E.g. I am having an overview over all floors. If I click on a button "1st floor", it opens a pop-up with all rooms in the first floor. If I then click on "kitchen", it should open another pop-up with entities in the kitchen). I am using the "navigate" option with hashtags.
Version 1.0.2 has an issue. When I want to open the second popup, it does not open the second popup, but only closes the first.
It used to work on Dekstop and it IS working for mobile.
I tested with Firefox and Safari on MacOS. Cache cleard.

KR
Nazze

**Comment by Clooos** [comment]
Hi and thanks for your feedback! Can you try to add this to one of your pop-up YAML? (You only need to set this to one pop-up)

```yaml
back_open: true
```

**Comment by Nazze** [comment]
Hi! No, that did not solve the issue.

**Comment by Clooos** [comment]
Yup I just realized that, a new version will come really soon, thanks again for pointing me this issue!

**Comment by Clooos** [comment]
The new version is here 🥳

**Comment by Nazze** [comment]
YEAH! Works, thanks! 🥳🙏
