### ISSUE TITLE
Climate card - Constant background colour when ON - not working

### ISSUE THREAD

**Issue by juscode** [Clooos/Bubble-Card#993]
Hi, there appears to be an issue with the climate card, after switching the Constant background colour when ON to off the climate card sometimes displays the background colour and sometime does not. The code editor shows that the state_color is set to false so it shouldn't be coming on.

**Comment by MrBearPresident** [comment]
This is the desired function.
When the switch (state_color) is on:
- heating mode=off - > color off
- heating mode=on - > color om

When the switch (state_color) is off:
- heating action=off - > color off
- heating action=on - > color on

Heating action is on when the actual relay of the thermostat is on. Or the equivalent from this.
